### PR TITLE
Fix/Bybit_perpetual: best price randomly getting desynchronized

### PR DESCRIPTION
**Pull request by mhrvth**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

The problem was caused by:

1) Infrequent status updates
2) Loss of precision error in floating point conversion 
https://github.com/CoinAlpha/hummingbot/pull/221

**Tests performed by the developer**:

Ran the Perpetual MM strategy with the Bybit connector, tested `status --live` with `order_book --live` and compared with the real exchange.

**Tips for QA testing**:

This issue is not specific to Bybit.

### CODE REVIEW

**Comment by mhrvth** [comment]
[sc-25776]

**Review by Deepali6997 — APPROVED** [review]
LGTM!

Test Summary

1. Can confirm that post creation of strategy the commands; status --live, ticker --live and orderbook --live, are behaving as expected
2. The prices were matching with the exchanges that went under testing. 
3. Also, seemingly lagging status was not spotted. The gap to sync the prices was not taking too long. 
4. The exchanges that went under testing (7) - Bybit perpetual, AscendEx, Binance, Gate_io, Huobi, KuCoin, OkEx

**Review by aarmoa — APPROVED** [review]
The change looks good to be, but 0.1 seconds of refresh time seems too small. Did we try a refresh time of 0.5 (twice as fast as the original code) before going to 0.1?

**Comment by mhrvth** [comment]
Created a PR in the Foundation repo: https://github.com/hummingbot/hummingbot/pull/5286

**Pull request closed without merging**
