### PR TITLE
fix / update windows dependencies

### PR DESCRIPTION
**Pull request by kmcgowan2000**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Update hummingsim dependency + 2 additional dependencies (due to birdfeeder)
Only for Windows

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Comment by dennisocana** [comment]
Requesting for @aarmoa and @RC-13 to review and sign-off before merging.

**Review by RC-13 — APPROVED** [review]
LGTM

**Review by aarmoa — COMMENTED** [review]
@kmcgowan2000 are the new versions of aiokafka and kafka-python only required for the Windows version?

**Review by aarmoa — APPROVED** [review]
I have already had a chat with @kmcgowan2000. Changes look good to me.

**Review by dennisocana — APPROVED** [review]

**Pull request merged**
