### PR TITLE
feat / celo docker

### PR DESCRIPTION
**Pull request by martinkou**
**Before submitting this PR, please make sure**:
- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue:
- Related Clubhouse Story:
https://app.clubhouse.io/coinalpha/story/9075/docker-build-can-t-access-celo-cli

**A description of the changes proposed in the pull request**:
This patch modifies Dockerfile to include `celocli` in hummingbot's Docker image, and the necessary configurations to allow Docker based hummingbot to run celocli.

### CODE REVIEW

**Comment by mifeng** [comment]
I tried to install the Docker build using instructions that I just added in a commit. However, I saw errors running `balance`

**Comment by martinkou** [comment]
```
======================================================================
ERROR: test_profitable_celo_buy_trade (test.test_celo_arb.CeloArbUnitTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/jenkins_home/workspace/hb-test_pull-request/test/test_celo_arb.py", line 183, in test_profitable_celo_buy_trade
    ctp_active_orders = self.strategy.market_info_to_active_orders[self.market_info]
KeyError: MarketTradingPairTuple(BacktestMarket, CGLD-CUSD, CGLD, CUSD)
-------------------- >> begin captured stdout << ---------------------
command: ('celocli', 'account:unlock', 'TEST_ADDRESS', '--password', 'TEST_PASSWORD')
output: 
command: ('celocli', 'exchange:show', '--amount', '19800000000000000000')
output: Fetching exchange rates...... done
19800000000000000000 cGLD => 199000000000000000000 cUSD
19800000000000000000 cUSD => 2100000000000000000 cGLD
command: ('celocli', 'exchange:show', '--amount', '2000000000000000000')
output: Fetching exchange rates...... done
2000000000000000000 cGLD => 20000000000000000000 cUSD
2000000000000000000 cUSD => 190000000000000000 cGLD
command: ('celocli', 'node:synced')

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
hummingbot.strategy.celo_arb.celo_arb: INFO: Markets are ready. Trading started.
hummingbot.core.clock: ERROR: Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 145, in hummingbot.core.clock.Clock.backtest_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/celo_arb/celo_arb.pyx", line 257, in hummingbot.strategy.celo_arb.celo_arb.CeloArbStrategy.c_tick
    self.c_main()
  File "hummingbot/strategy/celo_arb/celo_arb.pyx", line 263, in hummingbot.strategy.celo_arb.celo_arb.CeloArbStrategy.c_main
    self.main_process()
  File "hummingbot/strategy/celo_arb/celo_arb.pyx", line 271, in hummingbot.strategy.celo_arb.celo_arb.CeloArbStrategy.main_process
    err_msg = CeloCLI.validate_node_synced()
  File "/var/jenkins_home/workspace/hb-test_pull-request/hummingbot/market/celo/celo_cli.py", line 111, in validate_node_synced
    output = command(["celocli", "node:synced"])
  File "/root/miniconda/envs/hummingbot/lib/python3.8/site-packages/mock/mock.py", line 1100, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/root/miniconda/envs/hummingbot/lib/python3.8/site-packages/mock/mock.py", line 1104, in _mock_call
    return _mock_self._execute_mock_call(*args, **kwargs)
  File "/root/miniconda/envs/hummingbot/lib/python3.8/site-packages/mock/mock.py", line 1167, in _execute_mock_call
    result = effect(*args, **kwargs)
  File "/var/jenkins_home/workspace/hb-test_pull-request/test/test_celo_arb.py", line 36, in mock_command
    print(f"output: {celo_outputs[commands]}")
KeyError: ('celocli', 'node:synced')
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_profitable_celo_sell_trade (test.test_celo_arb.CeloArbUnitTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/jenkins_home/workspace/hb-test_pull-request/test/test_celo_arb.py", line 167, in test_profitable_celo_sell_trade
    ctp_active_orders = self.strategy.market_info_to_active_orders[self.market_info]
KeyError: MarketTradingPairTuple(BacktestMarket, CGLD-CUSD, CGLD, CUSD)
-------------------- >> begin captured stdout << ---------------------
command: ('celocli', 'account:unlock', 'TEST_ADDRESS', '--password', 'TEST_PASSWORD')
output: 
command: ('celocli', 'exchange:show', '--amount', '9950000000000000000')
output: Fetching exchange rates...... done
9950000000000000000 cGLD => 99500000000000000000 cUSD
9950000000000000000 cUSD => 1000000000000000000 cGLD
command: ('celocli', 'exchange:show', '--amount', '1000000000000000000')
output: Fetching exchange rates...... done
1000000000000000000 cGLD => 10500000000000000000 cUSD
1000000000000000000 cUSD => 95000000000000000 cGLD
command: ('celocli', 'node:synced')

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
hummingbot.strategy.celo_arb.celo_arb: INFO: Markets are ready. Trading started.
hummingbot.core.clock: ERROR: Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 145, in hummingbot.core.clock.Clock.backtest_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/celo_arb/celo_arb.pyx", line 257, in hummingbot.strategy.celo_arb.celo_arb.CeloArbStrategy.c_tick
    self.c_main()
  File "hummingbot/strategy/celo_arb/celo_arb.pyx", line 263, in hummingbot.strategy.celo_arb.celo_arb.CeloArbStrategy.c_main
    self.main_process()
  File "hummingbot/strategy/celo_arb/celo_arb.pyx", line 271, in hummingbot.strategy.celo_arb.celo_arb.CeloArbStrategy.main_process
    err_msg = CeloCLI.validate_node_synced()
  File "/var/jenkins_home/workspace/hb-test_pull-request/hummingbot/market/celo/celo_cli.py", line 111, in validate_node_synced
    output = command(["celocli", "node:synced"])
  File "/root/miniconda/envs/hummingbot/lib/python3.8/site-packages/mock/mock.py", line 1100, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/root/miniconda/envs/hummingbot/lib/python3.8/site-packages/mock/mock.py", line 1104, in _mock_call
    return _mock_self._execute_mock_call(*args, **kwargs)
  File "/root/miniconda/envs/hummingbot/lib/python3.8/site-packages/mock/mock.py", line 1167, in _execute_mock_call
    result = effect(*args, **kwargs)
  File "/var/jenkins_home/workspace/hb-test_pull-request/test/test_celo_arb.py", line 36, in mock_command
    print(f"output: {celo_outputs[commands]}")
KeyError: ('celocli', 'node:synced')
--------------------- >> end captured logging << ---------------------
```

**Comment by Nullably** [comment]
The unit test error should be fixed now in this PR #1867

**Comment by mifeng** [comment]
test this please

**Pull request merged**
