### PR TITLE
[v0.38] fix/Beaxy float rounding

### PR DESCRIPTION
**Pull request by novoxd**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

Due to Beaxy API changes - all nums as str to JSON float. There is a need to convert them to strings before casting to `Decimal`. Otherwise, such errors will appear:

```
INFO - Filled 0.0005000000000000000104083408559 out of 0.00050000 of the limit sell order HBOT-sell-BTC-USDC-1615560159002194.
```

### CODE REVIEW

**Comment by rxlxrxsx** [comment]
- After creating a pure mm bot and entering start command, it immediately shows `ERROR - created at` and will not proceed or not run the strategy
- Entering stop command also shows an error `Unhandled error in background task: list.remove(x): x not in list`

Screen Shot 2021-03-17 at 12 11 55 PM

```
2021-03-17 12:09:41,881 - 4218 - hummingbot.client.hummingbot_application - ERROR - 'created_at'
Traceback (most recent call last):
  File "/Users/reiniersalazar/hummingbot3/hummingbot/client/command/start_command.py", line 123, in start_market_making
    self.markets_recorder.restore_market_states(config_path, market)
  File "/Users/reiniersalazar/hummingbot3/hummingbot/connector/markets_recorder.py", line 174, in restore_market_states
    market.restore_tracking_states(market_states.saved_state)
  File "hummingbot/connector/exchange/beaxy/beaxy_exchange.pyx", line 209, in hummingbot.connector.exchange.beaxy.beaxy_exchange.BeaxyExchange.restore_tracking_states
    key: BeaxyInFlightOrder.from_json(value)
  File "hummingbot/connector/exchange/beaxy/beaxy_in_flight_order.pyx", line 79, in hummingbot.connector.exchange.beaxy.beaxy_in_flight_order.BeaxyInFlightOrder.from_json
    datetime.fromisoformat(data['created_at']),
KeyError: 'created_at'
```

```
2021-03-17 12:11:42,782 - 4218 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: list.remove(x): x not in list
Traceback (most recent call last):
  File "/Users/reiniersalazar/hummingbot3/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/reiniersalazar/hummingbot3/hummingbot/client/command/stop_command.py", line 37, in stop_loop
    self.clock.remove_iterator(self.strategy)
  File "hummingbot/core/clock.pyx", line 83, in hummingbot.core.clock.Clock.remove_iterator
    self._child_iterators.remove(iterator)
ValueError: list.remove(x): x not in list
```

Log file for the error: 
[logs_beaxy_test.log](https://github.com/CoinAlpha/hummingbot/files/6154512/logs_beaxy_test.log)

**Comment by RC-13** [comment]
Hi @novoxd PR has been tested and confirm the fix. Can you please sort out the current conflict so we can approve the pull request? Thanks

**Comment by mifeng** [comment]
Reminded Beaxy in our shared TG group

**Review by dennisocana — APPROVED** [review]

**Review by RC-13 — APPROVED** [review]
Tested and confirmed working by QA

**Pull request merged**
