### PR TITLE
feat/twap time span execution

### LINKED ISSUE #3480: Add the option for the user to set start and stop time on TWAP strategy
Improvement to be implemented after refactor #3431 is completed.

## What?

Instead of setting a fixed time between order creation (`order_delay_time`), allow the user to:

- set a date & time for the bot to start creating orders
- set a date & time for the bot to stop creating orders

## Why?

Traders wanting to transact a big volume on the market might set a specific time frame to execute the trades due to various reasons (high/less volume, less front-run bot activities, strategy timing, etc).

This setting also is required to implement a future feature (order randomization)

## How?

An extra question must be asked when creating the strategy:

`Do you want to specify a start & end time for the strategy?`
If answer is `no`, the bot will ask `How long must the bot wait between each order (in seconds)?`

If answer is `yes`, the bot will ask for a `start_date_time` and a `end_date_time`

After both values is defined, the bot must calculate the `order_delay_time` based on the `target_asset_amount` and the `order_step_size`

Example:

I want to trade 100 BTC, with individual orders sizes of 1 BTC, between 06/01/2021 16:00 and 06/01/2021 17:00

Total amount of orders = 100 orders of 1 BTC each

`start_date_time` = 06/01/2021 16:00
`end_date_time` = 06/01/2021 17:00
`total_trade_time` = 1 hour = 3600 seconds

`order_delay_time` = 3600 seconds / 100 orders = 1 new order created every 36 seconds

**The bot must show what is the expected time between each order for the user**

### PR DESCRIPTION
**Pull request by aarmoa**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Add time span execution to TWAP strategy.
New configuration values: is_time_span_execution, start_datetime, end_datetime.
The status message for the strategy also changed. Not it includes details of the configured execution type in the "Configuration" section.

Closes #3480

### CODE REVIEW

**Comment by RC-13** [comment]
Tested new parameters with the following configuration:
image
After all, orders are placed and canceled, it appears that no orders are made after the last order was canceled at `2021-06-25 10:301:03`. I don't see any requirement that orders will go back to cycle in the story so I'm assuming that this is expected behavior?

Here's the screenshot, the last order has been canceled and it's been 5 minutes since the end time, and if you check the device time, it has been 5 min since the end time and yet no orders are made:
twap new pr -no order created after end time
Edited logs for a better view:
```python
2021-06-25 10:14:41,151 - 6786 - hummingbot.strategy.twap.twap - INFO - Waiting for 300 to place orders
2021-06-25 10:15:00,003 - 6786 - hummingbot.strategy.twap.twap - INFO - Trying to place orders now. 
2021-06-25 10:15:00,005 - 6786 - hummingbot.strategy.twap.twap - INFO - Checking to see if the incremental order size is possible
2021-06-25 10:15:00,005 - 6786 - hummingbot.strategy.twap.twap - INFO - Checking to see if the user has enough balance to place orders
2021-06-25 10:15:00,005 - 6786 - hummingbot.strategy.twap.twap - INFO - Limit buy order has been placed
2021-06-25 10:15:00,146 - 6786 - hummingbot.connector.exchange.binance.binance_exchange - INFO - Created LIMIT BUY order x-XEKWYICX-BDEUT1624587300005495 for 50.00000000 DOGE-USDT.
2021-06-25 10:16:00,001 - 6786 - hummingbot.strategy.twap.twap - INFO - (DOGE-USDT) Cancelling the limit order x-XEKWYICX-BDEUT1624587300005495. [clock=2021-06-25 02:16:00+00:00]

2021-06-25 10:20:01,002 - 6786 - hummingbot.strategy.twap.twap - INFO - Current time: 2021-06-25 10:20:01 is now greater than Previous time: 2021-06-25 10:15:00  with time delay: 300. Trying to place orders now. 
2021-06-25 10:20:01,004 - 6786 - hummingbot.strategy.twap.twap - INFO - Checking to see if the incremental order size is possible
2021-06-25 10:20:01,004 - 6786 - hummingbot.strategy.twap.twap - INFO - Checking to see if the user has enough balance to place orders
2021-06-25 10:20:01,005 - 6786 - hummingbot.strategy.twap.twap - INFO - Limit buy order has been placed
2021-06-25 10:20:01,153 - 6786 - hummingbot.connector.exchange.binance.binance_exchange - INFO - Created LIMIT BUY order x-XEKWYICX-BDEUT1624587601004929 for 50.00000000 DOGE-USDT.
2021-06-25 10:21:01,004 - 6786 - hummingbot.strategy.twap.twap - INFO - (DOGE-USDT) Cancelling the limit order x-XEKWYICX-BDEUT1624587601004929. [clock=2021-06-25 02:21:01+00:00]

2021-06-25 10:25:02,005 - 6786 - hummingbot.strategy.twap.twap - INFO - Current time: 2021-06-25 10:25:02 is now greater than Previous time: 2021-06-25 10:20:01  with time delay: 300. Trying to place orders now. 
2021-06-25 10:25:02,007 - 6786 - hummingbot.strategy.twap.twap - INFO - Checking to see if the incremental order size is possible
2021-06-25 10:25:02,007 - 6786 - hummingbot.strategy.twap.twap - INFO - Checking to see if the user has enough balance to place orders
2021-06-25 10:25:02,008 - 6786 - hummingbot.strategy.twap.twap - INFO - Limit buy order has been placed
2021-06-25 10:25:02,148 - 6786 - hummingbot.connector.exchange.binance.binance_exchange - INFO - Created LIMIT BUY order x-XEKWYICX-BDEUT1624587902007891 for 50.00000000 DOGE-USDT.
2021-06-25 10:26:02,035 - 6786 - hummingbot.strategy.twap.twap - INFO - (DOGE-USDT) Cancelling the limit order x-XEKWYICX-BDEUT1624587902007891. [clock=2021-06-25 02:26:02+00:00]

2021-06-25 10:30:03,003 - 6786 - hummingbot.strategy.twap.twap - INFO - Current time: 2021-06-25 10:30:03 is now greater than Previous time: 2021-06-25 10:25:02  with time delay: 300. Trying to place orders now. 
2021-06-25 10:30:03,005 - 6786 - hummingbot.strategy.twap.twap - INFO - Checking to see if the incremental order size is possible
2021-06-25 10:30:03,005 - 6786 - hummingbot.strategy.twap.twap - INFO - Checking to see if the user has enough balance to place orders
2021-06-25 10:30:03,006 - 6786 - hummingbot.strategy.twap.twap - INFO - Limit buy order has been placed
2021-06-25 10:30:03,141 - 6786 - hummingbot.connector.exchange.binance.binance_exchange - INFO - Created LIMIT BUY order x-XEKWYICX-BDEUT1624588203005905 for 50.00000000 DOGE-USDT.
2021-06-25 10:31:03,005 - 6786 - hummingbot.strategy.twap.twap - INFO - (DOGE-USDT) Cancelling the limit order x-XEKWYICX-BDEUT1624588203005905. [clock=2021-06-25 02:31:03+00:00]
2021-06-25 10:31:03,214 - 6786 - hummingbot.strategy.twap.twap - INFO - Updating status after order cancel (id: x-XEKWYICX-BDEUT1624588203005905) [clock=2021-06-25 02:31:03+00:00]
2021-06-25 10:31:03,214 - 6786 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1624588263.0, "order_id": "x-XEKWYICX-BDEUT1624588203005905", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "binance"}
```

**Review by Nullably — APPROVED** [review]
LGTM

**Comment by aarmoa** [comment]
Hello @RC-13, thank you for the comments.
Since pending amount is still 200 DOGE according to the screenshot, the client should keep generating orders if the end time has not been reached. I will investigate this behavior.

**Comment by aarmoa** [comment]
@RC-13 the behavior you see there is caused by the delay time between creation of new orders. When using the time span execution that time is calculated as:
`creation_delta = (span_end_time - span_start_time) / initial_number_of_orders_to_create`
In this case the wait time was 5 minutes (20 minutes between start and end divided by 4 total orders). That means that the order creation would happen at:
- 10:15 -> as soon as the strategy starts executing the logic
- 10: 20 -> the second order
- 10:25 -> the third order
- 10:30 -> the fourth order
- 10:35 -> in this moment the strategy would try to generate a new order if the total amount to be traded has not been reached. But the time span already ended (the execution only takes place while current_time < end_time)

And that is why you will not see the application trying to create any more orders after 10:30:01. From 10:30:01 to 10:34:59 the strategy did not try to create an order because it was still waiting for 5 minutes after the last order. And from 10:35:00 onwards the time span execution condition will not allow the strategy to do anything else.

**Review by rapcmia — APPROVED** [review]
Tested and confirmed working ok. Approved on behalf of the QA team.

**Pull request merged**
