### PR TITLE
feat / live ui improvements

### PR DESCRIPTION
**Pull request by zappra**
Before submitting this PR, please make sure:

Your code builds clean without any errors or warnings
You are using approved title ("feat/", "fix/", "docs/", "refactor/")

A description of the changes proposed in the pull request:

Live UI Improvement. Creates a separate TextArea for rendering the live UI updates and adds this to the HSplit layout. This allows the main output area to persist, so you can use, and see the output of, other commands whilst a live update is active. When not active, the live output window occupies 1 line, plus separator, at the top of the left window split.

Live UI off:

Live UI on:

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramaaz) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by zappra** [comment]
Hey! How do I request a review for a PR?

**Comment by dennisocana** [comment]
Hey @zappra, thanks a lot for submitting this contribution. I will discuss internally with the team to review and test. I will keep you posted for updates.

**Comment by dennisocana** [comment]
@zappra would it be possible to use the upper part of the logs pane for the orderbook live update area instead? Not a lot of users are looking at the logs pane while the output pane is more useful especially when you want to view your current strategy configuration (`config` output) while the strategy / orderbook is running.

**Comment by zappra** [comment]
Let me investigate that..

**Comment by zappra** [comment]
@dennisocana changed as suggested - let me know what you think

new_live_pane

**Comment by dennisocana** [comment]
@zappra thanks again for this contribution! As @aarmoa mentioned, we provided a similar functionality in this release to display the order book output, but in the future it would also allow developers to add other command output in the tabs.

https://docs.hummingbot.io/release-notes/0.46.0/#client-ui-improvements

**Pull request closed without merging**
