### PR TITLE
docs / docker/tmux

### PR DESCRIPTION
**Pull request by PtrckM**
**Before submitting this PR, please make sure**:
- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**A description of the changes proposed in the pull request**:
- update tmux info

### CODE REVIEW

**Comment by PtrckM** [comment]
@Sirlupinwatson1 apt-get update doesn't actually install new versions of software. Instead, it updates the package lists for upgrades for packages that need upgrading, as well as new packages that have just come to the repositories.

**Comment by carlolm** [comment]
add to whitelist

**Comment by Sirlupinwatson1** [comment]
> @Sirlupinwatson1 apt-get update doesn't actually install new versions of software. Instead, it updates the package lists for upgrades for packages that need upgrading, as well as new packages that have just come to the repositories.

thanks for the reply with the explanation, I appreciate it

**Comment by carlolm** [comment]
test this please

**Pull request merged**
