### PR TITLE
fix/fees huobi

### LINKED ISSUE #2084: [BUG] Filled order fees are not recorded correctly
**Describe the bug**

Fees for orders that are filled are not recorded correctly for many connectors, instead of taking fees reported from exchange's API, the connectors call `c_get_fee` (which estimates fee). This results in incorrect fees stored on trades table (sqlite) and incorrect performance reported on `history` command.

This mistake was partly due to Binance connector had this bug which other connectors copied the code from. The bug was fixed on 29 December 2020 on Binance connector so connectors created after the date should not get affected.

Connectors which broadcast fee incorrectly on `OrderFilledEvent`:

- [ ] ~Kucoin~
- [x] Binance Perpetual Derivative
- [x] Bifinex
- [x] Coinbase Pro
- [x] Bittrex
- [ ] ~OkEx~
- [x] Huobi
- [ ] ~Beaxy~
- [x] FTX
- [ ] ~Blocktane~
- [ ] ~Coinzoom~
- [ ] ~DigiFinex~
- [x] Gate.io
- [ ] Liquid

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd1e7e) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by aarmoa**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
The PR include the required changes to consider the fees informed by the exchange when a trade takes place, instead of estimating them.
Partially closes #2084 

**Tests performed by the developer**:
Added new unit tests for the order fill process and the fees registration

**Tips for QA testing**:
Please check that partial and complete fills are working correctly in Huobi connector. Also verify if the fees are now being registered correctly.

### CODE REVIEW

**Comment by nikspz** [comment]
@aarmoa Upon checking with the team 
After start bot showing `ERROR - Cannot subscribe to user stream topic: trade.clearing#*`
image
image

**Comment by RC-13** [comment]
Posting for documentation: Filled trades are not recorded as well, similar case with Bittrex.

**Review by RC-13 — APPROVED** [review]
LGTM!

**Review by CrimsonJacket — APPROVED** [review]
Changes LGTM. Not sure why the trade stream wasnt included in the first place.

**Pull request merged**
