### PR TITLE
Fix/Client - `-h` and `--help` don't show help message on Hummingbot commands

### PR DESCRIPTION
**Pull request by mhrvth**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

- [-h] and [--help] options are not filtered out for dropdowns anymore
- help is printed for the particular command whenever an option [--help] or [-h] is provided

**Tests performed by the developer**:

- Ran the client, displayed dropdown for various commands, used the [-h] and [--help] options to print help for the particular command

### CODE REVIEW

**Comment by mhrvth** [comment]
[sc-21086]

**Review by petioptrv — APPROVED** [review]
Changes LGTM!

**Comment by rapcmia** [comment]
Tested the latest commit and confirmed the `tab_example` and `order_book` commands now return -h and --help message.
image

However the `spreads` return `invalid number of arguments for shortcut`
image

**Review by rxlxrxsx — APPROVED** [review]
Tested and confirmed working by QA.

Test performed:

- Ran all commands with [-h] and [--help] options and confirmed that help info is printed after running the command
- Confirmed that [-h] and [--help] options are now showing on dropdown on various commands
- Confirmed that all reported issues are now fixed

**Review by petioptrv — APPROVED** [review]
Changes LGTM

**Comment by mhrvth** [comment]
Created a PR in the Foundation repo: https://github.com/hummingbot/hummingbot/pull/4998

**Pull request closed without merging**
