### PR TITLE
HitBTC Exchange Connector

### PR DESCRIPTION
**Pull request by sanchaymittal**
**Before submitting this PR, please make sure**:
- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue:
- Related Clubhouse Story:

**A description of the changes proposed in the pull request**:
Exchange Connector for HitBTC, Request consists of first task completion, which includes Data Source and Order Book Tracker. Eagerly waiting for feedback and suggestions.

### CODE REVIEW

**Comment by nionis** [comment]
hey @sanchaymittal, I can see from the commits you have used the source code of my bitcoin.com connector [PR](https://github.com/CoinAlpha/hummingbot/pull/1015).
I have absolutely no issue with it, I just want to make sure this PR is not a submission for this contest https://github.com/CoinAlpha/hummingbot/issues/991 since I see you have applied as a contestant.

**Comment by sanchaymittal** [comment]
Hey @nionis, I understand your concern related to #991 but worry not this isn't related to your task moreover the code uses standard exchanges as a template as per the instructions. I checked your submission for #991 and backed out after burning two days of oil. Also, APIs for both the exchanges are pretty much similar and template too.

**Comment by nionis** [comment]
@sanchaymittal thanks for understanding, feel free to poke me on discord for any help you may need!

**Comment by carlolm** [comment]
@sanchaymittal please review the contributing guide on conventions such as on labeling commits & pull requests:
https://github.com/CoinAlpha/hummingbot/blob/master/CONTRIBUTING.md

**Comment by sanchaymittal** [comment]
@carlolm Thanks, didn't check the instructions. Here #1039 created another pull request, under the guidelines.

**Pull request closed without merging**
