### PR TITLE
fix/ several issues with API throttler not throttling as expected

### PR DESCRIPTION
**Pull request by CrimsonJacket**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This PR will address several issues found within the API throttler. 
Note that this PR should not affect existing connectors with API throttler.

The connectors below will need to be refactored to include the above changes
- [x] Ndax
- [x] AscendEx
- [x] Gateio
- [x] Crypto.com
 Note: Crypto.com connector has rate limits per endpoint. As such it should not be affected.

Below are the improvements:
- Tasks with no related limits will no longer block the Throttler.
- Calculation of capacity will now be done with the correct weights.
- Reduce the encapsulated code within the async lock.

**Tests performed by the developer**:
- Introduced a new data class, `LinkedLimitWeightPair`
- Made modifications to `within_capacity()` and `get_related_limit()` functions in `async_throttler.py`
- Update relevant unit tests.

**Tips for QA testing**:
- Test that existing connectors with API throttler still works as intended

### CODE REVIEW

**Comment by RC-13** [comment]
@CrimsonJacket I'm getting the following connection issue with Ascendex, NDAX and Crypto_com are okay. 
image
```python
2021-09-10 11:23:26,614 - 7143 - hummingbot.core.utils.trading_pair_fetcher - ERROR - Connector ascend_ex failed to retrieve its trading pairs. Trading pairs autocompletion won't work.
Traceback (most recent call last):
  File "/Users/clintgogoc/Desktop/github/api-throttler/hummingbot/core/utils/trading_pair_fetcher.py", line 56, in call_fetch_pairs
    self.trading_pairs[exchange_name] = await fetch_fn
  File "/Users/clintgogoc/Desktop/github/api-throttler/hummingbot/connector/exchange/ascend_ex/ascend_ex_api_order_book_data_source.py", line 89, in fetch_trading_pairs
    async with throttler.execute_task(CONSTANTS.TICKER_PATH_URL):
  File "/Users/clintgogoc/Desktop/github/api-throttler/hummingbot/core/api_throttler/async_throttler.py", line 61, in execute_task
    rate_limit, related_rate_limits = self.get_related_limits(limit_id=limit_id)
  File "/Users/clintgogoc/Desktop/github/api-throttler/hummingbot/core/api_throttler/async_throttler_base.py", line 78, in get_related_limits
    related_limits = [(self._id_to_limit_map[limit_weight_pair.limit_id], limit_weight_pair.weight)
  File "/Users/clintgogoc/Desktop/github/api-throttler/hummingbot/core/api_throttler/async_throttler_base.py", line 80, in <listcomp>
    if limit_weight_pair.limit_id in self._id_to_limit_map]
AttributeError: 'str' object has no attribute 'limit_id'
```

**Review by petioptrv — COMMENTED** [review]
Couple of documentation issues aside, changes LGTM

**Review by petioptrv — APPROVED** [review]
The changes LGTM

**Review by PtrckM — APPROVED** [review]
LGTM no issues found during testing. Approving in behalf of QA

**Pull request merged**
