### PR TITLE
docs / add MAC mismatch guide

### PR DESCRIPTION
**Pull request by rennel-tabing**
**Before submitting this PR, please make sure**:
- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue:
- Related Clubhouse Story:

**A description of the changes proposed in the pull request**:

Add a guide on how to troubleshoot MAC mismatch error

image

### CODE REVIEW

**Comment by sigit2306** [comment]
Regarding what @dennisocana mentioned on to make it straightforward for users (including non-technical). 
Please add these words above/before the error message. Hopefully, it may help users easily understand the cause:
`This error is usually caused by having multiple encrypted keys with different passwords in the same config folder. For example, when you copy the encrypted API and secret key from instance1 with password 1234 to instance2 with existing password 5678 you will get this error.`

and add these words after the error message:
`To fix this, delete the API and secret key encrypted with a different password then re-add them by doing a connect [exchange] command from the Hummingbot client.`

**Comment by rennel-tabing** [comment]
> @rennel-tabing addressing what @dennisocana mentioned on to make it straightforward for users (including non-technical).
> Please add these words above/before the error message. Hopefully, it may help users easily understand the cause:
> `This error is usually caused by having multiple encrypted keys with different passwords in the same config folder. For example, when you copy the encrypted API and secret key from instance1 with password 1234 to instance2 with existing password 5678 you will get this error.`
> 
> and add these words after the error message:
> `To fix this, delete the API and secret key encrypted with a different password then re-add them by doing a connect [exchange] command from the Hummingbot client.`

Thank you for the suggestion. I will remove my previous instructions just to keep the guide as short as possible.
Please check if the updated guide will suffice.

image

**Comment by dennisocana** [comment]
@rennel-tabing you can delete just the copied API key that has a password different from the instance's existing password instead of deleting all of them. Also to avoid making the process tedious if they have a lot of API keys added. See example below.

Instance1
Password : 1234
API key/s : Binance

Instance2
Password : 5678
API key/s : Bittrex, Coinbase Pro, Eterbase, Kraken, Huobi

Copying encrypted Binance key file from Instance1 to Instance2 will result to a MAC mismatch error. To fix this:

1. Delete just the `encrypted_binance_api/secret_key.json` from Instance2's `conf` folder
2. Restart Hummingbot and password should still be 5678
3. Run `connect binance` and add the API keys - this will encrypt the keys with 5678 password and make it synced with the rest of the API keys

**Comment by rennel-tabing** [comment]
> @rennel-tabing you can delete just the copied API key that has a password different from the instance's existing password instead of deleting all of them. Also to avoid making the process tedious if they have a lot of API keys added. See example below.
> 
> Instance1
> Password : 1234
> API key/s : Binance
> 
> Instance2
> Password : 5678
> API key/s : Bittrex, Coinbase Pro, Eterbase, Kraken, Huobi
> 
> Copying encrypted Binance key file from Instance1 to Instance2 will result to a MAC mismatch error. To fix this:
> 
> 1. Delete just the `encrypted_binance_api/secret_key.json` from Instance2's `conf` folder
> 2. Restart Hummingbot and password should still be 5678
> 3. Run `connect binance` and add the API keys - this will encrypt it with 5678 password and sync it with the rest of the API keys

I have drafted a new entry that looks like the following.
image

`2. Restart Hummingbot and password should still be 5678` - the steps mentioned is not needed if you just removed the api keys/secret from the other hummingbot instance

Let me know your inputs. Thank you.

**Pull request closed without merging**
