### PR TITLE
fix/ fix AscendEx NoOpenForCancel error

### PR DESCRIPTION
**Pull request by CrimsonJacket**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Fixes #4738
Investigation Notes:
- Error seems to only appear when an order is filled(on the exchange) and a cancellation request is sent before the WS order update is received and processed. 

Include a LIMIT to prevent connector from immediately calling `stop_tracking_order` upon receiving a `NoOpenForCancel` error from the AscendEx API.

**Tests performed by the developer**:
Included a new limit and included exceed limit checks in the `_process_order_message()` function

**Tips for QA testing**:
The `NoOpenForCancel` error will still be logged, however, ensure that order fills are still being recorded.

### CODE REVIEW

**Comment by RC-13** [comment]
For confirmation, when running multiple bots using different or same markets. Each bot encounters the following sample error message:
image

If we check the logs, it doesn't give additional details. Is this a debugging message?
```python
2021-12-20 07:52:31,702 - 2307 - hummingbot.connector.client_order_tracker - ERROR - Order is not/no longer being tracked. OrderUpdate(trading_pair='QRDO/USDT', update_timestamp=1639957967115, new_state=<OrderState.CANCELLED: 3>, client_order_id=None, exchange_order_id='HMBot17dd51c3b70U9496830767VFcFG', trade_id=None, fill_price=Decimal('0'), executed_amount_base=Decimal('0'), executed_amount_quote=Decimal('0'), fee_asset='USDT', cumulative_fee_paid=Decimal('0'), trade_fee_percent=None)
NoneType: None
2021-12-20 07:52:31,704 - 2307 - hummingbot.connector.client_order_tracker - ERROR - Order is not/no longer being tracked. OrderUpdate(trading_pair='QRDO/USDT', update_timestamp=1639957967115, new_state=<OrderState.CANCELLED: 3>, client_order_id=None, exchange_order_id='HMBot17dd51c3b72U9496830767yXLEN', trade_id=None, fill_price=Decimal('0'), executed_amount_base=Decimal('0'), executed_amount_quote=Decimal('0'), fee_asset='USDT', cumulative_fee_paid=Decimal('0'), trade_fee_percent=None)
NoneType: None
2021-12-20 07:52:38,684 - 2307 - hummingbot.connector.client_order_tracker - ERROR - Order is not/no longer being tracked. OrderUpdate(trading_pair='QRDO/USDT', update_timestamp=1639957973955, new_state=<OrderState.OPEN: 1>, client_order_id=None, exchange_order_id='HMBot17dd51cbc30U94968307670Qwhe', trade_id=None, fill_price=Decimal('0'), executed_amount_base=Decimal('0'), executed_amount_quote=Decimal('0'), fee_asset='USDT', cumulative_fee_paid=Decimal('0'), trade_fee_percent=None)
NoneType: None
2021-12-20 07:52:38,685 - 2307 - hummingbot.connector.client_order_tracker - ERROR - Order is not/no longer being tracked. OrderUpdate(trading_pair='QRDO/USDT', update_timestamp=1639957973955, new_state=<OrderState.OPEN: 1>, client_order_id=None, exchange_order_id='HMBot17dd51cbc31U94968307671Spof', trade_id=None, fill_price=Decimal('0'), executed_amount_base=Decimal('0'), executed_amount_quote=Decimal('0'), fee_asset='USDT', cumulative_fee_paid=Decimal('0'), trade_fee_percent=None)
NoneType: None
```
We confirm that there are no orphaned orders.

**Comment by rxlxrxsx** [comment]
Similar to the one reported above, this error message appears when running multiple bots using different or same markets. This error however is generated on the `hummingbot.connector.client_order_tracker` module.

Screen Shot 2021-12-20 at 10 23 30 AM

```python
2021-12-20 10:23:25,189 - 2414 - hummingbot.connector.client_order_tracker - ERROR - Order is not/no longer being tracked. OrderUpdate(trading_pair='BTC/USDT', update_timestamp=1639967005221, new_state=<OrderState.CANCELLED: 3>, client_order_id=None, exchange_order_id='HMBot17dd5a65eb6U8715390223Uv1ym', trade_id=None, fill_price=Decimal('0'), executed_amount_base=Decimal('0'), executed_amount_quote=Decimal('0'), fee_asset='USDT', cumulative_fee_paid=Decimal('0'), trade_fee_percent=None)
NoneType: None
```

Logs and config: [ascendex.zip](https://github.com/CoinAlpha/hummingbot/files/7742203/ascendex.zip)

**Comment by dennisocana** [comment]
Closed and reopened to trigger the workflow validation process.

**Comment by aarmoa** [comment]
@RC-13 @rxlxrxsx Thank you for the details. As you mentioned in your comments, the error was not really an error. The code was prepared to log an error when an update was received for an order that was not tracked by the client. But when a user connects more than one client to the same account and exchange, all clients will receive the updates that are sent for the others (that is, for orders it is not tracking). I have change the code to make the log in these cases a DEBUG log, because it is an expected situation and we should not alarm the user.

**Comment by aarmoa** [comment]
After reviewing the code I have added some changes to ensure we create fill events always getting the fill amount, price and fees directly from the update sent by the exchange, and not to take it from the inflight order. This is required to prevent the fill event to use information that could have been modified in the inflight order by some of the async parallel processes running in the client.
@RC-13 @rxlxrxsx please go ahead and perform an extra test for order updates and order fills

**Review by aarmoa — APPROVED** [review]
Changes look good to me. But we need a second opinion for the commits I made.

**Comment by RC-13** [comment]
Confirming that the reported issue above has been fixed on the latest commit, however, we are seeing an API error wherein the bot is unable to track the order, sometimes this results in leaving some orders uncancelled in the exchange:
```python
Traceback (most recent call last):
  File "/home/clint_g/ascendex/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 671, in _status_polling_loop
    await safe_gather(
  File "/home/clint_g/ascendex/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/clint_g/ascendex/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 731, in _update_order_status
    resp = await self._api_request(
  File "/home/clint_g/ascendex/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 424, in _api_request
    raise IOError(f"{url} API call failed, response: {parsed_response}")
OSError: https://ascendex.com/6/api/pro/v1/cash/order/status API call failed, response: {'code': 300006, 'message': 'Unable to find orderId', 'reason': 'INVALID_ORDER_ID'}
2021-12-21 12:22:50,400 - 25913 - hummingbot.connector.exchange.ascend_ex.ascend_ex_exchange - WARNING - Could not fetch account updates from AscendEx. Check API key and network connection.
```
It's quite difficult to replicate the behavior but it seems that it occurs when running multiple bots using the same account and API key. We attempted to replicate the behavior in the development branch by running 2 bots for 2 hours however we are unable to see the API error.
[logs_stuck-order-1.log](https://github.com/CoinAlpha/hummingbot/files/7749574/logs_stuck-order-1.log)
[logs_stuck-order-12.log](https://github.com/CoinAlpha/hummingbot/files/7749582/logs_stuck-order-12.log)

**Comment by aarmoa** [comment]
After a discussion with @petioptrv I have decided it is better to undo the changes I added to fix the possible issue with async executions. We realized that the code I was doubting about executes always synchronously. I will discuss this further with @CrimsonJacket before making changes

**Comment by rapcmia** [comment]
Tested the latest commit and got orders stuck after getting this error of `Failed to cancel all orders on Ascendex, Check API and network connection`. Tried to execute the `stop` command twice to check after a minute but no go. When you start the bot again, it doesn't recognize the stuck orders even after the set refresh time (expecting to cancel all orders), then it just repeats the issue again.

https://user-images.githubusercontent.com/73840223/146944685-8c35de1b-0063-43e5-b137-57b37dca4f14.mp4

```
2021-12-21 14:06:11,967 - 26148 - hummingbot.connector.exchange.ascend_ex.ascend_ex_exchange - NETWORK - Failed to cancel all orders.
Traceback (most recent call last):
  File "/home/ubuntu/github/6/hummingbot/core/data_type/in_flight_order.py", line 259, in get_exchange_order_id
    await self.exchange_order_id_update_event.wait()
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/asyncio/locks.py", line 309, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/github/6/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 787, in cancel_all
    "orders": [
  File "/home/ubuntu/github/6/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 790, in <listcomp>
    "orderId": await order.get_exchange_order_id(),
  File "/home/ubuntu/github/6/hummingbot/core/data_type/in_flight_order.py", line 259, in get_exchange_order_id
    await self.exchange_order_id_update_event.wait()
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
2021-12-21 14:06:11,967 - 26148 - hummingbot.connector.exchange.ascend_ex.ascend_ex_exchange - WARNING - Failed to cancel all orders on AscendEx. Check API key and network connection.
```

Also, there are instances of the bot getting this error upon executing the `start` command. 
Screenshot 2021-12-21 214602

```
2021-12-21 13:45:30,347 - 25749 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2021-12-21 13:45:30,644 - 25749 - hummingbot.connector.exchange.ascend_ex.ascend_ex_exchange - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2021-12-21 13:45:30,833 - 25749 - hummingbot.connector.exchange.ascend_ex.ascend_ex_order_book_tracker - INFO - Initialized order book for QRDO-USDT. 1/1 completed.
2021-12-21 13:45:31,025 - 25749 - hummingbot.connector.exchange.ascend_ex.ascend_ex_api_order_book_data_source - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
2021-12-21 13:45:31,025 - 25749 - hummingbot.connector.exchange.ascend_ex.ascend_ex_api_order_book_data_source - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/ubuntu/github/6/hummingbot/connector/exchange/ascend_ex/ascend_ex_api_order_book_data_source.py", line 205, in listen_for_subscriptions
    ws = await self._subscribe_to_order_book_streams()
  File "/home/ubuntu/github/6/hummingbot/connector/exchange/ascend_ex/ascend_ex_api_order_book_data_source.py", line 164, in _subscribe_to_order_book_streams
    ws = await self._shared_client.ws_connect(url=CONSTANTS.WS_URL,
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 769, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 502, message='Invalid response status', url=URL('wss://ascendex.com/0/api/pro/v1/stream')
```

Tested on both local and AWS getting the same results. The issue does not happen on dev branch.

Steps to reproduce:
1. Create PMM for AscendEx( Tested one or two bots running at the same API with different markets)
2. Start the bot, execute `status --live`
3. Stop the bot, check the connector (refresh the page to make sure)

Logs and config file:
[pmm-qrdo.zip](https://github.com/CoinAlpha/hummingbot/files/7756193/pmm-qrdo.zip)

**Comment by aarmoa** [comment]
Hello @rapcmia. The changes I have made were done before seeing the issue you commented. I will now investigate it. If you find more cases of orders that are left alive in the server it will be very helpful for the investigation if you could add their IDs to the report.

**Comment by aarmoa** [comment]
@rapcmia regarding the error after the start command, that seems to be an error in a part of the code that has not been changed in this PR. Could we validate the error is not caused by the exchange by checking it does not happen in the current development version?

**Comment by RC-13** [comment]
Re-tested the PR on the latest commit and still seeing an API error and leave an order uncancelled in the client.  Upon checking further into the logs, it appears that the order which is causing the error wasn't submitted in the exchange.
Order ID: `HMBot-BAVAUSD1640130673001776`
```python
2021-12-21 23:51:13,001 - 23025 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (AVAX-USDT) Creating 1 bid orders at (Size, Price): ['0.1 AVAX, 123.55 USDT']
2021-12-21 23:51:13,001 - 23025 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (AVAX-USDT) Creating 1 ask orders at (Size, Price): ['0.1 AVAX, 123.72 USDT']
2021-12-21 23:51:13,104 - 23025 - hummingbot.connector.exchange.ascend_ex.ascend_ex_exchange - ERROR - Error submitting BUY LIMIT_MAKER order to AscendEx for 0.100 AVAX-USDT 123.55.
Traceback (most recent call last):
  File "/home/ubuntu/ascendex/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 538, in _create_order
    resp = await self._api_request(
  File "/home/ubuntu/ascendex/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 425, in _api_request
    raise IOError(f"{url} API call failed, response: {parsed_response}")
OSError: https://ascendex.com/6/api/pro/v1/cash/order API call failed, response: {'code': 300011, 'message': 'Not Enough Account Balance', 'reason': 'INVALID_BALANCE', 'accountId': 'cshrDwJt4MmbOPZl3pt5StX2zg2B7uSe', 'ac': 'CASH', 'action': 'place-order', 'status': 'Err', 'info': {'id': 'HMBot-X5ODzx9RdsWlFhXJpDthIXBArM', 'symbol': 'AVAX/USDT'}}
2021-12-21 23:51:13,153 - 23025 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER SELL order HMBot-SAVAUSD1640130673002061 for 0.100 AVAX-USDT.
2021-12-21 23:51:13,163 - 23025 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1640130673154, "type": "OrderType.LIMIT_MAKER", "trading_pair": "AVAX-USDT", "amount": "0.100", "price": "123.72", "order_id": "HMBot-SAVAUSD1640130673002061", "exchange_order_id": "HMBot17ddf67f96cU94968307671mCBK", "leverage": 1, "position": "NILL", "event_name": "SellOrderCreatedEvent", "event_source": "ascend_ex"}
2021-12-21 23:51:14,001 - 23025 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (AVAX-USDT) Cancelling the limit order HMBot-BAVAUSD1640130673001776. [clock=2021-12-21 23:51:14+00:00]
2021-12-21 23:51:14,002 - 23025 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (AVAX-USDT) Cancelling the limit order HMBot-SAVAUSD1640130673002061. [clock=2021-12-21 23:51:14+00:00]
2021-12-21 23:51:14,125 - 23025 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1640130674114, "order_id": "HMBot-SAVAUSD1640130673002061", "exchange_order_id": "HMBot17ddf67f96cU94968307671mCBK", "event_name": "OrderCancelledEvent", "event_source": "ascend_ex"}
2021-12-21 23:51:14,125 - 23025 - hummingbot.connector.client_order_tracker - INFO - Successfully cancelled order HMBot-SAVAUSD1640130673002061.
2021-12-21 23:51:24,003 - 23025 - hummingbot.connector.exchange.ascend_ex.ascend_ex_exchange - ERROR - Failed to cancel order HMBot-BAVAUSD1640130673001776: 
Traceback (most recent call last):
  File "/home/ubuntu/ascendex/hummingbot/core/data_type/in_flight_order.py", line 260, in get_exchange_order_id
    await self.exchange_order_id_update_event.wait()
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/asyncio/locks.py", line 309, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/ascendex/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 644, in _execute_cancel
    ex_order_id = await tracked_order.get_exchange_order_id()
  File "/home/ubuntu/ascendex/hummingbot/core/data_type/in_flight_order.py", line 260, in get_exchange_order_id
    await self.exchange_order_id_update_event.wait()
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
2021-12-21 23:51:30,122 - 23025 - hummingbot.connector.exchange.ascend_ex.ascend_ex_exchange - ERROR - There was an error requesting updates for the active orders ({})
Traceback (most recent call last):
  File "/home/ubuntu/ascendex/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 736, in _update_order_status
    resp = await self._api_request(
  File "/home/ubuntu/ascendex/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 425, in _api_request
    raise IOError(f"{url} API call failed, response: {parsed_response}")
OSError: https://ascendex.com/6/api/pro/v1/cash/order/status API call failed, response: {'code': 100004, 'message': 'Invalid value for argument orderId: orderId length must be between 0 and 1000', 'reason': 'INVALID_REQUEST_DATA'}
2021-12-21 23:51:30,124 - 23025 - hummingbot.connector.exchange.ascend_ex.ascend_ex_exchange - ERROR - https://ascendex.com/6/api/pro/v1/cash/order/status API call failed, response: {'code': 100004, 'message': 'Invalid value for argument orderId: orderId length must be between 0 and 1000', 'reason': 'INVALID_REQUEST_DATA'}
```
avax-order-remain-in-client

**Comment by aarmoa** [comment]
@RC-13 I have added more logic in the connector to clean the orders that are tracked but are never confirmed in the exchange. The cleanup is not done the first time the inconsistency is detected. It takes 3 order update periods for the connector to be confident that the order will never be valid and remove it.

**Review by RC-13 — APPROVED** [review]
LGTM! Tested and confirmed working by QA.
Test performed:
- Run multiple bots for a long duration and confirmed that previously reported issues no longer persist.
- Set two bots to refresh order every one second, while the other one refreshes every 5 sec.
- Confirmed that orders are canceled and created according to the specified parameter. 
- Verify that both full and partial fills are recorded and match the record in the exchange.
- Confirmed that the fee deducted in each trade matches the fee shown in the exchange.
- Confirm no stuck order/s in the exchange.
- Reviewed the three logs and didn't hit any error.
- Other test bots run by other QA members encounter a failure to submit an order message but due to insufficient balance.

**Comment by aarmoa** [comment]
[ch21116]

**Review by petioptrv — APPROVED** [review]
The additional changes LGTM!

**Comment by aarmoa** [comment]
I have created the following PR in the official repo https://github.com/hummingbot/hummingbot/pull/4960
I am closing now the CoinAlpha PR

**Pull request closed without merging**
