### PR TITLE
Fix/TWAP - fix issues found in RFOX

### PR DESCRIPTION
**Pull request by mhrvth**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

- Small fixes for issues in TWAP found while working on the RFOX project

**Tests performed by the developer**:

- Ran unit tests

### CODE REVIEW

**Comment by mhrvth** [comment]
[sc-23099]

**Review by RC-13 — APPROVED** [review]
LGTM
Test Summary:
- Run unit test: All tests passed
- Run a TWAP strategy and confirmed no issue with creating, importing, and starting the strategy.
- Confirmed that orders are canceled and created according to the specified parameters
- Confirmed that all trades are recorded
- Check the history and confirmed that the total fee matches the total fee of each individual trades
- Test start time and end time: Ok

**Review by petioptrv — APPROVED** [review]
Changes LGTM!

**Comment by mhrvth** [comment]
Created a PR in the Foundation repo: https://github.com/hummingbot/hummingbot/pull/5119

**Pull request closed without merging**
