### PR TITLE
Feat / update config command and config validation

### PR DESCRIPTION
**Pull request by Nullably**
**Before submitting this PR, please make sure**:
- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue:
- Related Clubhouse Story: 8035, 8085, 8016

**A description of the changes proposed in the pull request**:
- `config` command now lists config parameter values, global (subset) and strategy.
- `config` also accepts 2 arguments, config key name and config value. This is to update the config.
- New inventory skew question at the end of `create` process
- Display meaningful error messages when config validation fails. Updated all validation function to return a string (error message) instead of a boolean.

### CODE REVIEW

**Comment by Nullably** [comment]
@mifeng 
> Don't show the default value for any configuration question, except the last one with the configuration file name. When answering the questions, it may be confusing which ones have the default value and which ones don't. It's better to not show the default value for all questions.

You mean on the `create` command only or `config [parameter]` as well? If the user just hits enter, should that triggers default value?

**Comment by Nullably** [comment]
@mifeng 
> Add the asset balances to the inventory skew question so that user knows we're fetching their asset balances:

Done.

For the defaults, I removed them for the configs during `create`

**Comment by Nullably** [comment]
run tests

**Comment by mifeng** [comment]
Yes, remove defaults for `create` only is what i meant.

**Pull request merged**
