### PR TITLE
docs / add paper trade supported

### PR DESCRIPTION
**Pull request by Hashira-Lars**
**Before submitting this PR, please make sure**:
- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue: https://github.com/CoinAlpha/hummingbot/pull/1344
- Related Clubhouse Story:

**A description of the changes proposed in the pull request**:
- update docs supported paper trade

### CODE REVIEW

**Comment by carlolm** [comment]
test this please

**Comment by Hashira-Lars** [comment]
Test Results : 

asdfsadfsa

**Comment by carlolm** [comment]
test this please

**Comment by carlolm** [comment]
test this please

**Comment by yzhang1994** [comment]
add to whitelist

**Pull request merged**
