### PR TITLE
Fix / binance trading pair split error

### PR DESCRIPTION
**Pull request by Nullably**
…first

**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**After creating this PR, please make sure:**

- [ ] You link the related GitHub issue or ticket

**A description of the changes proposed in the pull request**:
- Split the quote tokens into 4 and 3 letters group, try to match the longer one first.
- This is a better way to fix #2660

### CODE REVIEW

**Comment by rxlxrxsx** [comment]
Tested and confirmed fix by QA.

**Review by sdgoh — DISMISSED** [review]
LGTM

**Review by dennisocana — APPROVED** [review]
LGTM

**Review by dennisocana — APPROVED** [review]

**Review by carlolm — APPROVED** [review]
LGTM

**Pull request merged**
