### PR TITLE
refactor/NDAX stale orders

### PR DESCRIPTION
**Pull request by petioptrv**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This PR improves order handling for NDAX. The changes are inspired by the AscendEX exchange implementation.

A new order status is added ("WorkingLocal"), which indicates that the server has successfully received the order request, but that the order has not yet been confirmed. Triggering an order created event is delayed until the server sends a websocket update with a "Working" status for the newly-created order. The `_status_polling_loop` will start polling for the order's status only once the confirmation that the order is fully created on the server is received.

**Tests performed by the developer**:
Unit test that checks if the exchange will set the correct status on websocket update from the server.

**Tips for QA testing**:
Check that orders are successfully submitted and tracked, and that failed orders are successfully removed from the tracked ones. It's possible to have the order be rejected by inserting `amount = trading_rule.min_order_size * Decimal("0.9")` on line 396 of `ndax_exchange.py`.

### CODE REVIEW

**Comment by rapcmia** [comment]
While testing it on Pure market making, there are instances that the bot fails to cancel one of the orders and then I start the bot again getting an error log of `...resource not found..` This only happens when it failed to cancel one of the orders even when you tried to stop/exit then open/start the bot again. 

Steps to reproduce:
1. Create a simple Pure market making strategy (I used USDT-CAD)
2. Start the bot, then stop whenever you want (or stop/exit and relaunch the bot again)
3. When you stop the bot, check if it successfully canceled one of the orders, then start again
4. An error about failed to cancel should appear on the logs

```

2021-08-17 19:02:52,930 - 4640 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2021-08-17 19:02:53,013 - 4640 - hummingbot.connector.exchange.ndax.ndax_exchange - ERROR - Error fetching data from https://api.ndax.io:8443/AP/CancelOrder. HTTP status is 200. Message: {'result': False, 'errormsg': 'Resource Not Found', 'errorcode': 104, 'detail': None} Params: None Data: {"result":false,"errormsg":"Resource Not Found","errorcode":104,"detail":null}
2021-08-17 19:02:53,014 - 4640 - hummingbot.connector.exchange.ndax.ndax_exchange - ERROR - Failed to cancel order 1629198136008723: Error fetching data from https://api.ndax.io:8443/AP/CancelOrder. HTTP status is 200. Message: {'result': False, 'errormsg': 'Resource Not Found', 'errorcode': 104, 'detail': None} Params: None Data: {"result":false,"errormsg":"Resource Not Found","errorcode":104,"detail":null}
2021-08-17 19:02:53,014 - 4640 - hummingbot.connector.exchange.ndax.ndax_exchange - NETWORK - Failed to cancel order 1629198136008723: Error fetching data from https://api.ndax.io:8443/AP/CancelOrder. HTTP status is 200. Message: {'result': False, 'errormsg': 'Resource Not Found', 'errorcode': 104, 'detail': None} Params: None Data: {"result":false,"errormsg":"Resource Not Found","errorcode":104,"detail":null}
Traceback (most recent call last):
  File "C:\Users\Ralph\github\3946\hummingbot\connector\exchange\ndax\ndax_exchange.py", line 535, in _execute_cancel
    await self._api_request(
  File "C:\Users\Ralph\github\3946\hummingbot\connector\exchange\ndax\ndax_exchange.py", line 343, in _api_request
    raise Exception(f"Error fetching data from {url}. HTTP status is {response.status}. "
Exception: Error fetching data from https://api.ndax.io:8443/AP/CancelOrder. HTTP status is 200. Message: {'result': False, 'errormsg': 'Resource Not Found', 'errorcode': 104, 'detail': None} Params: None Data: {"result":false,"errormsg":"Resource Not Found","errorcode":104,"detail":null}
2021-08-17 19:02:53,014 - 4640 - hummingbot.connector.exchange.ndax.ndax_exchange - WARNING - Failed to cancel order 1629198136008723 on NDAX. Check API key and network connection.
2021-08-17 19:02:53,192 - 4640 - hummingbot.connector.exchange.ndax.ndax_exchange - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2021-08-17 19:02:54,268 - 4640 - hummingbot.connector.exchange.ndax.ndax_api_user_stream_data_source - INFO - Authenticating to User Stream...
2021-08-17 19:02:54,527 - 4640 - hummingbot.connector.exchange.ndax.ndax_order_book_tracker - INFO - Initialized order book for USDT-CAD. 1/1 completed.
```

Here's a screenshot for reference:
error on stop 2

For multiple orders:
error on multiple orders


Checked Ndax and it looks like the bot orders are canceled at the same time
error on stop 3

Here is also another sample of the bot after I tried to stop and exit then open/start the bot again:
error on stop 4

Also, while running the bot with multiple orders there was this instance that it failed to create the ask orders when it has the available balance. This might be in line with the bot not able to catch the balance right away so it only created one side.

Here is the video for reference, the issue started at 1:00min

https://user-images.githubusercontent.com/73840223/129720696-2923e1db-bcb7-442f-8c73-1f229af39ca9.mp4

Attached:
[3946.zip](https://github.com/CoinAlpha/hummingbot/files/6999710/3946.zip)

**Review by aarmoa — DISMISSED** [review]
Changes look good to me

**Comment by petioptrv** [comment]
Investigated the possibility, suggested by @aarmoa, that triggering the order-created event asynchronously only once the server acknowledges the order via websocket may affect the strategies' operation. The only strategy that seems to be using the order-created event is cross-exchange mm. It uses an "order-pending" list and uses the event to pop orders from that list, so the behaviour is compatible.

**Comment by petioptrv** [comment]
@rapcmia thank you for testing. The issue recorded in the video doesn't seem to originate from the current code changes. I've opened a new issue #3951 to investigate the bug. Please look it over and add more details if need. I will circle back on the stop-start-order-cancelation-failure issue raised

**Review by rxlxrxsx — DISMISSED** [review]
Tested and confirmed working by QA.

**Review by rxlxrxsx — APPROVED** [review]

**Comment by petioptrv** [comment]
Created an issue to address the order-cancellation problem raised above: #3953. This issue occurs on the development branch as well.

**Review by aarmoa — APPROVED** [review]
I agree with the comment added to the event functions

**Pull request merged**
