### PR TITLE
fix / order of buy and sell variables for arbitrage strategy

### PR DESCRIPTION
**Pull request by shankinson**
I ran into [issue 3016](https://github.com/CoinAlpha/hummingbot/issues/3106) today when running the arbitrage bot.

On one exchange I was using the ETH-USDT pair and on the other, I was using the ETH-CAD pair. 

For exchange one, the best bid was 2056.72 and the best ask was 2056.73. For exchange two the best bid was 2611.56 and the best ask 2612.39.

The secondary_to_primary_base_conversion_rate was set to 1.0 and secondary_to_primary_quote_conversion_rate was set to 0.795228628230616.

If you take the ask on exchange one ( 2056.73 / 0.795228628230616 = 2586.34 ) and take the bid (2611.56) on exchange 2 there is about a 1% arbitrage (2611.56 - 2586.34 = 25.22). 

Humming Bot tried to execute the order, but it seemed to mix up the prices:
```
Error submitting BUY LIMIT order to Exchange 1 for 0.10870000 ETH-USDT 2611.56000000
``` 
^ didn't have enough USDT
```
EVENT_LOG - {"timestamp": 1617535675.0, "type": "OrderType.LIMIT", "trading_pair": "ETH-CAD", "amount": "0.1087", "price": "2056.73", "order_id": "7131617535675009", "exchange_order_id": "14984491360", "leverage": 1, "position": "NILL", "event_name": "SellOrderCreatedEvent", "event_source": "Exchange 2"}
```

It tried to buy on exchange 1 with the price from exchange 2 and sell on exchange 2 with the price from exchange 1.

I looked through the code and I think the buy_price and sell_price are reversed here; https://github.com/CoinAlpha/hummingbot/blob/master/hummingbot/strategy/arbitrage/arbitrage.pyx#L349

The buy price is being set to the bid_price and the sell price is being set to the ask_price (https://github.com/CoinAlpha/hummingbot/blob/master/hummingbot/strategy/arbitrage/arbitrage.pyx#L524), however, since we are being takers in this scenario we should be selling at the bid and buying at the ask, shouldn't we?

### CODE REVIEW

**Comment by Morrow98J** [comment]
Forwarding your PR to the right person

**Review by AntonioDelleCanne — APPROVED** [review]
Was having the same issue, tried with the modification in this pull request and the issue was fixed

**Review by PtrckM — APPROVED** [review]
Tested and confirmed working by QA.

**Review by Nullably — APPROVED** [review]
LGTM

**Pull request merged**
