### PR TITLE
cleanup / deprecate get_active_exchange_markets

### PR DESCRIPTION
**Pull request by vic-en**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

This task is to deprecate the `get_active_exchange_markets` function in the main connector file.

### CODE REVIEW

**Comment by dennisocana** [comment]
As mentioned by backend team, there are some legacy code that still use that function. Checking again to make sure we don't break anything in the backend.

**Comment by michaelc9** [comment]
LGTM. The changed methods are not used in exchange data fetchers, or other backend code base.

**Comment by dennisocana** [comment]
Setting this PR for code review estimation.

**Comment by petioptrv** [comment]
Resolved in #4374

**Pull request closed without merging**
