### PR TITLE
Fix/Exception when no command provided

### PR DESCRIPTION
**Pull request by mhrvth**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

- the client needs to check whether the command string is empty

**Tests performed by the developer**:

- ran the client, entered empty command (just press ENTER)

### CODE REVIEW

**Comment by mhrvth** [comment]
[sc-23092]

**Review by RC-13 — APPROVED** [review]
LGTM
Test summary
- Start the Hummingbot client and enter blank inputs and confirmed that we no longer gets any error.

**Review by petioptrv — APPROVED** [review]
Changes LGTM!

**Comment by mhrvth** [comment]
Created a PR in the Foundation repo: https://github.com/hummingbot/hummingbot/pull/5118

**Pull request closed without merging**
