### PR TITLE
Epic/ NDAX connector

### PR DESCRIPTION
**Pull request by aarmoa**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
The epic/ndax_connector branch is a grouping branch including al required changes to have a working connector for NDAX exchange.
Code reviews have been done to each independent branch merged into the epic, and is not required here.
This PR requires validation from QA

**Tip for QA testing**
In the client you will find two variants of the connector:
- ndax -> connector pointing to the production NDAX servers
- ndax_testnet -> the same connector pointing to the test NDAX servers

### CODE REVIEW

**Comment by aarmoa** [comment]
Note for QA: do not start to test this PR yet. I have found an issue that we need to solve first. I will discuss it with @CrimsonJacket

**Comment by rapcmia** [comment]
While testing Ndax (mainnet), there are instances that the bot has delays in creating orders. Usually, it takes 5 or 10s after the initialization but it happens that the bot will have more or less 2mins before it starts creating orders. 

Steps to reproduce
1. Create a basic PMM bot
2. Run for 2-3mins then try to stop then start again

delayed start 3

While stopping the bot I noticed that sometimes it does not show or one of the orders only shows successfully canceled then when you start the bot again (even when you stop/exit the bot), it will show that it successfully canceled the order which should be done earlier. Checked the Ndax portal and there are no active orders

The bot stops
Delayed cancel orders

Exit then start the bot again
Delayed cancel orders 2

On the screenshots below, it did not show that it canceled the order andwhen the bot starts again it shows it successfully canceled:
Delayed cancel orders 3
Delayed cancel orders 4


Tried to run multiple orders then stop/exit the bot. Waited for 8mins (checked Ndax and there are no active orders) and then start the bot again, you would see that the client will return log files that it successfully canceled orders. The screenshot below, also triggered the delay in creating orders

Stop then exit the bot
Delayed cancel orders with multiple order

Start the bot again
Delayed cancel orders with multiple order 2

Attached:
[3743.zip](https://github.com/CoinAlpha/hummingbot/files/6912580/3743.zip)

**Comment by RC-13** [comment]
Adding additional issues seen during testing, the test is done on the mainnet and using pure market-making strategy.
- Related to the canceling issue posted by @rapcmia, the bot fails to immediately return a successful confirmation for the cancel order, resulting in failing to immediately cancel orders. The cancelation issue may occur as well if there is a network interruption:
Note: the order refresh duration is 60 sec
NDAX-delay cancellation
ndax delay cancellation
- Random instances wherein the best price doesn't update despite price changes in the order book
ndax-best-price-mismatch
ndax-best-price-mismatch2
- Bot failed to fetch orders that were filled when an interruption takes place. This can result in incorrect data aggregate
Step to reproduce the issue:
1. Configure a PMM strategy and tight spread.
2.  Start the bot
3. Once orders are placed, temporary disconnect from the internet.
4. Monitor open orders using a different device to check if the filled event takes place.
5. Reconnect to network and check the history
missing trade
[ndax-trades.xlsx](https://github.com/CoinAlpha/hummingbot/files/6914078/ndax-trades.xlsx)
[logs_conf_pure_mm_1.log](https://github.com/CoinAlpha/hummingbot/files/6914085/logs_conf_pure_mm_1.log)
- Some trading pairs like BTC-USD, BTC-USDT, and MATIC-CAD are shown in the market autocomplete list but don't exist in the exchange. Using this market result in an unhandled error
image
```python
2021-08-02 10:56:46,360 - 8830 - hummingbot.connector.exchange.ndax.ndax_api_order_book_data_source - WARNING - Unexpected error with WebSocket connection. Retrying in 30 seconds. Check network connection.
2021-08-02 10:56:48,398 - 8830 - hummingbot.connector.exchange.ndax.ndax_api_order_book_data_source - ERROR - Unexpected error occured listening for orderbook snapshots. Retrying in 5 secs...
Traceback (most recent call last):
  File "/home/clint_g/ndax/hummingbot/connector/exchange/ndax/ndax_api_order_book_data_source.py", line 190, in listen_for_order_book_snapshots
    snapshot: Dict[str: Any] = await self.get_order_book_data(trading_pair, domain=self._domain)
  File "/home/clint_g/ndax/hummingbot/connector/exchange/ndax/ndax_api_order_book_data_source.py", line 143, in get_order_book_data
    "timestamp": max([entry.actionDateTime for entry in orderbook_entries])}
ValueError: max() arg is an empty sequence
2021-08-02 10:56:54,362 - 8830 - hummingbot.connector.exchange.ndax.ndax_api_order_book_data_source - ERROR - Unexpected error occured listening for orderbook snapshots. Retrying in 5 secs...
Traceback (most recent call last):
  File "/home/clint_g/ndax/hummingbot/connector/exchange/ndax/ndax_api_order_book_data_source.py", line 190, in listen_for_order_book_snapshots
    snapshot: Dict[str: Any] = await self.get_order_book_data(trading_pair, domain=self._domain)
  File "/home/clint_g/ndax/hummingbot/connector/exchange/ndax/ndax_api_order_book_data_source.py", line 143, in get_order_book_data
    "timestamp": max([entry.actionDateTime for entry in orderbook_entries])}
ValueError: max() arg is an empty sequence
```
[logs_conf_pure_mm_2-long-refresh.log](https://github.com/CoinAlpha/hummingbot/files/6914101/logs_conf_pure_mm_2-long-refresh.log)

**Comment by RC-13** [comment]
- Failing to submit order when NDAX is used as taker exchange:
image
```python
2021-08-02 11:25:57,412 - 9117 - hummingbot.connector.exchange.ndax.ndax_exchange - NETWORK - Error submitting SELL MARKET order to NDAX for 0.000300 BTC-CAD NaN. Error: Error fetching data from https://api.ndax.io:8443/AP/SendOrder. HTTP status is 200. Message: {'result': False, 'errormsg': 'TimeInForce was not specified', 'errorcode': 83, 'detail': None} Params: None Data: {'InstrumentId': 1, 'OMSId': 1, 'AccountId': 169418, 'ClientOrderId': 1627874757079850, 'Side': 1, 'Quantity': Decimal('0.000300'), 'OrderType': 1}
Traceback (most recent call last):
  File "/home/clint_g/ndax/hummingbot/connector/exchange/ndax/ndax_exchange.py", line 423, in _create_order
    send_order_results = await self._api_request(
  File "/home/clint_g/ndax/hummingbot/connector/exchange/ndax/ndax_exchange.py", line 338, in _api_request
    raise Exception(f"Error fetching data from {url}. HTTP status is {response.status}. "
Exception: Error fetching data from https://api.ndax.io:8443/AP/SendOrder. HTTP status is 200. Message: {'result': False, 'errormsg': 'TimeInForce was not specified', 'errorcode': 83, 'detail': None} Params: None Data: {'InstrumentId': 1, 'OMSId': 1, 'AccountId': 169418, 'ClientOrderId': 1627874757079850, 'Side': 1, 'Quantity': Decimal('0.000300'), 'OrderType': 1}
2021-08-02 11:25:57,413 - 9117 - hummingbot.connector.exchange.ndax.ndax_exchange - WARNING - Error submitting order to NDAX. 
```

**Comment by RC-13** [comment]
- Minor issue when using Avellaneda MM, and if the balance ratio is not equal, the bot seems to be trying to still place the other side of the order which is blocked since the size used is below the minimum requirement of the exchange.
image
```python
2021-08-02 13:27:13,004 - 11826 - hummingbot.connector.exchange.ndax.ndax_exchange - NETWORK - Error submitting BUY LIMIT_MAKER order to NDAX for 0.000099 BTC-CAD 49500.01. Error: BUY order amount 0.000099 is lower than the minimum order size 0.0001.
Traceback (most recent call last):
  File "/home/clint_g/ndax/hummingbot/connector/exchange/ndax/ndax_exchange.py", line 389, in _create_order
    raise ValueError(f"{trade_type.name} order amount {amount} is lower than the minimum order size "
ValueError: BUY order amount 0.000099 is lower than the minimum order size 0.0001.
2021-08-02 13:27:13,005 - 11826 - hummingbot.connector.exchange.ndax.ndax_exchange - WARNING - Error submitting order to NDAX. 
```
Can this be hidden similar to other exchanges? And also the delay when starting the strategy seem to be more frequent using Avellaneda MM as seen in the screen above (2 min delay).

**Comment by rxlxrxsx** [comment]
- When running using the liquidity_mining strategy it also takes some time (1-2 mins) before the bot starts to place orders, similar to the ones reported above for other strategies.

Screen Shot 2021-08-02 at 2 45 36 PM

- When running using the liquidity_mining strategy as well, after running the strategy for some time suddenly network status will become not connected, tried locally (currently also running on cloud and trying to reproduce the issue). It also looks like the bot will not self recover after waiting for around 20 minutes. 

Screen Shot 2021-08-02 at 2 35 49 PM

- When I stopped the strategy that seems to be stuck on not connected status one order got stuck and wasn't successfully cancelled. Restarting the strategy will also show  `ndax is ready. Trading started.` continuously.

Screen Shot 2021-08-02 at 2 36 27 PM
Screen Shot 2021-08-02 at 2 40 03 PM

Screen Shot 2021-08-02 at 2 38 27 PM

Logs and config: [ndax_lm.zip](https://github.com/CoinAlpha/hummingbot/files/6915355/ndax_lm.zip)

**Comment by rapcmia** [comment]
There are instances that the bot would return `Exchange check: Invalid connections..` while on preliminary checks or after importing the strategy/config 

Error on checking paramters in VPS

When stopping the bot from the TWAP strategy, I noticed that the bot does not cancel all orders created and left it active on the order book. Started the bot again and it did not recognize it and created a new set of orders (the account has enough balance to continue). Then I tried to stop the bot again and it successfully canceled the order on the first instance however failed again to cancel another order. Please see the recording below started at 3:00mins


https://user-images.githubusercontent.com/73840223/127860237-6470c0c8-965c-4aa3-9907-a3de14bdacc4.mp4



Stop the bot and it failed to cancel order `1627899814001632`
```
2021-08-02 10:23:37,219 - 7724 - hummingbot.connector.exchange.ndax.ndax_exchange - ERROR - Failed to cancel order 1627899814001632: Error parsing data from https://api.ndax.io:8443/AP/CancelOrder. Error: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://api.ndax.io:8443/AP/CancelOrder')
2021-08-02 10:23:37,219 - 7724 - hummingbot.connector.exchange.ndax.ndax_exchange - NETWORK - Failed to cancel order 1627899814001632: Error parsing data from https://api.ndax.io:8443/AP/CancelOrder. Error: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://api.ndax.io:8443/AP/CancelOrder')
Traceback (most recent call last):
  File "/home/ubuntu/ndax/hummingbot/connector/exchange/ndax/ndax_exchange.py", line 327, in _api_request
    parsed_response = await response.json()
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1026, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://api.ndax.io:8443/AP/CancelOrder')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/ndax/hummingbot/connector/exchange/ndax/ndax_exchange.py", line 528, in _execute_cancel
    await self._api_request(
  File "/home/ubuntu/ndax/hummingbot/connector/exchange/ndax/ndax_exchange.py", line 332, in _api_request
    raise IOError(f"Error parsing data from {url}. Error: {str(e)}")
OSError: Error parsing data from https://api.ndax.io:8443/AP/CancelOrder. Error: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://api.ndax.io:8443/AP/CancelOrder')
```

Start the bot again then I stopped after all orders are created. It canceled the order `1627899814001632` but the same error occurred for order `1627899881002461`

```
2021-08-02 10:24:59,060 - 7724 - hummingbot.connector.exchange.ndax.ndax_exchange - ERROR - Failed to cancel order 1627899881002461: Error parsing data from https://api.ndax.io:8443/AP/CancelOrder. Error: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://api.ndax.io:8443/AP/CancelOrder')
2021-08-02 10:24:59,060 - 7724 - hummingbot.connector.exchange.ndax.ndax_exchange - NETWORK - Failed to cancel order 1627899881002461: Error parsing data from https://api.ndax.io:8443/AP/CancelOrder. Error: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://api.ndax.io:8443/AP/CancelOrder')
Traceback (most recent call last):
  File "/home/ubuntu/ndax/hummingbot/connector/exchange/ndax/ndax_exchange.py", line 327, in _api_request
    parsed_response = await response.json()
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1026, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://api.ndax.io:8443/AP/CancelOrder')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/ndax/hummingbot/connector/exchange/ndax/ndax_exchange.py", line 528, in _execute_cancel
    await self._api_request(
  File "/home/ubuntu/ndax/hummingbot/connector/exchange/ndax/ndax_exchange.py", line 332, in _api_request
    raise IOError(f"Error parsing data from {url}. Error: {str(e)}")
OSError: Error parsing data from https://api.ndax.io:8443/AP/CancelOrder. Error: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://api.ndax.io:8443/AP/CancelOrder')
2021-08-02 10:24:59,061 - 7724 - hummingbot.connector.exchange.ndax.ndax_exchange - WARNING - Failed to cancel order 1627899881002461 on NDAX. Check API key and network connection.

# 1627899814001632 has been successfully canceled
2021-08-02 10:24:59,092 - 7724 - hummingbot.connector.exchange.ndax.ndax_exchange - WARNING - Failed to cancel all orders on NDAX. Check API key and network connection.
2021-08-02 10:24:59,093 - 7724 - hummingbot.connector.exchange.ndax.ndax_exchange - INFO - Successfully cancelled order 1627899814001632
2021-08-02 10:24:59,104 - 7724 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1627899899.0, "order_id": "1627899814001632", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "ndax"}
2021-08-02 10:24:59,137 - 7724 - hummingbot.connector.exchange.ndax.ndax_exchange - INFO - Successfully cancelled order 1627899870002047
2021-08-02 10:24:59,147 - 7724 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1627899899.0, "order_id": "1627899870002047", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "ndax"}
2021-08-02 10:24:59,176 - 7724 - hummingbot.connector.exchange.ndax.ndax_exchange - INFO - Successfully cancelled order 1627899859001921
2021-08-02 10:24:59,186 - 7724 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1627899899.0, "order_id": "1627899859001921", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "ndax"}
2021-08-02 10:24:59,213 - 7724 - hummingbot.connector.exchange.ndax.ndax_exchange - INFO - Successfully cancelled order 1627899848002255
2021-08-02 10:24:59,224 - 7724 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1627899899.0, "order_id": "1627899848002255", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "ndax"}
2021-08-02 10:28:18,987 - 7724 - hummingbot.client.hummingbot_application - INFO - stop command initiated.

```

Attached:
[twap-3743.zip](https://github.com/CoinAlpha/hummingbot/files/6916736/twap-3743.zip)

**Comment by CrimsonJacket** [comment]
> Can this be hidden similar to other exchanges? And also the delay when starting the strategy seem to be more frequent using Avellaneda MM as seen in the screen above (2 min delay).

Avellaneda MM requires the bot to capture a certain amount of data more specifically a buffer of volatility entries. Generally this would mean that it will take some time before it actually begins to place orders. You did not include the bot config files, but I think it has to do with the `volatility_buffer_size` config parameter.  Reduce its value to reduce the wait time.

**Comment by RC-13** [comment]
> Avellaneda MM requires the bot to capture a certain amount of data more specifically a buffer of volatility entries. Generally this would mean that it will take some time before it actually begins to place orders. You did not include the bot config files, but I think it has to do with the `volatility_buffer_size` config parameter. Reduce its value to reduce the wait time.

Sorry forgot to attach the config, regarding the `volatility_buffer_size` this is set to 10 so it doesn't take that long. If you check the screenshot, it got delayed after subscribing to the user event (13:22:13). Volatility calculation starts after receiving a cancellation message from the previous order.
[avellaneda.docx](https://github.com/CoinAlpha/hummingbot/files/6917151/avellaneda.docx)

**Comment by RC-13** [comment]
As per discussion with @aarmoa and @CrimsonJacket, here are the remaining issues that currently hasn't been addressed yet and what I think we need to prioritize:
1. Find alternatives to sort out the delay issue during the start-up of the strategy.
2. Issue with best price/ order book getting out of sync or not updated.
3. Issue with filled orders getting lost tracked when an interruption takes place (Can be a separate task)
4. Keeps receiving WebSocket retry every after an order cycle if there was an interruption that takes place earlier when the bot started - QA to retest the behavior

**Comment by RC-13** [comment]
> Some trading pairs like BTC-USD, BTC-USDT, and MATIC-CAD are shown in the market autocomplete list but don't exist in the exchange. Using this market result in an unhandled error

@CrimsonJacket the issue with the inactive market still persists despite getting the fix merged.

**Comment by RC-13** [comment]
@CrimsonJacket I see that the reported markets are now available in the NDAX exchange and confirmed they are now working in the client. However, we still have two more problematic pairs and one duplicate. 
- BCH-CAD : not available in the exchange 
- BTC-USD : not available in the exchange
- AAVE-CAD : duplicated in the client autocomplete list
```python
2021-08-04 08:55:32,829 - 2089 - hummingbot.connector.exchange.ndax.ndax_api_order_book_data_source - ERROR - Unexpected error occured listening for orderbook snapshots. Retrying in 5 secs...
Traceback (most recent call last):
  File "/home/clint_g/ndax/hummingbot/connector/exchange/ndax/ndax_api_order_book_data_source.py", line 192, in listen_for_order_book_snapshots
    snapshot: Dict[str: Any] = await self.get_order_book_data(trading_pair, domain=self._domain)
  File "/home/clint_g/ndax/hummingbot/connector/exchange/ndax/ndax_api_order_book_data_source.py", line 128, in get_order_book_data
    "InstrumentId": cls._trading_pair_id_map[trading_pair],
KeyError: 'BCH-CAD'
2021-08-04 08:58:37,488 - 2089 - hummingbot.client.hummingbot_application - ERROR - 'BTC-USD'
Traceback (most recent call last):
  File "/home/clint_g/ndax/hummingbot/client/command/config_command.py", line 149, in _config_single_key
    await self.prompt_a_config(config_var, input_value=input_value, assign_default=False)
  File "/home/clint_g/ndax/hummingbot/client/command/create_command.py", line 106, in prompt_a_config
    prompt = await config.get_prompt()
  File "/home/clint_g/ndax/hummingbot/client/config/config_var.py", line 54, in get_prompt
    return await self.prompt()
  File "/home/clint_g/ndax/hummingbot/strategy/pure_market_making/pure_market_making_config_map.py", line 42, in order_amount_prompt
    min_amount = await minimum_order_amount(exchange, trading_pair)
  File "/home/clint_g/ndax/hummingbot/client/config/config_helpers.py", line 382, in minimum_order_amount
    mid_price = await get_last_price(exchange, trading_pair)
  File "/home/clint_g/ndax/hummingbot/core/utils/market_price.py", line 27, in get_last_price
    last_prices = await module.get_last_traded_prices(**args)
  File "/home/clint_g/ndax/hummingbot/connector/exchange/ndax/ndax_api_order_book_data_source.py", line 82, in get_last_traded_prices
    "InstrumentId": cls._trading_pair_id_map[trading_pair],
KeyError: 'BTC-USD'
```

**Comment by RC-13** [comment]
@aarmoa @CrimsonJacket My findings for the issue with order price getting desynchronized happens randomly within 1-hour duration. I did four tests in total, and the behavior happens on different duration.
Test summary:
Test 1: the test is done on a local machine
- Best bid price stop updating after 20-25 minutes
- After 30-35 min, the ask side is no longer in sync with the exchange order book (run time 30-40min)
- after 1 hr, order prices recover and sync with the exchange

Test2: Running from cloud server
- After 15-18 min, the ASK prices are no longer in sync however it recovers after 23 min (38 min run time)
- ASK price stops updating after a total run time of 40-45min, then recovers after 10min (total run time of 50 min)
- Prices recover after 1hr (end of test)

Third test: Running from cloud
- Bid best price stop updating after 10 min but is possibly triggered by the account error when someone uses the API key on different IP.

Fourth test: Running on cloud
- 30 min straight, no issue
- after 40 min of running, best bid price/ order book bid prices stop updating 
- failed to recover after 1 hr of running
@rxlxrxsx might add more samples base on his local testing.

I'll run another test using the fix PR from Abel and compare the results.

**Review by RC-13 — DISMISSED** [review]
As been discussed during client standup, the last fix we had for the order book synchronization issue is a temporary fix. A full fix will be worked on once our developers receive updates from NDAX team. LGTM

**Review by dennisocana — APPROVED** [review]
Re-approving after fixing the conflict.

**Pull request merged**
