### PR TITLE
fix/fees coinbase pro

### LINKED ISSUE #2084: [BUG] Filled order fees are not recorded correctly
**Describe the bug**

Fees for orders that are filled are not recorded correctly for many connectors, instead of taking fees reported from exchange's API, the connectors call `c_get_fee` (which estimates fee). This results in incorrect fees stored on trades table (sqlite) and incorrect performance reported on `history` command.

This mistake was partly due to Binance connector had this bug which other connectors copied the code from. The bug was fixed on 29 December 2020 on Binance connector so connectors created after the date should not get affected.

Connectors which broadcast fee incorrectly on `OrderFilledEvent`:

- [ ] ~Kucoin~
- [x] Binance Perpetual Derivative
- [x] Bifinex
- [x] Coinbase Pro
- [x] Bittrex
- [ ] ~OkEx~
- [x] Huobi
- [ ] ~Beaxy~
- [x] FTX
- [ ] ~Blocktane~
- [ ] ~Coinzoom~
- [ ] ~DigiFinex~
- [x] Gate.io
- [ ] Liquid

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd1e7e) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by aarmoa**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
The PR include the required changes to consider the fees informed by the exchange when a trade takes place, instead of estimating them.
Partially closes #2084 

**Tests performed by the developer**:
Added new unit tests for the order fill process and the fees registration

**Tips for QA testing**:
Please check that partial and complete fills are working correctly in Coinbase Pro connectors. Also verify if the fees are now being registered correctly.

### CODE REVIEW

**Comment by nikspz** [comment]
Bot use correct percent fees (`0.5%`), but on the exchange most likely it rounded to the nearest cents ($0.01)
In the history 13.55*0.005=0.0677(0.06775), exchange use 0.07 for that trade. (order trade volume 13.55)
Another example 6.39*0.005=0.0319879, exchange use 0.03 fees for that trade. (order trade volume 6.39)

image
image
image

Here for the multiple trades:
image
image

**Review by CrimsonJacket — CHANGES_REQUESTED** [review]
Seems like some of the changes for the Binance perpetual and Bitfinex changes are reflected here as well. Please do resolve this.

However, changes for Coinbase Pro LGTM.

**Comment by aarmoa** [comment]
@CrimsonJacket that will be solved as soon as we can merge the other PR into development (the one with the changes Binance Perpetual and Bitfinex)

**Comment by aarmoa** [comment]
I have updated the PR and now the changes from the other one are not shown any more.

**Review by RC-13 — APPROVED** [review]
LGTM

**Review by petioptrv — APPROVED** [review]
Changes LGTM!

**Pull request merged**
