### PR TITLE
Fix/ AscendEx conflicting ex order

### LINKED ISSUE #3970: AscendEX - Failed to create order due to DupNewCoid error
**Describe the bug**
Traceback (most recent call last):
  File "/root/mm2/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 541, in _create_order
    raise Exception(f'Failed to create an order, reason: {resp["data"]["info"]["errorCode"]}')
Exception: Failed to create an order, reason: DupNewCoid

Based on the documentation on ascendex, it might be duplicated new client order id generated. It is unable to generate unique client order id per trade.

**Steps To Reproduce**
Run pure market making strategy with order refresh time 1s and order_level 3 in ascendex exchange

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
0.42.0.
Running Source build. Linux on cloud server

**Attachments**
[logs_conf_pure_mm_1.log](https://github.com/CoinAlpha/hummingbot/files/7032022/logs_conf_pure_mm_1.log)

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ran00b) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by CrimsonJacket**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Fixes real possibility of conflicting order ids being sent to the AscendEx API server when placing orders between multiple HB instances.
Resolves #3970 

**Pending confirmation of broker id mechanism**

**Tests performed by the developer**:
Usage of uuid for trailing section of `client_order_id`

**Tips for QA testing**:
Test that conflicting order id error no longer occurs across multiple instances.
Instances need not be on the same market

### CODE REVIEW

**Comment by zappra** [comment]
Won't this change break various bits of strategy logic - eg. cancelling orders over max age - that depend on being able to extract a timestamp from the client id?

**Review by aarmoa — APPROVED** [review]
I agree with the changes

**Review by RC-13 — APPROVED** [review]
Run 5 test bots for 24 hours and all bots are unable to get the `DupNewCoid` error. LGTM!

**Comment by zappra** [comment]
Ah of course, you can retain the same client id whilst passing a uuid to the server. Nice :)

**Pull request merged**
