### PR TITLE
Feat/lbank spot connector

### PR DESCRIPTION
**Pull request by aarmoa**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Implementation of LBank exchange spot connector

**Tests performed by the developer**:
Added unit tests for all new components

**Tips for QA testing**:
Run all validations required for a new connector

[sc-31764]

### CODE REVIEW

**Comment by aarmoa** [comment]
No need for development review in this PR

**Comment by RC-13** [comment]
Test run: https://hummingbot.testrail.io/index.php?/runs/view/2353

**Review by PtrckM — APPROVED** [review]
Test Summary:

- Connected API keys (valid and invalid key) and confirmed working as expected
- Confirmed asset and exchange balances are reflecting correct
- Created a pure_mm strategy and went through initial prompts successfully
- Started the strategy without issues, confirmed orders are created and cancelled based on config
- Confirmed order book prices is in sync with the exchange
- Trade information are correct based on history command output
- Compared trades in client and exchange, no discrepancies found
- Confirmed hanging order/cancellation and multiple order levels works as expected
- Tested on other supported strategies as well and confirmed working
- Successfully built a docker image and create a docker instance

**Comment by aarmoa** [comment]
Closing the PR after opening it in the foundation repo https://github.com/hummingbot/hummingbot/pull/5817

**Pull request closed without merging**
