### PR TITLE
fix/user balance failure for time synchronizer

### PR DESCRIPTION
**Pull request by aarmoa**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Change in the logic that gets the user balance for Binance and Binance Perpetual. Since the exchange requires the time to be synchronized before any interaction, with this PR we add logic to the _update_balances() function to ensure the TimeSynchronizer has been initialized before requesting the balance.

**Tests performed by the developer**:
Added unit tests.

**Tips for QA testing**:
Run the balance command in a client instance with Binance and Binance Perpetual connectors correctly configured, and the machine time delayed 10 minutes.

[ch-22831]

### CODE REVIEW

**Comment by RC-13** [comment]
Hello, @aarmoa Is this error to be expected? This comes up whenever you run balance at a first-run but disappear after restarting the client. Although it keeps coming back when you start a strategy (doesn't matter if time is current or not) and this logging message is not saved to the log file.
image
Despite getting this in the logs, balance is working as intended and strategies are able to start.

**Comment by aarmoa** [comment]
@RC-13 thank you for that. The error is not expected. I will investigate it.

**Comment by RC-13** [comment]
- Confirming that the issue above has been fixed.
- Adding additional unusual behavior that occurs after the recent commit, when running a perpetual market making using  binance_perpetual, it doesn't detect the position mode when the strategy is started (didn't occur on the earlier commit):
```python
2022-02-24 13:23:35,018 - 20255 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'dualSidePosition'
Traceback (most recent call last):
  File "/Users/clintg/testing/binance-time/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "hummingbot/core/network_iterator.pyx", line 112, in _check_network_loop
    await self.start_network()
  File "/Users/clintg/testing/binance-time/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 195, in start_network
    await self._get_position_mode()
  File "/Users/clintg/testing/binance-time/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 1126, in _get_position_mode
    self._position_mode = PositionMode.HEDGE if response["dualSidePosition"] else PositionMode.ONEWAY
KeyError: 'dualSidePosition'
```
image
[logs_conf_perpetual_market_making_1.log](https://github.com/CoinAlpha/hummingbot/files/8129916/logs_conf_perpetual_market_making_1.log)

**Comment by mhrvth** [comment]
LGTM

**Comment by aarmoa** [comment]
@RC-13 Are you changing the machine time in the middle of the client execution? Or you change the time before starting the client and then just run with the same delayed time?

**Comment by RC-13** [comment]
Hello @aarmoa the error happens when you change the time before starting the client or before starting the strategy. It works when the strategy started using the correct time then changes it while running but the error will come up once you stop and start.

**Comment by aarmoa** [comment]
@RC-13 I have applied several changes to solve the issue for any request that might be done to Binance Perpetual exchange before the connector is completely initialized and running. If the changes solve all issues for Binance Perpetual I will have to apply the same to Binance Spot, because both connectors use the time synchronizer.

**Comment by PtrckM** [comment]
- getting error on `connect binance_perpetual` / binance_perpetual_testnet
  - error appears on both correct time and adjusted time (behind 10 minutes)
image

```
2022-02-26 07:12:19,710 - 35397 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative - ERROR - Error fetching /account
Traceback (most recent call last):
  File "/Users/patrick/Documents/HB/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 1327, in _api_request
    return await web_utils.api_request(
  File "/Users/patrick/Documents/HB/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_web_utils.py", line 96, in api_request
    raise IOError(f"Error executing request {method.name} {path}. "
OSError: Error executing request GET /account. HTTP status is 400. Error: {'code': -1102, 'msg': "Mandatory parameter 'timestamp' was not sent, was empty/null, or malformed."}
2022-02-26 07:12:19,717 - 35397 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative - WARNING - Error executing request GET /account. HTTP status is 400. Error: {'code': -1102, 'msg': "Mandatory parameter 'timestamp' was not sent, was empty/null, or malformed."}
```

- logs 
[logs_hummingbot.log](https://github.com/CoinAlpha/hummingbot/files/8145408/logs_hummingbot.log)

**Comment by aarmoa** [comment]
Thank you for finding that @PtrckM. I fixed the issue and added a unit test that verifies the scenario, to avoid the error from happening again in the future.

**Comment by RC-13** [comment]
Update: Confirm that the reported issue mentioned by Patrick has been addressed in the latest commit, currently continuing the test for both connectors.

**Comment by aarmoa** [comment]
@RC-13 @PtrckM I think I was able to fix the issue. I have also applied all the changes to Binance spot connector too.

**Comment by RC-13** [comment]
Confirm that the reported issues have been resolved in the latest commits.

**Review by RC-13 — APPROVED** [review]
LGTM!

Test summary:
- Install the feature branch and start the Hummingbot client without any issues
- Adjust the machine time ahead by 10 minutes or more and connect the Binance and Binance perpetual API keys successfully
- Checked the balance and confirmed that balances are displayed
- Adjust the machine time by delaying it for about 10 minutes or more and rechecking the API key connections and confirming that keys are still confirmed.
- Started perpetual market-making and pure market-making strategies using the two connectors without any more issues or errors.
- Open the Binance exchange and check the timestamps of the open orders and confirmed that orders are using the Binance server time
- After an order gets filled or a position is opened and closed, checked the timestamp in the order history or trade history and confirmed that they used the Binance server time.

**Review by petioptrv — CHANGES_REQUESTED** [review]
There must be a way to simplify passing all these parameters around (`api_factory`, `throttler`, and `time_synchronizer`). At first, I thought the domain, throttler, and time synchronizer can be combined in something like a `BinanceWebContext` data class, but I see that the `TradingPairFetcher` passes the domain as an arg. I also see that the throttler is sometimes needed separate from the `api_factory` (i.e. in `api_request`). But that, to me, is the perfect opportunity to finally push the throttler in the api factory and in the assistants. If we do that, then the method signatures only need to accept `api_factory` from the caller. If not provided, then instantiate it and pass it along

**Comment by aarmoa** [comment]
I agree with you @petioptrv. Please create a task in our backlog to bring the throttler inside the Assistants

**Comment by PtrckM** [comment]
- getting this error randomly
image


- status shows theres an order but there is none on exchange also loop on cancelling 

image
image

- logs, config and data

**Review by petioptrv — APPROVED** [review]
Changes LGTM!

**Review by RC-13 — APPROVED** [review]
Re-approving the PR, as discussed in the client stand-up, the last issue reported will keep coming up since one of the required changes is currently not yet merged in the development branch.

**Comment by aarmoa** [comment]
Closing this PR after creating its equivalent in Hummingbot repository: https://github.com/hummingbot/hummingbot/pull/5165

**Pull request closed without merging**
