### PR TITLE
Feat/hanging orders tracker for pure mm

### PR DESCRIPTION
**Pull request by mhrvth**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

Replacement of an old hanging orders tracker and integration of a new hanging orders tracker as in the Avellaneda-Stoikov strategy

**Tests performed by the developer**:

Already existing unit tests were modified to account for a different functioning of the new hanging orders tracker, and verified.

**Tips for QA testing**:

Run the unit tests. Unlike before, hanging orders are created on refresh, not immediately.

### CODE REVIEW

**Review by aarmoa — APPROVED** [review]
The PR seems to cover all changes required to use the HangingOrderTracker in PMM strategy.

**Comment by RC-13** [comment]
@mhrvth We are getting the following error when checking for status after a a hanging order is created:
```python
2021-09-08 12:02:53,874 - 3340 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: local variable 'level' referenced before assignment
Traceback (most recent call last):
  File "/Users/clintgogoc/Desktop/github/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/clintgogoc/Desktop/github/hummingbot/hummingbot/client/command/status_command.py", line 131, in status_check_all
    await self.strategy_status(live=True) + script_status + "\n\n Press escape key to stop update.", 1
  File "/Users/clintgogoc/Desktop/github/hummingbot/hummingbot/client/command/status_command.py", line 79, in strategy_status
    st_status = self.strategy.format_status()
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 640, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.format_status
    df = map_df_to_str(self.active_orders_df())
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 565, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.active_orders_df
    amount_orig = self._order_amount + ((level - 1) * self._order_level_amount)
UnboundLocalError: local variable 'level' referenced before assignment
```
Despite getting the error, hanging orders are still tracked.
image

**Review by RC-13 — APPROVED** [review]
Confirming that the reported issue has been resolved. LGTM!

**Review by aarmoa — APPROVED** [review]
The latest fix also looks good

**Pull request merged**
