### PR TITLE
Feat/add creation timestamp to in flight orders

### PR DESCRIPTION
**Pull request by aarmoa**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This PR adds the creation timestamp in the inflight orders. It also changes the calculation of the orders age that was done by taking the creation timestamp from the client order id. It also applies the same changes to the hanging orders.
Modifies the JSON serialization/deserialization of orders to include the creation timestamp.
Changes the market recorder to use the new timestamp when storing the creation time instead of using the timestamp when the event was received (the previous logic).

**Tests performed by the developer**:
Added unit tests to validate the serialization/deserialization and the market recorder changes.
Changed existing tests for hanging orders.

**Tips for QA testing**:
Since the PR modified the in flight orders for all connectors it is required to check that all of them continue working correctly. Please also test running either Pure Market Making or Avellaneda strategy using hanging orders.

[ch21139]

### CODE REVIEW

**Comment by rxlxrxsx** [comment]
- Filled trades on Binance and Ascendex are not recorded on history, bottom nav and data files when running both on pure market making and avellaneda market making strategy. This error also appears during the filled trade event:

Screen Shot 2022-01-23 at 12 25 23 PM

```python

# Binance
2022-01-23 12:51:15,685 - 17084 - hummingbot.connector.exchange.binance.binance_exchange - ERROR - Unexpected error while processing event 107.
Traceback (most recent call last):
  File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
    typed_listener.c_call(arg)
  File "hummingbot/core/event/event_listener.pyx", line 25, in hummingbot.core.event.event_listener.EventListener.c_call
    self(arg)
  File "/Users/reiniersalazar/hummingbot_c1/hummingbot/core/event/event_forwarder.py", line 24, in __call__
    self._to_function(self.current_event_tag, self.current_event_caller, arg)
  File "/Users/reiniersalazar/hummingbot_c1/hummingbot/connector/markets_recorder.py", line 276, in _did_fill_order
    self.append_to_csv(trade_fill_record)
  File "/Users/reiniersalazar/hummingbot_c1/hummingbot/connector/markets_recorder.py", line 328, in append_to_csv
    age = pd.Timestamp(int((trade.timestamp * 1e-3) - (trade.order.creation_timestamp * 1e-6)), unit='s').strftime(
  File "pandas/_libs/tslibs/timestamps.pyx", line 1095, in pandas._libs.tslibs.timestamps.Timestamp.__new__
  File "pandas/_libs/tslibs/conversion.pyx", line 416, in pandas._libs.tslibs.conversion.convert_to_tsobject
OverflowError: Python int too large to convert to C long
```

```python
# Ascendex
2022-01-23 14:32:34,494 - 22888 - hummingbot.connector.exchange.ascend_ex.ascend_ex_exchange - ERROR - Unexpected error while processing event 107.
Traceback (most recent call last):
  File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
    typed_listener.c_call(arg)
  File "hummingbot/core/event/event_listener.pyx", line 25, in hummingbot.core.event.event_listener.EventListener.c_call
    self(arg)
  File "/Users/reiniersalazar/hummingbot_c6/hummingbot/core/event/event_forwarder.py", line 24, in __call__
    self._to_function(self.current_event_tag, self.current_event_caller, arg)
  File "/Users/reiniersalazar/hummingbot_c6/hummingbot/connector/markets_recorder.py", line 276, in _did_fill_order
    self.append_to_csv(trade_fill_record)
  File "/Users/reiniersalazar/hummingbot_c6/hummingbot/connector/markets_recorder.py", line 328, in append_to_csv
    age = pd.Timestamp(int((trade.timestamp * 1e-3) - (trade.order.creation_timestamp * 1e-6)), unit='s').strftime(
  File "pandas/_libs/tslibs/timestamps.pyx", line 1095, in pandas._libs.tslibs.timestamps.Timestamp.__new__
  File "pandas/_libs/tslibs/conversion.pyx", line 416, in pandas._libs.tslibs.conversion.convert_to_tsobject
OverflowError: Python int too large to convert to C long
```

Logs/config: 
[binance.zip](https://github.com/CoinAlpha/hummingbot/files/7920039/binance.zip)
[ascendex.zip](https://github.com/CoinAlpha/hummingbot/files/7920040/ascendex.zip)

- Filled trades are being tracked on Kucoin both on pure both on pure market making and avellaneda market making strategy however this error appears when a partial order is filled:

```python
2022-01-23 15:05:24,476 - 23711 - hummingbot.connector.exchange.kucoin.kucoin_exchange - ERROR - Unexpected error while processing event 107.
Traceback (most recent call last):
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: TradeFill.market, TradeFill.order_id, TradeFill.exchange_trade_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
    typed_listener.c_call(arg)
  File "hummingbot/core/event/event_listener.pyx", line 25, in hummingbot.core.event.event_listener.EventListener.c_call
    self(arg)
  File "/Users/reiniersalazar/hummingbot_c6/hummingbot/core/event/event_forwarder.py", line 24, in __call__
    self._to_function(self.current_event_tag, self.current_event_caller, arg)
  File "/Users/reiniersalazar/hummingbot_c6/hummingbot/connector/markets_recorder.py", line 271, in _did_fill_order
    self.save_market_states(self._config_file_path, market, session=session)
  File "/Users/reiniersalazar/hummingbot_c6/hummingbot/connector/markets_recorder.py", line 157, in save_market_states
    market_states: Optional[MarketState] = self.get_market_states(config_file_path, market, session=session)
  File "/Users/reiniersalazar/hummingbot_c6/hummingbot/connector/markets_recorder.py", line 185, in get_market_states
    market_states: Optional[MarketState] = query.one_or_none()
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2836, in one_or_none
    return self._iter().one_or_none()
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2894, in _iter
    result = self.session.execute(
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1640, in execute
    ) = compile_state_cls.orm_pre_session_exec(
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/context.py", line 318, in orm_pre_session_exec
    session._autoflush()
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2237, in _autoflush
    util.raise_(e, with_traceback=sys.exc_info()[2])
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2226, in _autoflush
    self.flush()
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3363, in flush
    self._flush(objects)
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3503, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3463, in _flush
    flush_context.execute()
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 244, in save_obj
    _emit_insert_statements(
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1096, in _emit_insert_statements
    c = connection._execute_20(
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) UNIQUE constraint failed: TradeFill.market, TradeFill.order_id, TradeFill.exchange_trade_id
[SQL: INSERT INTO "TradeFill" (config_file_path, strategy, market, symbol, base_asset, quote_asset, timestamp, order_id, trade_type, order_type, price, amount, leverage, trade_fee, exchange_trade_id, position) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('kucoin.yml', 'pure_market_making', 'kucoin', 'ETH-USDT', 'ETH', 'USDT', 1642921524000, 'sell-ETH-USDT-1642921520002462', 'SELL', 'LIMIT_MAKER', 2467600000, 132, 1, '{"percent": 0.001, "percent_token": null, "flat_fees": []}', '61ecfe300244cd000193a8fa', 'NIL')]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
```

Logs/config: 
[kucoin.zip](https://github.com/CoinAlpha/hummingbot/files/7920042/kucoin.zip)

- At random instances trades are not tracked on history, bottom nav and data files when this error appears during the filled order event when running Gate.io both on pure market making and avellaneda market making strategy

```python
2022-01-23 15:45:14,287 - 23711 - hummingbot.connector.exchange.gate_io.gate_io_exchange - ERROR - Unexpected error while processing event 107.
Traceback (most recent call last):
  File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
    typed_listener.c_call(arg)
  File "hummingbot/core/event/event_listener.pyx", line 25, in hummingbot.core.event.event_listener.EventListener.c_call
    self(arg)
  File "/Users/reiniersalazar/hummingbot_c6/hummingbot/core/event/event_forwarder.py", line 24, in __call__
    self._to_function(self.current_event_tag, self.current_event_caller, arg)
  File "/Users/reiniersalazar/hummingbot_c6/hummingbot/connector/markets_recorder.py", line 276, in _did_fill_order
    self.append_to_csv(trade_fill_record)
  File "/Users/reiniersalazar/hummingbot_c6/hummingbot/connector/markets_recorder.py", line 328, in append_to_csv
    age = pd.Timestamp(int((trade.timestamp * 1e-3) - (trade.order.creation_timestamp * 1e-6)), unit='s').strftime(
AttributeError: 'NoneType' object has no attribute 'creation_timestamp'
```

Logs/config: 
[gate_io.zip](https://github.com/CoinAlpha/hummingbot/files/7920043/gate_io.zip)

- Ongoing test on other connectors and hanging orders on pure market making and avellaneda market making strategy

**Comment by aarmoa** [comment]
Hello @rxlxrxsx, thank you for the feedback. I committed a change that should fix the issue that cause the "int too large to convert to C long" and the "'NoneType' object has no attribute 'creation_timestamp'" errors. 
Regarding the errors for OKEx and Kucoin, that error only could happen if we receive in the client two fill notifications for the same order with the dame trade id, but that is something that should never happen. I believe there is an error in the connectors, that are populating the fill events with the `exchange_order_id` as the `trade_id`. I will need to dig more into that problem, but is an error that should be present already in the current development version (after the change we made to the DB sessions management, because that PR changed the TradeFill table primary key).

**Comment by rxlxrxsx** [comment]
> Hello @rxlxrxsx, thank you for the feedback. I committed a change that should fix the issue that cause the "int too large to convert to C long" and the "'NoneType' object has no attribute 'creation_timestamp'" errors.
Regarding the errors for OKEx and Kucoin, that error only could happen if we receive in the client two fill notifications for the same order with the dame trade id, but that is something that should never happen. I believe there is an error in the connectors, that are populating the fill events with the exchange_order_id as the trade_id. I will need to dig more into that problem, but is an error that should be present already in the current development version (after the change we made to the DB sessions management, because that PR changed the TradeFill table primary key).

- Still getting the `OverflowError: Python int too large to convert to C long` error on Binance and Ascendex on the latest commit. The traceback is the same as the one reported earlier
- After 30 trades on Gate.io I wasn't able to reproduce the 'NoneType' object has no attribute 'creation_timestamp' error anymore
- For the issue with OKEx and Kucoin, I was able to reproduce the issue on development and created a [ticket](https://github.com/hummingbot/hummingbot/issues/5037) for tracking

**Comment by rxlxrxsx** [comment]
> Still getting the OverflowError: Python int too large to convert to C long error on Binance and Ascendex on the latest commit. The traceback is the same as the one reported earlier
- This is confirmed fixed.

- New issue found: On Binance when hanging orders is enabled it creates a ghost hanging order (based on the order that was cancelled after stopping the bot) every time you restart the bot. This happens both on pure market making and avellaneda market making strategy

Screen Shot 2022-01-25 at 10 37 01 AM

Logs/config: [binance.zip](https://github.com/CoinAlpha/hummingbot/files/7930432/binance.zip)

**Comment by RC-13** [comment]
Update: there are remaining connectors that need to be cross-checked with this PR. If no issue is found on these remaining connectors, we will proceed with the approval.

**Review by CrimsonJacket — APPROVED** [review]
Changes LGTM.

**Comment by rxlxrxsx** [comment]
- When running on perpetual market making strategy the status output is not showing when running the status command. This only happens when there orders currently open and seems to affect all perpetual connectors. Tested on development but didn't get the issue.

Screen Shot 2022-01-26 at 3 42 18 PM

Logs/config: [perp_mm_status_output.zip](https://github.com/CoinAlpha/hummingbot/files/7939892/perp_mm_status_output.zip)

**Comment by rxlxrxsx** [comment]
Testing update:

- Finished testing the spot connectors both running on pure market making and avellaneda market making
- Also finished testing the AMM connectors
- Pending test for perpetual connectors, got blocked by the issue reported above

**Comment by RC-13** [comment]
> * When running on perpetual market making strategy the status output is not showing when running the status command. This only happens when there orders currently open and seems to affect all perpetual connectors. Tested on development but didn't get the issue.
> 
> Screen Shot 2022-01-26 at 3 42 18 PM
> 
> Logs/config: [perp_mm_status_output.zip](https://github.com/CoinAlpha/hummingbot/files/7939892/perp_mm_status_output.zip)

Adding a detail for these issue, on my side, an error is given when status is run
```python
2022-01-26 12:25:20,245 - 30506 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: unsupported operand type(s) for /: 'str' and 'float'
Traceback (most recent call last):
  File "/home/ubuntu/creation-timestamp/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ubuntu/creation-timestamp/hummingbot/client/command/status_command.py", line 139, in status_check_all
    self._notify(await self.strategy_status())
  File "/home/ubuntu/creation-timestamp/hummingbot/client/command/status_command.py", line 82, in strategy_status
    st_status = self.strategy.format_status()
  File "/home/ubuntu/creation-timestamp/hummingbot/strategy/perpetual_market_making/perpetual_market_making.py", line 434, in format_status
    df = self.active_orders_df()
  File "/home/ubuntu/creation-timestamp/hummingbot/strategy/perpetual_market_making/perpetual_market_making.py", line 358, in active_orders_df
    age = pd.Timestamp(int(time.time() - (order.client_order_id / 1e6)),
TypeError: unsupported operand type(s) for /: 'str' and 'float'
```
image
[logs_conf_perpetual_market_making_1.log](https://github.com/CoinAlpha/hummingbot/files/7941722/logs_conf_perpetual_market_making_1.log)

**Comment by aarmoa** [comment]
@rxlxrxsx @RC-13 I have committed a change to solve the issue. Also I have rebased the branch on top of the latest changes in development branch.

**Review by rxlxrxsx — APPROVED** [review]
Tested and confirmed working by QA.

Tests performed:
- Create and run pure market making and avellaneda market making strategies on spot connectors
- Confirmed that hanging order execution and cancellation works on both strategies and no ghost hanging orders are created when restarting the strategy
- Create and run perpetual market making on perpetual connectors
- Create and run amm_arb strategy on protocol connectors
- Confirmed that filled order event on tested strategies works as expected
- Confirmed all issues found were addressed and fixed

**Comment by aarmoa** [comment]
Closing the PR because it has been created in Hummingbot repository https://github.com/hummingbot/hummingbot/pull/5064

**Pull request closed without merging**
