### PR TITLE
(fix) Discovery unable to start on decentralized exchanges | Bamboo Relay & Radar Relay [Fixes #1504]

### LINKED ISSUE #1504: [BUG] Discovery unable to start on decentralized exchanges | Bamboo Relay & Radar Relay
**Describe the bug**
Discovery Strategy won't start when selecting decentralize exchanges like Bamboo Relay & Radar Relay as primary and secondary markets.

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a new conf strategy (discovery)
2. Select decentralized exchanges (Bamboo Relay & Radar Relay)
3. Set ``trading_pair 1 & 2`` to [ ]
4. Set ``target_prof`` to 0.0
5. Set ``target_amount`` to inf
6. Start the bot

NOTE: When paper_trade is ON, the error will show at the very end of the discovery process. See attached screenshots.

**Screenshots**
Paper_Trade OFF
image
image

Paper_Trade ON
image

**Release version**
Dev. 0.25.0 & Master 0.24.1
```
"branch": "development",
                "commit": "f1f42383a4e63b84e7591623f6668baa4f75279f",
                "date": "2020-03-06T02:20:38Z",
                "maintainer": "CoinAlpha, Inc. <dev@coinalpha.com>"
```

**Attachments**
[logs_conf_discovery_strategy_0.log](https://github.com/CoinAlpha/hummingbot/files/4303934/logs_conf_discovery_strategy_0.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**MishaelT**
**Optional: your ETH address:** (0x98211e49660e5680AeA6bb84b4bDB099bc3BE083)

### PR DESCRIPTION
**Pull request by vic-en**
…lay & Radar Relay [Fixes #1504]

**Before submitting this PR, please make sure**:
- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue:
- Related Clubhouse Story:

**A description of the changes proposed in the pull request**:

### CODE REVIEW

**Comment by PtrckM** [comment]
Unable to get result (wait 35 minutes)
- Bamboo_relay - Radar_relay = failed
image
[logs_conf_discovery_strategy_0.log](https://github.com/CoinAlpha/hummingbot/files/4412632/logs_conf_discovery_strategy_0.log)

tested on other connectors:
- huobi - bamboo_relay = failed
image

- radar_relay - binance = failed

**Comment by Hashira-Lars** [comment]
Tested this branch (default params) will update this thread for the following test results.

Pair                     Strategy  Initialize                  Discovery Output                     Discovery Save
Bamboo-Radar            Success                                Fail                                         Fail
Bamboo-Binance          Success                                  ?                                            ?

Bamboo-Radar
image


[logs_conf_discovery_strategy_0.log](https://github.com/CoinAlpha/hummingbot/files/4412678/logs_conf_discovery_strategy_0.log)

bamboo-Binance
image

[logs_conf_discovery_strategy_1.log](https://github.com/CoinAlpha/hummingbot/files/4412686/logs_conf_discovery_strategy_1.log)

**Comment by vic-en** [comment]
@PtrckM and @Hashira-Lars , run discovery again. I discovered the problem was with a pair(LOYALTY PO-WETH) in BambooRelay and I worked something around it.

**Comment by Clint-G13** [comment]
Bamboo Relay and Radar Relay = Success
Discovery rr-bamboo

Bamboo Relay and Binance = Success
Discovery bamboo-binance

Bamboo Relay and Liquid = Success
Discovery bamboo-liquid

Bamboo Relay and KuCoin = Success
Discovery bamboo-Kucoin

**Comment by yzhang1994** [comment]
ok to test

**Comment by Hashira-Lars** [comment]
Strategy Initialize / Discovery Output / Discovery Save Output = CONFIRM FIX

bamboo-radar = ok
bamboo-binance = ok
bamboo-liquid = ok
bambo-huobi = ok
bambo-coinbase = ok
bambo-bittrex = ok
bambo-kucoin = ok

radar-bamboo = ok
radar-binance = ok
radar-liquid = ok
radar-huobi = ok
radar-coinbase = ok
radar-bittrex = ok
radar-kucoin = ok

**Comment by martinkou** [comment]
retest this please

**Pull request merged**
