### PR TITLE
Feat/lite strategy

### PR DESCRIPTION
**Pull request by Nullably**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
- Implemented all stories in the [Lite strategy epic](https://github.com/hummingbot/hummingbot/issues/4715)
- There is no unit tests for example strategies yet
- Quick start cannot be used to start lite strategy (yet)

**Tests performed by the developer**:
- Started both examples, stop, status, all work
- Ran all unit tests, all passed 

**Tips for QA testing**:

### CODE REVIEW

**Comment by PtrckM** [comment]
- On going test

**Comment by PtrckM** [comment]
Source build

- while running the strategy doing `config` will get an error.
   - also when the bot is stop then config
image

```
2022-02-26 04:42:45,578 - 78627 - root - ERROR - No module named 'hummingbot.strategy.lite1'
Traceback (most recent call last):
  File "/home/ubuntu/lite_strategy/hummingbot/client/config/config_helpers.py", line 187, in get_strategy_config_map
    strategy_module = __import__(f"hummingbot.strategy.{strategy}.{cm_key}",
ModuleNotFoundError: No module named 'hummingbot.strategy.lite1'
2022-02-26 04:42:45,582 - 78627 - root - ERROR - No module named 'hummingbot.strategy.lite1'
Traceback (most recent call last):
  File "/home/ubuntu/lite_strategy/hummingbot/client/config/config_helpers.py", line 187, in get_strategy_config_map
    strategy_module = __import__(f"hummingbot.strategy.{strategy}.{cm_key}",
ModuleNotFoundError: No module named 'hummingbot.strategy.lite1'
```

- While the strategy is stop I accidentally do `ctrl + s` and similar error appears
image


-logs 
[logs_live1.py.log](https://github.com/CoinAlpha/hummingbot/files/8146004/logs_live1.py.log)



---

Docker Build
- unable to detect `lite_strategies`

https://user-images.githubusercontent.com/54516858/155828689-3a357aa2-4595-4c60-a9b8-ba9dc0a07c02.mov

- using the example files
image

**Comment by Nullably** [comment]
@PtrckM I just pushed some changes, hopefully they address all the issues you found. Please verify.

**Comment by PtrckM** [comment]
- confirmed fix issues on source build (no more error on config command and status command while stop)

---
Source Build


- no notification on left pane for filled trades
image


- on loop to create order even balance is no longer sufficient.
image


Note: Are both issues are user options to include/fix by themselves?

- logs
[source.zip](https://github.com/CoinAlpha/hummingbot/files/8158272/source.zip)


---
Docker build

- lite strategies are not working as expected
  - the folder is not exposed using the [create.sh](https://github.com/CoinAlpha/hummingbot/blob/feat/lite_strategy/installation/docker-commands/create.sh)
image

**Comment by aarmoa** [comment]
Hello @PtrckM. The following two behaviors you noticed are dependent on the implementation of the script (lite strategy):
- no notification on left pane for filled trades
- on loop to create order even balance is no longer sufficient
I am working on the remaining changes but in a separate PR, to preserve Jack's initial implementation. I will create a new PR soon.

**Comment by aarmoa** [comment]
The work for the lite strategies will be continued in https://github.com/CoinAlpha/hummingbot/pull/191

**Comment by dennisocana** [comment]
@aarmoa can we close this PR?

**Comment by aarmoa** [comment]
Clossing this PR after creating https://github.com/hummingbot/hummingbot/pull/5221

**Pull request closed without merging**
