### PR TITLE
fix/user_stream_data_source.py

### PR DESCRIPTION
**Pull request by fengkiej**
**Before submitting this PR, please make sure**:
- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue:
- Related Clubhouse Story:

**A description of the changes proposed in the pull request**:
Calling LiquidAPIOrderBookDataSource's `get_active_exchange_markets()` to get quoteAsset is too extraneous, it causes problems in other parts of the connector due to rate limit because in `listen_for_user_trades`, it polls to the api through  `get_active_exchange_markets()` without any interval spacing between calls (`while True: ..` without sleep).

This fix changes the way to retrieve quoteAsset by splitting the trading_pair.

### CODE REVIEW

**Comment by Nullably** [comment]
Hi @fengkiej 
Sorry for the delay in reviewing this change.
You're right, it's call api for every ws message is not very efficient. 
As this branch is out-of-date now, can you please update the branch? and I will help you merge this change into ours.
Thank you for helping us pointing this out.

**Comment by fengkiej** [comment]
@Nullably 
sure, I've updated the branch please check again for any possible conflicts

**Comment by Nullably** [comment]
@fengkiej Sorry it's out of date again, can you please update the branch or give us a permission?

**Comment by carlolm** [comment]
OK to test

**Comment by Nullably** [comment]
@fengkiej Sorry, can you please update the branch one more time? Jenkins' build didn't start yesterday.

**Pull request merged**
