### PR TITLE
Refactor / rename client_id

### PR DESCRIPTION
**Pull request by Nullably**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
* Rename client_id to instance_id

### CODE REVIEW

**Comment by Nullably** [comment]
To QA, when testing please test to see if the old client id (for existing global config file) is replaced with a new instance id (with a new randomly generated value).

**Comment by rxlxrxsx** [comment]
Can confirm the old client_id is now replaced with a random generated value on instance_id however after starting the bot, getting trades filled and wait for more than 5 minutes (I set the `heartbeat_interval_min` to 5) there are still no data shown `hummingbot.order_count`, `hummingbot.trade_count` and `hummingbot.filled_quote_volume`.

**Comment by rxlxrxsx** [comment]
Tested and confirmed working by QA. The issue reported above was because of redeployment of reporting proxy and can confirm now that it's working fine.

**Review by vic-en — APPROVED** [review]
LGTM

**Pull request merged**
