### PR TITLE
Feat/perp generic connector

### PR DESCRIPTION
**Pull request by vic-en**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Adds gateway_EVM_Perpetual connector
[ch28707]

**Tests performed by the developer**:
- nosetest for new endpoint
- Tested with spot-perp arb strategy

**Tips for QA testing**:
- Connect perp to ethereum-optimism on client using gateway command
- Ensure balance ETH and USD balances are returned
- use new connection as derivative connector in spot-perp arb strategy

### CODE REVIEW

**Comment by PtrckM** [comment]
- getting an error (network or internet issue?)
  - running it for more than 30 minutes the error doesn't repeat

image

```
2022-07-14 18:30:13,036 - 74355 - GatewayEVMPerpetual - ERROR - 'ServerDisconnectedError' object is not subscriptable
Traceback (most recent call last):
  File "/Users/patrick/Documents/HB/perpgen/hummingbot/connector/gateway_EVM_Perpetual.py", line 364, in _status_polling_loop
    await safe_gather(
  File "/Users/patrick/Documents/HB/perpgen/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/Users/patrick/Documents/HB/perpgen/hummingbot/connector/gateway_EVM_Perpetual.py", line 463, in update_positions
    trading_pair = f"{position['base']}-{position['quote']}"
TypeError: 'ServerDisconnectedError' object is not subscriptable
2022-07-14 18:30:49,031 - 74355 - hummingbot.core.gateway.gateway_http_client - WARNING - Call to https://localhost:16921/amm/perp/position failed. See logs for more details.
```

- getting this intermittently

```
2022-07-14 18:30:49,035 - 74355 - GatewayEVMPerpetual - ERROR - 'ServerDisconnectedError' object is not subscriptable
Traceback (most recent call last):
  File "/Users/patrick/Documents/HB/perpgen/hummingbot/connector/gateway_EVM_Perpetual.py", line 364, in _status_polling_loop
    await safe_gather(
  File "/Users/patrick/Documents/HB/perpgen/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/Users/patrick/Documents/HB/perpgen/hummingbot/connector/gateway_EVM_Perpetual.py", line 463, in update_positions
    trading_pair = f"{position['base']}-{position['quote']}"
TypeError: 'ServerDisconnectedError' object is not subscriptable
```


```
2022-07-14 11:48:18 | error | 	Unknown error. | Error: Unknown error.
    at /usr/src/app/dist/src/connectors/perp/perp.controllers.js:24:19
    at Generator.throw (<anonymous>)
    at rejected (/usr/src/app/dist/src/connectors/perp/perp.controllers.js:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    ```

**Comment by vic-en** [comment]
@PtrckM pls let me know if that issue you reported persists.

**Comment by PtrckM** [comment]
> @PtrckM pls let me know if that issue you reported persists.

The error no longer shows upon starting the strategy.

---

- an error arise when `Arbitrage position opening opportunity found.`

```
2022-07-16 06:35:50,073 - 21518 - hummingbot.strategy.spot_perpetual_arbitrage.spot_perpetual_arbitrage - INFO - Arbitrage position opening opportunity found.
2022-07-16 06:35:50,073 - 21518 - hummingbot.strategy.spot_perpetual_arbitrage.spot_perpetual_arbitrage - INFO - Profitability (0.17%) is now above min_opening_arbitrage_pct.
2022-07-16 06:35:50,075 - 21518 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'GatewayEVMPerpetual' object has no attribute 'budget_checker'
Traceback (most recent call last):
  File "/Users/patrick/Documents/HB/perpgen/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/patrick/Documents/HB/perpgen/hummingbot/strategy/spot_perpetual_arbitrage/spot_perpetual_arbitrage.py", line 217, in main
    if self.check_budget_constraint(proposal):
  File "/Users/patrick/Documents/HB/perpgen/hummingbot/strategy/spot_perpetual_arbitrage/spot_perpetual_arbitrage.py", line 309, in check_budget_constraint
    return self.check_spot_budget_constraint(proposal) and self.check_perpetual_budget_constraint(proposal)
  File "/Users/patrick/Documents/HB/perpgen/hummingbot/strategy/spot_perpetual_arbitrage/spot_perpetual_arbitrage.py", line 350, in check_perpetual_budget_constraint
    budget_checker = market_info.market.budget_checker
AttributeError: 'GatewayEVMPerpetual' object has no attribute 'budget_checker'
```


https://user-images.githubusercontent.com/54516858/179322411-9e984531-708e-4df0-b942-034040257f37.mov

Logs+configs: 
[perp.zip](https://github.com/CoinAlpha/hummingbot/files/9124598/perp.zip)

**Comment by vic-en** [comment]
@PtrckM All issues and conflicts resolved. Pls test again.

**Review by PtrckM — APPROVED** [review]
Test Summary:

- install and compile feature branch no issue
- build docker image of gateway no issue
- `gateway connect perp` no issue
- `balance` command no issue
- create spot_perpetual_arbitrage with binance no issue
  - observe filled trade events between binance and perp no issue
  - both `min_opening_arbitrage_pct` and `min_closing_arbitrage_pct` triggers correctly no issue
- build docker image of client on both x86 intel and m1/arm architecture no issue
- test endpoints 
  - ping gateway endpoint no issue
  - /amm/perp/market-prices no issue
  - /amm/perp/market-status no issue
  - /amm/perp/pairs no issue
  - /amm/perp/position no issue
  - /amm/perp/open no issue
  - /amm/perp/close no issue
  - /evm/approve no issue

**Pull request closed without merging**
