### PR TITLE
docs / add Connect Metamask using Brave browser

### PR DESCRIPTION
**Pull request by rennel-tabing**
**Before submitting this PR, please make sure**:
- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue:
- Related Clubhouse Story:

**A description of the changes proposed in the pull request**:
Additional entry for FAQs troubleshooting guide. This contain instructions on how to connect Metamask on a Brave browser.

It will be placed below the instructions of setting the timezone on the Windows computer.

image

### CODE REVIEW

**Comment by rennel-tabing** [comment]
> Please take screenshots and paste them in the PR description.
> 
> https://discordapp.com/channels/530578568154054663/571108169338716220/708126931500924978

Thank you. I have added the screenshots.

**Comment by dennisocana** [comment]
test this please

**Comment by dennisocana** [comment]
add to whitelist

**Comment by mifeng** [comment]
test this please

**Pull request merged**
