### PR TITLE
Feat/metric collection and submission to proxy

### PR DESCRIPTION
**Pull request by vic-en**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

[ch21106]

### CODE REVIEW

**Review by martinkou — APPROVED** [review]

**Comment by martinkou** [comment]
As discussed in gateway standup today, need to check w/ Michael C on whether this actually submits the logs and metrics in the accepted format, and whether the reporting proxy actually records the logs and metrics.

I'd recommend waiting for some confirmations first before merging this in.

**Comment by martinkou** [comment]
Victor has done an end-to-end test with this metric collection patch and successfully got the results on Datadog's side. However, the backend team still needs to fix a few things w.r.t. the api.coinalpha.com endpoint.

 1. They need to convert the API frontend to Cloudflare, to prevent HTTP request smuggling attacks. This will also fix the SSL certificate issue on api.coinalpha.com because converting to Cloudflare would automatically give us Cloudflare SSL certificates as well.
   a. This implies changing the configurations on both Cloudflare side and also on the Google domain records side.
 2. Rate limits needs to be enforced on Cloudflare's side.
 3. Kenny from backend team mentioned the domain name server also need to be changed for some reason - I don't know the rationale behind at the moment. I'll follow up w/ him there.

These are being tracked on backend team via the following tasks:
* https://app.shortcut.com/coinalpha/story/20876/setup-cloudflare-for-reporting-proxy-endpoints-to-rate-limit-incoming-request
* https://app.shortcut.com/coinalpha/story/20875/create-a-cloudflare-waf-rated-limited-endpoint-for-the-reporting-proxy

**Comment by dennisocana** [comment]
@vic-en is the PR ready to be merged after Martin's comment? Or is it required that we wait for the backend team to complete the new tasks first? Let me know so we can mark it as draft if we don't want to merge for now.

**Comment by vic-en** [comment]
@dennisocana It's best we merge after backend team is done.

**Comment by dennisocana** [comment]
Changed status to draft to avoid accidentally merging.

**Comment by vic-en** [comment]
Tested and confirm entry in datadog.

**Pull request merged**
