### PR TITLE
Feat / filled volume data collection

### PR DESCRIPTION
**Pull request by Nullably**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**After creating this PR, please make sure:**

- [x] You link the related GitHub issue or ticket

**A description of the changes proposed in the pull request**:
- Added `heartbeat_enabled` and `heartbeat_interval_min` config vars
- Modified `ReportingProxyHandler` to listen to order events and report metrics to reporting proxy.

**Notes**
- This PR needs to be reviewed/tested in conjuncture with `Reporting Proxy` PR
https://github.com/CoinAlpha/reporting_proxy/pull/2

### CODE REVIEW

**Comment by Nullably** [comment]
@michaelc9 
I am not clear on how ReportingProxyHandler is initialised, on `add_remote_logger_handler` looks like it refers to `log_server_url` in `global_config_map` which no longer exists.
It seems ReportingProxyHandler is initialised by `logging` configuration, so remove the use of `add_remote_logger_handler` for now.

**Review by michaelc9 — APPROVED** [review]
LGTM

**Comment by PtrckM** [comment]
No issues found during testing by QA


 -> pull PR and delete current logs_hummingbot.yml file
 -> edit heartbeat_interval_min to 5 minutes to easily see data on data dog
 -> create pmm strategy using PHB-BTC pair
 -> Set 1% bid and ask spread and start strategy
 -> Manually count order created for 5 minutes duration and compare with `hummingbot.order_count` : 20 orders within 5 minutes, matched
 -> Switched to MFT-USDT pair and set 0.01% spread for both bid and ask so orders will get filled
 -> Set order_amount to a bit higher than minimum allowed size
 -> compare `hummingbot.trade_count` and bot trade that happen within 5 minutes duration: Bot=3, data dog=3 : Ok matched
 -> Adjust bid spread to 1% and retain sell spread ( 1 fill taken place) and compare data: 1 filled trade recognize and graph drop as expected
 -> compare `hummingbot.filled_quote_volume` and trades that happen on the bot: First 3 trade (2 buy +1 sell = approx 33 USDT) while last trade is approximately equal to 11USDT: data matched
 -> run test bot for 4hrs constantly checking if data is match on bot and metrics : data matched

**Review by sdgoh — APPROVED** [review]
LGTM

**Pull request merged**
