### PR TITLE
Harmony Gateway

### PR DESCRIPTION
**Pull request by mlguys**
**Before submitting this PR, please make sure:**

- [x] Tests for Gateway successful.
- [x] Included unit and integration tests.
- [x] All newly included packages should be compatible, licencing-wise.
- [x]  Your code builds clean without any errors or warnings
- [x]  You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request:**
- First part of Harmony integration into Gateway v2
- Since Harmony is EVM-compatible, the endpoints of Harmony should follow the specification in `Network base` and `EVM only` sections in https://hummingbot.notion.site/Gateway-V2-trading-interfaces-482e2684d48c450ebcfff5401ba806aa
- There is no connector for DEX yet, they will be added later

**Tests performed by the developer:**
Unit tests for:

```
gateway/test/chains/harmony/harmony.routes.test.ts
gateway/test/chains/harmony/harmony.validators.test.ts
gateway/test/services/wallet/wallet.controllers.test.ts
gateway/test/services/wallet/wallet.routes.test.ts
gateway/test/services/wallet/wallet.validators.test.ts
```

**Manual integration test with Harmony devnet and mainnet through:**
```
gateway/test-scripts/harmony.test.ts
```

**Tips for QA testing:**
Currently the endpoint `/evm/approve` for setting the allowances for tokens can't be tested yet, I keep getting the overflow error everytime I try to approve a new allowance on harmony, here is the error log:
```
2022-02-09 05:19:24 | error | 	overflow (fault="overflow", operation="BigNumber.from", value=3000000000000000000, code=NUMERIC_FAULT, version=bignumber/5.5.0)
```

Otherwise, other endpoints for `Network base` and `EVM only` are tested and should work as specified in the Gateway-V2 trading interfaces notion page. 

Thanks,
Hoang

### CODE REVIEW

**Comment by dennisocana** [comment]
Thanks for submitting a PR @mlguys , @martinkou will review.

**Comment by martinkou** [comment]
The Harmony connector code on gateway side looks ok to me. I still need some more time to read through the test cases and other integration code.

**Comment by martinkou** [comment]
LGTM. Need to fix the test coverage issues and also investigate into what's causing the `/evm/approve` endpoint failure.

**Comment by mlguys** [comment]
Thanks for the feedback @martinkou 👍  I have added new tests to increase the coverage. For `/evm/approve` endpoint, I made a small fix to make it works, look like we didn't pass value as String to `BigNumber.from` method thus causing the failure. Please let me know if I need to add anything else 🙏

**Review by martinkou — APPROVED** [review]

**Comment by mlguys** [comment]
Look like I need approval for workflow to run, could you help me to run it? @martinkou

**Pull request merged**
