### PR TITLE
fix/ Allow alternation between first and second arbitrage

### PR DESCRIPTION
**Pull request by kienzli**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

- The orders list is being filtered for "amount != decimal_zero", this enables the alternation between first and second arbitrages.
- This adresses the issue https://github.com/CoinAlpha/hummingbot/issues/3763, but possibly only as workaround.

**Tests performed by the developer**:

- Tested during 24h on ALGO/USDT (crypto_com/binance_perpetual) with a spread of 0.2 and 0.02.
- It made at least 10 trades with first and second arbitrages alternating.

**Tips for QA testing**:

### CODE REVIEW

**Comment by kienzli** [comment]
Hello

This is my first commit, so I apologize for any mistakes which I possibly have made during this process.

Best regards

**Comment by dennisocana** [comment]
Thanks for contributing @kienzli . I asked @vic-en to review and approve if all looks good.

**Review by vic-en — APPROVED** [review]
LGTM

**Review by rxlxrxsx — APPROVED** [review]
Tested and confirmed working by QA.

**Pull request merged**
