### PR TITLE
(feat) add trade notifications for XMM and ARB to the left output pan…

### PR DESCRIPTION
**Pull request by vic-en**
…el to give users better visibility

**Before submitting this PR, please make sure**:
- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue: #1711 
- Related Clubhouse Story:

**A description of the changes proposed in the pull request**:
Output for XMM
XMM

Output for ARM
ARB

### CODE REVIEW

**Comment by Nullably** [comment]
retest this please.

**Comment by kmcgowan2000** [comment]
@vic-en this is good but could you replace the order_id in the arb notifications with more useful info? maybe price + quantity?

**Comment by vic-en** [comment]
> 
> 
> @vic-en this is good but could you replace the order_id in the arb notifications with more useful info? maybe price + quantity?

Arb
Better?

**Comment by kmcgowan2000** [comment]
@vic-en yeah that looks a lot cleaner!

**Comment by mifeng** [comment]
This feature is working but I think we should make these trade notifications across strategies more informative:
* timestamp
* order type
* price
* amount

OrderID is not necessary.

Also, please standardize the format across all strategies.

**Comment by mifeng** [comment]
test this please

**Pull request merged**
