### PR TITLE
Refactor/perpetual trading main

### PR DESCRIPTION
**Pull request by Nullably**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
- This is the main branch for changes regarding new Perpetual Trading interface
- For QA please test the following strategies:
  - Spot Perpetual Arbitrage   
  - Perpetual Market Making
- Please test on all perpetual derivative connectors:
  - Binance Perpetual Derivative
  - DyDx  Perpetual Derivative
  - Perpetual Finance 

Note: This is a refactor task and there is no new functionality on the above strategies/connectors.

### CODE REVIEW

**Comment by rapcmia** [comment]
Connected the API and check the balances all ok. Create simple config for each strategy and when I started the bot, I encounter the following errors: 

Perpetual Market making (Binance testnet)
- Getting unhandled errors even while the bot was trying to create orders. Thinking maybe there's a need to change the leverage, I tried to change it from 1 to 5 then 100 but the same result. When I checked the status, it seems the client had created the orders but it is not available on the open order in Binance testnet

```
2021-06-30 18:21:22,258 - 15000 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'BinancePerpetualDerivative' object has no attribute '_leverage'
Traceback (most recent call last):
  File "C:\Users\Ralph\github\3657\hummingbot\core\utils\async_utils.py", line 9, in safe_wrapper
    return await c
  File "C:\Users\Ralph\github\3657\hummingbot\connector\derivative\binance_perpetual\binance_perpetual_derivative.py", line 967, in _set_leverage
    self._leverage[trading_pair] = leverage
AttributeError: 'BinancePerpetualDerivative' object has no attribute '_leverage'
```

image

- I tried this with live trading using Binance futures and getting the same error. On random instance, I found this on the logs when the unhandled error occurs:
```
[conf_files.zip](https://github.com/CoinAlpha/hummingbot/files/6740380/conf_files.zip)

2021-06-30 18:33:59,895 - 3728 - hummingbot.client.ui.hummingbot_cli - ERROR - Unhandled error in prompt_toolkit: [WinError 10038] An operation was attempted on something that is not a socket
Traceback (most recent call last):
  File "C:\Users\Ralph\anaconda3\envs\hummingbot\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Ralph\anaconda3\envs\hummingbot\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
OSError: [WinError 10038] An operation was attempted on something that is not a socket
```

Perpetual Market Making (DyDX perpetual)
- Getting the same error message when submitting orders (on this instance its BUY order)
```
2021-06-30 19:00:54,866 - 16412 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'DydxPerpetualDerivative' object has no attribute '_leverage'
Traceback (most recent call last):
  File "C:\Users\Ralph\github\3657\hummingbot\core\utils\async_utils.py", line 9, in safe_wrapper
    return await c
  File "C:\Users\Ralph\github\3657\hummingbot\connector\derivative\dydx_perpetual\dydx_perpetual_derivative.py", line 1040, in _set_leverage
    self._leverage[trading_pair] = leverage
AttributeError: 'DydxPerpetualDerivative' object has no attribute '_leverage'
```

image


Spot-Perp Arbitrage (Binance testnet / Binance)
- The bot seems to be still checking the divergence however as shown on the logs it is getting the same unhandled error with Perpetual market making

```
2021-06-30 18:45:25,979 - 5500 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'BinancePerpetualDerivative' object has no attribute '_leverage'
Traceback (most recent call last):
  File "C:\Users\Ralph\github\3657\hummingbot\core\utils\async_utils.py", line 9, in safe_wrapper
    return await c
  File "C:\Users\Ralph\github\3657\hummingbot\connector\derivative\binance_perpetual\binance_perpetual_derivative.py", line 967, in _set_leverage
    self._leverage[trading_pair] = leverage
AttributeError: 'BinancePerpetualDerivative' object has no attribute '_leverage'
```

image

Spot-Perp Arbitrage (PerpFi / Binance)
- Gateway connection is ok and its showing balance for XDAI but when you start the bot, it's stuck on this error on the logs:

```
2021-06-30 17:06:37,950 - 3128 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'PerpetualFinanceDerivative' object has no attribute '_funding_info_polling_task'
Traceback (most recent call last):
  File "C:\Users\Ralph\github\3657\hummingbot\core\utils\async_utils.py", line 9, in safe_wrapper
    return await c
  File "C:\Users\Ralph\github\3657\hummingbot\connector\derivative\perpetual_finance\perpetual_finance_derivative.py", line 434, in stop_network
    if self._funding_info_polling_task is not None:
AttributeError: 'PerpetualFinanceDerivative' object has no attribute '_funding_info_polling_task'

2021-06-30 17:06:53,528 - 3128 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2021-06-30 17:07:24,549 - 3128 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2021-06-30 17:07:24,594 - 3128 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'PerpetualFinanceDerivative' object has no attribute '_leverage'
Traceback (most recent call last):
  File "C:\Users\Ralph\github\3657\hummingbot\core\utils\async_utils.py", line 9, in safe_wrapper
    return await c
  File "C:\Users\Ralph\github\3657\hummingbot\client\command\start_command.py", line 40, in _run_clock
    await clock.run()
  File "hummingbot\core\clock.pyx", line 86, in run
    await self.run_til(float("nan"))
  File "hummingbot\core\clock.pyx", line 101, in run_til
    child_iterator.c_start(self, self._current_tick)
  File "hummingbot\strategy\strategy_py_base.pyx", line 27, in hummingbot.strategy.strategy_py_base.StrategyPyBase.c_start
    self.start(clock, timestamp)
  File "C:\Users\Ralph\github\3657\hummingbot\strategy\spot_perpetual_arbitrage\spot_perpetual_arbitrage.py", line 508, in start
    self.apply_initial_settings(self._derivative_market_info.trading_pair, self._derivative_leverage)
  File "C:\Users\Ralph\github\3657\hummingbot\strategy\spot_perpetual_arbitrage\spot_perpetual_arbitrage.py", line 504, in apply_initial_settings
    deriv_market.set_leverage(trading_pair, leverage)
  File "C:\Users\Ralph\github\3657\hummingbot\connector\derivative\perpetual_finance\perpetual_finance_derivative.py", line 572, in set_leverage
    self._leverage[trading_pair] = leverage
AttributeError: 'PerpetualFinanceDerivative' object has no attribute '_leverage'
```

I tried to compare the results using the latest release (0.40.0) and it created orders. Please see attached for the config and log files
[perp-logs.zip](https://github.com/CoinAlpha/hummingbot/files/6740369/perp-logs.zip)
[conf_files.zip](https://github.com/CoinAlpha/hummingbot/files/6740381/conf_files.zip)

**Comment by Nullably** [comment]
@rapcmia 
Sorry, my fault, didn't check the branch again before asking for review.
It should be fixed now.

**Comment by rxlxrxsx** [comment]
- Getting this error upon funding payment while using binance_perpetual_testnet

Screen Shot 2021-07-01 at 4 37 52 PM

```python
2021-07-01 16:00:40,146 - 16449 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative - ERROR - Unexpected error whilst retrieving funding payments. Retrying after 10 seconds... 
Traceback (most recent call last):
  File "/Users/reiniersalazar/hummingbot1/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 746, in _funding_fee_polling_loop
    await self.get_funding_payment(startTime)
  File "/Users/reiniersalazar/hummingbot1/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 995, in get_funding_payment
    funding_rate=self._funding_info[trading_pair]["rate"],
TypeError: tuple indices must be integers or slices, not str
```

Logs and config: [perp_mm.zip](https://github.com/CoinAlpha/hummingbot/files/6746810/perp_mm.zip)

**Comment by Nullably** [comment]
Just pushed the fixed.

**Comment by RC-13** [comment]
Adding additional error,  this is for Perpetual finance connector using spot-perpetual arbitrage strategy, it happens both on testnet and mainnet. Cross-checked the development branch and confirm that error doesn't occur.
perpfi-testnet
```python
2021-07-02 13:19:12,856 - 18253 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'position_action'
Traceback (most recent call last):
  File "/Users/clint_g/Documents/Github-Repo/hb-general/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/clint_g/Documents/Github-Repo/hb-general/hummingbot/strategy/spot_perpetual_arbitrage/spot_perpetual_arbitrage.py", line 335, in execute_derivative_side
    order_id = place_order_fn(arb_side.market_info,
  File "hummingbot/strategy/strategy_base.pyx", line 424, in hummingbot.strategy.strategy_base.StrategyBase.buy_with_specific_market
    return self.c_buy_with_specific_market(market_trading_pair_tuple, amount,
  File "hummingbot/strategy/strategy_base.pyx", line 450, in hummingbot.strategy.strategy_base.StrategyBase.c_buy_with_specific_market
    str order_id = market.c_buy(market_trading_pair_tuple.trading_pair,
  File "hummingbot/connector/connector_base.pyx", line 240, in hummingbot.connector.connector_base.ConnectorBase.c_buy
    return self.buy(trading_pair, amount, order_type, price)
  File "/Users/clint_g/Documents/Github-Repo/hb-general/hummingbot/connector/derivative/perpetual_finance/perpetual_finance_derivative.py", line 197, in buy
    return self.place_order(True, trading_pair, amount, price, kwargs["position_action"])
KeyError: 'position_action'
```
[logs_conf_spot_perpetual_arbitrage_2.log](https://github.com/CoinAlpha/hummingbot/files/6752391/logs_conf_spot_perpetual_arbitrage_2.log)

**Comment by Nullably** [comment]
@RC-13 
I just pushed the fix for the position_action error.

**Comment by PtrckM** [comment]
Issues fix on latest commit
- funding time / fee / payment = FIX :white_check_mark: 
- creating/closing positions = FIX :white_check_mark:

**Comment by rapcmia** [comment]
Testing Perpetual Market Making with DyDx Perpetual connector. 
I have set the bid side with tighter spreads so I can check the filled order event. On the first filled order instance, It seems the bot did not open a LONG position but created again another bid and ask orders:

```
# The bot created bid and ask orders
2021-07-04 15:44:49,983 - 6824 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (ETH-USD) Creating 1 LIMIT bid orders at (Size, Price): ['0.01 ETH, 2332.7 USD'] to OPEN position.
2021-07-04 15:44:49,984 - 6824 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (ETH-USD) Creating 1  LIMIT ask orders at (Size, Price): ['0.01 ETH, 2358.4 USD'] to OPEN position.
2021-07-04 15:44:50,847 - 6824 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_derivative - INFO - Created ordertype.limit tradetype.sell order sell-ETH-USD-1625384689984743 for 0.010 ETH-USD.
2021-07-04 15:44:50,848 - 6824 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1625384690000, "type": "OrderType.LIMIT", "trading_pair": "ETH-USD", "amount": "0.010", "price": "2358.4", "order_id": "sell-ETH-USD-1625384689984743", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "SellOrderCreatedEvent", "event_source": "dydx_perpetual"}
2021-07-04 15:44:50,876 - 6824 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_derivative - INFO - Created ordertype.limit tradetype.buy order buy-ETH-USD-1625384689984742 for 0.010 ETH-USD.
2021-07-04 15:44:50,877 - 6824 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1625384690000, "type": "OrderType.LIMIT", "trading_pair": "ETH-USD", "amount": "0.010", "price": "2332.7", "order_id": "buy-ETH-USD-1625384689984742", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "BuyOrderCreatedEvent", "event_source": "dydx_perpetual"}
2021-07-04 15:45:49,997 - 6824 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Not cancelling active orders since difference between new order prices and current order prices is within 0.00% order_refresh_tolerance_pct

# Bid order got filled
2021-07-04 15:46:38,004 - 6824 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (ETH-USD) Cancelling the limit order sell-ETH-USD-1625384689984743. [clock=2021-07-04 07:46:38+00:00]
2021-07-04 15:46:38,004 - 6824 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Initiated cancellation of sell order sell-ETH-USD-1625384689984743 in favour of take profit order.
2021-07-04 15:46:38,140 - 6824 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (ETH-USD) Maker buy order of 0.01 ETH filled. [clock=2021-07-04 07:46:38+00:00]
2021-07-04 15:46:38,141 - 6824 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1625384798.0, "order_id": "buy-ETH-USD-1625384689984742", "trading_pair": "ETH-USD", "trade_type": "TradeType.BUY", "order_type": "OrderType.LIMIT", "price": "2332.7", "amount": "0.01", "trade_fee": ["0", [["USD", "0.011663"]]], "exchange_trade_id": "buy-ETH-USD-1625384689984742", "leverage": 1, "position": "OPEN", "event_name": "OrderFilledEvent", "event_source": "dydx_perpetual"}
2021-07-04 15:46:38,173 - 6824 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_derivative - INFO - The market buy order buy-ETH-USD-1625384689984742 has completed according to user stream.
2021-07-04 15:46:38,173 - 6824 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (ETH-USD) Maker buy order buy-ETH-USD-1625384689984742 (0.010 ETH @ 2332.7 USD) has been completely filled. [clock=2021-07-04 07:46:38+00:00]
2021-07-04 15:46:38,186 - 6824 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1625384798.0, "order_id": "buy-ETH-USD-1625384689984742", "base_asset": "ETH", "quote_asset": "USD", "fee_asset": "USD", "base_asset_amount": "0.01", "quote_asset_amount": "23.327", "fee_amount": "0.00011663", "order_type": "OrderType.LIMIT", "exchange_order_id": null, "event_name": "BuyOrderCompletedEvent", "event_source": "dydx_perpetual"}
2021-07-04 15:46:38,502 - 6824 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_derivative - INFO - Successfully cancelled order sell-ETH-USD-1625384689984743
2021-07-04 15:46:38,502 - 6824 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1625384798.0, "order_id": "sell-ETH-USD-1625384689984743", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "dydx_perpetual"}

# The bot created bid and ask order again to open positon
2021-07-04 15:47:39,006 - 6824 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (ETH-USD) Creating 1 LIMIT bid orders at (Size, Price): ['0.01 ETH, 2331.1 USD'] to OPEN position.
2021-07-04 15:47:39,006 - 6824 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (ETH-USD) Creating 1  LIMIT ask orders at (Size, Price): ['0.01 ETH, 2356.7 USD'] to OPEN position.
2021-07-04 15:47:39,982 - 6824 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_derivative - INFO - Created ordertype.limit tradetype.buy order buy-ETH-USD-1625384859006695 for 0.010 ETH-USD.
2021-07-04 15:47:39,982 - 6824 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1625384859000, "type": "OrderType.LIMIT", "trading_pair": "ETH-USD", "amount": "0.010", "price": "2331.1", "order_id": "buy-ETH-USD-1625384859006695", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "BuyOrderCreatedEvent", "event_source": "dydx_perpetual"}
2021-07-04 15:47:40,026 - 6824 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_derivative - INFO - Created ordertype.limit tradetype.sell order sell-ETH-USD-1625384859006696 for 0.010 ETH-USD.
2021-07-04 15:47:40,026 - 6824 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1625384860000, "type": "OrderType.LIMIT", "trading_pair": "ETH-USD", "amount": "0.010", "price": "2356.7", "order_id": "sell-ETH-USD-1625384859006696", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "SellOrderCreatedEvent", "event_source": "dydx_perpetual"}
```

The bot should open a LONG position and then create take-profit order but it did not. Instead, it tries to create orders again to open a position. It seems it only happens on random because on the second filled order the bot opens a LONG position and created take-profit order (to close the position). However after few seconds (7s), the take-profit order got `successfully cancelled`
- It did not indicate why it was cancelled
- No `cancelling the limit order...` logs
- Waited for 22mins to check if the bot will recreate the order but no go.

```
2021-07-04 17:06:43,049 - 9684 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (ETH-USD) Maker buy order buy-ETH-USD-1625389570999076 (0.010 ETH @ 2320.9 USD) has been completely filled. [clock=2021-07-04 09:06:42+00:00]
2021-07-04 17:06:43,049 - 9684 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (ETH-USD) Cancelling the limit order sell-ETH-USD-1625389571000082. [clock=2021-07-04 09:06:43+00:00]
2021-07-04 17:06:43,050 - 9684 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Initiated cancellation of sell order sell-ETH-USD-1625389571000082 in favour of take profit order.
2021-07-04 17:06:44,012 - 9684 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Initiated cancellation of sell order sell-ETH-USD-1625389571000082 in favour of take profit order.
2021-07-04 17:06:44,409 - 9684 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_derivative - INFO - Successfully cancelled order sell-ETH-USD-1625389571000082
2021-07-04 17:06:44,409 - 9684 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1625389604.0, "order_id": "sell-ETH-USD-1625389571000082", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "dydx_perpetual"}

# The bot created take-profit order to close the position
2021-07-04 17:07:28,010 - 9684 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (ETH-USD) Creating 1  LIMIT ask orders at (Size, Price): ['0.01 ETH, 2332.5 USD'] to CLOSE position.
2021-07-04 17:07:29,079 - 9684 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_derivative - INFO - Created ordertype.limit tradetype.sell order sell-ETH-USD-1625389648010941 for 0.010 ETH-USD.
2021-07-04 17:07:29,091 - 9684 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1625389649000, "type": "OrderType.LIMIT", "trading_pair": "ETH-USD", "amount": "0.010", "price": "2332.5", "order_id": "sell-ETH-USD-1625389648010941", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "SellOrderCreatedEvent", "event_source": "dydx_perpetual"}

# The bot successfully cancelled the order
2021-07-04 17:17:36,325 - 9684 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_derivative - INFO - Successfully cancelled order sell-ETH-USD-1625389648010941
2021-07-04 17:17:36,325 - 9684 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1625390256.0, "order_id": "sell-ETH-USD-1625389648010941", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "dydx_perpetual"}

# Stop / Start the bot to check if it will create another take-profit order but no go, it created orders to open position
2021-07-04 17:39:37,369 - 9684 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2021-07-04 17:39:39,465 - 9684 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2021-07-04 17:39:40,188 - 9684 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_derivative - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2021-07-04 17:39:40,712 - 9684 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_order_book_tracker - INFO - Initialized order book for ETH-USD. 1/1 completed.
2021-07-04 17:39:42,005 - 9684 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (ETH-USD) Creating 1 LIMIT bid orders at (Size, Price): ['0.01 ETH, 2312.4 USD'] to OPEN position.
2021-07-04 17:39:42,005 - 9684 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (ETH-USD) Creating 1  LIMIT ask orders at (Size, Price): ['0.01 ETH, 2337.9 USD'] to OPEN position.
2021-07-04 17:39:42,768 - 9684 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_derivative - INFO - Created ordertype.limit tradetype.sell order sell-ETH-USD-1625391582006808 for 0.010 ETH-USD.
2021-07-04 17:39:42,768 - 9684 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1625391582000, "type": "OrderType.LIMIT", "trading_pair": "ETH-USD", "amount": "0.010", "price": "2337.9", "order_id": "sell-ETH-USD-1625391582006808", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "SellOrderCreatedEvent", "event_source": "dydx_perpetual"}
2021-07-04 17:39:42,906 - 9684 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_derivative - INFO - Created ordertype.limit tradetype.buy order buy-ETH-USD-1625391582005800 for 0.010 ETH-USD.
2021-07-04 17:39:42,906 - 9684 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1625391582000, "type": "OrderType.LIMIT", "trading_pair": "ETH-USD", "amount": "0.010", "price": "2312.4", "order_id": "buy-ETH-USD-1625391582005800", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "BuyOrderCreatedEvent", "event_source": "dydx_perpetual"}
```
DyDX

I manually cancelled the LONG position on DyDx Perpetual portal and continue to check on it. On the third filled order instance, it opens a LONG position but took a few minutes to create take-profit order:

```
2021-07-04 18:02:57,047 - 9684 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (ETH-USD) Maker buy order of 0.01 ETH filled. [clock=2021-07-04 10:02:57+00:00]
2021-07-04 18:02:57,047 - 9684 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_derivative - INFO - The market buy order buy-ETH-USD-1625392961006549 has completed according to user stream.
2021-07-04 18:02:57,047 - 9684 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1625392977.0, "order_id": "buy-ETH-USD-1625392961006549", "base_asset": "ETH", "quote_asset": "USD", "fee_asset": "USD", "base_asset_amount": "0.01", "quote_asset_amount": "23.233", "fee_amount": "0.00011616", "order_type": "OrderType.LIMIT", "exchange_order_id": null, "event_name": "BuyOrderCompletedEvent", "event_source": "dydx_perpetual"}
2021-07-04 18:02:57,069 - 9684 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (ETH-USD) Maker buy order buy-ETH-USD-1625392961006549 (0.010 ETH @ 2323.3 USD) has been completely filled. [clock=2021-07-04 10:02:57+00:00]
2021-07-04 18:02:57,447 - 9684 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_derivative - INFO - Successfully cancelled order sell-ETH-USD-1625392961006550
2021-07-04 18:02:57,448 - 9684 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1625392977.0, "order_id": "sell-ETH-USD-1625392961006550", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "dydx_perpetual"}

# After 14mins, it created a take-profit order
2021-07-04 18:17:07,003 - 9684 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (ETH-USD) Creating 1  LIMIT ask orders at (Size, Price): ['0.01 ETH, 2334.9 USD'] to CLOSE position.
2021-07-04 18:17:07,767 - 9684 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_derivative - INFO - Created ordertype.limit tradetype.sell order sell-ETH-USD-1625393827003712 for 0.010 ETH-USD.
2021-07-04 18:17:07,767 - 9684 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1625393827000, "type": "OrderType.LIMIT", "trading_pair": "ETH-USD", "amount": "0.010", "price": "2334.9", "order_id": "sell-ETH-USD-1625393827003712", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "SellOrderCreatedEvent", "event_source": "dydx_perpetual"}

# After 10mins it cancelled and created another take-profit order
2021-07-04 18:27:14,344 - 9684 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_derivative - INFO - Successfully cancelled order sell-ETH-USD-1625393827003712
2021-07-04 18:27:14,344 - 9684 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1625394434.0, "order_id": "sell-ETH-USD-1625393827003712", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "dydx_perpetual"}
2021-07-04 18:27:15,005 - 9684 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (ETH-USD) Creating 1  LIMIT ask orders at (Size, Price): ['0.01 ETH, 2334.9 USD'] to CLOSE position.
2021-07-04 18:27:15,746 - 9684 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_derivative - INFO - Created ordertype.limit tradetype.sell order sell-ETH-USD-1625394435005880 for 0.010 ETH-USD.
2021-07-04 18:27:15,746 - 9684 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1625394435000, "type": "OrderType.LIMIT", "trading_pair": "ETH-USD", "amount": "0.010", "price": "2334.9", "order_id": "sell-ETH-USD-1625394435005880", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "SellOrderCreatedEvent", "event_source": "dydx_perpetual"}
```

LONG position
image

Take-Profit order to close the position
image

image

Attached logs:
[logs_perp-dydx.zip](https://github.com/CoinAlpha/hummingbot/files/6759777/logs_perp-dydx.zip)

**Comment by RC-13** [comment]
After running dYdX perpetual connector for an hour. When the funding period comes in, the bot is getting an issue picking up the funding rate.
image
```python
Traceback (most recent call last):
  File "/Users/clint_g/Documents/Github-Repo/hb-general/hummingbot/connector/derivative/dydx_perpetual/dydx_perpetual_derivative.py", line 739, in _update_funding_rates
    await self._get_funding_info(trading_pair)
  File "/Users/clint_g/Documents/Github-Repo/hb-general/hummingbot/connector/derivative/dydx_perpetual/dydx_perpetual_derivative.py", line 727, in _get_funding_info
    markets_info = (await self.dydx_client.get_markets())['markets']
  File "/Users/clint_g/Documents/Github-Repo/hb-general/hummingbot/connector/derivative/dydx_perpetual/dydx_perpetual_client_wrapper.py", line 83, in get_markets
    return await f
  File "/Users/clint_g/opt/anaconda3/envs/hummingbot/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/clint_g/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/dydx3/modules/public.py", line 70, in get_markets
    return self._get(uri, {'market': market})
  File "/Users/clint_g/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/dydx3/modules/public.py", line 16, in _get
    return request(
  File "/Users/clint_g/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/dydx3/helpers/requests.py", line 18, in request
    response = send_request(
  File "/Users/clint_g/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/dydx3/helpers/requests.py", line 32, in send_request
    return getattr(session, method)(uri, headers=headers, **kwargs)
  File "/Users/clint_g/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/Users/clint_g/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/clint_g/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Users/clint_g/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(60, 'ETIMEDOUT')"))
2021-07-05 12:25:27,077 - 8717 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_derivative - WARNING - Could not fetch funding_rate for ETH-USD. Check API key and network connection.
```
[logs_conf_perpetual_market_making_1.log](https://github.com/CoinAlpha/hummingbot/files/6761824/logs_conf_perpetual_market_making_1.log)

**Comment by Nullably** [comment]
@rapcmia 
> The bot should open a LONG position and then create take-profit order but it did not. Instead, it tries to create orders again to open a position.

I couldn't reproduce this behaviour. To me, the bot recognises the position, and it created a profit taking order after 12 minutes as the position profit was negative beforehand (as intended, according to doc).
image

I couldn't yet reproduce your other errors but it seems to me to be existing bugs in the strategy and not caused by this PR.

**Comment by Nullably** [comment]
@RC-13 
> After running dYdX perpetual connector for an hour. When the funding period comes in, the bot is getting an issue picking up the funding rate.

I can't reproduce this one as running the bot for 45 minutes. I have checked the code manually on the getting funding info part, it seems to work fine. This might be exiting issue unrelated to this PR.

**Comment by RC-13** [comment]
Thanks, @Nullably, it appears that you are right. I ran a bot overnight and it didn't get any funding error, however after I started another bot using the same market when a position was opened, this triggers the funding error in the first bot that was run overnight.

**Review by RC-13 — APPROVED** [review]
LGTM

**Pull request merged**
