### PR TITLE
Epic/config management refactoring

### PR DESCRIPTION
**Pull request by petioptrv**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

This PR lays the foundation for a refactor of the configuration management of `hummingbot`. 

The new approach uses `pydantic` models to define the configuration maps. Aside from built-in validation functionality, this approach also allows the automatic generation of JSON schemas which is a big first step in the direction of decoupling the bot from its interface. Another major step in that direction is significantly restricting the use of global variables when dealing with the global config map (now renamed to client config map) and the `AllConnectorSettings` class.

The approach to storing and retrieving secure configs has also been refactored. We no longer store secure configs in the client config map (former global config map). Those are only stored in the `Security` class (which is still unfortunately accessed globally). In addition, the secure values are no longer stored separate from non-secure configs — they are both part of the same config map and stored in the same `yaml` file.

Two of the strategies, `AMM` and `XEMM`, were already adapted to the new configs style. The rest remain to be adapted. To accommodate for legacy configs, some of the legacy config management code still remains. If the legacy functionality is an entire function, then the function has been renamed with a `_legacy` postfix. If the legacy functionality are lines of code part of an otherwise non-refactored routine, then a comment `# legacy` was added. This was done to later facilitate complete removal of legacy config code.

The `Pydantic` model now allows for nested config maps. This is used for two purposes. First, it is used to provide more organizational structure as with the color map, which is now a nested sub-model of the client config map. Second, it is used to provide conditional requirements for the configurations (i.e. "field `foo` is required only if field `bar` is est to the value `X`). An example of this is the `AvellanedaMarketMakingConfigMap.execution_timeframe_mode` field.

A legacy migration routine was included on the bot's startup, which will detect if the bot is being ran for the first time since the upgrade, and will guide the user through the migration of the refactored configs. The routine will start by creating a backup of the current state of the configs folder, and proceed from there. It will also alert the user if any config map migration failed along the way.

The folder structure of the configs has been further split into `connectors` and `strategies` for better organization.

**Tests performed by the developer**:

- Unit tests for the covered changes.
- Manual tests for a good portion of the changes.

**Tips for QA testing**:

- Please re-run essentially a full test of the client. Some of the specific things I can think of are listed below.
- All commands should be re-tested with the config command thoroughly re-tested, including secure configs.
- Please make sure to test odd cases like `celo` as well.
- Gateway should be tested.
- XEMM and AMM configs can be tested superficially (no need to thoroughly test these as they have been tested previously and have not changed since then).

### CODE REVIEW

**Comment by rxlxrxsx** [comment]
- Getting this message after entering the old password during migration process

Screen Shot 2022-06-14 at 4 28 31 PM

**Comment by petioptrv** [comment]
@rxlxrxsx, the latest commit addresses this warning.

**Comment by rxlxrxsx** [comment]
- This is confirmed fix.

> Getting this message in the background after entering the old password during migration process

- Another issue found, getting this error after starting a strategy when kill switch is enabled.

Screen Shot 2022-06-14 at 8 41 31 PM

```python
2022-06-14 20:46:26,980 - 24694 - hummingbot.core.utils.kill_switch - ERROR - Error calculating profitability: 'ActiveKillSwitch' object has no attribute '_kill_switch_enabled'
Traceback (most recent call last):
  File "/Users/reiniersalazar/hummingbot/hummingbot/core/utils/kill_switch.py", line 44, in check_profitability_loop
    if self._kill_switch_enabled:
AttributeError: 'ActiveKillSwitch' object has no attribute '_kill_switch_enabled'
```

**Comment by RC-13** [comment]
Similar to the issue reported by Rein, we get the following error as well when enabling a PMM script which prevents the strategy to start:
```python
2022-06-15 10:23:45,769 - 90057 - hummingbot.client.hummingbot_application - ERROR - 'PMMScriptEnabledMode' object has no attribute 'strategy'
Traceback (most recent call last):
  File "/Users/clintg/testing/epic-pydantic/hummingbot/client/command/start_command.py", line 208, in start_market_making
    self._pmm_script_iterator = self.client_config_map.pmm_script_mode.get_iterator(
  File "/Users/clintg/testing/epic-pydantic/hummingbot/client/config/client_config_map.py", line 404, in get_iterator
    self.strategy,
AttributeError: 'PMMScriptEnabledMode' object has no attribute 'strategy'
```
image

**Comment by petioptrv** [comment]
@rxlxrxsx, the latest flagged issue should be fixed along with the merge commit I pushed just now

**Comment by Deepali6997** [comment]
The issue which was flagged is now fixed in the latest commit.

Screenshot 2022-06-22 at 2 18 28 PM

Screenshot 2022-06-22 at 2 15 59 PM

[logs_conf_pure_mm_1.log](https://github.com/CoinAlpha/hummingbot/files/8956024/logs_conf_pure_mm_1.log)

**Review by Deepali6997 — APPROVED** [review]
Test Summary

-Tested the following commands successfully. Namely  kill switch, telegram integration, autofill import, PPm-script feature, colour configuration settings, client command options, rate limit and rate timeouts
-Tested the following in AMM. Creation of AMM strategy, reviewing of log pane after strategy is started, configure strategy while running, stoping the strategy and then configuring the parameters
-Tested the following in XMM. Creation of AMM strategy, reviewing of log pane after strategy is started, configure strategy while running, stoping the strategy and then configuring the parameters
-Tested Gateway as well. Creating a docker instance, gateway create, connecting infura, connecting gateway connectors, verification of gateway status, gasLimit check, allowed slippage check
-And Docker testing, wherein Docker image was created from feature branch, verifying migration feature, running import command to check all the available strategies

**Comment by petioptrv** [comment]
Closing to re-open towards foundation:

**Pull request closed without merging**
