### PR TITLE
fix/ Incorrect balance reporting

### PR DESCRIPTION
**Pull request by CrimsonJacket**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Fix Issues:
#2773 #2864

### CODE REVIEW

**Comment by rxlxrxsx** [comment]
Tested and confirmed working on Binance
Screen Shot 2021-01-26 at 4 03 56 PM

USDT still not getting picked up on Bitfinex
Screen Shot 2021-01-26 at 4 50 47 PM

Note: Tokens that are not supported by Binance will still show 0 on the Total USD conversion column which is currently the expected behavior.
Example:
Screen Shot 2021-01-26 at 5 16 57 PM

Screen Shot 2021-01-26 at 5 16 42 PM

**Comment by rapcmia** [comment]
Checked this as well inline with #2773, PHB has now value.
image

**Comment by CrimsonJacket** [comment]
@rxlxrxsx @rapcmia Made some changes to handle specific trading pairs and tokens in BitFinex. This should resolve issues in #2864

**Review by rxlxrxsx — APPROVED** [review]
Tested latest commits and confirmed working. USDT token on Bitfinex now showing values on Total USD conversion column.
Screen Shot 2021-01-28 at 12 50 53 PM

Also, when configuring `market` on Bitfinex it now shows USDT instead of UST which is basically the same token.
Screen Shot 2021-01-28 at 12 59 12 PM

**Pull request merged**
