### PR TITLE
Feat/binance multiple domains

### PR DESCRIPTION
**Pull request by Nullably**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**After creating this PR, please make sure:**

- [x] You link the related GitHub issue or ticket

**A description of the changes proposed in the pull request**:
- Binance US connector is available in this PR
- Since there are changes in binance connector, please retest our existing binance connector as well.

### CODE REVIEW

**Comment by RC-13** [comment]
After adding Binance.com API key, Binance.us API info will be asked immediately. It doesn't happen if you start add Binance.us API key first, however, even if you add Binance.us API key first, it will be asked again once you add the Binance.com API info.
Binance_US-1

PMM strategy fails to start, bot is stuck connecting websocket
Binance_US-2

enabling paper trade gives shows the following error upon starting strategy:  `Connector Binance_us OrderBookTracker class not found`
Binance_US-3 (paper)
```
2020-10-20 20:48:01,290 - 1720 - hummingbot.connector.exchange.binance.binance_exchange - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2020-10-20 20:48:02,023 - 1720 - hummingbot.connector.exchange.binance.binance_order_book_tracker - INFO - Initialized order book for ETH-BTC. 1/1 completed.
2020-10-20 20:48:02,066 - 1720 - hummingbot.connector.exchange.binance.binance_api_user_stream_data_source - INFO - Reconnecting to wss://stream.binance.us:9443/ws/AfUY2oKoBv3LDCFs00So7AvYK30rRjlyR6gHI1LHxOkmPJUubEjFZHkS9Noq.
2020-10-20 20:52:19,244 - 1720 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2020-10-20 20:52:30,915 - 1720 - hummingbot.client.hummingbot_application - ERROR - Unknown error during initialization.
Traceback (most recent call last):
  File "/home/rsa-key-20200326/hb-source/hummingbot/hummingbot/strategy/pure_market_making/start.py", line 56, in start
    self._initialize_markets(market_names)
  File "/home/rsa-key-20200326/hb-source/hummingbot/hummingbot/client/hummingbot_application.py", line 210, in _initialize_markets
    connector = create_paper_trade_market(market_name, trading_pairs)
  File "/home/rsa-key-20200326/hb-source/hummingbot/hummingbot/connector/exchange/paper_trade/__init__.py", line 20, in create_paper_trade_market
    order_book_tracker = get_order_book_tracker_class(exchange_name)
  File "/home/rsa-key-20200326/hb-source/hummingbot/hummingbot/connector/exchange/paper_trade/__init__.py", line 16, in get_order_book_tracker_class
    raise Exception(f"Connector {connector_name} OrderBookTracker class not found")
Exception: Connector binance_us OrderBookTracker class not found
```
[logs_pmm-binance-us.log](https://github.com/CoinAlpha/hummingbot/files/5411964/logs_pmm-binance-us.log)

**Comment by Nullably** [comment]
I fixed the connect command and paper trade bugs.
However I cannot reproduce this
> PMM strategy fails to start, bot is stuck reconnecting to websocket

The changes that I have done on the other might have fixed it, can you please retest. 
Thanks

**Comment by rxlxrxsx** [comment]
Confirmed fix on ``connect`` command and paper trade bug. I'm getting a similar behavior regarding the websocket reconnecting after starting the strategy (see third screenshot below).

connect binance
paper trade binance us

Websocket reconnection

wss

**Comment by Nullably** [comment]
@rxlxrxsx 
Can you do `balance` command and show me the result?

**Comment by rxlxrxsx** [comment]
Currently the account doesn't have any balance yet, it's possible that it's the reason for the behavior shown but should it notify something like ``Insufficient balance`` instead? Will test this again after acquiring the asset needed for testing.

**Comment by Nullably** [comment]
@rxlxrxsx Yeah, it's possible Binance limits parts of their functionality if an account is new and has no balance.

**Comment by ZeroCool940711** [comment]
@Nullably and @rxlxrxsx I'm pretty sure that behavior and messages on the log reconnecting after a few minutes is normal on Binance, at least I have the same behavior on my Binance.us connector, I think they disconnect you if a websocket subscription is open for more than a few minutes or if you make too many requests, when it reconnects HB will just continue like normal from where it left so it isn't really that bad, you could try to see if you can fix it but the bot works even with that, just saying.

**Comment by thomasyit** [comment]
@Nullably edited task4

**Comment by Nullably** [comment]
@ZeroCool940711 Thanks a lot for detailed explanation. 
@thomasyit Thanks for the edit.

**Review by dennisocana — DISMISSED** [review]
Tested and recommended by QA to be merged into development.

**Comment by Nullably** [comment]
@dennisocana Thanks. I found a small minor issue and updated the branch.

**Review by dennisocana — APPROVED** [review]
LGTM

**Pull request merged**
