### PR TITLE
fix/ get funding info error

### PR DESCRIPTION
**Pull request by Nullably**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
- Looks like @vic-en forgot to update the strategy when he refactored perp connectors.

### CODE REVIEW

**Review by rxlxrxsx — DISMISSED** [review]
Tested and confirmed fix by QA. Bot is now able to run perpetual_market_making properly.
Screen Shot 2021-03-08 at 12 13 36 PM

**Comment by vic-en** [comment]
I revised the `c_apply_budget_constraint` function.
Factoring in the funding fee isn't necessary.

**Review by vic-en — APPROVED** [review]
@Nullably @rxlxrxsx PR is still OK to merged despite my revision.

**Review by RC-13 — APPROVED** [review]
Re-approving in behalf of @rxlxrxsx. Re-tested and did not encounter any issue, tried on different markets and each market started and open orders accordingly.

**Pull request merged**
