### PR TITLE
Refactor/gate io throttler

### PR DESCRIPTION
**Pull request by petioptrv**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This PR refactors the Gate.io connector to use the new `AsyncThrottler`. It also introduces unit-tests for the parts of the code affected by this change.

**Tests performed by the developer**:
- Unit tests added for the relevant parts of the code that were affected by the change.

**Tips for QA testing**:
- As the limits are quite liberal on this one, to check that the requests do get rate-limited, the percentage of the rate limit allocated to the client must be something along the lines of 0.3% with two orders on each side of the trade.
- Ensure that the connector otherwise functions as expected (places, cancels , and detects fills on orders)

### CODE REVIEW

**Comment by petioptrv** [comment]
> Best to include the whole lot in the throttler task as before, if you generate the auth signature (with time based nonce) with too much of a delay (due to throttling) before making the http call it may cause failures

Nice catch; included

**Comment by rapcmia** [comment]
While testing on PMM with `rate_limit_share_pct set to 1%`, `order_refresh of 5s`, and `multiple orders`, there were instances that after successfully cancels the order the bot getting an error on submitting an order due to the `available balance` not being updated. Though getting warnings of rate limit (9 calls per 1s) the bot still managed to create orders. 

Tried to crosscheck if this happens on the master and dev branch but no go (however there is an ongoing issue/[3686](https://github.com/CoinAlpha/hummingbot/issues/3686))

Here is a recording for reference, the issue started in 25s

https://user-images.githubusercontent.com/73840223/132185686-e8a191e5-2825-439e-8146-18510473107c.mp4

```
2021-09-06 15:28:33,254 - 20208 - hummingbot.connector.exchange.gate_io.gate_io_exchange - INFO - Successfully cancelled order t-HBOT-B-ASUT1630913307981858 on gate_io.
2021-09-06 15:28:33,254 - 20208 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1630913313.0, "order_id": "t-HBOT-B-ASUT1630913307981858", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "gate_io"}
2021-09-06 15:28:34,006 - 20208 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (AXS-USDT) Creating 1 bid orders at (Size, Price): ['0.002 AXS, 81.809 USDT']
2021-09-06 15:28:34,114 - 20208 - hummingbot.connector.exchange.gate_io.gate_io_exchange - NETWORK - Error submitting BUY LIMIT order to gate_io for 0.002 AXS-USDT 81.809 - Your order size 0.002 is too small. The minimum is 1 USDT.
Traceback (most recent call last):
  File "C:\Users\Ralph\github\4088\hummingbot\connector\exchange\gate_io\gate_io_exchange.py", line 473, in _create_order
    order_result = await self._api_request("POST", CONSTANTS.ORDER_CREATE_PATH_URL, api_params, True)
  File "C:\Users\Ralph\github\4088\hummingbot\connector\exchange\gate_io\gate_io_exchange.py", line 376, in _api_request
    raise GateIoAPIError(parsed_response)
hummingbot.connector.exchange.gate_io.gate_io_utils.GateIoAPIError: {'label': 'INVALID_PARAM_VALUE', 'message': 'Your order size 0.002 is too small. The minimum is 1 USDT'}
```

Steps to reproduce:
1. Create Pure Market Making and set rate_limit_share_pct to 1%
2. Set low order_refresh time (tested on 5s) and order levels 
3. Start the bot and notice there are instances the available balance is not being updated

Attached:
[pmm-test.zip](https://github.com/CoinAlpha/hummingbot/files/7114495/pmm-test.zip)

**Comment by petioptrv** [comment]
@rapcmia, here is the issue reproduced on `development`. The config file is the one you've attached, with an `a-` attached to it.

Attached:
[logs_a-pmm-test.log](https://github.com/CoinAlpha/hummingbot/files/7121993/logs_a-pmm-test.log)

**Review by CrimsonJacket — APPROVED** [review]
Changes LGTM. Do however resolve the issue that QA has brought up.

**Review by rapcmia — APPROVED** [review]
Tested and confirmed all working in behalf of QA team

**Pull request merged**
