### PR TITLE
(feat) Adds `isort` pre-commit hook.

### PR DESCRIPTION
**Pull request by petioptrv**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Adds the `isort` git pre-commit hook to sort the imports of modified files.

**Tests performed by the developer**:
Tested it on a dummy commit

**Tips for QA testing**:
N/A

### CODE REVIEW

**Comment by aarmoa** [comment]
Shouldn't we add isort to the prerequisites? Does the pre commit change work without isort installed?

**Comment by petioptrv** [comment]
When we run the install command, pre-commit will install it automatically based on the `.pre-commit-config.yaml` file

**Review by aarmoa — APPROVED** [review]
The change looks good to me

**Comment by petioptrv** [comment]
Closing to re-open towards foundation repo

**Pull request closed without merging**
