### PR TITLE
cleanup / remove unneeded methods that are now in other repo

### PR DESCRIPTION
**Pull request by kmcgowan2000**
Before submitting this PR, please make sure:

Your code builds clean without any errors or warnings
You are using approved title ("feat/", "fix/", "docs/", "refactor/")

A description of the changes proposed in the pull request:These methods were only used in a separate repo, and so have now been moved there to be maintained by the relevant team.

Tests performed by the developer:

Tips for QA testing:

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ran44k) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by kmcgowan2000** [comment]
hmm, I didn't change any dependencies but it's failing the install step

**Comment by phbrgnomo** [comment]
@kmcgowan2000 @dennisocana is this PR still needed?

**Comment by kmcgowan2000** [comment]
@aarmoa this one's stale but yeah feel free to remove these (tbh might be easier to create a new branch for this than properly refresh this one)

**Comment by aarmoa** [comment]
I close this PR after creating a new one applying the clean up on top of the current development branch (see #4932)

**Pull request closed without merging**
