### PR TITLE
hotfix/ kucoin api v2 update to master

### PR DESCRIPTION
**Pull request by Nullably**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
- A hotfix to `master` branch

### CODE REVIEW

**Review by rxlxrxsx — DISMISSED** [review]
Tested and confirmed working by QA.

**Review by CrimsonJacket — APPROVED** [review]
LGTM

**Review by dennisocana — APPROVED** [review]
Accidentally dismissed QA's review. Re-adding merge approval.

**Review by vic-en — APPROVED** [review]
LGTM

**Pull request merged**
