### PR TITLE
Fix/ndax order book out of sync

### PR DESCRIPTION
**Pull request by aarmoa**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Change to provide the bid and ask events to the client order book sorted by price and age. Not doing that brakes the order book internal lists.
Also added a validation in the REST API request execution in the exchange class to detect the API limit reached error.
Changed the implementation of the function that provides the last traded price for a trading pair to reuse the information that is regularly received as events to update the order book.

**Tests performed by the developer**
Added unit tests.
Tested manually by running the bot connected to the NDAX production server and using a PMM strategy.

### CODE REVIEW

**Review by CrimsonJacket — COMMENTED** [review]
Tested this PR and it seems like the orderbook is still having sync issues.

**Review by aarmoa — COMMENTED** [review]
I agree with all the changes introduced by @CrimsonJacket on top of my initial commit

**Review by CrimsonJacket — APPROVED** [review]
As @aarmoa mentioned I will approve this PR on his behalf.

**Review by PtrckM — APPROVED** [review]
Tested and confirmed working using aws cloud and local. Approving in behalf of QA

- Observe the bot for more than 30 minutes this fix https://github.com/CoinAlpha/hummingbot/issues/3861 :white_check_mark: 

- I had an issue and only occurs once during testing and can't replicate it, included it here just for reference:
    - duplicate orders
ndax2
ndax3
   - orderbook empty
ndax1
```
2021-08-07 02:46:51,002 - 23262 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 698, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_tick
    self.c_apply_budget_constraint(proposal)
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 867, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_apply_budget_constraint
    if quote_balance < quote_size:
decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]
2021-08-07 02:46:52,000 - 23262 - hummingbot.connector.exchange.ndax.ndax_exchange - WARNING - Ask orderbook for BTC-CAD is empty.
2021-08-07 02:46:52,000 - 23262 - hummingbot.connector.exchange.ndax.ndax_exchange - WARNING - Buy orderbook for BTC-CAD is empty.
2021-08-07 02:46:52,000 - 23262 - hummingbot.connector.exchange.ndax.ndax_exchange - WARNING - Ask orderbook for BTC-CAD is empty.
2021-08-07 02:46:52,000 - 23262 - hummingbot.connector.exchange.ndax.ndax_exchange - WARNING - Buy orderbook for BTC-CAD is empty.
2021-08-07 02:46:52,001 - 23262 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
```
   - delay on start
ndax4

Logs and configs: 
[ndax.zip](https://github.com/CoinAlpha/hummingbot/files/6948562/ndax.zip)

**Comment by rapcmia** [comment]
While testing the PR, I can confirm that the order book from the client and Ndax are matched. However, when I tried to use one of our supported exchanges as my primary and use Ndax as an external price source, I'm getting a clock-tick error of `ValueError: No order book exists for 'BTC-USDT'`

Steps to reproduce
1. Create PMM using any of our supported exchanges (tested on Binance/Kucoin)
2. Set price source to external_market
3. Set price source exchange to ndax
4. Set price source market to BTC-USDT

Tested on Kucoin
Price source to Ndax failed kucoin

Tested on Binance: 
Price source to Ndax failed binance

Both getting the same error below:
```

2021-08-08 15:12:04,016 - 15936 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot\\core\\clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot\\strategy\\pure_market_making\\pure_market_making.pyx", line 673, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_tick
    self._all_markets_ready = self._asset_price_delegate.ready
  File "hummingbot\\strategy\\order_book_asset_price_delegate.pyx", line 18, in hummingbot.strategy.order_book_asset_price_delegate.OrderBookAssetPriceDelegate.ready.__get__
    return self._market.ready
  File "hummingbot\\connector\\exchange\\paper_trade\\paper_trade_exchange.pyx", line 238, in hummingbot.connector.exchange.paper_trade.paper_trade_exchange.PaperTradeExchange.ready.__get__
    self.init_paper_trade_market()
  File "hummingbot\\connector\\exchange\\paper_trade\\paper_trade_exchange.pyx", line 198, in hummingbot.connector.exchange.paper_trade.paper_trade_exchange.PaperTradeExchange.init_paper_trade_market
    assert type(order_book) is CompositeOrderBook
AssertionError
2021-08-08 15:12:04,690 - 15936 - hummingbot.client.ui.hummingbot_cli - ERROR - Unhandled error in prompt_toolkit: 
NoneType: None
2021-08-08 15:12:04,980 - 15936 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot\\core\\clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot\\strategy\\pure_market_making\\pure_market_making.pyx", line 690, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_tick
    proposal = self.c_create_base_proposal()
  File "hummingbot\\strategy\\pure_market_making\\pure_market_making.pyx", line 717, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_create_base_proposal
    buy_reference_price = sell_reference_price = self.get_price()
  File "hummingbot\\strategy\\pure_market_making\\pure_market_making.pyx", line 381, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.get_price
    price = price_provider.get_price_by_type(self._price_type)
  File "hummingbot\\strategy\\order_book_asset_price_delegate.pyx", line 21, in hummingbot.strategy.order_book_asset_price_delegate.OrderBookAssetPriceDelegate.get_price_by_type
    return self._market.get_price_by_type(self._trading_pair, price_type)
  File "hummingbot\\connector\\exchange_base.pyx", line 277, in hummingbot.connector.exchange_base.ExchangeBase.get_price_by_type
    return (self.c_get_price(trading_pair, True) + self.c_get_price(trading_pair, False)) / Decimal("2")
  File "hummingbot\\connector\\exchange_base.pyx", line 100, in hummingbot.connector.exchange_base.ExchangeBase.c_get_price
    OrderBook order_book = self.c_get_order_book(trading_pair)
  File "hummingbot\\connector\\exchange\\paper_trade\\paper_trade_exchange.pyx", line 912, in hummingbot.connector.exchange.paper_trade.paper_trade_exchange.PaperTradeExchange.c_get_order_book
    raise ValueError(f"No order book exists for '{trading_pair}'.")
ValueError: No order book exists for 'BTC-USDT'.
```

Tested using development branch seems to work ok:
Price source to Ndax ok on dev branch

**Comment by rxlxrxsx** [comment]
Using NDAX on paper trade mode seems to be broken as well. I got this immediately after starting the bot.

Screen Shot 2021-08-08 at 3 50 14 PM

```
2021-08-08 15:50:00,133 - 12553 - hummingbot.client.hummingbot_application - ERROR - 
Traceback (most recent call last):
  File "/Users/reiniersalazar/hummingbot2/hummingbot/client/command/start_command.py", line 159, in start_market_making
    await self.wait_till_ready(self.kill_switch.start)
  File "/Users/reiniersalazar/hummingbot2/hummingbot/client/command/start_command.py", line 45, in wait_till_ready
    all_ready = all([market.ready for market in self.markets.values()])
  File "/Users/reiniersalazar/hummingbot2/hummingbot/client/command/start_command.py", line 45, in <listcomp>
    all_ready = all([market.ready for market in self.markets.values()])
  File "hummingbot/connector/exchange/paper_trade/paper_trade_exchange.pyx", line 238, in hummingbot.connector.exchange.paper_trade.paper_trade_exchange.PaperTradeExchange.ready.__get__
    self.init_paper_trade_market()
  File "hummingbot/connector/exchange/paper_trade/paper_trade_exchange.pyx", line 198, in hummingbot.connector.exchange.paper_trade.paper_trade_exchange.PaperTradeExchange.init_paper_trade_market
    assert type(order_book) is CompositeOrderBook
AssertionError
```

Logs and config: [ndax.zip](https://github.com/CoinAlpha/hummingbot/files/6950407/ndax.zip)

**Pull request merged**
