### PR TITLE
Fix/pure mm hanging memory leak

### PR DESCRIPTION
**Pull request by veecos2**
**Before submitting this PR, please make sure**:
- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue:
https://github.com/CoinAlpha/hummingbot/issues/1167
- Related Clubhouse Story:
https://app.clubhouse.io/coinalpha/story/6715/hanging-orders-resulting-to-memory-leak

**A description of the changes proposed in the pull request**:
In flight orders inside the market class were not being removed once its left hanging by the strategy. Moved the stop tracking order to market base and called that for hanging orders mode.

### CODE REVIEW

**Comment by martinkou** [comment]
The stop tracking patch should theoretically solve the memory leak problem - yes. However, the current implementation for `enable_order_filled_stop_cancellation` seems strange... simply stopping tracking means the strategy is free to make more orders on the same side on the next tick. Is this the intended result?

**Comment by veecos2** [comment]
Yes, that is how we want this feature to work.

**Comment by dennisocana** [comment]
Confirmed no more continuous increase in memory usage. One noticeable behavior is it uses more memory this time (2.7gb) than it used to before (1.7gb). Below are screenshots taken when Hummingbot started and kept running after 12 hours.

**Comment by veecos2** [comment]
Hummingsim needs to be updated for this

**Comment by veecos2** [comment]
test this please

**Comment by veecos2** [comment]
test this please

**Comment by veecos2** [comment]
test this

**Comment by veecos2** [comment]
test this please

**Comment by veecos2** [comment]
The tests are working locally for me and Daniel with the latest environment. They are only failing in Jenkins.

**Comment by veecos2** [comment]
Investigating the linux build which Jenkins uses.

**Pull request merged**
