### PR TITLE
Feat / Arbitrage - Add more Price Sources for Base+Quote Conversion rates

### PR DESCRIPTION
**Pull request by TheHolyRoger**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Depends on PRs https://github.com/CoinAlpha/hummingbot/pull/3128 and https://github.com/CoinAlpha/hummingbot/pull/3123
This PR must be rebased after those PRs are merged. ⚠️ 

As discussed with @Nullably & @phbrgnomo 
Fixes: https://github.com/CoinAlpha/hummingbot/issues/2797

### CODE REVIEW

**Comment by TheHolyRoger** [comment]
Screenshot 2021-01-25 at 14 41 49

Screenshot showing it in action - the external price feeds are also added to the status display

**Comment by TheHolyRoger** [comment]
Should probably consolidate some of the quote/base price methods into single methods with `asset_mode` parameters

**Comment by dennisocana** [comment]
@Nullably please do a quick review of this PR to see how it affects or is related to the rate oracle module story we have in the pipeline

**Comment by TheHolyRoger** [comment]
@Nullably @dennisocana I've been working on the same thing for XEMM, seems to work as I'm actively using it now :)
https://github.com/CoinAlpha/hummingbot/compare/development...TheHolyRoger:feat/xemm-price-sources?w=1

Given the duplicated code/classes I'd be happy to tackle a new PR to refactor the price delegates from PMM (+arb, XEMM) into `strategy_base`

**Comment by Nullably** [comment]
@TheHolyRoger Thanks a lot for sharing your code with us, and sorry for taking a long time to get back to you (I spent weeks battling with covid earlier this year, still am to an extent actually). 

I like the approach in general. I can see our soon coming Rate Oracle could be one source of the rate conversion. 
There are a few terminology that we should clarify to avoid confusion. 
`base_price_source` - This should be more like `base_rate_conversion_source` and in use only when base tokens of primary and secondary markets differ.
`quote_price_source` - Similarly to above.
`base_price_source_type` - This is more like `base_conversion_ext_market_price_type` since it applies only when external market is chosen as a base_rate_conversion_source. 
`quote_price_source_type` - Similarly to above.

Not sure if we should offer custom API source, in the past this wasn't popular and the CustomAPIDataFeed might no longer work properly, @dennisocana Can you please confirm on this.

@phbrgnomo From the product prospective, what do you think? Is this approach easy to use and clear enough to understand to most users?

**Comment by Nullably** [comment]
> @Nullably @dennisocana I've been working on the same thing for XEMM, seems to work as I'm actively using it now :)
> https://github.com/CoinAlpha/hummingbot/compare/development...TheHolyRoger:feat/xemm-price-sources?w=1
> 
> Given the duplicated code/classes I'd be happy to tackle a new PR to refactor the price delegates from PMM (+arb, XEMM) into `strategy_base`

I think what we can do is simply move the price delegate classes to `strategy` and any strategy that want to use them and import them as needed. I don't think we need to modify `strategy_base` for this.

**Comment by TheHolyRoger** [comment]
No worries @Nullably sorry to hear that but hope it starts to bugger off soon!

I'll make all these changes and wait for feedback from @phbrgnomo re removing custom_api.

Shall I include the moving of the delegate classes to `strategy` as part of this PR too? Would only be a couple of import changes in the PMM strat too.

But yeah probably best for me to hold off and rebase this all from the 0.37 release since it's so close :)

**Comment by phbrgnomo** [comment]
@TheHolyRoger the PR #3036 is our starting point on implementing an external price oracle in a more general way to be used on any strategy.

Feel free to take a look and any comments there.

**Comment by TheHolyRoger** [comment]
@Nullably 
If this PR is going to be merged, maybe it's worth me consolidating the settings and including rate oracle as a setting in `base_rate_conversion_source` and `quote_rate_conversion_source`?

https://github.com/CoinAlpha/hummingbot/pull/2865/commits/ff7173b1cd0b7352336ce6df171c977f70eb920f#diff-811f0083dd10e0078d65d7f6076b2df23eee44a7c29c5a09c6da06db93899a0cR165

**Comment by phbrgnomo** [comment]
@TheHolyRoger Thanks a lot for you contribution, and it helped us understand a lot how to work with price sources and conversions.

After looking through the PR we used it as inspiration, but we are going to implement the ideas through some different solutions.

You can check the solution we will be working on issues #3495 and #3494.

We are closing this PR for now, but feel free to contribute with the Issues mentioned above.

**Pull request closed without merging**
