### PR TITLE
Fix/dexalot lost orders fix

### PR DESCRIPTION
**Pull request by petioptrv**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

This PR addresses the issue where Dexalot orders remain stuck (orphaned) on the exchange.

[ch-45141]

**Tests performed by the developer**:

Unit tests.

**Tips for QA testing**:

Please ensure the behaviour is no longer reproducible.

### CODE REVIEW

**Comment by mrhzysbl** [comment]
Test run: https://hummingbot.testrail.io/index.php?/runs/view/5122&group_by=cases:section_id&group_order=asc

**Review by vic-en — APPROVED** [review]
LGTM

**Review by rxlxrxsx — APPROVED** [review]
Tested and confirmed working by QA.

- Successfully cloned and installed the branch
- Successfully setup gateway both on source and docker
- Connected API keys (valid and invalid key) and confirmed working as expected
- Confirmed wallet and exchange balances are reflecting correct
- Created a pure_mm strategy and went through initial prompts successfully
- Started the strategy without issues, confirmed orders are created and cancelled based on config
- Confirmed order book prices is in sync with the exchange
- Trade information are correct based on history command output
- Compared trades in client and exchange, no discrepancies found
- Confirmed hanging order/cancellation and multiple order levels works as expected

**Comment by petioptrv** [comment]
Closing to re-open towards foundation

**Pull request closed without merging**
