### PR TITLE
fix / telegram commands not working

### LINKED ISSUE #3062: Telegram - Various commands not working correctly
**Describe the bug**
If you enter the command "trades" via the bot UI it will report trades for the last 24 hours, ie using default values for the positional arguments

If you enter the same command via telegram the following error is generated:

2021-03-10 07:27:39,622 - 1 - hummingbot.client.ui.hummingbot_cli - ERROR - Unhandled error in prompt_toolkit: trades() missing 3 required positional arguments: 'days', 'market', and 'open_order_markets'

**Release version**
dev-0.37.0

### PR DESCRIPTION
**Pull request by zappra**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

Fixes #3062 

Telegram commands are relayed via call_soon_threadsafe and there were some missing arguments

### CODE REVIEW

**Comment by zappra** [comment]
Fixed balance command in addition to commands noted in original issue

**Comment by zappra** [comment]
Hiya can I get a review for this PR?

**Comment by CrimsonJacket** [comment]
The reason for this failing the coverage check is because the coverage tool is considering coverage for commands. Let me get back to you @zappra once we have come to a decision on what to do for command coverages.

**Comment by aarmoa** [comment]
In my opinion the best way to proceed it to approve the PR disregarding the diff-coverage failure. Changes done by Zappra are  related to execution of commands in multiple threads, and that is functionality that would be very difficult to unit test.

**Review by CrimsonJacket — APPROVED** [review]
Changes LGTM. As per discussed with the team, I will be approving the PR as is, ignoring the coverage diff.

**Pull request merged**
