### PR TITLE
feat / config process tests

### PR DESCRIPTION
**Pull request by Nullably**
**Before submitting this PR, please make sure**:
- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue:
- Related Clubhouse Story: 6882

**A description of the changes proposed in the pull request**:
- Add test cases for configuration process
- The tests simulate user response and test conditions are mainly based on feedback/prompt on the screen.
- Fixture test data is added to offer a bit more flexibility when configuration procedure is updated. 
- The tests can be run from PyCharm, however the run configuration needs to be set similar to how to run the bot normally (as opposed to running as unittest cases)

### CODE REVIEW

**Comment by martinkou** [comment]
As discussed after the standup today... Jenkins CI doesn't provide a terminal to the unit testing process - this causes prompt_toolkit to fail.

You may experiment with `pty.spawn()` to fork the process again with a pseudo-terminal to do the test. But I don't expect that to be easy. Failing that... we may just ask QA team to manually test it every month or so.

**Comment by Nullably** [comment]
@martinkou I have tried pty.spawn() quickly but couldn't get it to work. 
So I excluded this test from jenkins build (by moving it to integration folder), the test got to be run manually.

**Comment by Nullably** [comment]
Run Tests

**Comment by Nullably** [comment]
run tests

**Pull request merged**
