### PR TITLE
refactor/ remove blocking get_mid_price

### PR DESCRIPTION
**Pull request by Nullably**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
- Remove blocking `get_mid_price`, use `get_last_price` instead
- prompt and validator on config_var can now be async (optional)

### CODE REVIEW

**Comment by Nullably** [comment]
`get_mid_price` was used in a few configurations, but it uses blocking `requests` library. I refactored it to use `get_last_price` instead (this is non blocking). `get_mid_prices` is used for below configurations:
* `order_amount` where minimum order amount is checked against, this applies to most strategies where order_amount is required.
* `inventory_target_base_pct` on pure_market_making strategy

As part of the refactoring, I updated `prompt` and `validator` to accept `async` function (optional).

For testers, please help test the above configuration plus
* Test if overall configuration process of `import` and `create` work correctly on our major strategies.
* Check particularly if prompt messages show up correctly and config values are validated as intended.

**Comment by rxlxrxsx** [comment]
- When choosing the trading pair for Balancer or Uniswap, client will freeze intermittently until you enter a trading pair. While in this situation, client will freeze for approximately 5-10 minutes and will recover for 2 seconds, after that it’ll freeze again until you haven’t entered a trading pair. So far the issue only happens when running on Source build
- Getting an `Unhandled error on background` task 20-30 seconds after entering the client

```
2021-03-15 19:05:21,955 - 6191 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 
Traceback (most recent call last):
  File "/Users/reiniersalazar/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 80, in _coro_scheduler
    fut.set_result(await coro)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/reiniersalazar/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/reiniersalazar/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 128, in call_async
    return await self.schedule_async_call(coro, timeout_seconds, app_warning_msg=app_warning_msg)
  File "/Users/reiniersalazar/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 117, in schedule_async_call
    return await fut
  File "/Users/reiniersalazar/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 80, in _coro_scheduler
    fut.set_result(await coro)
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
```

**Comment by Nullably** [comment]
@rxlxrxsx 
Can I have more details? 
- What strategy did you try to configure?
- When exactly did the bot freeze?
- Did you update `ethereum_token_list_url` to `https://defi.cmc.eth.link/`?
- Can you attach both global and strategy config files?

For Uniswap trading pair config, can you please test it on #2905?

**Comment by rxlxrxsx** [comment]
>  What strategy did you try to configure?

Strategies where Balancer and Uniswap is accepted, in this case amm_arb and spot_perpetual_arbitrage (as amm market)

> When exactly did the bot freeze?

The behavior will exactly start happening on this prompt when you press `tab` or if you try to manually enter a value
Screen Shot 2021-03-16 at 6 51 38 AM

> Did you update `ethereum_token_list_url` to `https://defi.cmc.eth.link/`?

Yes

> Can you attach both global and strategy config files?

[conf_global.txt](https://github.com/CoinAlpha/hummingbot/files/6144976/conf_global.txt)
[conf_amm_arb_1.txt](https://github.com/CoinAlpha/hummingbot/files/6145020/conf_amm_arb_1.txt)
[conf_spot_perpetual_arbitrage_1.txt](https://github.com/CoinAlpha/hummingbot/files/6145021/conf_spot_perpetual_arbitrage_1.txt)

> For Uniswap trading pair config, can you please test it on #2905?

This is noted

**Review by rxlxrxsx — APPROVED** [review]
I did a re-test by cloning a fresh repository but didn't encounter the issues I reported above, must be something wrong with the old repo I'm using. I can confirm that there were no more issues found during testing and all test cases provided are working as expected.

**Review by sdgoh — APPROVED** [review]
LGTM

**Pull request merged**
