### PR TITLE
doc / remove documentation folder

### PR DESCRIPTION
**Pull request by dennisocana**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

Since the official documentation page [hummingbot.org](https://hummingbot.org/) now lives in https://github.com/hummingbot/hummingbot-site repository, this directory is no longer needed.

**Tips for QA testing**:

Please run tests to make sure there are no issues with installing Hummingbot from source and Docker.

### CODE REVIEW

**Comment by dennisocana** [comment]
Test

**Comment by dennisocana** [comment]
Test

**Comment by dennisocana** [comment]
Test

**Review by aarmoa — APPROVED** [review]
I did not detect any code or functionality impact. I approve the PR.

**Comment by PtrckM** [comment]
Update: on-going test

**Review by PtrckM — APPROVED** [review]
Tested and confirmed working by QA.

Tests performed:

- Confirmed successful builds on both source and docker on supported OS (linux,mac,windows and arm)
- Created a strategy and went through initial prompts successfully
- Confirmed wallet and exchange balances are reflecting correct
- Started the strategy without issues, confirmed orders are created and cancelled based on config
- Ran a test bot for hours without errors
- Confirmed in logs that there is no errors when orders are filled
- Trade information are correct (price, size) based on history command output
- Confirmed no issues when running Hummingbot commands and keyboard shortcuts.

**Comment by dennisocana** [comment]
Thanks @aarmoa @PtrckM , will re-create PR in the Foundation repository.

**Pull request closed without merging**
