### PR TITLE
[v0.38] feat/ oracle on Arbitrage and XEMM strategies

### PR DESCRIPTION
**Pull request by Nullably**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
See linked issue.

### CODE REVIEW

**Comment by TheHolyRoger** [comment]
@Nullably as discussed in other PRs I do quite strongly feel that the conversion rates from the rate oracle as it stands won't be "real-time" enough to compete with how I achieved things in this PR:
https://github.com/CoinAlpha/hummingbot/pull/2865

Since that PR creates paper trade markets and uses live order book data for arbitrage prices.

Just my personal thoughts, but in my case I would continue using my PR instead of these proposed changes with the rate oracle as it currently stands using prices from binance/coingecko.

**Comment by Nullably** [comment]
> @Nullably as discussed in other PRs I do quite strongly feel that the conversion rates from the rate oracle as it stands won't be "real-time" enough to compete with how I achieved things in this PR:
> #2865
> 
> Since that PR creates paper trade markets and uses live order book data for arbitrage conversion prices.

Yep, agree, hence my comment there https://github.com/CoinAlpha/hummingbot/pull/2865#issuecomment-789440529
There are pros and cons to both order book prices and oracle approaches. I'd rather have both of them (configurable as mentioned) and let the user chooses, but this is not up to me to decide.

**Comment by Nullably** [comment]
A few more changes I added to this PR:
- Add USD rates for `binance` oracle source, this is achieved by querying binance.us for prices on USD pairs and add them to prices retrieved from binance.com.
- Update `global_token` config prompt by removing USDT from example list, this is to avoid confusion

**Comment by TheHolyRoger** [comment]
> > @Nullably as discussed in other PRs I do quite strongly feel that the conversion rates from the rate oracle as it stands won't be "real-time" enough to compete with how I achieved things in this PR:
> > #2865
> > Since that PR creates paper trade markets and uses live order book data for arbitrage conversion prices.
> 
> Yep, agree, hence my comment there [#2865 (comment)](https://github.com/CoinAlpha/hummingbot/pull/2865#issuecomment-789440529)
> There are pros and cons to both order book prices and oracle approaches. I'd rather have both of them (configurable as mentioned) and let the user chooses, but this is not up to me to decide.

Aha! Ok cool sorry I actually forgot to make those changes you asked for, I was waiting for feedback from phbrgnomo then apparently just got sidetracked 🤦 

I'll rebase that PR on top of this one to have them both as options and clean up the terminology as you said.

**Comment by phbrgnomo** [comment]
@TheHolyRoger Both approaches are being considered, and you also presented a very interesting approach.
For the next release we will be adding @Nullably approach first because this is a simpler approach to a feature that we want to be more global, instead of only being applied to one specific strategy.

I will get in touch with you later so we can go through your code to see how we can change your PR to be able use it on a more general way by  any strategy.

Meanwhile, @Nullably, a few improvements ideas before we merge:

Captura de tela 2021-03-29 14 26 10

On the `status` we could add a section below `Markets:` To show what is the converted price and the current conversion rate, so the user can have an idea of how is the conversion happening.

Besides that, another improvement would be to show every X seconds on the right panel if there was a significant change in the conversion price.

**Comment by TheHolyRoger** [comment]
@Nullably @phbrgnomo 
I've finished refactoring/updating my PR so that it's compatible with this one:
https://github.com/CoinAlpha/hummingbot/pull/2865

**Comment by Nullably** [comment]
@phbrgnomo  
Since our working hours are quite far apart, can you be more specific on requested changes? 

> On the `status` we could add a section below `Markets:` To show what is the converted price and the current conversion rate, so the user can have an idea of how is the conversion happening.

Agree this is a good idea.
What should the section be called and what data should be there? and Is it displayed only when `use_oracle_conversion_rate` is set? 
E.g. (in case both base and quote symbols differ)
Rate Oracle: 
| source | LINK-ETH | USDT-USDC |
| --- | --- | --- | 
|Binance | 0.056 | 1.01 |

> Besides that, another improvement would be to show every X seconds on the right panel if there was a significant change in the conversion price.

How big a change is significant? And change from when?
I think it would be better to just log the conversion rates every 5 minutes regardless of the change, this data for investigation later on if needed.

**Comment by phbrgnomo** [comment]
> use_oracle_conversion_rate is set?
I think so. That way we don't polute with too much information if the oracle isn't used.

>What should the section be called and what data should be there?
My first idea was to show something like (copying from the screenshot):
```
Markets:
     Exchange     Market     Best Bid      Best ask    Mid Price
0   KUCOIN       BTC-USD    (----------prices in usd-----------)
1   BINANCE      BTC-BRL    (----------prices in brl---------)
Converted Prices
1   BINANCE      BTC-USD   (----------prices in USD---------)
```

In the case we have more than one match (3 or more different asset), if possible, we should show all the conversions that are happening. (Not 100% sure though, this could become too much information. We have to test it)

If not, we should at least show a full conversation from exchange 0 to exchange 1:

```
0   KUCOIN       ETH-USD    (----------prices in usd-----------)
1   BINANCE      BTC-BRL    (----------prices in brl---------)
Converted Prices
1   BINANCE      ETH-BRL   (----------prices in USD---------)
1   BINANCE      BTC-USD   (----------prices in USD---------)
```

>I think it would be better to just log the conversion rates every 5 minutes regardless of the change, this data for investigation later on if needed.

Agree. "Significant change" is too relative to find a good number.

**Comment by Nullably** [comment]
Rate conversion section is added to the status.
image
Note: the source will show "fixed" if oracle is not used, it's the rate from the config.

The conversion rates are also logged every 5 minutes.
image

**Comment by PtrckM** [comment]
- getting this error upon exiting the bot after doing create strategy, start, stop then exit after a minute. 
   -  does not affect bot performance
   -  importing the strategy(arb/xemm) = no error on exit
   -  creating new strategy(arb/xemm) on top of a strategy = no error on exit
image
image

```Traceback (most recent call last):
  File "bin/hummingbot.py", line 75, in <module>
    ev_loop.run_until_complete(main())
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "bin/hummingbot.py", line 68, in main
    await safe_gather(*tasks)
  File "/home/ubuntu/oracle_on_arb_xemm/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/ubuntu/oracle_on_arb_xemm/hummingbot/client/hummingbot_application.py", line 182, in run
    await self.app.run()
  File "/home/ubuntu/oracle_on_arb_xemm/hummingbot/client/ui/hummingbot_cli.py", line 73, in run
    await self.app.run_async()
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 777, in run_async
    return await _run_async2()
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 765, in _run_async2
    await self.cancel_and_wait_for_background_tasks()
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 862, in cancel_and_wait_for_background_tasks
    await task
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/buffer.py", line 1854, in new_coroutine
    await coroutine(*a, **kw)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/buffer.py", line 1683, in async_completer
    async for completion in self.completer.get_completions_async(
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/completion/base.py", line 269, in get_completions_async
    async for completion in completer.get_completions_async(
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/completion/base.py", line 196, in get_completions_async
    for item in self.get_completions(document, complete_event):
  File "/home/ubuntu/oracle_on_arb_xemm/hummingbot/client/ui/completer.py", line 227, in get_completions
    for c in self._trading_pair_completer.get_completions(document, complete_event):
  File "/home/ubuntu/oracle_on_arb_xemm/hummingbot/client/ui/completer.py", line 75, in _trading_pair_completer
    trading_pairs = trading_pair_fetcher.trading_pairs.get(market, []) if trading_pair_fetcher.ready else []
UnboundLocalError: local variable 'market' referenced before assignment
```

**Comment by RC-13** [comment]
re-test PR and confirm no other issue has occurred aside from the reported issue above.

**Comment by dendenski** [comment]
Running XEMM strategy, encountered clock tick error.
Steps:
1. create XEMM strategy market: binance, kucoin. Pair: BTC-USDT, BTC-USDT
2. start/stop bot then change (taker_market)kucoin pair to ETH-USDT.
3. Start the bot.

Other info:
Same issue when using arbitrage strategy.
Same issue when changing maker_maker pair.
XEMM Config:
image

image
[logs_conf_xemm_3.log](https://github.com/CoinAlpha/hummingbot/files/6240010/logs_conf_xemm_3.log)

2021-04-01 04:43:07,997 - 5036 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
File "hummingbot\core\clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
child_iterator.c_tick(self._current_tick)
File "hummingbot\strategy\cross_exchange_market_making\cross_exchange_market_making.pyx", line 368, in hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making.CrossExchangeMarketMakingStrategy.c_tick
self.c_process_market_pair(market_pair, market_pair_to_active_orders[market_pair])
File "hummingbot\strategy\cross_exchange_market_making\cross_exchange_market_making.pyx", line 469, in hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making.CrossExchangeMarketMakingStrategy.c_process_market_pair
self.c_check_and_create_new_orders(market_pair, has_active_bid, has_active_ask)
File "hummingbot\strategy\cross_exchange_market_making\cross_exchange_market_making.pyx", line 1205, in hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making.CrossExchangeMarketMakingStrategy.c_check_and_create_new_orders
effective_hedging_price_adjusted = effective_hedging_price * self.market_conversion_rate()
File "hummingbot\strategy\cross_exchange_market_making\cross_exchange_market_making.pyx", line 1168, in hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making.CrossExchangeMarketMakingStrategy.market_conversion_rate
return quote_rate / base_rate
TypeError: unsupported operand type(s) for /: 'decimal.Decimal' and 'NoneType'

Arbitrage strategy
image

image
[logs_conf_arb_11.log](https://github.com/CoinAlpha/hummingbot/files/6240049/logs_conf_arb_11.log)

2021-04-01 07:31:58,983 - 7216 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot\core\clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot\strategy\arbitrage\arbitrage.pyx", line 254, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_tick
    self.c_process_market_pair(market_pair)
  File "hummingbot\strategy\arbitrage\arbitrage.pyx", line 383, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_process_market_pair
    self.c_calculate_arbitrage_top_order_profitability(market_pair)
  File "hummingbot\strategy\arbitrage\arbitrage.pyx", line 319, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_calculate_arbitrage_top_order_profitability
    object market_2_bid_price = self.market_conversion_rate(market_pair.second) * \
  File "hummingbot\strategy\arbitrage\arbitrage.pyx", line 456, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.market_conversion_rate
    return quote_rate / base_rate
TypeError: unsupported operand type(s) for /: 'decimal.Decimal' and 'NoneType'

**Comment by Nullably** [comment]
@PtrckM 
> getting this error upon exiting the bot after doing create strategy, start, stop then exit after a minute.

This is fixed.

**Comment by rxlxrxsx** [comment]
After switching the secondary_market_trading_pair from ETH-USDT to BTC-USDT, rate oracle still recognizes the conversion for ETH to BTC after starting the strategy

Screen Shot 2021-04-01 at 12 40 13 PM

**Review by RC-13 — DISMISSED** [review]
Confirming all reported issues has been fixed

**Comment by TheHolyRoger** [comment]
@RC-13 @Nullably I've found some issues which I've fixed in this PR: https://github.com/CoinAlpha/hummingbot/pull/3145#pullrequestreview-626443863 see my review for explanations

**Review by vic-en — APPROVED** [review]
LGTM

**Comment by vic-en** [comment]
> @RC-13 @Nullably I've found some issues which I've fixed in this PR: [#3145 (review)](https://github.com/CoinAlpha/hummingbot/pull/3145#pullrequestreview-626443863) see my review for explanations

Kindly make similar changes for the balances in the arbitrage strategy as well in your pr so we can review together. Thanks in anticipation.

**Comment by TheHolyRoger** [comment]
> > @RC-13 @Nullably I've found some issues which I've fixed in this PR: [#3145 (review)](https://github.com/CoinAlpha/hummingbot/pull/3145#pullrequestreview-626443863) see my review for explanations
> 
> Kindly make similar changes for the balances in the arbitrage strategy as well in your pr so we can review together. Thanks in anticipation.

@vic-en I'm not sure if these changes are applicable to arbitrage? I'm looking through the code and I think everything is converted correctly in `c_find_profitable_arbitrage_orders` ?

**Review by TheHolyRoger — APPROVED** [review]

**Review by dennisocana — APPROVED** [review]
Re-approving since we already collected required approvals for this PR which were dismissed by accident.

**Pull request merged**
