### PR TITLE
Feat/adjust on fill

### PR DESCRIPTION
**Pull request by veecos2**
**Before submitting this PR, please make sure**:
- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue:
- Related Clubhouse Story:
https://app.clubhouse.io/coinalpha/story/4492/binary-request-adjust-orders-upon-fill
https://app.clubhouse.io/coinalpha/story/5076/pure-mm-update-both-bid-ask-orders-when-a-trade-on-either-side-is-filled

**A description of the changes proposed in the pull request**:
Adding the feature to adjust orders whenever a buy or sell order is completed. One feature is delay in replenishing orders and another feature is adjusting the prices of the orders placed based on the filled price.

### CODE REVIEW

**Comment by mifeng** [comment]
Currently testing and it seems to adjust correctly upon a fill event. Will continue testing but so far so good.

**Comment by mifeng** [comment]
Ran this on DDEX and saw some strange trade log messages. Looks like the bot tries to place orders twice and returns these errors the 2nd time:
```
2019-08-15 05:06:21,000 - hummingbot.strategy.pure_market_making.constant_size_sizing_delegate - NETWORK - Buy(bid) order is not placed because there is not enough Quote asset. Quote Asset: -9.9659523e+16, Price: 0.00096523,Size: 100.00
2019-08-15 05:06:21,001 - hummingbot.strategy.pure_market_making.constant_size_sizing_delegate - WARNING - Not enough asset to place the required buy(bid) order. Check balances.
2019-08-15 05:06:21,001 - hummingbot.strategy.pure_market_making.constant_size_sizing_delegate - NETWORK - Sell(ask) order is not placed because there is not enough Base asset. Base Asset: -1e+20, Size: 100.00
2019-08-15 05:06:21,001 - hummingbot.strategy.pure_market_making.constant_size_sizing_delegate - WARNING - Not enough asset to place the required sell(ask) order. Check balances
```

This is after it has placed orders successfully.

[hummingbot_logs_2019-08-15-05-01-58.log](https://github.com/CoinAlpha/hummingbot/files/3506291/hummingbot_logs_2019-08-15-05-01-58.log)

**Comment by veecos2** [comment]
@mifeng : As we discussed today, this is the behavior in the existing development branch as well. Currently what is happening is that the wallet takes time to refresh after the orders are cancelled during which the strategy also tries to place the order and throws out not available balance. Please refer to https://github.com/CoinAlpha/hummingbot/issues/642.

**Comment by mifeng** [comment]
Looks like the mid price used to determine the new orders after a fill event is the pre-delay price, when it should be the post-delay price.

**Comment by veecos2** [comment]
@mifeng : The price used for new orders after a filled event is the price at which the order was filled. "After a filled order, assume that the filled order price is the new mid price. Wait filled_order_replenish_wait_time, then adjust the order on the other side of the book" is what's described in the feature request.

**Comment by veecos2** [comment]
Feature needs further discussion. Closing for now.

**Pull request closed without merging**
