### PR TITLE
Feat / New open_orders, trades and pnl commands

### PR DESCRIPTION
**Pull request by Nullably**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**After creating this PR, please make sure:**

- [ ] You link the related GitHub issue or ticket

**A description of the changes proposed in the pull request**:

### CODE REVIEW

**Comment by PtrckM** [comment]
@Nullably based on the calculation we discussed, the output on most of the connectors match based on our manual calculation except Binance, Huobi and Coinbase Pro. Please confirm if this is a bug or this is as expected.

There's atleast 0.13% - 1.00% difference

image
image
image

**Comment by rxlxrxsx** [comment]
Although there's a notification of a filled trade, ``history`` command and ``Trades`` on the bottom nav bar doesn't show any trades. I'm also getting an error everytime there's a filled trade and when running ``history`` command. Tested using source build locally. Here's the error:

**On order filled event:**

```
2020-11-24 18:20:42,827 - 10564 - hummingbot.client.ui.hummingbot_cli - ERROR - Unhandled error in prompt_toolkit: unsupported operand type(s) for +: 'float' and 'decimal.Decimal'
NoneType: None
```

**When running ``history`` command:**

```
2020-11-24 18:25:52,994 - 10564 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: unsupported operand type(s) for +: 'float' and 'decimal.Decimal'
Traceback (most recent call last):
  File "C:\Users\Rein\Documents\GitHub\hummingbot\hummingbot\core\utils\async_utils.py", line 9, in safe_wrapper
    return await c
  File "C:\Users\Rein\Documents\GitHub\hummingbot\hummingbot\client\command\history_command.py", line 72, in history_report
    perf = calculate_performance_metrics(symbol, cur_trades, cur_balances, cur_price)
  File "C:\Users\Rein\Documents\GitHub\hummingbot\hummingbot\client\performance.py", line 149, in calculate_performance_metrics
    perf.unrealised_pnl = undone_vol * (undone_price + current_price)
TypeError: unsupported operand type(s) for +: 'float' and 'decimal.Decimal'
```

image

Logs: 
[logs_jack_tailored.log](https://github.com/CoinAlpha/hummingbot/files/5594378/logs_jack_tailored.log)
Config: 
[jack_tailored.txt](https://github.com/CoinAlpha/hummingbot/files/5594386/jack_tailored.txt)

**Comment by Nullably** [comment]
@PtrckM The small rounding error is due to how you use the rounded numbers to calculate the total allocated %, ie. you can't use rounded numbers for this. I don't think this is a problem, the allocated % is to indicate to user how efficiently they allocate their capital, this doesn't have to fine decimal precision.

**Comment by Nullably** [comment]
@rxlxrxsx Thanks for catching the error. I have updated the PR with a fix.

**Comment by Nullably** [comment]
@PtrckM @rxlxrxsx I added `--market` arg to `pnl` command, when used the command shows detailed performance like what you get on `history` command.

**Comment by rxlxrxsx** [comment]
Confirmed fix for issues listed above and no other issues found during testing by QA.

**Review by sdgoh — APPROVED** [review]
LGTM

**Pull request merged**
