### PR TITLE
Refactor/ minor updates to price band and spread adjusted script examples

### PR DESCRIPTION
**Pull request by Nullably**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
- Minor example and comment updates to script examples 
- Only dynamic price band example needs testing.

Tips for QA
- Please test dynamic price band example script

### CODE REVIEW

**Comment by dennisocana** [comment]
Only requires testing / validation from QA. @Nullably will add details to the description for tips. Moving to Testing pipeline.

**Comment by Nullably** [comment]
There are currently no unit tests for script examples and I don't think we need ones. As such there is no unit test accompanying this PR.

**Review by CrimsonJacket — APPROVED** [review]
Simple enough fix. LGTM

**Comment by rapcmia** [comment]
Tested and confirmed script is working ok however when running the bot on `status --live` getting the `script_iterator` on the logs every 1s. There are also instances of the bot returning `AttributeError: 'NoneType' object has no attribute 'format_status'`

Here is a sample screenshot, this does not happen on the latest version v0.43.1
3N7giUYBCn

```
2021-09-16 15:43:08,908 - 18508 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'NoneType' object has no attribute 'format_status'
Traceback (most recent call last):
  File "C:\Users\Ralph\github\3343\hummingbot\core\utils\async_utils.py", line 9, in safe_wrapper
    return await c
  File "C:\Users\Ralph\github\3343\hummingbot\client\command\status_command.py", line 131, in status_check_all
    await self.strategy_status() + script_status + "\n\n Press escape key to stop update.", 1
  File "C:\Users\Ralph\github\3343\hummingbot\client\command\status_command.py", line 76, in strategy_status
    if inspect.iscoroutinefunction(self.strategy.format_status):
AttributeError: 'NoneType' object has no attribute 'format_status'
```

Steps to reproduce:
1. Create Pure market making
2. Enable script, dynamic_price_band_script.py
3. Start the bot, run `status --live`
4. Stop the bot for the `AttributeError..`

Attached: 
[3343.zip](https://github.com/CoinAlpha/hummingbot/files/7175825/3343.zip)

**Review by RC-13 — APPROVED** [review]
Approving PR, the script is working as intended and the error reported has been address on newer version.

**Pull request merged**
