### PR TITLE
docs/ Update 0.17.0.md

### PR DESCRIPTION
**Pull request by rennel-tabing**
**Before submitting this PR, please make sure**:
- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue:
- Related Clubhouse Story:

**A description of the changes proposed in the pull request**:

### CODE REVIEW

**Comment by mifeng** [comment]
@rennel-tabing Please re-submit this PR to `development` branch, not `master.` We only merge to `master` when we release, so all commits for documentation updates should be to `development`. Thanks

**Comment by carlolm** [comment]
@mifeng rather than closing and issuing a new pull request, you can just hit "edit":

image

And then change the branch to development:

image

**Comment by mifeng** [comment]
> @mifeng rather than closing and issuing a new pull request, you can just hit "edit":
> 
> image
> 
> And then change the branch to development:
> 
> image

got it thanks!

**Comment by yzhang1994** [comment]
ok to test

**Pull request merged**
