### PR TITLE
feat/Mandala Exchange Connector

### PR DESCRIPTION
**Pull request by MudDev**
Before Submitting this PR, I verified the following:
- [x] Ran Tests
- [x] The code builds clean without any errors or warnings
- [x] Using approved title ("feat/", "fix/", "docs/", "refactor/")

This PR is to add the Mandala Exchange connector to humming bot.

### CODE REVIEW

**Comment by dennisocana** [comment]
After today's discussion with @keithbaum , this connector is not yet ready for QA testing. Changing status from Open to Draft.

**Comment by dennisocana** [comment]
Per @MudDev , this PR is ready for review. @RC-13 has started testing and moving this to Review/QA pipeline.

**Comment by RC-13** [comment]
Test PR and encounter the following issues:
1. Orders failing to cancel: logs indicate that orders are cancelled however the order remains on the order book and if you check the status, the orders are still in place and order age continuous to increase.
config-mandala
status-mandala

2. Stopping and starting strategy results to creating hanging orders: After stop then starting strategy, bot detects dangling order after that, hanging orders are created instead of a normal order. The message shown on the logs pertains to orders reaching the max order age however those orders haven't reached the max age yet.
- This also happens when you try to use the pause and resume feature, upon restoring, it restore the previous order but makes other orders as hanging order as well.
stop-start-incorrect-hanging order

3. Failed to track filled orders: Whenever a filled trade takes place, bot always encounter an API network issue resulting to unable to track the filled orders.
lost-trade-mandala
trade-history
```ruby
2021-03-26 14:12:42,279 - 16056 - hummingbot.connector.exchange.mandala.mandala_exchange - ERROR - Unexpected error while processing event 103.
Traceback (most recent call last):
  File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
    typed_listener.c_call(arg)
  File "hummingbot/strategy/strategy_base.pyx", line 47, in hummingbot.strategy.strategy_base.SellOrderCompletedListener.c_call
    self._owner.c_did_complete_sell_order_tracker(arg)
  File "hummingbot/strategy/strategy_base.pyx", line 372, in hummingbot.strategy.strategy_base.StrategyBase.c_did_complete_sell_order_tracker
    self.c_did_complete_buy_order_tracker(order_completed_event)
  File "hummingbot/strategy/strategy_base.pyx", line 366, in hummingbot.strategy.strategy_base.StrategyBase.c_did_complete_buy_order_tracker
    if order_type.is_limit_type():
AttributeError: 'str' object has no attribute 'is_limit_type'
2021-03-26 14:12:42,283 - 16056 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1616739162.0, "order_id": "502192", "base_asset": "ETH", "quote_asset": "USDT", "fee_asset": "USDT", "base_asset_amount": "0.00797", "quote_asset_amount": "12.930528", "fee_amount": "0", "order_type": "1", "exchange_order_id": null, "event_name": "SellOrderCompletedEvent", "event_source": "mandala_None"}
2021-03-26 14:12:45,628 - 16056 - hummingbot.connector.exchange.mandala.mandala_exchange - NETWORK - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/mandala/mandala_exchange.pyx", line 547, in hummingbot.connector.exchange.mandala.mandala_exchange.MandalaExchange._status_polling_loop
    await safe_gather(
  File "/Users/clint_g/Documents/Github-Repo/hb-mandala/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "hummingbot/connector/exchange/mandala/mandala_exchange.pyx", line 398, in _update_order_fills_from_trades
    applied_trade = order_map[order_id].update_with_trade_update(trade)
  File "hummingbot/connector/exchange/mandala/mandala_in_flight_order.pyx", line 89, in hummingbot.connector.exchange.mandala.mandala_in_flight_order.MandalaInFlightOrder.update_with_trade_update
    trade_id = trade_update["id"]
KeyError: 'id'
```
[logs_conf_pure_mm_1.log](https://github.com/CoinAlpha/hummingbot/files/6209791/logs_conf_pure_mm_1.log)

**Comment by RC-13** [comment]
Looping in @MudDev, kindly check the following issues reported.

**Comment by rxlxrxsx** [comment]
The following issues reported above are still happening based on the recent push:

> Orders failing to cancel: logs indicate that orders are cancelled however the order remains on the order book and if you check the status, the orders are still in place and order age continuous to increase.

> Stopping and starting strategy results to creating hanging orders: After stop then starting strategy, bot detects dangling order after that, hanging orders are created instead of a normal order. The message shown on the logs pertains to orders reaching the max order age however those orders haven't reached the max age yet.

As for the filled trade event, I'm getting two different behaviors:

Scenario 1:
After getting trades filled, filled orders are still shown as open orders upon checking on `status`. It does show on history now and no more errors are showing however there's no notification of the left pane that it's filled.

Screen Shot 2021-03-30 at 11 34 57 AM

Screen Shot 2021-03-30 at 11 35 08 AM

Scenario 2:
After encountering scenario 1 I restarted the strategy without deleting the .sqlite file (current workaround for hanging orders issue reported above as well), later on the bot detects the recently filled trade from the session prior restarting, this time showing a notification on the left pane but getting an error as well after the filled trade event.

Screen Shot 2021-03-30 at 12 09 32 PM

```
2021-03-30 11:57:28,954 - 4360 - hummingbot.connector.exchange.mandala.mandala_exchange - ERROR - Unexpected error while processing event 103.
Traceback (most recent call last):
  File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
    typed_listener.c_call(arg)
  File "hummingbot/strategy/strategy_base.pyx", line 47, in hummingbot.strategy.strategy_base.SellOrderCompletedListener.c_call
    self._owner.c_did_complete_sell_order_tracker(arg)
  File "hummingbot/strategy/strategy_base.pyx", line 372, in hummingbot.strategy.strategy_base.StrategyBase.c_did_complete_sell_order_tracker
    self.c_did_complete_buy_order_tracker(order_completed_event)
  File "hummingbot/strategy/strategy_base.pyx", line 366, in hummingbot.strategy.strategy_base.StrategyBase.c_did_complete_buy_order_tracker
    if order_type.is_limit_type():
AttributeError: 'str' object has no attribute 'is_limit_type'
```

Logs: [logs_mandala_test.log](https://github.com/CoinAlpha/hummingbot/files/6226113/logs_mandala_test.log)
Config: [mandala_test.txt](https://github.com/CoinAlpha/hummingbot/files/6226114/mandala_test.txt)

**Comment by RC-13** [comment]
Re-tested PR, and I'm still getting the same issue reported above.
- Stop and starting the strategy resulted in having hanging orders for previously created orders and new orders. We need to clear the DB file to remove the hanging orders.
hanging order
- Failed to cancel orders (filled or not)

https://user-images.githubusercontent.com/57189990/113241397-34703d80-92e1-11eb-8d55-a06aa0a4fd5f.mp4


- No notification if filled trade takes place, after running history or status that's where you will know that a filled trade has occurred. Trade is recorded on the exchange.


https://user-images.githubusercontent.com/57189990/113241416-405bff80-92e1-11eb-9c44-aa4cf3b84245.mp4

**Comment by dennisocana** [comment]
QA team's recommendation is to not merge the PR for now due to outstanding critical issues with the connector. Moving this to next release.

**Comment by whatagem** [comment]
no updates since april?

**Comment by dennisocana** [comment]
@whatagem correct, more information in this Reddit post https://www.reddit.com/r/Hummingbot/comments/n0tyte/announcement_review_stoppage_on_tokocrypto_and/

**Comment by dennisocana** [comment]
Connector is incomplete and outdated. Closing for now due to no progress for three months. Feel free to reopen when work will be resumed for this connector.

**Pull request closed without merging**
