### PR TITLE
fix/ KuCoin unable to place limit_maker orders

### PR DESCRIPTION
**Pull request by vic-en**
**Before submitting this PR, please make sure**:
- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue:
- Related Clubhouse Story:

**A description of the changes proposed in the pull request**:

### CODE REVIEW

**Comment by PtrckM** [comment]
- It place orders as intended but I got an error `Unexpected error in user stream listener loop.`

image
image

```
2020-08-08 08:10:30,468 - 18958 - hummingbot.market.kucoin.kucoin_market - ERROR - Unexpected error in user stream listener loop.
Traceback (most recent call last):
  File "hummingbot/market/kucoin/kucoin_market.pyx", line 298, in hummingbot.market.kucoin.kucoin_market.KucoinMarket._user_stream_event_listener
    self._account_balances.update({currency, total_balance})
ValueError: dictionary update sequence element #0 has length 4; 2 is required
2020-08-08 08:10:31,001 - 18958 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - Insufficient balance: Buy order (price: 390.95, size: 0.0250000) is omitted, USDC available balance: 1.20697969.
2020-08-08 08:10:32,001 - 18958 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - Insufficient balance: Buy order (price: 390.96, size: 0.0250000) is omitted, USDC available balance: 1.20697969.
2020-08-08 08:10:33,001 - 18958 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - Insufficient balance: Buy order (price: 390.95, size: 0.0250000) is omitted, USDC available balance: 1.20697969.
2020-08-08 08:10:34,001 - 18958 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - Insufficient balance: Buy order (price: 390.96, size: 0.0250000) is omitted, USDC available balance: 1.20697969.
2020-08-08 08:10:35,001 - 18958 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - Insufficient balance: Buy order (price: 390.96, size: 0.0250000) is omitted, USDC available balance: 1.20697969.
2020-08-08 08:10:35,471 - 18958 - hummingbot.market.kucoin.kucoin_market - INFO - Successfully cancelled order sell-ETH-USDC-1596888600002570.
2020-08-08 08:10:35,537 - 18958 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1596888635.0, "order_id": "sell-ETH-USDC-1596888600002570", "event_name": "OrderCancelledEvent", "event_source": "kucoin"}
2020-08-08 08:10:35,538 - 18958 - hummingbot.market.kucoin.kucoin_market - ERROR - Unexpected error in user stream listener loop.
Traceback (most recent call last):
  File "hummingbot/market/kucoin/kucoin_market.pyx", line 298, in hummingbot.market.kucoin.kucoin_market.KucoinMarket._user_stream_event_listener
    self._account_balances.update({currency, total_balance})
ValueError: dictionary update sequence element #0 has length 3; 2 is required
2020-08-08 08:10:36,001 - 18958 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - Insufficient balance: Buy order (price: 390.96, size: 0.0250000) is omitted, USDC available balance: 1.20697969.
2020-08-08 08:10:36,002 - 18958 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDC) Creating 1 ask orders at (Size, Price): ['0.025 ETH, 394.89 USDC']
2020-08-08 08:10:36,553 - 18958 - hummingbot.market.kucoin.kucoin_market - INFO - Created OrderType.LIMIT_MAKER sell order sell-ETH-USDC-1596888636002661 for 0.0250000 ETH-USDC.
2020-08-08 08:10:36,674 - 18958 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1596888636.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ETH-USDC", "amount": 0.025, "price": 394.89, "order_id": "sell-ETH-USDC-1596888636002661", "event_name": "SellOrderCreatedEvent", "event_source": "kucoin"}
2020-08-08 08:10:40,540 - 18958 - hummingbot.market.kucoin.kucoin_market - ERROR - Unexpected error in user stream listener loop.
Traceback (most recent call last):
  File "hummingbot/market/kucoin/kucoin_market.pyx", line 298, in hummingbot.market.kucoin.kucoin_market.KucoinMarket._user_stream_event_listener
    self._account_balances.update({currency, total_balance})
ValueError: dictionary update sequence element #0 has length 3; 2 is required
2020-08-08 08:10:52,263 - 18958 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
```
- logs
[logs_kc_pmm_eth_usdc.log](https://github.com/CoinAlpha/hummingbot/files/5045234/logs_kc_pmm_eth_usdc.log)

**Comment by vic-en** [comment]
@PtrckM , kindly test again.

**Comment by dennisocana** [comment]
Ran into new errors during testing and still cannot submit orders. Will do a cross check on another branch to see if this is isolated in this PR.

[logs_test_kucoin_place_orders.log](https://github.com/CoinAlpha/hummingbot/files/5046770/logs_test_kucoin_place_orders.log)

image
image

**Comment by vic-en** [comment]
@dennisocana 
This PR is good now.

**Comment by mifeng** [comment]
Screen Shot 2020-08-10 at 5 01 19 PM

My bot still doesn't place orders for Kucoin even though I have sufficient BTC balance. I would expect the bot to place a sell order in the example above. Since we releasing today, I'll merge this as it does fix a bug but I think we need to do more testing.

**Pull request merged**
