### PR TITLE
[v0.33] Refactor / Refactor condition check for utils file in ConnectorSettings

### PR DESCRIPTION
**Pull request by vic-en**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**After creating this PR, please make sure:**

- [x] You link the related GitHub issue or ticket

**A description of the changes proposed in the pull request**:

### CODE REVIEW

**Comment by RC-13** [comment]
Build a binary installer for windows and run bot. Other exchange are now displayed except for Binance_perpetual and Binance_perpetual_testnet, and no issue exiting from bot.
image

**Review by dennisocana — APPROVED** [review]
Tested and confirmed fix by QA

**Comment by vic-en** [comment]
@RC-13 Binance perpetual and binance perpetual testnet are on a separate branch and yet to be merged to development branch.

**Review by Nullably — APPROVED** [review]
LGTM

**Pull request merged**
