### PR TITLE
feat / improve notification about status of gateway

### PR DESCRIPTION
**Pull request by vic-en**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
[ch25729]

**Tests performed by the developer**:
- Started client then stopped and started gateway docker and confirmed new log messages.
- Repeated about but with gateway from source and confirmed new log messages as well.

**Tips for QA testing**:
- Run client then make gateway docker start and stop the confirm that appropriate log is shown in log panel each time.
- Repeat above step but with gateway from source.

### CODE REVIEW

**Comment by vic-en** [comment]
> Gas limit is still defaulted to 150688 (should it be 3000000?) image Main PR for this is - #217
> 
> Allowed Slippage is taking any inputs image Main PR for this is - #219
> 
> Test Summary 1.Cloned and install featured branch 2.Run gateway create and add infura keys 3.Run gateway config uniswap.versions.v2.gaslimit - default to 150688 4.Run gateway config uniswap.versions.v2.allowedslippage "random input" - accepts Random Input
> 
> I also created a docker image for this featured branch and was able to get the same result.

@gerald-hb Those are out of scope for this pr.
This pr is mainly concerned about logs outputs about gateway starting or stopping on the log panel of the client.

**Comment by vic-en** [comment]
Also note that this pr doesn't undo any of those changes you reported. Those changes are in the improvement_proposal pr which is yet to be created and merged on the foundation side.

**Comment by gerald-hb** [comment]
Thanks for clarifying. This changes looks good to me. Appropriate log is shown in log panel each time gateway is stopped or start.

Test Summary (gateway docker)
1.Cloned and install featured branch
2.Run gateway create and add infura keys
    -confirmed that gateway connection is established
3. Trigger Gateway stop command
    -confirmed that gateway connection is lost.
4. Trigger gateway start/stop command multiple times: no issue
5. Created a docker image and do the same test. No notable issue are found.     

Note: I was not able to test this on gateway source as I am having issues running it.

**Review by RC-13 — APPROVED** [review]
LGTM, we skipped the test of the gateway source version due to a communication issue with the client (a separate ticket has been created).

Test Summary 
1. Cloned and install featured branch
2. Run gateway create and add infura keys
-confirmed that gateway connection is established
3. Trigger Gateway stop command
-confirmed that gateway connection is lost.
4. Trigger gateway start/stop command multiple times: no issue
5. Created a docker image and do the same test. No notable issues are found.

**Comment by vic-en** [comment]
Prp: https://snapshot.org/#/hbot-prp.eth/proposal/0x0bbd3028e22b27a976425233382a4bb263d8317df7f3a3100f4494959470dee9
Foundation pr: https://github.com/hummingbot/hummingbot/pull/5348

**Pull request closed without merging**
