### PR TITLE
feat/loopring-update updates to loopring connector for loopring v1 -> v2

### PR DESCRIPTION
**Pull request by trkoneill18**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

### CODE REVIEW

**Comment by RC-13** [comment]
Test PR and encounter this error: `18:59:14 - loopring_exchange - {"exchange":["Must satisfy 0x[0-9a-fA-F]{40}"]}` which cause order to fail to be submitted. I'm not sure if this is account specific but I was able to place order manually using the same wallet.
image
[logs_lrc-eth-loopring.log](https://github.com/CoinAlpha/hummingbot/files/5893405/logs_lrc-eth-loopring.log)


another minor issue is that the auto complete when choosing market pair is currently not working.

**Comment by trkoneill18** [comment]
The autocomplete should be working now. As for the first error, are you using the exchange id provided by loopring as explained here https://docs.loopring.io/en/basics/key_mgmt.html ?

**Comment by RC-13** [comment]
@trkoneill18 Yes, although for v2 exchangeID is no longer available, so I use the exchangeID from v1
loopring api

**Comment by trkoneill18** [comment]
You are to use the exchange address shown there. I have just changed the connect key name to reflect this.

**Comment by jason-hb** [comment]
@CrimsonJacket Here's a note from Michael @ Linq:

Loopring PR's build is now fixed as well. Based on feedback from testing that connector, there might need to be a mention in the release notes that this new update to the loopring connector means that the keys used previously (last HB version) will be invalid and the user must get the new keys from the new version of the exchange

Please include this in documentation for the updated connector. Tagging @JeremyKono in case he has bandwidth to update the doc

**Comment by RC-13** [comment]
Hi @trkoneill18, just checked our long term test bot and we have one trade that has fee in it, however the fee wasn't taken into account when calculating PnL:
loopring
```
branch: feat/loopring-update
commit: b51690add9ddcde82e0eb106847056d24093bfb9
```
[loopring.zip](https://github.com/CoinAlpha/hummingbot/files/5909139/loopring.zip)

**Comment by trkoneill18** [comment]
I believe the problem was that the get_last_traded_prices function wasn't updated from the last version of loopring; this would have caused perf.fee_in_quote to be multiplied by 0 in calculate_performance_metrics in hummingbot/client/performance. Should be fixed now.

**Comment by RC-13** [comment]
@trkoneill18 Hi again, here's another issue seen after running for 24 hours, the bot keeps creating an order that doesn't meet the exchange minimum which results to the following log message and appear every time the order refresh. This order should be omitted to avoid spamming the log pane.
```
2021-02-03 01:42:30,002 - 14314 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Order notional value(0.00882234282) is less than the minimum allowable notional value for an order (0.0100000000000000000)
Traceback (most recent call last):
  File "/home/ubuntu/loopring/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "hummingbot/connector/exchange/loopring/loopring_exchange.pyx", line 421, in execute_buy
    if await self.execute_order(TradeType.BUY, order_id, trading_pair, amount, order_type, price):
  File "hummingbot/connector/exchange/loopring/loopring_exchange.pyx", line 366, in execute_order
    raise ValueError(f"Order notional value({str(amount*price)}) is less than the minimum allowable notional value for an order ({str(trading_rule.min_notional_size)})")
ValueError: Order notional value(0.00882234282) is less than the minimum allowable notional value for an order (0.0100000000000000000)
2021-02-03 01:42:30,814 - 14314 - hummingbot.connector.exchange.loopring.loopring_exchange - INFO - Created ordertype.limit tradetype.sell order sell-LRC-ETH-1612316550001683 for 274.678 LRC-ETH.
```
Loopring order

**Review by CrimsonJacket — CHANGES_REQUESTED** [review]
Other than the bug @RC-13 mentioned, the update to Loopring v2 API looks good to me.
Do have the bug fixed ASAP.

**Comment by trkoneill18** [comment]
I think the last change should have fixed that bug. The quantize order amount function in the loopring exchange class was sending back a non-zero amount in the case where no price was provided; this permitted the pmm strategy to place the order despite the insufficient notional order size.

**Comment by RC-13** [comment]
Confirmed, last reported issue no longer persist, will monitor once merge.

**Review by RC-13 — APPROVED** [review]

**Review by CrimsonJacket — APPROVED** [review]
LGTM

**Pull request merged**
