### PR TITLE
feat/allows for fewer orders in multiple orders PMM if balance not enough

### PR DESCRIPTION
**Pull request by fengkiej**
**Before submitting this PR, please make sure**:
- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue: #517 
- Related Clubhouse Story:

**A description of the changes proposed in the pull request**:
allows for fewer orders in multiple orders PMM if balance not enough

### CODE REVIEW

**Comment by fengkiej** [comment]
> @fengkiej What issue does this PR address? From inspection, it seems that while this code is cleaner than what was there before, the functionality is the same.

As Carlo described in #517 and from my experience from using the strategy, it doesn't allow to any orders if current balance is not enough to submit all proposed orders.

Notice that in current implementation, it returns buy or sell orders as [s_decimal_0] if base or quote balance is not enough.
```
            (buy_orders
             if quote_asset_balance >= required_quote_asset_balance and not has_active_bid
             else [s_decimal_0]),	
            (sell_orders	
             if base_asset_balance >= required_base_asset_balance and not has_active_ask else	
             [s_decimal_0])
```

This PR checks if balance is enough during incremental required balance in loop before
```
buy_orders.append(buy_order_size)
```
and
```
sell_orders.append(sell_order_size)
```

so, when it returning the calculated values, it will return [s_decimal_0] if `buy_orders`/`sell_orders` are `None` or if it has active orders.
```
(buy_orders or [s_decimal_0] if not has_active_bid else [s_decimal_0]),
(sell_orders or [s_decimal_0] if not has_active_ask else [s_decimal_0])
```

It enables the strategy to submit some orders although if it is not enough to submit all proposed orders.

**Example**
Current balance:
Base = 0.5 BTC
Quote = 100 000 000 IDRT (~ 1 BTC)

Config is set to :
- number_of_orders: 5
- order_start_size: 0.2
- order_step_size: 0.0

order sizes = [0.2, 0.2, 0.2, 0.2, 0.2]
While it allows for `buy_orders` to be submitted, the `sell_orders` will become [0] at the end of the function, thus all `sell_orders` can't be placed, this PR will enable `sell_orders` to have value of [0.2, 0.2] and submit 2 sell orders instead of none at all.

**Comment by mifeng** [comment]
Thanks @fengkiej for the detailed explanation. @dennisocana please verify this fix - if it passes I will approve and merge this in

**Comment by mifeng** [comment]
LGTM thanks @fengkiej for the detailed explanation and @dennisocana for confirming the fix

**Comment by dennisocana** [comment]
test this please

**Comment by carlolm** [comment]
OK to test

**Pull request merged**
