### PR TITLE
[WIP] Feat / celo integration

### PR DESCRIPTION
**Pull request by Nullably**
**Before submitting this PR, please make sure**:
- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue:
- Related Clubhouse Story:

**A description of the changes proposed in the pull request**:
- Celo integration

### CODE REVIEW

**Comment by mifeng** [comment]
Tested while my Celo node is syncing:
`connect`: works well.
`balance`: If Celo node is not synced, display a warning message. Currently this produces an error message in the trade log.

**Comment by mifeng** [comment]
For `balance`, the symbols should be `CGLD` for gold and `CUSD` for the stablecoin

**Comment by mifeng** [comment]
Also, we should make Celo-related changes on a feature branch. Can you create one and change this PR to merge to it?

**Comment by Nullably** [comment]
A new PR for this has been created #1697

**Pull request closed without merging**
