### PR TITLE
Fix / Avellaneda spread update with volatility

### PR DESCRIPTION
**Pull request by keithbaum**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

Changed min and max spread inflation when vol * vol_multiplier exceeds spreads
See comments below for further description

### CODE REVIEW

**Comment by keithbaum** [comment]
Original version had a bug where max_spread limits would expand when volatility was high, but spreads used to calculate the parameters were still using the original spreads.
Modification includes changes with volatility to the parameters, hence to the final spreads

This an example (using very small original spreads with highly volatility period of DOGE-USDT)

See how volatility reaches values around 0.5% and more, while original min_spread = 0.4% vol_to_spread_multiplier = 1.2
image


See how volatility severely modifies spreads
image

Harder to notice, but spreads widen during the volatility peaks (although they should be declining as time goes by)
image

**Comment by keithbaum** [comment]
In a longer horizon it can barely be seen but during high volatility peaks, if close to trading cycle's end blue line (mid-price) and green line (reserved price) should be overlapping, but due to the volatility modification green line separates from the blue line

image

**Comment by PtrckM** [comment]
No issue found. Confirmed working and passed QA testing.

**Review by PtrckM — APPROVED** [review]

**Comment by phbrgnomo** [comment]
@PtrckM can we close this issue?

**Review by Nullably — APPROVED** [review]
LGTM

**Pull request merged**
