### PR TITLE
Feat / sqlite db for each strategy config

### PR DESCRIPTION
**Pull request by Nullably**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**After creating this PR, please make sure:**

- [x] You link the related GitHub issue or ticket

**A description of the changes proposed in the pull request**:
- Create a new sqlite db for each strategy config file.

**Note**
- Old db file name was `hummingbot_trades.sqlite`, and there is no automatic data migration
- This is to address #2106 for some reason I cannot link this issue with the PR

### CODE REVIEW

**Comment by TheHolyRoger** [comment]
YES! Brilliant change! Thanks Jack :) 👍 

Much simpler to run from multiple from source now.

**Comment by RC-13** [comment]
- Test made using 2 terminal:
 -> separate sqlite db files were created
 -> no conflict with the history output
 -> number of filled order on each sqlite file matches the csv file and exchange

- Test made using single terminal without restarting the instance.
 -> After creating the first strategy, a new sqlite file will be created, however, if you stop and create another strategy without restarting the current instance, it won't create a new sqlite file. Filled trades will be added on the first strategy's sqlite db files but creates a separate csv for each strategy.
-> Restarting instance and importing second strategy is needed for a new sqlite db file to be created.

**Comment by Nullably** [comment]
@RC-13 
Thank you for doing very thorough testing, very good QA.
> -> After creating the first strategy, a new sqlite file will be created, however, if you stop and create another strategy without restarting the current instance, it won't create a new sqlite file. Filled trades will be added on the first strategy's sqlite db files but creates a separate csv for each strategy.
-> Restarting instance and importing second strategy is needed for a new sqlite db file to be created.

I have addressed both these issues.

**Comment by rxlxrxsx** [comment]
Confirmed fix for issues listed above and no other issues found during testing by QA.

**Review by sdgoh — APPROVED** [review]
LGTM

**Pull request merged**
