### PR TITLE
Fix / XEMM taker order error

### PR DESCRIPTION
**Pull request by Nullably**
**Before submitting this PR, please make sure**:
- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue:
- Related Clubhouse Story:

**A description of the changes proposed in the pull request**:

### CODE REVIEW

**Comment by dennisocana** [comment]
@rxlxrxsx please test this today

**Comment by rxlxrxsx** [comment]
Getting this error after the maker order got filled. Maker exchange is Bittrex while taker exchange is Huobi.

```
2020-10-01 05:14:14,151 - 5213 - hummingbot.connector.exchange.huobi.huobi_exchange - ERROR - Error received from https://api.huobi.pro/v1/order/orders/place. Response is {'status': 'error', 'err-code': 'order-invalid-price', 'err-msg': 'invalid price', 'data': None}.
2020-10-01 05:14:14,151 - 5213 - hummingbot.connector.exchange.huobi.huobi_exchange - NETWORK - Error submitting buy limit order to Huobi for 0.001200 BTC-USDT NaN.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/huobi/huobi_exchange.pyx", line 752, in hummingbot.connector.exchange.huobi.huobi_exchange.HuobiExchange.execute_buy
    exchange_order_id = await self.place_order(order_id, trading_pair, decimal_amount, True, order_type, decimal_price)
  File "hummingbot/connector/exchange/huobi/huobi_exchange.pyx", line 722, in place_order
    exchange_order_id = await self._api_request(
  File "hummingbot/connector/exchange/huobi/huobi_exchange.pyx", line 277, in _api_request
    async with response_coro as response:
  File "hummingbot/connector/exchange/huobi/huobi_exchange.pyx", line 288, in hummingbot.connector.exchange.huobi.huobi_exchange.HuobiExchange._api_request
    raise HuobiAPIError({"error": parsed_response})
hummingbot.connector.exchange.huobi.huobi_exchange.HuobiAPIError: {'error': {'status': 'error', 'err-code': 'order-invalid-price', 'err-msg': 'invalid price', 'data': None}}
```

[logs_xemm_taker_fix.log](https://github.com/CoinAlpha/hummingbot/files/5309671/logs_xemm_taker_fix.log)

**Comment by Nullably** [comment]
@rxlxrxsx Sorry, I thought i marked this as draft. Anyway, it's ready for testing now.

**Review by dennisocana — APPROVED** [review]
Tested by QA and confirmed fix.

**Pull request merged**
