### PR TITLE
fix/ `StartCommand` not waiting for Gateway service to be ready

### PR DESCRIPTION
**Pull request by CrimsonJacket**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
`StartCommand` now waits for the gateway service to be running and online before initialising a gateway-reliant strategy.

Resolves [sc-27456]

**Tests performed by the developer**:
Changes from PR #266 is included in this PR.
Add helper functions within the `StartCommand` class to do additional preliminary checks to ensure that Gateway service `RUNNING` and `ONLINE`.
Refactor and add additional properties into `GatewayStatusMonitor` to help with the above checks.

**Tips for QA testing**:
Changes from PR #266 is included in this PR to aid with testing with `hummingbot_quickstart.py`

Ensure that the bot now waits for the the gateway service to be running and online before the gateway-reliant strategy gets started. 
A 3 minute timeout is enforced to prevent the bot from waiting indefinitely

### CODE REVIEW

**Comment by RC-13** [comment]
@gerald-hb That is a normal behavior, checking the balance or starting the strategy needs to be triggered for the status to change.

**Comment by RC-13** [comment]
Issue mentioned above doesn't seems to happen on my side, I tried restarting the client multiple times (5 times at least):
image

**Comment by rxlxrxsx** [comment]
When trying to start amm_arb strategy using `bin/hummingbot.py` or restarting amm_arb strategy while running on `bin/hummingbot_quickstart.py` it's just stuck after entering start command

Screen Shot 2022-07-06 at 10 21 19 AM

Screen Shot 2022-07-06 at 10 26 40 AM

Logs and config: [conf_log_amm_arb.zip](https://github.com/CoinAlpha/hummingbot/files/9051165/conf_log_amm_arb.zip)

**Comment by RC-13** [comment]
Retested on the latest commit and confirming that the issue mentioned by @rxlxrxsx has been fixed. However, the issue mentioned by @gerald-hb still persist, this resulted to the same problem mentioned by Rein wherein we get stuck at starting the strategy since the gateway status did not update (remain running, stopped).
image

**Comment by CrimsonJacket** [comment]
> Retested on the latest commit and confirming that the issue mentioned by @rxlxrxsx has been fixed. However, the issue mentioned by @gerald-hb still persist, this resulted to the same problem mentioned by Rein wherein we get stuck at starting the strategy since the gateway status did not update (remain running, stopped).

So wrt the `INFO` log `Connection to Gateway established.` it just tell us that the Docker container has successfully started. It however doesnt tell us that the Gateway service is able to establish a connection to the chains. So in the scenario described above, it is the expected behaviour. 

Could you provide me the logs from within the gateway services instead? It should be in the `.hummingbot-gateway-XYZ` folder

**Comment by gerald-hb** [comment]
Getting this error when I do a normal start for amm_arb strategy. The strategy wont start
image
Expected result: Should start without any error
[supportpackets1.zip](https://github.com/CoinAlpha/hummingbot/files/9073533/supportpackets1.zip)

Only this issue now, hummingbot_quickstart.py seems to work on stopped/running docker container.

**Comment by Deepali6997** [comment]
The latest commit fixes the issue.
Screenshot 2022-07-12 at 7 19 54 PM

**Review by petioptrv — APPROVED** [review]
Changes LGTM!

**Comment by CrimsonJacket** [comment]
Closed and re-created PR on Foundation.
Foundation PR: https://github.com/hummingbot/hummingbot/pull/5490
Snapshot URL: https://snapshot.org/#/hbot-prp.eth/proposal/0xa20c501250a110d4630bb96d04aa24c8ebc7c3d5a428f8e3927e18515f3b9049

**Comment by RC-13** [comment]
Still LGTM!

**Comment by aarmoa** [comment]
@CrimsonJacket this should be closed if the PR has already been created in the Foundation repository

**Pull request merged**
