### PR TITLE
Fix/TWAP status order order, order spread

### PR DESCRIPTION
**Pull request by mhrvth**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

- fixes order of orders in status
- fixes order spread in status

**Tests performed by the developer**:

- ran strategy with binance paper
- ran unit test

### CODE REVIEW

**Comment by mhrvth** [comment]
[sc-23514]

**Comment by mhrvth** [comment]
[sc-23510]

**Review by petioptrv — APPROVED** [review]
Changes LGTM!

**Review by PtrckM — APPROVED** [review]
Test Summary:

- Clone and install `fix/twap_status_order` and working as expected.
- Create twap strategy and choose any supported exchange connector
- Confirmed that starting twap strategy without any error
- Status shows active orders in correct arrangement and match the exchange orders
- Using `status --live` shows spread are updating in real time.

**Comment by mhrvth** [comment]
@petioptrv @PtrckM Hello, please re-review it again. I had to reimplement the ordering to be by price because there's a PR that will remove timestamp from the Order ID so it won't be possible to use it for ordering in the future.

**Review by petioptrv — APPROVED** [review]
Changes LGTM

**Review by PtrckM — APPROVED** [review]
Retested..  changes still LGTM

**Comment by mhrvth** [comment]
Created a PR in the Foundation repo: https://github.com/hummingbot/hummingbot/pull/5135

**Pull request closed without merging**
