### PR TITLE
Feat/injective w batch update

### PR DESCRIPTION
**Pull request by petioptrv**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

This PR introduces batch order creation and cancelation for the client.

The functionality is implemented with backward compatibility.

The Injective connector is refactored to provide this enhanced order management.

**Tests performed by the developer**:

Added tests for the new functionality.

**Tips for QA testing**:

Please test that each exchange works with a normal PMM strategy, as well as with the new `batch_order_update.py` script. The script strategy has four phases:

1. Two orders are placed successfully. 
2. Then the orders are canceled successfully.
3. After that, two more orders are attempted; one order is placed successfully and one order fails due to the amount being zero. Here, the bot should log the failed event appropriately.
4. Finally, the existing order is canceled.

The script begins by setting some global variables
```Python
CONNECTOR = "okx"
TRADING_PAIR = combine_to_hb_trading_pair(base="BTC", quote="USDT")
AMOUNT = Decimal("0.0001")
ORDERS_INTERVAL = 10
PRICE_OFFSET_RATIO = Decimal("0.1")  # 10%
```
The `ORDERS_INTERVAL` variable is the number of ticks (seconds) between each of the script phases. The `PRICE_OFFSET_RATIO` variable sets the orders' prices at 10% from the current mid-market price.

### CODE REVIEW

**Comment by petioptrv** [comment]
@CoinAlpha/qa-team, please not that Injective will be failing, as with the parent PR, so no need to test it for now.

**Comment by gerald-hb** [comment]
Test runs
binance perpetual: https://hummingbot.testrail.io/index.php?/runs/view/3670
binance: https://hummingbot.testrail.io/index.php?/runs/view/3663
bitmart: https://hummingbot.testrail.io/index.php?/runs/view/3664
bybit: https://hummingbot.testrail.io/index.php?/runs/view/3665
gate_io: https://hummingbot.testrail.io/index.php?/runs/view/3666
huobi: https://hummingbot.testrail.io/index.php?/runs/view/3667
kucoin: https://hummingbot.testrail.io/index.php?/runs/view/3668
okx: https://hummingbot.testrail.io/index.php?/runs/view/3669
ascend_ex: https://hummingbot.testrail.io/index.php?/runs/view/3671

Injective: On hold for now

**Review by aarmoa — CHANGES_REQUESTED** [review]
@petioptrv let's coordinate a meeting to discuss the current approach.

**Comment by petioptrv** [comment]
Converting this PR to draft in favour of [this PR](https://github.com/CoinAlpha/hummingbot/pull/305), which will be submitted to foundation.

**Pull request closed without merging**
