### PR TITLE
Fix / performance fee calculation

### PR DESCRIPTION
**Pull request by Nullably**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
* Replace fee_token and fee_paid with a dictionary of fees (token and amount)
* When there are multiple fee token, display a list of the fees on `history` command
* Account for fee when the fee token is other than the quote token (achieved by get the latest price of the fee_token in quote value

### CODE REVIEW

**Comment by Nullably** [comment]
The `history` should now display a list of fee token and fee amount (when there are multiple) as below
image

**Comment by Nullably** [comment]
Suggested additional test cases
* Submit and wait til both buy and sell orders are filled (e.g. on Crypto.com) to see the bot accounts for both the fees correctly.
* Manually calculate fees and check if Trade PnL accounts for the fees correctly.
* Switch to Binance account, check if `pnl` command shows fee correctly there as well (`pnl` command is only available for Binance at the moment)

**Comment by RC-13** [comment]
Test PR on crypto.com using CRO-USDT pair, and confirm fees are now accounted into the total PNL calculation:
fee

Test on Binance as well using LINK-USDC market and fee is calculated in terms of quote token
image

Kill switch still works as expected.

**Comment by RC-13** [comment]
Fee calculation under `pnl` command is correct as well:
pnl command
history1

Question though, in Binance if you set to pay fees in BNB should that appear as well under performance status?

**Review by RC-13 — APPROVED** [review]

**Review by keithbaum — APPROVED** [review]
Looks ok

**Comment by Nullably** [comment]
@RC-13 
> Question though, in Binance if you set to pay fees in BNB should that appear as well under performance status?
Yes, fees should show correct fees after the trade is done. I have fixed it in the PR now.

@keithbaum 
I updated places where OrderFilledEvent is created to store real trade fee from API.

**Comment by RC-13** [comment]
Re-test PR and confirmed BNB fee is now showing when using Binance.
Total PnL calculation: OK
history1
BNB fee to USD : Ok
pnl command
Fee used and pnl calculation when using crypto.com: Ok
image

**Review by RC-13 — APPROVED** [review]

**Review by dennisocana — APPROVED** [review]
LGTM

**Pull request merged**
