### PR TITLE
[v0.33] Feat / history redesigned

### PR DESCRIPTION
**Pull request by Nullably**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**After creating this PR, please make sure:**

- [x] You link the related GitHub issue or ticket

**A description of the changes proposed in the pull request**:
- Redesign output report based on google sheet in #2129 

**Notes**
- Since there is now no start balances saved, the start balances are calculated from current balances (account for trades done)
- Start price is the first trade price, this might not be the start price for the history period.
- For paper trade mode, the current balances are from paper balances config when the strategy is not running. So might create a bit of confusion to users.

### CODE REVIEW

**Comment by mifeng** [comment]
Screen Shot 2020-10-26 at 11 15 57 PM

I ran the bot for a while and then hit `stop`, then `history --verbose`. The performance statistics are correct, but I would expect the trades to appear as well. Is that possible?

**Comment by mifeng** [comment]
My trades corresponding to the screenshot above
[trades_conf_pure_mm_1 copy.csv.zip](https://github.com/CoinAlpha/hummingbot/files/5443392/trades_conf_pure_mm_1.copy.csv.zip)

**Comment by Nullably** [comment]
@mifeng 
The Avg price on Trades table on your screen shot looks wrong (over avg buy and avg sell prices). 
I think this is bc. the formula for it is Total trade volume (quote) divided by Total trade volume (base). 
What it should be is 
`((avg_buy_price * buy_volume_base) + (avg_sell_price * sell_volume_base)) / (buy_volume_base + sell_volume_base)`
What do you think?

**Comment by mifeng** [comment]
> @mifeng
> The Avg price on Trades table on your screen shot looks wrong (over avg buy and avg sell prices).
> I think this is bc. the formula for it is Total trade volume (quote) divided by Total trade volume (base).
> What it should be is
> `((avg_buy_price * buy_volume_base) + (avg_sell_price * sell_volume_base)) / (buy_volume_base + sell_volume_base)`
> What do you think?

Yes, I agree

**Review by mifeng — APPROVED** [review]
LGTM

**Review by mifeng — CHANGES_REQUESTED** [review]
Screen Shot 2020-10-27 at 12 58 13 PM

I think I found a bug: Total P&L should be Trade P&L minus fees, but it seems like it's adding fees.

**Comment by Nullably** [comment]
@mifeng 
> I think I found a bug: Total P&L should be Trade P&L minus fees, but it seems like it's adding fees.

Yep, it's a bug. I just fixed it.

**Review by mifeng — APPROVED** [review]
LGTM

**Pull request merged**
