### PR TITLE
altered setup files to pull upgraded dydx client

### PR DESCRIPTION
**Pull request by trkoneill18**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

This upgrades the dydxv3 client to version 1.0.10. This facilitates support of all current markets on the dydx exchange

### CODE REVIEW

**Comment by dennisocana** [comment]
@RC-13 please test this PR to confirm if this fixes #3450

**Review by RC-13 — APPROVED** [review]
Tested and confirmed that this PR addresses ticket #3450. No issue was found as well during testing.

**Comment by rxlxrxsx** [comment]
- dYdX recently released the COMP-USD market on perpetual, upon trying the market pair I'm getting the same issue reported [here](https://github.com/CoinAlpha/hummingbot/issues/3450)

Screen Shot 2021-07-21 at 10 32 25 AM

```python
2021-07-21 10:14:35,338 - 1979 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_derivative - INFO - 'COMP-USD'
Traceback (most recent call last):
  File "/Users/reiniersalazar/hummingbot/hummingbot/connector/derivative/dydx_perpetual/dydx_perpetual_derivative.py", line 355, in execute_order
    creation_response = await self.place_order(client_order_id, trading_pair, amount,
  File "/Users/reiniersalazar/hummingbot/hummingbot/connector/derivative/dydx_perpetual/dydx_perpetual_derivative.py", line 303, in place_order
    return await self.dydx_client.place_order(
  File "/Users/reiniersalazar/hummingbot/hummingbot/connector/derivative/dydx_perpetual/dydx_perpetual_client_wrapper.py", line 60, in place_order
    return await f
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/dydx3/modules/private.py", line 488, in create_order
    order_to_sign = SignableOrder(
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/dydx3/starkex/order.py", line 58, in __init__
    synthetic_asset = SYNTHETIC_ASSET_MAP[market]
KeyError: 'COMP-USD'
```

- Also from the screenshot above, there's a minor cosmetic issue with time related parameters like order_refresh_time and filled_order_delay. I set the order_refresh_time to 30 but upon checking on `config` it shows 3 instead.

Logs and config: [dydx.zip](https://github.com/CoinAlpha/hummingbot/files/6852406/dydx.zip)

**Review by vic-en — APPROVED** [review]
LGTM. Just a library update.  And since QA confirmed it resolve the issue then I guess it's ok to merge.

**Pull request merged**
