### PR TITLE
Feat/Add broker ID to Huobi connector - Refactored + Unit test

### PR DESCRIPTION
**Pull request by mhrvth**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
A Hummingbot's broker id assigned by Huobi is added as a prefix to order-id (client-order-id). Refactored previous PR, unit test added.

**Tests performed by the developer:**
Ran a live pure market making strategy on Huobi and printed in logs the "client-order-id" parameter that's being sent to the exchange.

### CODE REVIEW

**Review by aarmoa — APPROVED** [review]
Changes look good to me

**Comment by dennisocana** [comment]
Sent order ID of sample trades to Huobi. Let's wait and see for confirmation tomorrow.

**Review by RC-13 — APPROVED** [review]
Confirmed new broker ID is now added to orders created and filled trades.

**Comment by dennisocana** [comment]
Merging this PR since the task of adding the prefix broker ID is complete. No further actions required from our side.

**Pull request merged**
