### PR TITLE
Fix/update smart round in uniswap v3 lp strategy

### PR DESCRIPTION
**Pull request by vic-en**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

### CODE REVIEW

**Review by aarmoa — DISMISSED** [review]
The change corrects a merge issue with other PR. Looks good.

**Comment by dennisocana** [comment]
@vic-en I changed the base branch to `staging` where all bug fixes in pre-prod are going to be merged.

**Comment by RC-13** [comment]
Confirming fix, error no longer occurs during strategy startup and successfully open positions. The test is done using the KOVAN network and the custom assets.
image

**Review by RC-13 — APPROVED** [review]

**Review by dennisocana — CHANGES_REQUESTED** [review]
Requesting to rebase with staging

**Pull request closed without merging**
