### PR TITLE
Revert "doc / remove Solana from LM docs"

### PR DESCRIPTION
**Pull request by Nullably**
Reverts CoinAlpha/hummingbot#2144

### CODE REVIEW

**Comment by TheHolyRoger** [comment]
@dennisocana Why did you only approve and not merge this? The branch is currently broken after the mess you left it in and this resolves it 😂

**Comment by Nullably** [comment]
@TheHolyRoger Please play nice and be polite. We don't know what happened exactly yet, regardless it's very clear that it wasn't intentional and mistakes do happen.

**Comment by TheHolyRoger** [comment]
Did not intend to be rude, sorry! Just being honest :)

**Comment by TheHolyRoger** [comment]
Thank you :)

**Pull request merged**
