### PR TITLE
Fix/Avellaneda MM - fix reserved price calculation for the infinite time horizon

### PR DESCRIPTION
**Pull request by mhrvth**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

Replacement of the equations for the infinite timeframe. The solution described in the paper seems to contain mistakes, and therefore is unusable. It has been replaced with the equations for constrained timeframes, but with dependency on time neutralized.

**Tests performed by the developer**:

- Ran the unit tests
- Ran the strategy with binance paper and ETH-USDT to see if the strategy is able to achieve it's target portfolio allocation

**Tips for QA testing**:

- The arbitrary values in the Avellaneda unit tests come from a measurement and estimation of a stochastic process. They have to be taken as they are without further explanation.

### CODE REVIEW

**Comment by mhrvth** [comment]
[sc-21774]

**Review by aarmoa — APPROVED** [review]
The PR seems good to me. QA might need some details to validate the new calculations.

**Comment by PtrckM** [comment]
- Currently reserved price is working as expected. 
   - reserved price is far from the mid price if current inventory is doesn't meet the allocation specified
   - reserved price is close enough to the mid price if inventory is close or meet the specified allocation

- Awaiting for way to actually verify or compute the reserve price

**Review by PtrckM — APPROVED** [review]
Tested and approved by QA team.
Test summary:

- Created a strategy and went through initial prompts successfully
- Confirmed wallet and exchange balances are reflecting correct
- Started the strategy without issues, confirmed orders are created and cancelled based on config
- Ran a test bot for hours without errors
- Confirmed no error on logs during run time and order filled events.
- Trade information are correct (price, size) based on history command output
- Confirms bot behavior on reserve price thru observation: 
  - the more portfolio from target the further away the reservation price will be from the mid price
  - the portfolio is close to target the reservation price and mid price are close to each other. 

Note: Reservation price - It’s not possible to calculate it so simply, It measures the changes of order book in time and then estimates a probability function.

**Comment by mhrvth** [comment]
Create a PR in the Foundation repo: 

https://github.com/hummingbot/hummingbot/pull/5028

**Pull request closed without merging**
