### PR TITLE
fix/Allow 2 chars token pairs ( IQ ) against BUSD on binance

### PR DESCRIPTION
**Pull request by kesar**
IQ-BUSD becomes IQB-USD

this regexp was assuming first part of the pair was 3 chars.

Captura de pantalla 2021-07-03 a las 13 52 35
Captura de pantalla 2021-07-03 a las 13 52 25

### CODE REVIEW

**Comment by dennisocana** [comment]
Thanks @kesar for contributing. Please change the rebase your branch with `development` instead of `master`.

**Comment by dennisocana** [comment]
@kesar there we're going to review your PR starting next week once the merge conflicts in this PR have been resolved. You can do either one of the following:

1. Re-sync your branch with `development` or..
2. Create another PR based on `development` branch and submit these changes

**Comment by RC-13** [comment]
@dennisocana @kesar It appears that this issue with IQ-BUSD pair has been covered by this PR: #3921 
image

**Comment by dennisocana** [comment]
> @dennisocana @kesar It appears that this issue with IQ-BUSD pair has been covered by this PR: #3921
> image

Thanks @RC-13 for confirming.

**Pull request closed without merging**
