### PR TITLE
fix / price_type=inventory_cost will trigger config inventory_price prompt

### PR DESCRIPTION
**Pull request by keithbaum**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

when setting up price_type="inventory_cost", config will now require inventory_price setting

### CODE REVIEW

**Comment by rxlxrxsx** [comment]
Still getting the same behavior even after switching `price_type` to `inventory_cost` and going through the prompts

Screen Shot 2021-03-04 at 7 20 05 AM

```
2021-03-04 07:07:10,037 - 2100 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 672, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_tick
    proposal = self.c_create_base_proposal()
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 712, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_create_base_proposal
    raise RuntimeError("Initial inventory price is not set while inventory_cost feature is active.")
RuntimeError: Initial inventory price is not set while inventory_cost feature is active.
```

[logs_inventory_cost.log](https://github.com/CoinAlpha/hummingbot/files/6079775/logs_inventory_cost.log)

**Comment by dennisocana** [comment]
Discussed with @keithbaum that we need to figure out a different approach for this since there are new related issues discovered while testing the fix. Moving to version 0.38 release so we have more time to plan

**Comment by keithbaum** [comment]
Hi @rxlxrxsx, code updated to fix that error.

**Review by rxlxrxsx — APPROVED** [review]
Tested and confirmed fix for issue listed above and no other issues found during testing by QA.

Screen Shot 2021-03-31 at 7 30 06 AM

**Comment by dennisocana** [comment]
@JeremyKono please take note and of Daniel's comment above and add to docs.

**Pull request merged**
