### PR TITLE
Fix/hitbtc trading pairs parsing

### LINKED ISSUE #4750: HitBTC fails to parse trading pairs
**Describe the bug**
// A clear and concise description of what the bug is.
The HitBTC connector fails to regex-match some of the trading pairs using its `convert_from_exchange_trading_pair` utility function. When that happens, the function simply returns `None`, which in turn adds a new rule with trading pair `None` to the trading rules dictionary. The next time this happens, the previously created rule is simply overwritten. This means that the failure is silent and unless one of the failed-to-parse trading pairs is used, this wouldn't have been apparent until the changes introduced to the `TradingRule` data class made in [#4678](https://github.com/CoinAlpha/hummingbot/pull/4678).

**Steps To Reproduce**
Use the HitBTC connector with any strategy.

**Release version**
dev-0.46.0

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

### PR DESCRIPTION
**Pull request by aarmoa**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Change in HitBTC connector to keep a list of available tokens and use it to translate tokens from exchange format to client format back and forth. Since the connector is a spot connector the new logic excludes all perpetual tokens from the list.

**Tests performed by the developer**:
I have added unit tests for all the new functionality related to the population of the token list and the new functions to translate token formats.
I have not added tests for the connector functions that consume the translation methods because we need to send this fix to production with the next release. Also in the near future we will be working on replacing websockets library for aiohttp in HItBTC, and we will add all the required tests when tackling that task.

**Tips for QA testing**:
Please test the connector can create and cancel orders correctly, and the trade fills are processed without issues. I could not test the connector myself because the support HitBTC account has no founds.

Fixes #4750

### CODE REVIEW

**Comment by nikspz** [comment]
@aarmoa upon checking with the team, 
Failed to connect hitbtc API keys on Source ubuntu, mac and windows

image 
image

**Review by nikspz — CHANGES_REQUESTED** [review]
Failed to connect hitbtc API keys on Source ubuntu, mac and windows

**Review by nikspz — CHANGES_REQUESTED** [review]
Converted USDT to DAI (bot showing BTC-DAI) 

When ran BTC-DAI Bot showing `Error parsing trading pair rule`, then go into `Unexpected error with websocket connection`

Bot not showing BTC-USDT and other pairs

image
image


image

**Comment by aarmoa** [comment]
Hello @nikspz. This is the list of tokens accepted in the V2 API (the one used by the current HitBTC connector implementation): https://api.hitbtc.com/api/2/public/symbol
BTCUSDT is not in the list. I am not sure why you say it is accepted and should be visible in the client.

**Comment by nikspz** [comment]
> This is the list of tokens accepted in the V2 API (the one used by the current HitBTC connector implementation): https://api.hitbtc.com/api/2/public/symbol BTCUSDT is not in the list. 

Thank you, got it. 
[There](https://github.com/CoinAlpha/hummingbot/pull/4812#pullrequestreview-816420692) I tested pureMM for BTC-DAI pair, that's in the list.
After start bot shows `Error parsing trading pair rule`, then stuck with `Unexpected error with WebSocket connection`.

**Comment by aarmoa** [comment]
Thank you @nikspz. I am reviewing now the rest of the errors.

**Comment by aarmoa** [comment]
@nikspz in the discussion we had with @RC-13 during the daily meeting he mentioned that HitBTC names USDT as USD in their V2 API. I have added back the translation that was used for USDT in the previous token parsing logic into the new one. I have also solved the other issues you discovered.

**Comment by nikspz** [comment]
Tested BTC-USDT Pair, now running ok.
image

**Review by nikspz — APPROVED** [review]
LGTM

**Review by CrimsonJacket — APPROVED** [review]
Changes LGTM

**Comment by dennisocana** [comment]
@aarmoa I'm going to merge this PR after collecting the required approvals from QA and engineering so I can sync to staging. Should there be any more changes after this, please create a separate PR.

**Pull request merged**
