### PR TITLE
Fix / Add throttler parameter for connector settings to fix paper trade on several connectors.

### LINKED ISSUE #4300: Paper trade broken on recently refactored connectors using the new asyncio throttler (gate.io, binance, kucoin)
**Describe the bug**
Paper trade is broken on all the recently refactored exchanges using the new asyncio throttler as it adds a new required arg to the classes

**Steps To Reproduce**
Run any of these refactored connectors in paper trade mode (gate.io, binance, kucoin, ascend_ex, crypto.com, ndax, kraken)

...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
development

**Attachments**
```
2021-09-27 15:47:15,546 - 1 - hummingbot.core.remote_control.remote_command_executor - INFO - Starting Remote Command Executor.
2021-09-27 15:47:15,548 - 1 - hummingbot.client.hummingbot_application - ERROR - Unknown error during initialization.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/strategy/pure_market_making/start.py", line 60, in start
    self._initialize_markets(market_names)
  File "/home/hummingbot/hummingbot/client/hummingbot_application.py", line 265, in _initialize_markets
    connector = create_paper_trade_market(connector_name, trading_pairs)
  File "/home/hummingbot/hummingbot/connector/exchange/paper_trade/init.py", line 27, in create_paper_trade_market
    obt_obj = obt_class(**obt_kwargs)
TypeError: init() missing 1 required positional argument: 'throttler'
2021-09-27 15:47:15,548 - 1 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2021-09-27 15:47:15,618 - 1 - hummingbot.core.remote_control.remote_command_executor - INFO - Remote Command Executor is listening.
2021-09-27 15:47:20,867 - 1 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2021-09-27 15:47:20,867 - 1 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: list.remove(x): x not in list
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/hummingbot/hummingbot/client/command/stop_command.py", line 37, in stop_loop
    self.clock.remove_iterator(self.strategy)
  File "hummingbot/core/clock.pyx", line 83, in hummingbot.core.clock.Clock.remove_iterator
    self._child_iterators.remove(iterator)
ValueError: list.remove(x): x not in list
```

### PR DESCRIPTION
**Pull request by TheHolyRoger**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Fix for Paper trade failing to start on the following exchanges since the asyncio throttler refactor:
gate.io, binance, kucoin, ascend_ex, crypto.com, ndax, kraken

Fixes #4300

### CODE REVIEW

**Comment by dennisocana** [comment]
@CoinAlpha/dev-client even though we plan to rework paper trade mode in the future, we can't leave it in a broken state for now. Adding this for code review and testing by QA before we release version 0.44

**Comment by petioptrv** [comment]
Thank you for this PR @TheHolyRoger. I made a mistake when making the throttler init param mandatory for the order book and user stream classes. My thinking was that those will be only instantiated from the exchange class, but I have clearly overlooked this case, and perhaps others.

That being said, I think the solution to this issue should be to apply the approach used in the `BinanceAPIOrderBookDataSource` class where the throttler is an optional parameter and if not provided, then a default instance is created.

**Comment by RC-13** [comment]
Tested the PR and issue has been fix for most of the affected connectors except for crypto.com connector.

Ascend_Ex  :white_check_mark:
Binance :white_check_mark:
Crypto_com :x:
Gate_io :white_check_mark:
Kraken :white_check_mark:
KuCoin :white_check_mark:
NDAX :white_check_mark:

**Comment by TheHolyRoger** [comment]
@petioptrv that should do it :)

**Comment by TheHolyRoger** [comment]
@RC-13 if you still have an error with crypto_com can you share it please?

**Review by petioptrv — APPROVED** [review]
Thank you for making the changes @TheHolyRoger, LGTM!

**Review by RC-13 — APPROVED** [review]
Tested again on the latest commit and confirm that all affected connectors are now working in paper trade mode.

**Pull request merged**
