### PR TITLE
Refactor/spot perp arb rework

### PR DESCRIPTION
**Pull request by Nullably**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
- Implement changes as described in #3791 
- Fixes bugs in #3679 

**Tests performed by the developer**:
- Unit tests
- Strategy test on real trading on ETH-USDT on Binance and Binance Perpetual
- Configuration process test (create, import)

**Tips for QA testing**:
- You can set min_opening_arbitrage_pct to negative value for the strategy to immediate open arbitrage position, though you will open the position at negative profit expectation. Similar to other arbitrage strategy, this is mainly intended for testing purpose.

### CODE REVIEW

**Comment by RC-13** [comment]
@Nullably When I was testing the PR, the strategy was able to recognized that the Binance test account I was using is in Hedge mode (which is a good thing) however it seems that it permanently save that status and doesn't recognize that I  already switched the position to one-way mode. I tried running a perpetual market making strategy using the same account in the same PR and it was able to recognize that the account is already in one-way mode.

https://user-images.githubusercontent.com/57189990/134636384-caccb091-4908-4251-9d5b-1168a71118f4.mov

.
Cross check on development branch and it seems that the behavior happens in the PR only.
image

Using other perpetual connector, the strategy works as intended.

**Comment by Nullably** [comment]
> @Nullably When I was testing the PR, the strategy was able to recognized that the Binance test account I was using is in Hedge mode (which is a good thing) however it seems that it permanently save that status and doesn't recognize that I already switched the position to one-way mode. I tried running a perpetual market making strategy using the same account in the same PR and it was able to recognize that the account is already in one-way mode.
> 
>  spot-perp.vs.perp-mm.mov 
> .
> Cross check on development branch and it seems that the behavior happens in the PR only.
> image
> 
> Using other perpetual connector, the strategy works as intended.

The perpetual market making set position mode for a user every time the strategy starts. 
Looks like there is a bug in Binance perpetual connector where it doesn't get user position mode at the start, so the spot perp arb strategy doesn't get this information.

**Comment by dennisocana** [comment]
I think that's related to the BInance Perpetual issue here: https://github.com/CoinAlpha/hummingbot/issues/3961

**Comment by RC-13** [comment]
Thank you @Nullably for the explanation.

**Review by RC-13 — APPROVED** [review]
LGTM!

**Review by mhrvth — APPROVED** [review]

**Pull request merged**
