### PR TITLE
fix/ reset UI prompt when returning from within prompts

### PR DESCRIPTION
**Pull request by CrimsonJacket**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Fix minor UI issue where prompt is not present when exiting a UI prompt
[sc-25511]

**Tests performed by the developer**:

**Tips for QA testing**:
Ensure that reported issue no longer occurs.

### CODE REVIEW

**Comment by martinkou** [comment]
I'm still getting the same issue after the patch.

**Comment by martinkou** [comment]
Taking this over. A `contextmanager` would be a cleaner fix for this.

**Comment by martinkou** [comment]
Should be fixed now. @CoinAlpha/qa-team ready for test.

**Review by PtrckM — APPROVED** [review]
LGTM!
Test summary:

Install the feature branch without any issues
Run gateway create and input infura confirms gateway created and running on background
Confirm gateway connect {uniswap, pangolin} bot validates input/selection, confirms blockchain network availability and exit config question successfully.

**Pull request merged**
