### PR TITLE
fix / create orders using remaining balance

### LINKED ISSUE #2321: [Feature] Submit lower order amount on low balance.
**Why**
I set up my bot to run on PMM COTI-BTC with order amount of 1500, and my COTI balance is 1500.
After the bot starts making market, the sell order got partially filled, say 200, then the bot stops placing sell orders, as the available balance (1300) is now less than the order amount setting. And the bot also misses on buy orders as my BTC balance is less than what it needs to place 1500 COTI buy order.

**Feature Suggestion**
A new default bot behaviour for when if the available balance is not enough for the order, the bot recalculates new lesser order amount based on available balance after balance limit applied (if any). For sell orders, this is the base token available balance, for buy orders this is the quote token available balance. Note that this does not permanently change `order_amount`.

### PR DESCRIPTION
**Pull request by dennisocana**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**After creating this PR, please make sure:**

- [x] You link the related GitHub issue or ticket

**A description of the changes proposed in the pull request**:

Fixes #2321 that allows pure market making strategy to create orders using the remaining available balance if it's less than the specified `order_amount` value instead of not creating any orders at all.

image

### CODE REVIEW

**Comment by rxlxrxsx** [comment]
Tested using two different pairs as I have encountered different scenarios for each pair. Note that the test done considers the ``minimum_order`` amount for each pair to make sure it'll create orders with the remaining balance.

### Test using COTI-USDT

``order_amount = 900``
``order_levels = 1``

Notice that it didn't create a buy order with the current balance it has.

order_level 1 coti-usdt

``order_amount = 500``
``order_levels = 1``
``balance limit COTI = 420, USDT = 12``

Same as the result above, notice that it didn't create a buy order with the current balance it has.

with balance limit (420 coti 12 usdt)

``order_amount = 850``
``order_levels = 1``
``inventory_skew = true``

Same as the result above, notice that it didn't create a buy order with the current balance it has.

with skew coti-usdt

``order_amount = 420``
``order_levels = 2``

No orders are created on the second order level of the buy and sell side which should use the remaining balance it has.

order_levels 2 coti-usdt

``order_amount = 420``
``order_levels = 1``
``hanging_orders_enabled = true``

After the order got filled and creates a new batch of orders, the bot didn't create a buy order with the current balance it has unlike with the sell order.

with hanging orders coti-usdt (not ok buy order)
with hanging orders coti-usdt (ok sell order)

### Test using ETH-USDT

``order_amount = 0.07``
``order_levels = 1``

Ok - Bot places buy and sell orders using the remaining balance it has.

order_level 1 eth-usdt (ok)

``order_amount = 0.07``
``order_levels = 1``
``balance limit ETH = 0.05, USDT = 20``

Ok - Bot places buy and sell orders using the remaining balance it has.

with balance limit ( 05 eth 20 usdt) -ok

``order_amount = 0.07``
``order_levels = 1``
``inventory_skew = true``

Ok - Bot places buy and sell orders using the remaining balance it has.

with skew eth-usdt (ok)

``order_amount = 0.035``
``order_levels = 1``
``hanging_orders_enabled = true``

Ok - After the order got filled, bot places buy and sell orders using the remaining balance it has.

with hanging orders eth-usdt (buy ok)
with hanging orders eth-usdt (sell ok)

``order_amount = 0.033``
``order_levels = 2``

Bot fails to create a 2nd sell order using the remaining balance however for the buy order, instead of creating 2 separate buy orders, it combined bot orders into a single order.

order_levels 2 eth-usdt

Also found this in the logs that might be helpful.

```
2020-10-20 07:55:36,002 - 19761 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - Not enough balance to create all sell orders: order_levels is set to 2
2020-10-20 07:55:36,002 - 19761 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Creating 2 bid orders at (Size, Price): ['0.033 ETH, 368.99 USDT', '0.06701 ETH, 367.11 USDT']
2020-10-20 07:55:36,003 - 19761 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Creating 1 ask orders at (Size, Price): ['0.033 ETH, 380.22 USDT']
2020-10-20 07:55:36,088 - 19761 - hummingbot.connector.exchange.binance.binance_exchange - INFO - Created LIMIT_MAKER BUY order x-XEKWYICX-BEHUT1603180536003176 for 0.03300000 ETH-USDT.
2020-10-20 07:55:36,108 - 19761 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1603180536.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ETH-USDT", "amount": "0.03300000", "price": "368.99000000", "order_id": "x-XEKWYICX-BEHUT1603180536003176", "exchange_order_id": null, "event_name": "BuyOrderCreatedEvent", "event_source": "binance"}
2020-10-20 07:55:36,590 - 19761 - hummingbot.connector.exchange.binance.binance_exchange - NETWORK - Error submitting BUY LIMIT_MAKER order to Binance for 0.06701000 ETH-USDT 367.11000000.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/binance/binance_exchange.pyx", line 845, in hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange.create_order
    order_result = await self.query_api(self._binance_client.create_order, **api_params)
  File "hummingbot/connector/exchange/binance/binance_exchange.pyx", line 223, in query_api
    async with self._throttler.weighted_task(request_weight=request_weight):
  File "hummingbot/connector/exchange/binance/binance_exchange.pyx", line 235, in hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange.query_api
    raise ex
  File "hummingbot/connector/exchange/binance/binance_exchange.pyx", line 225, in hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange.query_api
    return await self._async_scheduler.call_async(partial(func, *args, **kwargs),
  File "/home/rsa-key-20200326/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 128, in call_async
    return await self.schedule_async_call(coro, timeout_seconds, app_warning_msg=app_warning_msg)
  File "/home/rsa-key-20200326/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 117, in schedule_async_call
    return await fut
  File "/home/rsa-key-20200326/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 80, in _coro_scheduler
    fut.set_result(await coro)
  File "/home/rsa-key-20200326/miniconda3/envs/hummingbot/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/rsa-key-20200326/miniconda3/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 1149, in create_order
    return self._post('order', True, data=params)
  File "/home/rsa-key-20200326/miniconda3/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 210, in _post
    return self._request_api('post', path, signed, version, **kwargs)
  File "/home/rsa-key-20200326/miniconda3/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 181, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/home/rsa-key-20200326/miniconda3/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 176, in _request
    return self._handle_response(response)
  File "/home/rsa-key-20200326/miniconda3/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 200, in _handle_response
    raise BinanceAPIException(response)
binance.exceptions.BinanceAPIException: APIError(code=-2010): Account has insufficient balance for requested action.
2020-10-20 07:55:36,592 - 19761 - hummingbot.connector.exchange.binance.binance_exchange - WARNING - APIError(code=-2010): Account has insufficient balance for requested action.
```

[logs_binance-test.log](https://github.com/CoinAlpha/hummingbot/files/5407201/logs_binance-test.log)

**Comment by rxlxrxsx** [comment]
No other issues found during testing by QA.

**Review by Nullably — APPROVED** [review]
LGTM

**Comment by Nullably** [comment]
@rxlxrxsx 
> No other issues found during testing by QA.

Does this mean all the issues you reported earlier are fixed?

**Comment by rxlxrxsx** [comment]
@Nullably yes, thanks for pointing it out. I edited my comment above to avoid confusion.

**Pull request merged**
