### PR TITLE
(feat) Implements the Polkadex exchange connector

### PR DESCRIPTION
**Pull request by petioptrv**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

Introduces the Polkadex exchange connector.

**Tests performed by the developer**:

- Unit tests
- Manual test of PMM

**Tips for QA testing**:

Please test the full extent of the connector.

[ch-39726]

### CODE REVIEW

**Comment by mrhzysbl** [comment]
Test run: https://hummingbot.testrail.io/index.php?/runs/view/4344&group_by=cases:section_id&group_order=asc

**Review by vic-en — APPROVED** [review]
LGTM

**Review by mrhzysbl — APPROVED** [review]
Tested and confirmed working by QA
- Installed the feature branch without any issue
- Connected API key for Polkadex
- Created PMM strategy
- Able to create and cancel orders, setup order levels
- Balance are updated
- Checked history, order book
- Able to export keys and csv file
- Handled filled and partial fills
- Setup long term bots; no orphan orders found
- No unexpected errors on log pane
- Build docker image and repeat same tests performed on source build. Confirmed no issues
- Blocked: Verifying trading fee since trading history is not available from the web app, manual cancellation of orders from exchange (client app issue)

**Review by vic-en — APPROVED** [review]
LGTM

**Comment by petioptrv** [comment]
Closing to re-open towards foundation

**Pull request closed without merging**
