### PR TITLE
hotfix / version 0.43.1

### PR DESCRIPTION
**Pull request by dennisocana**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

This release is a hotfix to version [0.43.0](/release-notes/0.43.0).

Fixed dependencies issues resulting to errors when installing Hummingbot from source on different operating systems as described in GitHub issue [#4173](https://github.com/CoinAlpha/hummingbot/issues/4173).

### CODE REVIEW

**Review by Nullably — DISMISSED** [review]
LGTM

**Comment by RC-13** [comment]
Requesting minor change for the version number, it still shows 0.43.0 instead of 0.43.1
image

**Comment by dennisocana** [comment]
@RC-13 thanks for the catch. Pushed a commit to fix

**Review by rapcmia — APPROVED** [review]
Tested and working ok, approved on behalf of QA team.

**Pull request merged**
