### PR TITLE
feat / Historical Volatility & rename Average Volatility

### PR DESCRIPTION
**Pull request by keithbaum**
Added Historical Volatility indicator.
Renamed Average volatility to Instant Volatility Indicator (changed in avellaneda strategy)

**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

Solves #3629

### CODE REVIEW

**Review by aarmoa — APPROVED** [review]
The code adds historical volatility calculator.
The code seems good to me. The calculations should be validated also by @phbrgnomo or QA team.

**Comment by phbrgnomo** [comment]
@keithbaum shouldn't the avellaneda strategy code be changed because of the volatility naming refactor?

**Review by aarmoa — APPROVED** [review]
All changes look good to me

**Comment by mifeng** [comment]
Thanks a lot for your contribution @keithbaum! 😊

**Pull request merged**
