### PR TITLE
feat/script_command_and_shortcuts

### PR DESCRIPTION
**Pull request by zappra**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

#2928 #2922

Add ability to define command shortcuts, and/or group often used commands together
Also add ability to send commands to a running script instance
Modify hello_world_script.py to demonstrate script command

Example output:

Screenshot 2021-02-23 at 06 36 04

### CODE REVIEW

**Comment by zappra** [comment]
Hey! How do I request a review for a PR?

**Comment by krisj** [comment]
I would love to add a vote for this PR to be included upstream, It is beyond useful and I am only custom docker images where this PR is always included!

**Comment by zappra** [comment]
Yeah this has proven to be super-useful, I have about 25 shortcuts setup.

Happy to respond to change requests obvs, but just needs someone to review it!

**Comment by dennisocana** [comment]
Hey @zappra thanks for contributing. We're planning to review this PR within the next couple of weeks. Please resolve the conflicting files to move forward.

**Review by Nullably — APPROVED** [review]
A really nice feature indeed, clever and very useful.
I really like the command shortcuts as well.
@zappra Could you share with us some other shortcuts, apart from spreads, that you created?
The code changes look good and well written.
Thanks a lot for sharing this with us.

**Comment by zappra** [comment]
@Nullably thanks for reviewing this

Another good example would be a command I set up to set long_profit_taking_spread, short_profit_taking_spread and stop_loss_spread in a single command for perpetual market making. Try typing that lot out longhand, especially over Telegram!

I make a lot of use of the script command, and then the shortcuts allow me to make the script commands more usable, eg. a shortcut "pause" that expands to "script pause"

**Review by RC-13 — APPROVED** [review]
Tested PR and confirmed working as expected.

**Pull request merged**
