### PR TITLE
Feat/loopring connector

### PR DESCRIPTION
**Pull request by mborraccia**
**Before submitting this PR, please make sure**:
- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

Related GitHub issue: https://github.com/CoinAlpha/hummingbot/issues/1989

Adds a connector for loopring.io

### CODE REVIEW

**Comment by dennisocana** [comment]
In `history` command output, the `Start Price` and `End Price` are not quantized.

image

**Review by dennisocana — COMMENTED** [review]
In `history` command output, the `Start Price` and `End Price` are not quantized.

image

image

**Comment by dennisocana** [comment]
Order prices are not showing correctly in logs, shows as exponent values for markets with big decimal values in price.

image

**Comment by dennisocana** [comment]
Logs shows the order size in exponent value if `order_amount` is in multiples of 10.

image

Tested with `order_amount` set to a value like 51 and shows correctly.

image

**Comment by dennisocana** [comment]
Multiple instances of this error shown in the logs, but no impact on the said orders.

[logs_loopring_lrc-eth_2.log](https://github.com/CoinAlpha/hummingbot/files/5236596/logs_loopring_lrc-eth_2.log)

Screen Shot 2020-09-17 at 1 42 54 PM

**Comment by dennisocana** [comment]
Error when trying to execute unit tests in `test_loopring_market.py`.

image

**Comment by dennisocana** [comment]
3. Cannot run cross exchange market making.

[xemm_loopring_binance_usdc-usdt.log](https://github.com/CoinAlpha/hummingbot/files/5249006/xemm_loopring_binance_usdc-usdt.log)

```
2020-09-19 02:28:31,002 - 20267 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/cross_exchange_market_making/cross_exchange_market_making.pyx", line 304, in hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making.CrossExchangeMarketMakingStrategy.c_tick
    self.c_process_market_pair(market_pair, market_pair_to_active_orders[market_pair])
  File "hummingbot/strategy/cross_exchange_market_making/cross_exchange_market_making.pyx", line 391, in hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making.CrossExchangeMarketMakingStrategy.c_process_market_pair
    self.c_check_and_create_new_orders(market_pair, has_active_bid, has_active_ask)
  File "hummingbot/strategy/cross_exchange_market_making/cross_exchange_market_making.pyx", line 1108, in hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making.CrossExchangeMarketMakingStrategy.c_check_and_create_new_orders
    bid_price = self.c_get_market_making_price(market_pair, True, bid_size)
  File "hummingbot/strategy/cross_exchange_market_making/cross_exchange_market_making.pyx", line 776, in hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making.CrossExchangeMarketMakingStrategy.c_get_market_making_price
    OrderBook maker_order_book = market_pair.maker.order_book
  File "/home/ubuntu/11-loopring/hummingbot/strategy/market_trading_pair_tuple.py", line 23, in order_book
    return self.market.get_order_book(self.trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 217, in hummingbot.connector.exchange_base.ExchangeBase.get_order_book
    raise NotImplementedError
NotImplementedError
```

image

image

**Comment by dennisocana** [comment]
4. Same error issue when running arbitrage strategy.

[logs_test_loopring_arb.log](https://github.com/CoinAlpha/hummingbot/files/5249013/logs_test_loopring_arb.log)

```
2020-09-19 02:50:11,001 - 20973 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/arbitrage/arbitrage.pyx", line 192, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_tick
    self.c_process_market_pair(market_pair)
  File "hummingbot/strategy/arbitrage/arbitrage.pyx", line 327, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_process_market_pair
    self.c_process_market_pair_inner(market_pair.second, market_pair.first)
  File "hummingbot/strategy/arbitrage/arbitrage.pyx", line 345, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_process_market_pair_inner
    best_amount, best_profitability, buy_price, sell_price = self.c_find_best_profitable_amount(
  File "hummingbot/strategy/arbitrage/arbitrage.pyx", line 422, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_find_best_profitable_amount
    OrderBook buy_order_book = buy_market_trading_pair_tuple.order_book
  File "/home/ubuntu/11-loopring/hummingbot/strategy/market_trading_pair_tuple.py", line 23, in order_book
    return self.market.get_order_book(self.trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 217, in hummingbot.connector.exchange_base.ExchangeBase.get_order_book
    raise NotImplementedError
NotImplementedError
```

image

**Comment by dennisocana** [comment]
5. Some unit tests are failing in `test_loopring_market.py`:

- `test_cancel_order`
- ` test_get_fee`
- `test_place_limit_buy_and_sell`

I have 0.1714 ETH in Loopring account while running the tests.

[test_loopring_market.log](https://github.com/CoinAlpha/hummingbot/files/5255589/test_loopring_market.log)

**Comment by mborraccia** [comment]
The 5 issues listed here should be fixed with the most recent pushes.

The loopring market unit test will require USDT on the exchange (~$20 USDT)

**Comment by dennisocana** [comment]
@mborraccia I'm running into errors when running nosetests for `test_loopring_market.py`, please see error below.

```
Failure: ModuleNotFoundError (No module named 'bitstring') ... ERROR

======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'bitstring')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/11-loopring/test/integration/test_loopring_market.py", line 26, in <module>
    from hummingbot.connector.exchange.loopring.loopring_market import LoopringMarket
  File "hummingbot/connector/exchange/loopring/loopring_market.pyx", line 54, in init hummingbot.connector.exchange.loopring.loopring_market
  File "/home/ubuntu/11-loopring/hummingbot/connector/exchange/loopring/ethsnarks2/eddsa.py", line 2, in <module>
    import bitstring
ModuleNotFoundError: No module named 'bitstring'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
```

There are also conflicting files that needs to be resolved.

**Comment by mborraccia** [comment]
@dennisocana The bitstring module has been added to the pip dependencies in the environment*.yml files. Is there somewhere else those dependencies need to be listed, or perhaps your environment wasn't updated with the new dependencies?

**Comment by vic-en** [comment]
@mborraccia 


> @dennisocana The bitstring module has been added to the pip dependencies in the environment*.yml files. Is there somewhere else those dependencies need to be listed, or perhaps your environment wasn't updated with the new dependencies?

No, that's okay.

**Comment by vic-en** [comment]
@mborraccia 
To resolve the conflicts which is due to recent refactor to code in Hummingbot, you are required to do the following:
1. Rename the main market files from loopring_market.p* to loopring_exchange.p*
2. Rename the main market class from `LoopringMarket` to `LoopringExchange`
3. Remove code added to `hummingbot/client/command/connect_command.py`, `hummingbot/client/config/fee_overrides_config_map.py`, `hummingbot/connector/exchange/paper_trade/__init__.py`, `hummingbot/user/user_balances.py`
4. Move code added in `hummingbot/core/utils/market_mid_price.py` and `hummingbot/core/utils/trading_pair_fetcher.py` files as static method into the `LoopringAPIOrderBookDataSource` class located in `hummingbot/connector/exchange/loopring/loopring_api_order_book_data_source.py`
5. For codes added to `hummingbot/core/utils/estimate_fee.py` and `hummingbot/client/settings.py`, move the to a new file to be named `hummingbot/connector/exchange/loopring/loopring_utils.py`

You can use the following commits which did the above to another connector as guide:
https://github.com/CoinAlpha/hummingbot/pull/2400/commits/8d57a1fc854b2a435c37d3498c62aff5be6fc226
https://github.com/CoinAlpha/hummingbot/pull/2400/commits/cdc7c436429f2f020e8150db113da7bb6d92a3c9
https://github.com/CoinAlpha/hummingbot/pull/2400/commits/b740adbe3482d0db29521b705393e7e340413ea1

Let me know if you have any questions.

**Comment by mborraccia** [comment]
@vic-en Thanks. The modifications for those changes are up now.

**Review by dennisocana — APPROVED** [review]
Generally, the connector works and can be merged into `development` branch even with minor cosmetic errors. See summary of manual tests below.

- All unit tests in `test_loopring_market.py` passed
- Connected API keys without problems
- Balances are showing correctly
- Created pure market making strategy config file and went through all prompts without errors
- No issues or network errors in logs running a basic pure-mm strategy on ETH-USDT market with single orders per side, 1 minute order refresh time, disabled refresh tolerance to see how it reacts when orders are always cancelled and created all the time
- Available balance is updated correctly when there are active orders
- Ran the strategy for 2 hours with 10 seconds refresh time, 2 order levels, inventory skew of 50% and refresh tolerance of 0.01%
- No major issues, **only intermittent error message “Issue with Loopring API GET to /api/v2/order” in the logs when orders are not cancelled because they are within the tolerable change in spreads**
- Also no orders getting stuck in the exchange (uncancelled)
- Executed 5 trades without errors and matches the same in the exchange’s fill history
- **Cosmetic bug where start price shows in 13 decimal values**
- Prices of orders created are quantized properly **but the prices in `history` output are not which makes it difficult to compare trades on the exchange**
- Order book in sync in both client and exchange
- Working with all price reference types (last trade, best bid/ask, last own trade)
- Works on paper trade mode with pure market making, cross exchange and arbitrage

**Review by Nullably — APPROVED** [review]
The overall code looks good to me.  I didn't review the `ethsnarks2` module as I barely understood what it does. 

There are a few minor issues which can be fixed/considered later
- Should the `ethsnarks2` be an installable package?
- There are many places where the code doesn't follow PEP8 coding convention.
- There are a number of Todos left, should they be addressed?

**Pull request merged**
