### PR TITLE
feat / tokocrypto connector

### PR DESCRIPTION
**Pull request by Tokocrypto**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

First commit for Tokocrypto connector for hummingbot. 

Founded in June 2017, Tokocrypto was born from a crypto fan group with strong confidence in the examples and benefits that blockchain technology can offer to the public. Tokocrypto aims to be Southeast Asia's leading exchange for digital assets by providing customers with an easy, simple, instant, and secure platform to transact with confidence. Furthermore, Tokocryoto aims to be a community center for members of the crypto world to gather together, allowing for the sharing of technical knowledge and expertise and championing new ideas.

### CODE REVIEW

**Comment by dennisocana** [comment]
After today's discussion with @keithbaum , this connector is not yet ready for QA testing. Changing status from Open to Draft.

**Comment by keithbaum** [comment]
Moving PR from draft to ready for review after initial successful testing

**Comment by RC-13** [comment]
Unable to proceed further testing, immediately encounter failure to submit orders.
```
2021-03-19 15:39:06,274 - 10652 - hummingbot.connector.exchange.tokocrypto.tokocrypto_exchange - NETWORK - Error submitting BUY LIMIT_MAKER order to Tokocrypto for 0.01200000 ETH-USDT 1780.89000000.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/tokocrypto/tokocrypto_exchange.pyx", line 729, in hummingbot.connector.exchange.tokocrypto.tokocrypto_exchange.TokocryptoExchange.create_order
    exchange_order_id = str(order_result["orderId"])
KeyError: 'orderId'
2021-03-19 15:39:06,278 - 10652 - hummingbot.connector.exchange.tokocrypto.tokocrypto_exchange - WARNING - 'orderId'
```
Screen Shot 2021-03-19 at 3 43 04 PM

**Comment by RC-13** [comment]
Looping in @Tokocrypto for the reported issue above

**Comment by RC-13** [comment]
- Initial reported issue is confirmed fixed. However, submitted order fails to be cancelled during refresh period which prevents us from continuing the test. Upon checking the logs, there are no successful call during cancellation process.

sample order which fails to be cancelled, order refresh time is set to 60 sec with order_refresh_tolerance_pct disabled
Screen Shot 2021-03-24 at 2 26 44 PM
Screen Shot 2021-03-24 at 2 29 32 PM
[logs_conf_pure_mm_2.log](https://github.com/CoinAlpha/hummingbot/files/6194889/logs_conf_pure_mm_2.log)



- Is it possible to use `bid` and `ask` instead of `0` and `1` on the logging message when an order is created to avoid confusion?
Screen Shot 2021-03-24 at 2 20 43 PM
Screen Shot 2021-03-24 at 2 19 30 PM

**Comment by RC-13** [comment]
@Tokocrypto Kindly please check the reported issues, thank you.

**Comment by dennisocana** [comment]
No recent updates on this branch with critical issues that needs to be addressed. Moving to next release.

**Comment by dennisocana** [comment]
Connector is incomplete and outdated. Closing for now due to no progress for four months. Feel free to reopen when work will be resumed for this connector.

**Pull request closed without merging**
