### PR TITLE
(fix) `hummingbot_quickstart.py` blocked by confirmation prompt

### PR DESCRIPTION
**Pull request by CrimsonJacket**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

Resolves [sc-27351]

**Tests performed by the developer**:
Add additional initialisation parameter for `HummingbotApplication` that will be used to determine if confirmation prompt is necessary

**Tips for QA testing**:
Running `hummingbot_quickstart.py` with a gateway-supported strategy would no longer be blocked by the confirmation prompt.

### CODE REVIEW

**Comment by gerald-hb** [comment]
Hi @CrimsonJacket I can see that it imports the strategy and connected to gateway automatically. Only seeing this error on the log pane, aside from this, it seems to work fine.
image

Also getting this error on the logs
```
2022-07-01 20:08:31,180 - 12276 - hummingbot.core.gateway.status_monitor - INFO - Connection to Gateway established.
2022-07-01 20:13:41,595 - 12357 - hummingbot.client.ui.hummingbot_cli - ERROR - Unhandled error in prompt_toolkit: 'weakref' object has no attribute 'client_config_map'
NoneType: None
```

Steps to reproduce
1.Setup gateway and create a strategy (amm_arb)
2.exit the bot
3.run `bin/hummingbot_quickstart.py -f ammtest.yml -p <password>`
[logs_hummingbot.log](https://github.com/CoinAlpha/hummingbot/files/9029505/logs_hummingbot.log)
[ammtest.zip](https://github.com/CoinAlpha/hummingbot/files/9029520/ammtest.zip)

**Comment by petioptrv** [comment]
Changes LGTM with re to the configs.

Re the issue, is the desired behaviour that we always avoid this check when running through quickstart? The way I understand it, we want to have the check when starting manually, but not have it when quickstarting; so if we run a bot through quickstart, but then we manually stop it, make changes and start again manually, we want the prompt to go off.

If that's the case, I think we can achieve it by passing an arg to `start_command` and pass it down from `hummingbot_quickstart.py` via `HummingbotApplication.run` -> `HummingbotCLI.run` -> `HummingbotCLI.did_start_ui` -> `HummingbotCLI.trigger_event` and to the `UIStartListener`, which calls the start command.

This way, if the start command is afterwards called from the UI, it defaults to asking for confirmation

**Review by rxlxrxsx — APPROVED** [review]
Tested and confirmed working by QA.

- Clone and install branch
- Successfully created a gateway image
- Successfully created a gateway container after running gateway create
- Create an amm_arb strategy to be used for hummingbot quickstart
- Successfully executed bin/hummingbot_quickstart.py without issues and confirmed that amm_arb strategy is no longer blocked by the confirmation and proceeds to run the strategy properly
- Tested on other strategies as well and confirmed working

**Review by petioptrv — APPROVED** [review]
Changes LGTM!

**Comment by PtrckM** [comment]
@CrimsonJacket still LGTM! behavior and expectation achieved!!!

**Review by PtrckM — APPROVED** [review]

**Comment by CrimsonJacket** [comment]
Closed and re-created PR on Foundation.
Foundation PR: https://github.com/hummingbot/hummingbot/pull/5490
Snapshot URL: https://snapshot.org/#/hbot-prp.eth/proposal/0xa20c501250a110d4630bb96d04aa24c8ebc7c3d5a428f8e3927e18515f3b9049

**Pull request closed without merging**
