### PR TITLE
fix / Bittrex unable to place orders with low prices

### PR DESCRIPTION
**Pull request by CrimsonJacket**
**Before submitting this PR, please make sure**:
- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue:
#1032 
- Related Clubhouse Story:

**A description of the changes proposed in the pull request**:

Bug #1032: 
Placing orders with extremely low prices(`3.17E-7`) on Bittrex would fail.

Current Fix:
Enforce f-string literals when crafting signatures and request parameters.

### CODE REVIEW

**Comment by yzhang1994** [comment]
@CrimsonJacket If you are just fixing a bug in Bittrex, might not be a good idea to change the other market connectors. Is there a reason why they need to be changed?

**Comment by CrimsonJacket** [comment]
> @CrimsonJacket If you are just fixing a bug in Bittrex, might not be a good idea to change the other market connectors. Is there a reason why they need to be changed?

This bug potentially affects other connectors considering that they use `Decimal` for price. I did make sure to test that placing of orders across the connectors still works.

**Comment by martinkou** [comment]
Discussed this w/ Daniel last week. The `str({decimal object})` method has a problem that it'll output scientific notation when the decimal value is too small. That, as I understand, is a problem for all exchange APIs.

One superficially risky change here is changing the output type of price and size from float to str in Coinbase Pro connector. But according to their API specs, that's actually correct as they expect a string there.

**Comment by martinkou** [comment]
I think I'd merge this and then allow for testing on Friday.

**Pull request merged**
