### PR TITLE
deprecate api key

### PR DESCRIPTION
**Pull request by vic-en**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This pr deprecates Dexalot's api key.
[ch39631]

**Tests performed by the developer**:
- Reconnecting Dexalot connector.

**Tips for QA testing**:
- Perform end-to-end testing with client pr - https://github.com/CoinAlpha/gateway/pull/18

### CODE REVIEW

**Comment by rxlxrxsx** [comment]
Test run: https://hummingbot.testrail.io/index.php?/runs/view/4286

**Review by aarmoa — APPROVED** [review]
Changes look good to me

**Review by rxlxrxsx — APPROVED** [review]
Tested and confirmed working by QA.

- Successfully cloned and installed the branch
- Successfully setup and ran gateway
- Connected dexalot and confirmed working as expected, both with and without the API keys used
- Created and run a pure_mm strategy using dexalot and confirmed working as expected

**Comment by vic-en** [comment]
closing in favour of https://github.com/hummingbot/hummingbot/pull/6271

**Pull request closed without merging**
