### PR TITLE
Feat / script

### PR DESCRIPTION
**Pull request by Nullably**
**Before submitting this PR, please make sure**:
- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue:
- Related Clubhouse Story: 9199

**A description of the changes proposed in the pull request**:
- As per Clubhouse story requirement.

### CODE REVIEW

**Comment by Nullably** [comment]
retest this please.

**Comment by Nullably** [comment]
retest this please.

**Comment by Nullably** [comment]
retest this please.

**Comment by martinkou** [comment]
LGTM. The queue polling logic can be improved - e.g. by setting a different event loop in the child process and using `run_in_executor()` to do get `queue.get()`. But I think we can leave that for later.

**Pull request merged**
