### PR TITLE
(refactor) Refactor RateOracle to extract the rate sources

### PR DESCRIPTION
**Pull request by petioptrv**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

This PR mostly ports the changes introduced by (https://github.com/CoinAlpha/hummingbot-professional/pull/51).

It was adapted to work with the Pydantic configs. The most notable/controversial changes would be the inclusion of the client config map for the liquidity mining start routine.

**Tests performed by the developer**:

- Tests cases for all changes.

**Tips for QA testing**:

Please make sure that full extent of the rate command works as expected, including the option to set additional CoiGecko tokens to track.

[ch-28938]

### CODE REVIEW

**Comment by Deepali6997** [comment]
hi @petioptrv while giving coingecko as rate_oracle_source we can see that log-pane shows following message in the loog-pane.

Screenshot 2022-07-21 at 8 06 14 PM

Post that, when checking global configs the parameter rate_oracle_source remains unchanged

**Comment by petioptrv** [comment]
@Deepali6997, I have resolved the issue you spotted

**Review by Deepali6997 — APPROVED** [review]
Test Summary

Tested along side @PtrckM and found no issues. The PR can be approved now. Below is the testing that was done on the feature branch.

- Successful installation of branch
- Changing rate_oracle_source to the following connectors and then checking rate --pair and rate --token values (Tested connectors are : Binance, Kucoin, Ascendex, Coingecko)
- Created a xemm strategy and test all rate-oracle source and check conversion
- Set a market pair that has a low market cap and high market cap and started the strategy
- Verified that rate is shown/given
- Configured global_token_symbol (no validator, expected behavior)
- Ran balance command and checked if modified global_token_symbol is reflected
- Configured global_token
- Ran balance command and checked if modified global_token is reflected

**Review by CrimsonJacket — APPROVED** [review]
Changes LGTM

**Comment by petioptrv** [comment]
Closing to re-open towards foundation:

**Pull request closed without merging**
