### PR TITLE
Feat/simplify uniswap v3

### PR DESCRIPTION
**Pull request by vic-en**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
- Strategy doesn't remove positions and doesn't perform swaps anymore. It just keeps adding positions as the market moves.

- Configs related to volatility have been disabled and wouldn't be prompted by default.

- Id of restored orders is now displayed:
restore lp orders

- Bot now detects and removes orders that are manually closed on uniswap web app:
dectect closed orders

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Comment by RC-13** [comment]
- Tested this PR together with gateway PR `Feat/simplify uniswap v3 #119` however it fails to recognized or fails to connect to localhost. If you check the gateway logs, it doesn't throw any error.
- Test this PR using gateway PR `test/add_test_script_for_uniswap_v3` and `development` branch: Successfully connect to local host
        * Confirm orderID are now displayed whenever a position is open or added
        * Confirm that new liquidity/position is added and existing position are not remove if the market move.	
        * Manually delete position from Uniswap app: On the hummingbot client, a log message shows that the orderID has been closed.
         * Restart strategy (stop/start and restarting client):  restores order and displays the orderID
        * Confirm no longer getting volatility message in the logs
- However whenever a network issue occurs `Could not fetch balances from Gateway API` it fails to detect change in price and as well as fails to detect the status of a position (closed). Restarting strategy is required to detect the changes.
image
image
- There are instances as well the the orderID shows `None` (encountered by @PtrckM)
image

**Comment by dennisocana** [comment]
This is 2/3 pull requests we want to merge in the staging phase to be included in this upcoming Friday's release. These are changes in the HB client side for https://github.com/CoinAlpha/gateway-api/pull/119.

Adding QA as approver to sign-off before merging this in.

**Review by RC-13 — CHANGES_REQUESTED** [review]
- Tested this PR together with gateway PR `Feat/simplify uniswap v3 #119` however it fails to recognized or fails to connect to localhost. If you check the gateway logs, it doesn't throw any error.
- Test this PR using gateway PR `test/add_test_script_for_uniswap_v3` and `development` branch: Successfully connect to local host
        * Confirm orderID are now displayed whenever a position is open or added
        * Confirm that new liquidity/position is added and existing position are not remove if the market move.	
        * Manually delete position from Uniswap app: On the hummingbot client, a log message shows that the orderID has been closed.
         * Restart strategy (stop/start and restarting client):  restores order and displays the orderID
        * Confirm no longer getting volatility message in the logs
- However whenever a network issue occurs `Could not fetch balances from Gateway API` it fails to detect change in price and as well as fails to detect the status of a position (closed). Restarting strategy is required to detect the changes.
image
image
- There are instances as well the the orderID shows `None` (encountered by @PtrckM)
image
Note: Test is done using KOVAN network

**Review by RC-13 — APPROVED** [review]

**Comment by RC-13** [comment]
As discussed on the client standup, the reported behavior are not covered in these PR and they will be covered in gateway v2.

**Review by mifeng — APPROVED** [review]

**Pull request merged**
