### PR TITLE
refactor/ rename Bitmax -> AscendEx

### PR DESCRIPTION
**Pull request by CrimsonJacket**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

Since [BitMax has rebrand itself as AscendEX](https://bitmax.io/en/help-center/articles/1500004514341).
This PR should update the necessary components to reflect this change.

### CODE REVIEW

**Comment by RC-13** [comment]
Getting the following error when connecting API key:
image
```ruby
2021-03-29 11:16:55,579 - 3495 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: cannot import name 'getWsUrlPriv' from 'hummingbot.connector.exchange.ascend_ex.ascend_ex_constants' (/home/clint_g/hbot-new/hummingbot/connector/exchange/ascend_ex/ascend_ex_constants.py)
Traceback (most recent call last):
  File "/home/clint_g/hbot-new/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/clint_g/hbot-new/hummingbot/client/command/connect_command.py", line 76, in show_connections
    df, failed_msgs = await self.connection_df()
  File "/home/clint_g/hbot-new/hummingbot/client/command/connect_command.py", line 88, in connection_df
    err_msgs = await UserBalances.instance().update_exchanges(reconnect=True)
  File "/home/clint_g/hbot-new/hummingbot/user/user_balances.py", line 87, in update_exchanges
    results = await safe_gather(*tasks)
  File "/home/clint_g/hbot-new/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/clint_g/hbot-new/hummingbot/user/user_balances.py", line 70, in update_exchange_balance
    return await self.add_exchange(exchange, **api_keys)
  File "/home/clint_g/hbot-new/hummingbot/user/user_balances.py", line 53, in add_exchange
    market = UserBalances.connect_market(exchange, **api_details)
  File "/home/clint_g/hbot-new/hummingbot/user/user_balances.py", line 24, in connect_market
    connector_class = get_connector_class(exchange)
  File "/home/clint_g/hbot-new/hummingbot/client/config/config_helpers.py", line 208, in get_connector_class
    mod = __import__(conn_setting.module_path(),
  File "/home/clint_g/hbot-new/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 40, in <module>
    from hummingbot.connector.exchange.ascend_ex.ascend_ex_user_stream_tracker import AscendExUserStreamTracker
  File "/home/clint_g/hbot-new/hummingbot/connector/exchange/ascend_ex/ascend_ex_user_stream_tracker.py", line 10, in <module>
    from hummingbot.connector.exchange.ascend_ex.ascend_ex_api_user_stream_data_source import \
  File "/home/clint_g/hbot-new/hummingbot/connector/exchange/ascend_ex/ascend_ex_api_user_stream_data_source.py", line 13, in <module>
    from hummingbot.connector.exchange.ascend_ex.ascend_ex_constants import REST_URL, getWsUrlPriv, PONG_PAYLOAD
ImportError: cannot import name 'getWsUrlPriv' from 'hummingbot.connector.exchange.ascend_ex.ascend_ex_constants' (/home/clint_g/hbot-new/hummingbot/connector/exchange/ascend_ex/ascend_ex_constants.py)
```

**Comment by RC-13** [comment]
- Confirming that the reported issue above has been fixed.
- Additional issue encountered: the best prices and order book are out of synced/delayed.
best bid
best bid and ask
ascendex-orderbook

**Comment by dennisocana** [comment]
After today's discussion, @CrimsonJacket will investigate whether the issue with order book prices being delayed is related to the changes in this PR. If not, we will fix on a separate story and merge in this connector.

**Review by RC-13 — APPROVED** [review]
As of today's client stand up, we will open a separate issue for the delay problem. No other error encountered on the long term test bot.

**Review by keithbaum — APPROVED** [review]
Change looks ok

**Pull request merged**
