### PR TITLE
Refactor / Refactor common price delegate classes to strategy root - PMM + PerpMM

### PR DESCRIPTION
**Pull request by TheHolyRoger**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
As discussed in https://github.com/CoinAlpha/hummingbot/pull/3123 and https://github.com/CoinAlpha/hummingbot/pull/2865
This refactors the asset price delegate classes to `strategy` root so that they can be re-used in more strategies.

### CODE REVIEW

**Comment by TheHolyRoger** [comment]
@Nullably @phbrgnomo if you could take a look please :)

**Comment by TheHolyRoger** [comment]
@CrimsonJacket  @dennisocana this one could make it in for 0.38 imo, it's just a refactor/consolidation

**Comment by dennisocana** [comment]
The required unit tests are in this pull request https://github.com/CoinAlpha/hummingbot/pull/3447 so right now that's a blocker in reviewing this.

image

**Review by Nullably — APPROVED** [review]
LGTM

**Comment by Nullably** [comment]
@RC-13 Can you please test pure market making and perpetual market making strategies, specifically when `external_market` price source is configured.

**Review by rapcmia — APPROVED** [review]
Tested price source (external markets) and price types for both PMM and PerpMM and confirmed all ok by QA.

**Comment by dennisocana** [comment]
Thanks @TheHolyRoger for contributing!

**Pull request merged**
