### PR TITLE
[v0.38] Fix / OrderBookTracker debug logging substitutions

### PR DESCRIPTION
**Pull request by TheHolyRoger**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
At some point logger was changed and all these substitutions don't work, they just print %s, %d etc in the debug log. Fixing them in this PR.

### CODE REVIEW

**Review by CrimsonJacket — CHANGES_REQUESTED** [review]
@TheHolyRoger Note that we have renamed BitMax -> AscendEX. Hence the conflict. Overall the PR looks good but do make the necessary fixes for the conflict.

**Comment by TheHolyRoger** [comment]
@CrimsonJacket done now thanks!

**Review by dennisocana — APPROVED** [review]
According to @CrimsonJacket PR looks good overall. Since the file conflicts have already been addressed and thorough testing is not required for this fix, adding approval to this PR.

**Review by CrimsonJacket — APPROVED** [review]
LGTM!

**Pull request merged**
