### PR TITLE
refactor / move wings.model to hummingbot.core.model

### PR DESCRIPTION
**Pull request by yzhang1994**
**Before submitting this PR, please make sure**:
- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**A description of the changes proposed in the pull request**:
move wings.model to hummingbot.core.model

### CODE REVIEW

**Comment by martinkou** [comment]
If you do a grep of all the dependencies with `wings.model`, it's all about the SQLConnectionManager, local cluster order book data, and hummingsim.

I'd recommend removing the local cluster order book data altogether - since nobody is using them anymore. This means we can then cleanly move the whole `wings.model` module to hummingsim.

**Comment by martinkou** [comment]
Also, a note about making changes to hummingsim - even though we haven't set up any CI on hummingsim... you should make sure any change made to hummingsim would at least compile.

**Comment by yzhang1994** [comment]
@martinkou Ok will make those changes.

I should have marked the hummingsim PR -- it is meant to work after all 3 PRs for in the currently hummingbot repo have been merged.  Once those changes have been confirmed, will re-edit the hummingsim PR.

**Comment by martinkou** [comment]
I'm going to update merge your patch on hummingsim side and then bump the hummingsim versions to make the CI work.

**Pull request merged**
