### PR TITLE
doc/upcoming change in LM terms

### PR DESCRIPTION
**Pull request by RC-13**
**Before submitting this PR, please make sure**:
- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue:
- Related Clubhouse Story:

**A description of the changes proposed in the pull request**:
Update upcoming change in liquidity mining terms:
image
image

### CODE REVIEW

**Comment by RC-13** [comment]
Set reward to USDT
image

**Review by mifeng — COMMENTED** [review]
We should write in Markdown wherever possible for better future portability. 

Please change all HTML to Markdown where possible.

**Review by mifeng — CHANGES_REQUESTED** [review]
see comment above

**Comment by dennisocana** [comment]
Closing w.r.t. https://github.com/CoinAlpha/hummingbot/pull/2403

**Pull request closed without merging**
