### PR TITLE
[v0.38] Fix / HitBTC Balance updates and tests for USD/USDT

### LINKED ISSUE #3160: HitBTC - USDT balance no longer recognize
**Describe the bug**
The USDT balance is no longer recognize. Since HitBTC labels USD as USDT,  I think this  PR (https://github.com/CoinAlpha/hummingbot/pull/3124)  alters how bot check the USDT asset.
Hitbtc

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Update to the latest development commit
2. Create PMM strategy using HitBTC as a connector
3.  Set any USDT market pair
4.  Start strategy and run the status command
5. Run balance command and compare the USD and USDT asset
...

**Release version**
0.38.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

### PR DESCRIPTION
**Pull request by TheHolyRoger**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Fixes #3160

### CODE REVIEW

**Comment by TheHolyRoger** [comment]
@RC-13 @dennisocana if you could test please?

**Review by RC-13 — DISMISSED** [review]
Confirming fix, tested on different USDT markets and the bot was able to recognize the balance and place orders accordingly.
Screen Shot 2021-04-05 at 10 33 39 PM

**Review by dennisocana — DISMISSED** [review]

**Comment by TheHolyRoger** [comment]
Sorry @dennisocana !

**Review by RC-13 — APPROVED** [review]
Re-approving PR

**Pull request merged**
