### PR TITLE
Feat / connect and balance command

### PR DESCRIPTION
**Pull request by Nullably**
**Before submitting this PR, please make sure**:
- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue:
- Related Clubhouse Story: 8086, 8125

**A description of the changes proposed in the pull request**:
- Add connect and balance command
- connect without an argument shows all current exchanges connections
- If connection failed, the reason is displayed.

### CODE REVIEW

**Comment by Nullably** [comment]
run tests

**Comment by Nullably** [comment]
run tests

**Comment by mifeng** [comment]
1. `connect`: what is the difference between **Keys Saved** and **Connected**?
Screen Shot 2020-04-06 at 5 39 46 PM

2. `balance`: this is a really useful command. are you using the price feeds to calculate the USD rate? what happens if an asset doesn't have the price feed available?

**Comment by mifeng** [comment]
For `balance`, please sort the dataframe so that it's descending based on USD value.

**Comment by Nullably** [comment]
> 1. `connect`: what is the difference between **Keys Saved** and **Connected**?

Keys Saved is whether the user has provided api key/secret through connect/config command.
Connected is whether the connection can be made from those keys, though connection could fail for other reason, e.g. an exchange down, ip address not white listed...
> 2. `balance`: this is a really useful command. are you using the price feeds to calculate the USD rate? what happens if an asset doesn't have the price feed available?

For the USD value, likely it is from CoinGecko, if the conversion not available it shows zero.

**Comment by mifeng** [comment]
In the medium term, we should add the user's Ethereum wallet as well to `balance` so that if the user trades on DEXs they can see how that compares.

However, currently users can import/create multiple Ethereum wallets into Hummingbot. Before we add wallets to `balance`, I think we should restrict users to only have a single ETH wallet in Hummingbot. This allows us to treat wallets and exchange accounts similarly.

**Comment by mifeng** [comment]
>Keys Saved is whether the user has provided api key/secret through connect/config command.
Connected is whether the connection can be made from those keys, though connection could fail for other reason, e.g. an exchange down, ip address not white listed...

I see - please change the column headings to "Keys Added" and "Keys Confirmed". Also, insert a newline before **Failed connections:** to separate that from the table a bit more.

**Comment by mifeng** [comment]
Remove the following exchanges from `connect` and `balance`, since they are Ethereum DEXs that use the balance in the user's wallet:
`radar_relay`
`dolomite`
`bamboo_relay`

Also, please remove `bitcoin_com` since we're not officially supporting them

**Comment by Nullably** [comment]
> In the medium term, we should add the user's Ethereum wallet as well to balance so that if the user trades on DEXs they can see how that compares.

Looks like it's gonna be a fair bit of work on the design and implementation for Ethereum wallet and DEXs, let's leave them for another PR?

> I see - please change the column headings to "Keys Added" and "Keys Confirmed". Also, insert a newline before Failed connections: to separate that from the table a bit more.

Done

> For balance, please sort the dataframe so that it's descending based on USD value.

Done, both Token and Exchanges are now sorted based on their total USD value.

> Remove the following exchanges from connect and balance, since they are Ethereum DEXs that use the balance in the user's wallet:

Done

**Comment by mifeng** [comment]
>Looks like it's gonna be a fair bit of work on the design and implementation for Ethereum wallet and DEXs, let's leave them for another PR?

Definitely - just wanted to highlight that as something that we'll do in the future.

**Comment by Nullably** [comment]
run tests

**Pull request merged**
