### PR TITLE
[v0.34] feat/dydx connector

### PR DESCRIPTION
**Pull request by trkoneill18**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**After creating this PR, please make sure:**

- [ ] You link the related GitHub issue or ticket

**A description of the changes proposed in the pull request**:
Adds dydx.exchange connector

### CODE REVIEW

**Comment by RC-13** [comment]
PR tested by QA and here are the issues encountered:
1)  Auto complete list of available trading pairs is not available and,
 2) currently it doesn't have trading pair validator resulting to accepting any input.
market
market1

**Comment by RC-13** [comment]
3. Slight delay when starting (during market initialization) and stopping strategy, approximately 10 sec delay.
delay
delay1

**Comment by RC-13** [comment]
4. Duplicated lines for `Not enough balance` when the order_amount is  adjusted or doesn't have enough balance to place order on one side.
duplicated lines on log
[logs_dydx-test.log](https://github.com/CoinAlpha/hummingbot/files/5649820/logs_dydx-test.log)

**Comment by trkoneill18** [comment]
I have addressed the above problems. The fetch trading pairs function was not working in the previous push, which caused the first two issues. The other two were mostly a result of a problem with the connection to the websocket, resulting in slow event responses.

**Comment by RC-13** [comment]
@trkoneill18 Thanks for the explanation. Re-tested and confirm that initial issues reported has been address. 

Though, I believe the connector currently supports spot market only. Should it be best to hide perpetual markets and add them back in the future? 
dydx market list
Using this any of the perpetual market pairs results to the following error message:
```
2020-12-10 12:44:17,536 - 5774 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: None
Traceback (most recent call last):
  File "/home/clint_g/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/clint_g/hummingbot/hummingbot/core/data_type/order_book_tracker.py", line 178, in _init_order_books
    self._order_books[trading_pair] = await self._data_source.get_new_order_book(trading_pair)
  File "/home/clint_g/hummingbot/hummingbot/connector/exchange/dydx/dydx_api_order_book_data_source.py", line 117, in get_new_order_book
    bids, asks = self.active_order_tracker.convert_snapshot_message_to_order_book_row(snapshot_msg)
  File "hummingbot/connector/exchange/dydx/dydx_active_order_tracker.pyx", line 239, in hummingbot.connector.exchange.dydx.dydx_active_order_tracker.DydxActiveOrderTracker.convert_snapshot_message_to_order_book_row
    np_bids, np_asks = self.c_convert_snapshot_message_to_np_arrays(message)
  File "hummingbot/connector/exchange/dydx/dydx_active_order_tracker.pyx", line 66, in hummingbot.connector.exchange.dydx.dydx_active_order_tracker.DydxActiveOrderTracker.c_convert_snapshot_message_to_np_arrays
    price, amount = self.get_rates_and_quantities(float(bid_order["price"]), float(bid_order["amount"]), message.content["market"])
  File "hummingbot/connector/exchange/dydx/dydx_active_order_tracker.pyx", line 122, in hummingbot.connector.exchange.dydx.dydx_active_order_tracker.DydxActiveOrderTracker.get_rates_and_quantities
    new_price = float(self.token_configuration.unpad_price(price, basetokenid, quotetokenid))
  File "/home/clint_g/hummingbot/hummingbot/connector/exchange/dydx/dydx_api_token_configuration_data_source.py", line 84, in unpad_price
    return Decimal(price) * Decimal(f"1e{self._digits[quote_id] - self._digits[base_id]}")
KeyError: None
```
[logs_dydx-test.log](https://github.com/CoinAlpha/hummingbot/files/5670359/logs_dydx-test.log)

**Comment by PtrckM** [comment]
Cosmetic bug when using USDC, USDC price display differs with exchange
- DAI-USDC
image
image

- WETH-USDC
image
image

-logs
[logs_dai_usdc.log](https://github.com/CoinAlpha/hummingbot/files/5670608/logs_dai_usdc.log)
[logs_weth_usdc.log](https://github.com/CoinAlpha/hummingbot/files/5670609/logs_weth_usdc.log)

**Comment by RC-13** [comment]
The fix for the cosmetic issue with USDC market appears to cause another problem with the order price on the exchange.
The price is now showing correctly on the bot however, it differs on the exchange, the precision change causing the order price to become so large and putting the order at bottom of the order_book.
dydx exchange price

**Comment by RC-13** [comment]
The fix for the cosmetic bug for USDC market seems to open a new issue with the price precision on the dydx exchange.
The price shows correctly on the bot however on the exchange, the price becomes so large and putting the order at the bottom of the order book
dydx exchange price

**Comment by trkoneill18** [comment]
I believe that both the price display and actually pricing are working properly now.

**Comment by PtrckM** [comment]
@trkoneill18 thank you for fixing the price display however we found minor issue but only when using `WETH-USDC` the last trade is out of sync and/or the value is differ from the exchange. Both `DAI-USDC` and `WETH-DAI` not affected.

image
image

**Review by Nullably — APPROVED** [review]
LGTM

**Pull request merged**
