### PR TITLE
fix/binance perpetual order fill amount bug

### PR DESCRIPTION
**Pull request by aarmoa**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Fix to the issue https://github.com/hummingbot/hummingbot/issues/5170 by correctly parsing the trade fill event from the connector and reading the fill amount for the particular trade instead of the accumulated quantity field.

**Tests performed by the developer**:
All unit tests passing in green

**Tips for QA testing**:
To validate the fix is working it is important to check the total amount filled for an order when there is at least one partial fill.

[ch-24364]

### CODE REVIEW

**Comment by RC-13** [comment]
Test update:
- Was able to capture partial fills for both open and close positions and confirmed that the total amount displayed in the client and log pane are correct.
- Still running additional tests and attempting to capture more partial fills.

**Review by mhrvth — APPROVED** [review]
LGTM

**Review by RC-13 — APPROVED** [review]
LGTM!

Test summary:
- Install feature branch and test the connector using perpetual market-making strategy.
- Leave the bot running to capture a partial fill both for open and close positions
- Checked the total order amount of the partially filled orders by running the history verbose command and confirmed that the total amount is equal to the specified order amount value.
- Leave the bot running for more than 24 hours and inspect the filled record after, 4 partial fill took place, and confirm that the total order amount is equal to the specified value in the order_amount parameter.
- Review the logs and confirmed that 
  -  When a partial fill takes place, then the remaining get filled right after, the total amount is correct
   - When partial fill takes place then the remaining gets canceled, the next order created will have a size equal to the remaining unfilled order to make sure that the total amount is still correct.

**Comment by aarmoa** [comment]
Closing the PR after re-creating it in the foundation repo https://github.com/hummingbot/hummingbot/pull/5183

**Pull request closed without merging**
