### PR TITLE
feat/separate order update from order fill in order tracker

### PR DESCRIPTION
**Pull request by aarmoa**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This PR includes 3 changes:
- Separate the logic in the client order tracker and the generic inflight order to process trade fills separate from the order update. The correct way to use the trade fill now is to process a TradeUpdate. A trade fill will not be automatically generated any more when processing an OrderUpdate.
- Improve the client order tracker to not process an OrderUpdate that will mark the order as completely filled until all fill updates have been processed (until the order is filled regarding the amount too). This is to avoid errors in the order complete event in exchanges that send the order complete event before the last order fill event.
- Include information about already processed order fills when storing an order as JSON, and when recovering it from JSON, to avoid processing repeated fills twice in a recovered order.

**Tests performed by the developer**:
Added new unit tests. Also executed manually a client using Binance and PMM.

**Tips for QA testing**:
The change will affect more the connectors where the client order tracker is being used: Binance, Binance Perpetual and AscendEx.
But in the PR we have moved some basic classes to other modules. If possible please do a basic check (just validate that strategy starts without problems) using all connectors.

[ch22010]

### CODE REVIEW

**Comment by RC-13** [comment]
- Using the AscendEX connector, the client fails to recognize that a filled event has taken place. During the fill event, the bot throws a message in the logs indicating that the order has failed. 
Affected order: `HMBot-SLRCUSD1644296080003594`
```python
2022-02-08 12:55:10,176 - 13355 - hummingbot.connector.client_order_tracker - INFO - Order HMBot-SLRCUSD1644296080003594 has failed. Order Update: OrderUpdate(trading_pair='LRC/USDT', update_timestamp=1644296110178, new_state=<OrderState.FAILED: 6>, client_order_id=None, exchange_order_id='HMBot17ed7af0a84U9496830767n4qti', trade_id=None, fill_price=Decimal('0'), executed_amount_base=Decimal('0'), executed_amount_quote=Decimal('0'), fee_asset='USDT', cumulative_fee_paid=Decimal('0'))

```
image
image
image
[ascendex-lrc-usdt.zip](https://github.com/CoinAlpha/hummingbot/files/8021131/ascendex-lrc-usdt.zip)

**Comment by PtrckM** [comment]
- using amm_arb on uniswap and balancer getting same error during trading started `04:11:57 - async_utils - Unhandled error in background task: Could not find the exchange rate for ETH-DAI using the RateOracle (please validate it is active) (See log file for stack trace dump)`
   - trying changing `rate_oracle_source` still getting error during start.

image

image

```
2022-02-08 04:12:23,848 - 1 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Could not find the exchange rate for ETH-DAI using the RateOracle (please validate it is active)
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/hummingbot/hummingbot/strategy/amm_arb/amm_arb.py", line 133, in main
    arb_proposals = [
  File "/home/hummingbot/hummingbot/strategy/amm_arb/amm_arb.py", line 135, in <listcomp>
    if t.profit_pct(
  File "/home/hummingbot/hummingbot/strategy/amm_arb/data_types.py", line 96, in profit_pct
    buy_fee_amount = buy_trade_fee.fee_amount_in_token(buy.market_info.trading_pair,
  File "/home/hummingbot/hummingbot/core/data_type/trade_fee.py", line 155, in fee_amount_in_token
    conversion_rate = self._get_exchange_rate(conversion_pair, exchange) if token is not None else Decimal(1)
  File "/home/hummingbot/hummingbot/core/data_type/trade_fee.py", line 197, in _get_exchange_rate
    raise ValueError(f"Could not find the exchange rate for {trading_pair} using the RateOracle "
ValueError: Could not find the exchange rate for ETH-DAI using the RateOracle (please validate it is active)
```

-logs and config 
[uniswap_balancer.zip](https://github.com/CoinAlpha/hummingbot/files/8021181/uniswap_balancer.zip)


- getting multiple errors after starting a pure_mm on binance
image

- 1> `ERROR - Unexpected error in user stream listener loop.`

```
2022-02-08 01:46:37,263 - 16417 - hummingbot.connector.exchange.binance.binance_exchange - ERROR - Unexpected error in user stream listener loop.
Traceback (most recent call last):
  File "/home/ubuntu/separate/hummingbot/connector/exchange/binance/binance_exchange.py", line 739, in _user_stream_event_listener
    self._order_tracker.process_trade_update(trade_update)
  File "/home/ubuntu/separate/hummingbot/connector/client_order_tracker.py", line 298, in process_trade_update
    updated: bool = tracked_order.update_with_trade_update(trade_update, connector=self._connector)
  File "/home/ubuntu/separate/hummingbot/core/data_type/in_flight_order.py", line 341, in update_with_trade_update
    fee_paid: Decimal = trade_update.fee.fee_amount_in_token(
  File "/home/ubuntu/separate/hummingbot/core/data_type/trade_fee.py", line 151, in fee_amount_in_token
    conversion_rate = self._get_exchange_rate(conversion_pair, exchange) if token is not None else Decimal(1)
  File "/home/ubuntu/separate/hummingbot/core/data_type/trade_fee.py", line 197, in _get_exchange_rate
    raise ValueError(f"Could not find the exchange rate for {trading_pair} using the RateOracle "
ValueError: Could not find the exchange rate for USDC-BNB using the RateOracle (please validate it is active)
```

- 2> `Error fetching data from https://api.binance.com/api/v3/order. HTTP status is 400 ({"code":-2011,"msg":"Unknown order sent."}).`

```
OSError: Error fetching data from https://api.binance.com/api/v3/order. HTTP status is 400 ({"code":-2011,"msg":"Unknown order sent."}).
2022-02-08 01:46:57,341 - 16417 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Error fetching data from https://api.binance.com/api/v3/order. HTTP status is 400 ({"code":-2011,"msg":"Unknown order sent."}).
Traceback (most recent call last):
  File "/home/ubuntu/separate/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ubuntu/separate/hummingbot/connector/exchange/binance/binance_exchange.py", line 566, in _execute_cancel
    cancel_result = await self._api_request(
  File "/home/ubuntu/separate/hummingbot/connector/exchange/binance/binance_exchange.py", line 1011, in _api_request
    raise IOError(f"Error fetching data from {url}. HTTP status is {response.status} ({data}).")
OSError: Error fetching data from https://api.binance.com/api/v3/order. HTTP status is 400 ({"code":-2011,"msg":"Unknown order sent."}).
```
- 3> filled orders are not being recorded

image
image


- config, logs and sqlite data
[binance.zip](https://github.com/CoinAlpha/hummingbot/files/8021214/binance.zip)

**Comment by aarmoa** [comment]
@PtrckM is the error for uniswap and balancer also happening in the current development branch? If the fee has to be expressed in DAI and the charged amount is in ETH, there is not other way to to convert the value to aggregate them

**Comment by RC-13** [comment]
> @RC-13 in the logs you attached I could not find any error. In fact I could not find the text `OrderFilledEvent` that is always present when a partial/total fill event is processed. Are you sure there was a trade fill?

Hello @aarmoa There are no errors in the logs, however, there are messages stating that an order has failed. And these orders that failed are confirmed to be filled. Here's another example for the ETH-USDT market:

I've added the initial and ending balance (made sure that there are no other bots using the ascendEX account) and as seen in the image, there was a change in the amount of the assets.
image

In these test, the first order that got fill is `HMBot-BETHUSD1644359996004942`. In the log pane, the order was about to get cancelled, followed by the message that the order has failed. However there was no completion event for the cancelation and upon checking the exchange, the order is filled.
ascendex-fill-order-has failed
```python
2022-02-09 06:39:56,003 - 2949 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Creating 1 bid orders at (Size, Price): ['0.005 ETH, 3106.52 USDT']
2022-02-09 06:39:56,005 - 2949 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Creating 1 ask orders at (Size, Price): ['0.005 ETH, 3106.83 USDT']
2022-02-09 06:39:56,164 - 2949 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER SELL order HMBot-SETHUSD1644359996005792 for 0.005 ETH-USDT.
2022-02-09 06:39:56,170 - 2949 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1644359996000, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ETH-USDT", "amount": "0.005", "price": "3106.83", "order_id": "HMBot-SETHUSD1644359996005792", "exchange_order_id": "HMBot17edb7e5268U9496830767JwajO", "leverage": 1, "position": "NILL", "event_name": "SellOrderCreatedEvent", "event_source": "ascend_ex"}
2022-02-09 06:39:56,171 - 2949 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER BUY order HMBot-BETHUSD1644359996004942 for 0.005 ETH-USDT.
2022-02-09 06:39:56,175 - 2949 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1644359996000, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ETH-USDT", "amount": "0.005", "price": "3106.52", "order_id": "HMBot-BETHUSD1644359996004942", "exchange_order_id": "HMBot17edb7e5266U94968307677f36i", "leverage": 1, "position": "NILL", "event_name": "BuyOrderCreatedEvent", "event_source": "ascend_ex"}
2022-02-09 06:40:26,002 - 2949 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Cancelling the limit order HMBot-BETHUSD1644359996004942. [clock=2022-02-08 22:40:26+00:00]
2022-02-09 06:40:26,003 - 2949 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Cancelling the limit order HMBot-SETHUSD1644359996005792. [clock=2022-02-08 22:40:26+00:00]
2022-02-09 06:40:26,201 - 2949 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1644360026000, "order_id": "HMBot-BETHUSD1644359996004942", "order_type": "OrderType.LIMIT_MAKER", "event_name": "MarketOrderFailureEvent", "event_source": "ascend_ex"}
2022-02-09 06:40:26,206 - 2949 - hummingbot.connector.client_order_tracker - INFO - Order HMBot-BETHUSD1644359996004942 has failed. Order Update: OrderUpdate(trading_pair='ETH/USDT', update_timestamp=1644360026148, new_state=<OrderState.FAILED: 6>, client_order_id=None, exchange_order_id='HMBot17edb7e5266U94968307677f36i', trade_id=None, fill_price=Decimal('0'), executed_amount_base=Decimal('0'), executed_amount_quote=Decimal('0'), fee_asset='USDT', cumulative_fee_paid=Decimal('0'))
2022-02-09 06:40:26,206 - 2949 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1644360026000, "order_id": "HMBot-SETHUSD1644359996005792", "exchange_order_id": "HMBot17edb7e5268U9496830767JwajO", "event_name": "OrderCancelledEvent", "event_source": "ascend_ex"}
2022-02-09 06:40:26,208 - 2949 - hummingbot.connector.client_order_tracker - INFO - Successfully cancelled order HMBot-SETHUSD1644359996005792.
```
This behavior happens whenever there is a fill, here are the affected orders:
`HMBot-BETHUSD1644359996004942`
`HMBot-BETHUSD1644360027002460`
`HMBot-SETHUSD1644360058011919`
`HMBot-SETHUSD1644360089006291`
ascendex-filled but not recorded
image

[eth-usdt-ascendex.zip](https://github.com/CoinAlpha/hummingbot/files/8028149/eth-usdt-ascendex.zip)

**Comment by PtrckM** [comment]
> @PtrckM is the error for uniswap and balancer also happening in the current development branch? If the fee has to be expressed in DAI and the charged amount is in ETH, there is not other way to to convert the value to aggregate them

- using development branch with the same config not getting the same error from this branch `feat/separate_order_update_from_order_fill_in_order_tracker`


image
image

image

**Comment by rxlxrxsx** [comment]
Testing update:

- Finished basic checks on all connectors, waiting for the fix on outstanding issues

**Comment by aarmoa** [comment]
@RC-13 @PtrckM I have added a couple of fixes to the PR. But I don't think that will be enough to solve the issue for Binance. The changes required to fully solve the Binance issue will be handled in a separate task, but we will end up sending both PRs together to the foundation repository.

**Comment by aarmoa** [comment]
I have committed a fix that should address AscendEx connector not tracking fill events. The changes introduced here impact the Client Order Tracker. Please retest also Binance and Binance Perpetual connectors.

**Comment by RC-13** [comment]
- Confirming that the reported issue for Binance and AscendEX related to trade fill has been resolved on the latest commit.
- Using the Binance connector, we still see an issue with finding the exchange rate for a certain pair (quite similar to the issue posted above)
image
```python
2022-02-10 00:50:57,514 - 4618 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Could not find the exchange rate for XRP-USDC using the rate source Binance rate oracle (please verify it has been correctly configured)
Traceback (most recent call last):
  File "/home/ubuntu/separate/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ubuntu/separate/hummingbot/connector/client_order_tracker.py", line 282, in _process_order_update
    self._trigger_order_completion(tracked_order, order_update)
  File "/home/ubuntu/separate/hummingbot/connector/client_order_tracker.py", line 253, in _trigger_order_completion
    self._trigger_completed_event(tracked_order)
  File "/home/ubuntu/separate/hummingbot/connector/client_order_tracker.py", line 200, in _trigger_completed_event
    order.cumulative_fee_paid(order.quote_asset),
  File "/home/ubuntu/separate/hummingbot/core/data_type/in_flight_order.py", line 285, in cumulative_fee_paid
    total_fee_in_token += trade_update.fee.fee_amount_in_token(
  File "/home/ubuntu/separate/hummingbot/core/data_type/trade_fee.py", line 210, in fee_amount_in_token
    conversion_rate = self._get_exchange_rate(conversion_pair, exchange, rate_source)
  File "/home/ubuntu/separate/hummingbot/core/data_type/trade_fee.py", line 183, in _get_exchange_rate
    raise ValueError(f"Could not find the exchange rate for {trading_pair} using the rate source "
ValueError: Could not find the exchange rate for XRP-USDC using the rate source Binance rate oracle (please verify it has been correctly configured)
```
[Archive.zip](https://github.com/CoinAlpha/hummingbot/files/8037232/Archive.zip)

- For Uniswap and Balancer, there was a mixup on the QA side, the error should be addressed in this PR since it was confirmed working on the latest development. The error changed though,
```python
2022-02-10 08:59:40,001 - 6484 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'UniswapConnector' object has no attribute 'order_books'
Traceback (most recent call last):
  File "/Users/hb/testing/separate-order-fill/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/hb/testing/separate-order-fill/hummingbot/strategy/amm_arb/amm_arb.py", line 133, in main
    arb_proposals = [
  File "/Users/hb/testing/separate-order-fill/hummingbot/strategy/amm_arb/amm_arb.py", line 135, in <listcomp>
    if t.profit_pct(
  File "/Users/hb/testing/separate-order-fill/hummingbot/strategy/amm_arb/data_types.py", line 96, in profit_pct
    buy_fee_amount = buy_trade_fee.fee_amount_in_token(buy.market_info.trading_pair,
  File "/Users/hb/testing/separate-order-fill/hummingbot/core/data_type/trade_fee.py", line 210, in fee_amount_in_token
    conversion_rate = self._get_exchange_rate(conversion_pair, exchange, rate_source)
  File "/Users/hb/testing/separate-order-fill/hummingbot/core/data_type/trade_fee.py", line 177, in _get_exchange_rate
    if exchange is not None and trading_pair in exchange.order_books:
AttributeError: 'UniswapConnector' object has no attribute 'order_books'
```
image
[amm-arb.zip](https://github.com/CoinAlpha/hummingbot/files/8037239/amm-arb.zip)

**Comment by aarmoa** [comment]
@RC-13 I have updated the PR to include the latest changes in the development branch. Also in the last commit I have pushed a change that should fix the error related to the conversion rate not found when using amm-arb strategy. If possible please test it again to validate the fix covers all scenarios.

**Review by PtrckM — APPROVED** [review]
Tested and approved by QA team.
Test summary:

- Created a strategy and went through initial prompts successfully
- Confirmed wallet and exchange balances are reflecting correct
- Started the strategies without issues, confirmed orders are created and cancelled based on config.
- Ran a test bot for all affected exchanges and protocol connectors without errors.
- Confirmed in logs that there are no errors when orders are filled.
- Trade information are correct (price, size) based on history command output
- Compared trades in client versus sqlite data, cvs trades and thru exchange are all matched.
- Confirmed all issues found were addressed and fixed.

**Review by CrimsonJacket — APPROVED** [review]
Changes LGTM. Do resolve the conflict.

**Comment by PtrckM** [comment]
recent changes still LGTM!

**Comment by aarmoa** [comment]
Closing the PR after creating it in Hummingbot repo (https://github.com/hummingbot/hummingbot/pull/5120)

**Pull request closed without merging**
