### PR TITLE
[refactor] Removed usless except block

### PR DESCRIPTION
**Pull request by martinvol**
**Before submitting this PR, please make sure**:
- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue:
- Related Clubhouse Story:

**A description of the changes proposed in the pull request**: A except had not effect as it re-raised the exception.

### CODE REVIEW

**Comment by Nullably** [comment]
@martinvol Thanks for the catch. Yeah, we don't need that try and except. Can you make the PR to `development` instead?

**Comment by martinvol** [comment]
Oh yeah, there you go

**Comment by mifeng** [comment]
test this please

**Comment by dennisocana** [comment]
test this please

**Pull request merged**
