### PR TITLE
release / v.0.34.0 sync dev => master (PR 2 of 3)

### PR DESCRIPTION
**Pull request by dennisocana**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

### CODE REVIEW

**Review by Nullably — APPROVED** [review]
my blessing, may there be no bugs ever.

**Review by vic-en — DISMISSED** [review]
LGTM

**Review by Nullably — APPROVED** [review]
blessed, may there be no problem in production.

**Review by sdgoh — APPROVED** [review]
LGTM

**Pull request merged**
