### PR TITLE
Fix/Bybit_perpetual: available balance doesn't update when possible liquidation is detected

### PR DESCRIPTION
**Pull request by mhrvth**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

Trigger explicit balance update when receives a position update through an user stream websocket.

**Tests performed by the developer**:

Ran Perpetual MM with Bybit connector, tested balance updates on position changes.
Ran unit tests.

### CODE REVIEW

**Comment by mhrvth** [comment]
[sc-25785]

**Review by Deepali6997 — APPROVED** [review]
LGTM! 

Test Summary

- Created Perpetual market making strategy for Bybit and post starting found that available balance is getting adjusted accordingly (as per newly created orders)
- Checked for various order levels and can confirm that available balance is getting adjusted 
- In the case of running multiple bots, the behaviour was found to be same
- Even when the order levels were adjusted - from low to high order levels - the available balance was adjusting accordingly

**Review by aarmoa — CHANGES_REQUESTED** [review]
I think we should do two changes to the PR:
- Put the code that triggers the balance update inside `_process_account_position_event`. That way in the future if the logic that process a position update is called from some other place it will automatically also call the balance update.
- The execution of the balance update should be started as a future and wait actively until it finishes. That action involves HTTP interaction and is slow by definition, and we are very interested on keep processing other update events.

**Review by aarmoa — APPROVED** [review]
The change looks good to me

**Comment by mhrvth** [comment]
Created a PR in the Foundation repo: https://github.com/hummingbot/hummingbot/pull/5292

**Pull request closed without merging**
