### PR TITLE
docs / scripts issue and feature template

### PR DESCRIPTION
**Pull request by phbrgnomo**
**Before submitting this PR, please make sure**:
- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue:
- Related Clubhouse Story:

**A description of the changes proposed in the pull request**:

### CODE REVIEW

**Comment by Nullably** [comment]
@phbrgnomo Can you please give more details in the description on what this template is for?
Also the PR should target `development` not `master` branch.

**Comment by phbrgnomo** [comment]
This is an extra template for the git hub repo, to create issues related to the script's features, including users requests for new scripts.

It would allow us to separate the requests, so other contributors could also create scripts based on users requests.

Should close this PR and open one on development branch?

**Comment by dennisocana** [comment]
@phbrgnomo I changed the base branch from `master` to `development`. In the future, you can do this by clicking the **Edit** button on the right side of the PR title.

**Review by Nullably — APPROVED** [review]
LGTM

**Pull request merged**
