### PR TITLE
Fix to checksum the addresses in the ZeroEx Order tuple, as Web3.py n…

### PR DESCRIPTION
**Pull request by Arctek**
**Before submitting this PR, please make sure**:
- [x ] Your code builds clean without any errors or warnings
- [x ] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue: https://github.com/CoinAlpha/hummingbot/issues/1793

**A description of the changes proposed in the pull request**:
Checksums the addresses in the ZeroEx Order tuple (`senderAddress` etc), as Web3.py now checks these.

### CODE REVIEW

**Comment by PtrckM** [comment]
- Tested this PR issues and error no longer occurs.

image
image

image
image
- clean logs
[logs_conf_pure_mm_1.log](https://github.com/CoinAlpha/hummingbot/files/4667741/logs_conf_pure_mm_1.log)

**Comment by mifeng** [comment]
test this please

**Comment by mifeng** [comment]
test this please

**Comment by Arctek** [comment]
Ok I figured I would just update this PR (since I need this to test this latest change).
But the `get_event_data` function had changed for the latest Web3.py and this needed updating in the ZeroExFillWatcher

**Comment by mifeng** [comment]
test this please

**Pull request merged**
