### PR TITLE
Feat/blocktane connector

### PR DESCRIPTION
**Pull request by trkoneill18**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

### CODE REVIEW

**Comment by PtrckM** [comment]
- getting this error when running the bot on low refresh time `order_refresh_time 10` (no stuck order on bot or exchange)
image
image

- and also this
image

here is the logs
[logs_eth_btc.log](https://github.com/CoinAlpha/hummingbot/files/5893199/logs_eth_btc.log)

**Comment by mborraccia** [comment]
@PtrckM It appears that the 403 errors during random network requests are a current issue on the exchange itself. We anticipate that they'll be fixed on the exchange side within the next day,

**Comment by keithbaum** [comment]
Hi @mborraccia ,
Could you please add a Throttler class and a context for _api_request like in Binance connector? That's to avoid hitting rate limits using the cost of the api calls

**Comment by jason-hb** [comment]
@RC-13 and @keithbaum Here's a message from Michael @ Linq regarding rate limiting:

@JackShiloh Regarding the blocktane connector, the ask in that PR was to add the Throttler class, but the exchange is quite generous with rate limits (6000/5 min). We run some strategies against that exchange that are much more intense on operations per second and never hit the 429 rate limit errors. Just curious if this a new requirement for connectors, or a misunderstanding about the nature of those 403 errors that had been encountered earlier?

Based on this message and the ample rate limit, let's move forward with the connector as-is

**Review by keithbaum — APPROVED** [review]
LGTM

**Comment by keithbaum** [comment]
@mborraccia please go ahead and merge, as I don't have write privileges in your branch to update it our last development version so as to merge

**Comment by PtrckM** [comment]
Aside from the `403 errors during random network requests` exchange are tested and confirmed working by QA.

**Review by PtrckM — APPROVED** [review]

**Pull request merged**
