### PR TITLE
Price source - Task 1 and 3

### PR DESCRIPTION
**Pull request by Nullably**
**Before submitting this PR, please make sure**:
- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue:
- Related Clubhouse Story:

**A description of the changes proposed in the pull request**:
- An open PR to easily see changes in this branch (as compare to `development`)

### CODE REVIEW

**Comment by Nullably** [comment]
@petioptrv I open this draft PR s.t. we can easily keep this branch up-to-date and avoid potentially large merge conflicts.

**Comment by Nullably** [comment]
@petioptrv Please see my comments on https://github.com/CoinAlpha/hummingbot/pull/2126

**Comment by Nullably** [comment]
The work so far on this branch, I believe, covers #1917 and #1919 
@dennisocana Can you please test these?
@petioptrv Once, the testing passes, we're going to merge this in and the other 2 issues #1918 and #1920 can be done in a future release.

**Comment by rxlxrxsx** [comment]
Got flooded with ``Unexpected error running clock tick`` upon starting the bot with ``price_type`` set to ``last_price`` and ``price_source`` set to ``external_market``

image
image

[logs_binance_test.log](https://github.com/CoinAlpha/hummingbot/files/5141603/logs_binance_test.log)

**Comment by petioptrv** [comment]
> Got flooded with `Unexpected error running clock tick` upon starting the bot with `price_type` set to `last_price` and `price_source` set to `external_market`
> 
> image
> image
> 
> [logs_binance_test.log](https://github.com/CoinAlpha/hummingbot/files/5141603/logs_binance_test.log)

Fixed in #2265

**Review by dennisocana — APPROVED** [review]
No other errors or bugs found by QA during testing.

**Pull request merged**
