### PR TITLE
refactor/gate io websockets removal

### PR DESCRIPTION
**Pull request by petioptrv**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This PR replaces Gate.io's use of `websockets` with `aiohttp`. It also adds several new functions to the network mocking assistant to help mock the `aiohttp.ClientWebSocketResponse.receive` method.

**Tests performed by the developer**:
- Test cases covering the affected portions of the code.

**Tips for QA testing**:
- Check that the functioning of the connector is as expected after the websocket changes.

### CODE REVIEW

**Comment by RC-13** [comment]
@petioptrv It seems that the exchange doesn't initialize properly, any strategy use fails to start and stop at `Market connector are not ready` status
image
unit test are failing as well
image

**Comment by petioptrv** [comment]
> @petioptrv It seems that the exchange doesn't initialize properly, any strategy use fails to start and stop at `Market connector are not ready` status

Thank you for testing @RC-13, I've pushed a fix for this.

> unit test are failing as well

Looks like `aiohttp` is not being found. Looking at the screenshot, this was ran in the `base` conda environment, which is most likely the cause.

**Review by CrimsonJacket — CHANGES_REQUESTED** [review]
I notice that for Gateio, we are still using 2 websocket connections in `GateIoAPIOrderBookDataSource`. I figure that we can take this opportunity to refactor it to use 1 websocket connection.

**Comment by petioptrv** [comment]
> I notice that for Gateio, we are still using 2 websocket connections in `GateIoAPIOrderBookDataSource`. I figure that we can take this opportunity to refactor it to use 1 websocket connection.

I created an issue for that a while back: https://app.zenhub.com/workspaces/hummingbot-5f340755c5e17300167a8f30/issues/coinalpha/hummingbot/4225

**Review by CrimsonJacket — APPROVED** [review]
Changes LGTM!

**Review by rapcmia — APPROVED** [review]
Tested and working ok, approved on behalf of QA team

**Pull request merged**
