### PR TITLE
fix / fix Liquid user stream tracker

### PR DESCRIPTION
**Pull request by vic-en**
**Before submitting this PR, please make sure**:
- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue: #2222 
- Related Clubhouse Story:

**A description of the changes proposed in the pull request**:

### CODE REVIEW

**Comment by Nullably** [comment]
@vic-en Can you fix `test_liquid_market.py` to mock web socket responses as well? Thanks

**Review by Nullably — CHANGES_REQUESTED** [review]
See my comment

**Comment by rxlxrxsx** [comment]
Orders are getting stuck in Liquid instead of cancelling the orders.

image
image

2 instances of this warning regarding WebSocket message.

image

[logs_liquid_test.log](https://github.com/CoinAlpha/hummingbot/files/5128040/logs_liquid_test.log)

**Review by dennisocana — COMMENTED** [review]
Getting flooded with the ff. errors during testing:

[logs_liquid_qash-eth.log](https://github.com/CoinAlpha/hummingbot/files/5129184/logs_liquid_qash-eth.log)

```
2020-08-26 18:21:37,659 - 1759 - hummingbot.market.liquid.liquid_api_user_stream_data_source - ERROR - Unexpected error with Liquid WebSocket connection. Retrying after 30 seconds...
Traceback (most recent call last):
  File "/home/pi/Hummingbot/liquid_qash-eth/hummingbot/market/liquid/liquid_api_user_stream_data_source.py", line 73, in listen_for_user_stream
    await ws.send(ujson.dumps(auth_request))
TypeError: reject_bytes is on and 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXRoIjoiL3JlYWx0aW1lIiwibm9uY2UiOiIxNTk4NDM3Mjk3NTU5IiwidG9rZW5faWQiOiIxMjQ5NTQzIn0.mnKkQzdWGPv5IHimq_wmw6CzfeoN2k5XBSuhOUqsRBA' is bytes
```

image

image

**Comment by rxlxrxsx** [comment]
Ran the bot for an hour and can confirm that it's now placing orders normally every cycle.

image

Got 17 instances of error while fetching account updates after running for an hour.

image

[logs_liquid_test.log](https://github.com/CoinAlpha/hummingbot/files/5140465/logs_liquid_test.log)

**Comment by rxlxrxsx** [comment]
Bot cannot place orders because of this error. Tried both when importing and creating a new strategy but got the same result.

image
image

[logs_liquid-test-083120.log](https://github.com/CoinAlpha/hummingbot/files/5149144/logs_liquid-test-083120.log)

**Comment by rxlxrxsx** [comment]
21 instances where the bot fails to submit an order

```
2020-08-31 22:01:25,129 - 20428 - hummingbot.market.liquid.liquid_market - NETWORK - Error submitting buy limit_maker order to Liquid for 100.0 QASH-ETH 0.00010154.
Traceback (most recent call last):
  File "hummingbot/market/liquid/liquid_market.pyx", line 933, in hummingbot.market.liquid.liquid_market.LiquidMarket.execute_buy
    order_result = await self.place_order(order_id, trading_pair, decimal_amount, True, order_type, decimal_price)
  File "hummingbot/market/liquid/liquid_market.pyx", line 876, in place_order
    order_result = await self._api_request("post", path_url=path_url, data=data)
  File "hummingbot/market/liquid/liquid_market.pyx", line 323, in _api_request
    async with client.request(http_method,
  File "hummingbot/market/liquid/liquid_market.pyx", line 327, in hummingbot.market.liquid.liquid_market.LiquidMarket._api_request
    raise IOError(f"Error fetching data from {url}. HTTP status is {response.status}. {data}")
OSError: Error fetching data from https://api.liquid.com/orders. HTTP status is 422. {'errors': {'order': ['product_disabled']}}
2020-08-31 22:01:25,129 - 20428 - hummingbot.market.liquid.liquid_market - WARNING - Failed to submit buy order to Liquid. Check API key and network connection.Error fetching data from https://api.liquid.com/orders. HTTP status is 422. {'errors': {'order': ['product_disabled']}}
```
```
2020-09-01 02:17:37,309 - 20428 - hummingbot.market.liquid.liquid_market - NETWORK - Error submitting sell limit_maker order to Liquid for 100.0 QASH-ETH 0.00010306.
Traceback (most recent call last):
  File "hummingbot/market/liquid/liquid_market.pyx", line 996, in hummingbot.market.liquid.liquid_market.LiquidMarket.execute_sell
    order_result = await self.place_order(order_id, trading_pair, decimal_amount, False, order_type, decimal_price)
  File "hummingbot/market/liquid/liquid_market.pyx", line 876, in place_order
    order_result = await self._api_request("post", path_url=path_url, data=data)
  File "hummingbot/market/liquid/liquid_market.pyx", line 323, in _api_request
    async with client.request(http_method,
  File "hummingbot/market/liquid/liquid_market.pyx", line 327, in hummingbot.market.liquid.liquid_market.LiquidMarket._api_request
    raise IOError(f"Error fetching data from {url}. HTTP status is {response.status}. {data}")
OSError: Error fetching data from https://api.liquid.com/orders. HTTP status is 422. {'errors': {'order': ['do_not_initiate']}}
2020-09-01 02:17:37,309 - 20428 - hummingbot.market.liquid.liquid_market - WARNING - Failed to submit sell order to Liquid.Check API key and network connection.Error fetching data from https://api.liquid.com/orders. HTTP status is 422. {'errors': {'order': ['do_not_initiate']}}
```

1 instance of error while fetching account updates after running the bot overnight

```
2020-09-01 02:44:50,004 - 20428 - hummingbot.market.liquid.liquid_market - NETWORK - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "hummingbot/market/liquid/liquid_market.pyx", line 1129, in hummingbot.market.liquid.liquid_market.LiquidMarket._status_polling_loop
    await safe_gather(
  File "/home/rsa-key-20200326/hummingbot/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "hummingbot/market/liquid/liquid_market.pyx", line 409, in _update_balances
    fiat_acct_balances = await self._api_request("get", path_url=fiat_accounts_path) or []
  File "hummingbot/market/liquid/liquid_market.pyx", line 323, in _api_request
    async with client.request(http_method,
  File "/home/rsa-key-20200326/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/home/rsa-key-20200326/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/home/rsa-key-20200326/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/home/rsa-key-20200326/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer
2020-09-01 02:44:50,139 - 20428 - hummingbot.market.liquid.liquid_market - WARNING - Could not fetch account updates on Liquid. Check API key and network connection.
```

[logs_liquid-test-083120.log](https://github.com/CoinAlpha/hummingbot/files/5154605/logs_liquid-test-083120.log)

**Comment by vic-en** [comment]
@rxlxrxsx 
Error `product_disabled` occured because Liquid disable the QASH-ETH pair for about 5 minutes for reasons best known to them.
Error `do_not_initiate` occurred because the LIMIT_MAKER order crossed the order book. It occurred once and that's normal once in a while.
Lastly, `Connection reset by peer` is purely a problem with the network connection between the bot to the exchange.

If those are all the error so far, I think this PR can be merged.

**Review by dennisocana — APPROVED** [review]

**Review by Nullably — APPROVED** [review]
LGTM

**Pull request merged**
