### PR TITLE
Feat/polkadex v2

### PR DESCRIPTION
**Pull request by petioptrv**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

This PR introduces an update to the Polkadex connector to use the [V2 API](https://documenter.getpostman.com/view/16239785/2s93shy9EY#8094c956-8ffe-4522-b442-8fa38f057329).

**Tests performed by the developer**:

- Unit tests.

**Tips for QA testing**:

Note that every now and then, the periodic order status update may fail because it happened immediately after submitting an order. Since Polkadex is a decentralized exchange, it takes a couple of seconds for the order to make it onto the chain and to become available for order status updates.

@CoinAlpha/qa-client, I am currently getting a segfault several seconds into using the OSS client. I've pinged Federico to check if that's a known issue on their end.

[ch-43708]

### CODE REVIEW

**Comment by mrhzysbl** [comment]
Test run: https://hummingbot.testrail.io/index.php?/runs/view/4851&group_by=cases:section_id&group_order=asc

**Review by vic-en — APPROVED** [review]
LGTM

**Review by rxlxrxsx — APPROVED** [review]
Tested and confirmed working by QA.

- Successfully cloned and installed the branch
- Connected seed phrase and confirmed working as expected
- Confirmed wallet and exchange balances are reflecting correct
- Created a pure_mm strategy and went through initial prompts successfully
- Started the strategy without issues, confirmed orders are created and cancelled based on config
- Confirmed order book prices is in sync with the exchange
- Trade information are correct based on history command output
- Compared trades in client and exchange, no discrepancies found
- Confirmed hanging order/cancellation and multiple order levels works as expected

**Comment by petioptrv** [comment]
Closing to re-open towards foundation:

**Pull request closed without merging**
