### PR TITLE
[v0.33] Feat / AMM arb strategy and connectors

### PR DESCRIPTION
**Pull request by Nullably**
**Before submitting this PR, please make sure**:
- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue:
- Related Clubhouse Story:

**A description of the changes proposed in the pull request**:
- A new AMM Arb strategy
- A new balancer connector
- ETH gas station lookup

### CODE REVIEW

**Comment by RC-13** [comment]
We have a typo for the question when enabling eth gas station parameter
typo client

**Comment by Nullably** [comment]
@RC-13 Thanks. I've just updated the branch with the fix.

**Review by sdgoh — APPROVED** [review]
LGTM

**Review by sdgoh — APPROVED** [review]
LGTM

**Pull request merged**
