### PR TITLE
refactor / environment.yml for MacOS

### PR DESCRIPTION
**Pull request by carlolm**
**Before submitting this PR, please make sure**:
- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue:
- Related Clubhouse Story: https://app.clubhouse.io/coinalpha/story/9209/reduce-docker-image-size-for-hummingbot

**A description of the changes proposed in the pull request**:

- mkl => nomkl to make consistent with refactored linux environment
- tested and installs/runs on MacOS

### CODE REVIEW

**Comment by martinkou** [comment]
Please don't change the cython version unnecessarily - it can break compatibility with hummingsim and thus cause test cases to fail.

**Comment by martinkou** [comment]
I've pushed another commit to limit the unnecessary changes.

**Comment by mifeng** [comment]
@carlolm @Nullably @dennisocana @vic-en 
should we merge this PR in before release?

**Comment by carlolm** [comment]
> @carlolm @Nullably @dennisocana @vic-en
> should we merge this PR in before release?

Probably not worth it if it delays release.  But if we get a few more people to try it out on Macs and it works, then it's fine. I'll try it out after standup since Martin made some changes to my original PR

**Pull request merged**
