### PR TITLE
Feat/ uniswap v3

### PR DESCRIPTION
**Pull request by Nullably**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
A feature branch for Uniswap v3 strategy and connector.

### CODE REVIEW

**Review by Nullably — COMMENTED** [review]
The code looks good to me so far. There is no unit test for the strategy yet. 
Since I am the one who created this PR I can officially review it.

**Comment by RC-13** [comment]
Re-posting the issues encountered when testing uniswap v3, the test is done on the KOVAN network.
- Bot shows 2 sell orders wherein the in-range sell order should be a buy order.
image
image

- Failing to remove out of range position resulting in failing to submit the adjusted position.
Failed to remove position
After restarting the bot, old position still persist in uniswap pool
uniswap-remove-position
kovan-tx-explorer

**Comment by RC-13** [comment]
Similar to the issue reported with removing the position, the bot is unable to recognize that the previous position has been adjusted and removed. In the logs, the bot created position 3007 and 3008,
```python
2021-05-31 14:33:01,002 - 5602 - hummingbot.strategy.uniswap_v3_lp.uniswap_v3_lp - INFO - Uniswap v3 connector is ready. Trading started.
2021-05-31 14:33:05,386 - 5602 - hummingbot.strategy.uniswap_v3_lp.uniswap_v3_lp - INFO - Creating new buy position over 0.741162142511060391 to 0.7486486287990509 price range. [clock=2021-05-31 06:33:05+00:00]
2021-05-31 14:33:05,387 - 5602 - hummingbot.strategy.uniswap_v3_lp.uniswap_v3_lp - INFO - Creating new sell position over 0.7486486287990509 to 0.756135115087041409 price range. [clock=2021-05-31 06:33:05+00:00]
2021-05-31 14:33:11,943 - 5602 - hummingbot.connector.connector.uniswap.uniswap_connector - INFO - Created range position for DAI-USDC, hb_id: DAI-USDC-1622442785386940, tx_hash: 0x735658b36f2002fc03cfa21ed6a71513f3b6f117f1186336b945021def0ce9a7 amount: 1.000000 (DAI), range: 0.741162 - 0.748649
2021-05-31 14:33:11,951 - 5602 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1622442791.0, "hb_id": "DAI-USDC-1622442785386940", "tx_hash": "0x735658b36f2002fc03cfa21ed6a71513f3b6f117f1186336b945021def0ce9a7", "trading_pair": "DAI-USDC", "fee_tier": "LOW", "lower_price": "0.741162", "upper_price": "0.748649", "base_amount": "1.000000", "quote_amount": "1.000000", "status": "PENDING_CREATE", "gas_price": 17.1, "event_name": "RangePositionInitiatedEvent", "event_source": "uniswap_v3"}
2021-05-31 14:33:11,951 - 5602 - hummingbot.connector.connector.uniswap.uniswap_connector - INFO - Created range position for DAI-USDC, hb_id: DAI-USDC-1622442785387241, tx_hash: 0xe36c017934160388d9a407f202ad63c2187768f50349297186c5aff50f460e06 amount: 1.000000 (DAI), range: 0.748649 - 0.756135
2021-05-31 14:33:11,959 - 5602 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1622442791.0, "hb_id": "DAI-USDC-1622442785387241", "tx_hash": "0xe36c017934160388d9a407f202ad63c2187768f50349297186c5aff50f460e06", "trading_pair": "DAI-USDC", "fee_tier": "LOW", "lower_price": "0.748649", "upper_price": "0.756135", "base_amount": "1.000000", "quote_amount": "1.000000", "status": "PENDING_CREATE", "gas_price": 17.1, "event_name": "RangePositionInitiatedEvent", "event_source": "uniswap_v3"}
2021-05-31 14:33:18,220 - 5602 - hummingbot.connector.connector.uniswap.uniswap_connector - INFO - Liquidity added for tokenID - 3007.
2021-05-31 14:33:18,230 - 5602 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1622442798.0, "hb_id": "DAI-USDC-1622442785386940", "tx_hash": "0x735658b36f2002fc03cfa21ed6a71513f3b6f117f1186336b945021def0ce9a7", "token_id": "3007", "base_amount": "0", "quote_amount": "1000000", "status": "OPEN", "event_name": "RangePositionUpdatedEvent", "event_source": "uniswap_v3"}
2021-05-31 14:33:18,230 - 5602 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1622442798.0, "hb_id": "DAI-USDC-1622442785386940", "tx_hash": "0x735658b36f2002fc03cfa21ed6a71513f3b6f117f1186336b945021def0ce9a7", "token_id": "3007", "trading_pair": "DAI-USDC", "fee_tier": "LOW", "lower_price": "0.741162", "upper_price": "0.748649", "base_amount": "0", "quote_amount": "1000000", "status": "OPEN", "gas_price": 17.1, "event_name": "RangePositionCreatedEvent", "event_source": "uniswap_v3"}
2021-05-31 14:33:20,513 - 5602 - hummingbot.connector.connector.uniswap.uniswap_connector - INFO - Liquidity added for tokenID - 3008.
2021-05-31 14:33:20,521 - 5602 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1622442800.0, "hb_id": "DAI-USDC-1622442785387241", "tx_hash": "0xe36c017934160388d9a407f202ad63c2187768f50349297186c5aff50f460e06", "token_id": "3008", "base_amount": "1000000000000000000", "quote_amount": "0", "status": "OPEN", "event_name": "RangePositionUpdatedEvent", "event_source": "uniswap_v3"}
2021-05-31 14:33:20,521 - 5602 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1622442800.0, "hb_id": "DAI-USDC-1622442785387241", "tx_hash": "0xe36c017934160388d9a407f202ad63c2187768f50349297186c5aff50f460e06", "token_id": "3008", "trading_pair": "DAI-USDC", "fee_tier": "LOW", "lower_price": "0.748649", "upper_price": "0.756135", "base_amount": "1000000000000000000", "quote_amount": "0", "status": "OPEN", "gas_price": 17.1, "event_name": "RangePositionCreatedEvent", "event_source": "uniswap_v3"}
```
I use postman to adjust the position of ID: 3007 and got a successful transaction. ID 3007 is now replaced by ID: 3009: https://kovan.etherscan.io/tx/0x9025e90f2543250c4bb73db947acc8dd1d5119088f4a7e7dc7ce94ae827d743b
However, the bot did not recognize this change even after restart:
image
[logs_conf_uniswap_v3_lp_2.log](https://github.com/CoinAlpha/hummingbot/files/6568460/logs_conf_uniswap_v3_lp_2.log)

**Comment by dennisocana** [comment]
@RC-13 we discussed during the standup today that the last reported behavior is not an issue - it happens when there is very low liquidity that results to the price being very high or very low.

@vic-en will make improvements on the second iteration of the strategy to address this scenario.

**Review by RC-13 — APPROVED** [review]
Thanks for the update @dennisocana. Approving PR on behalf of the QA team

**Pull request merged**
