### PR TITLE
Fix / remove extra take profit orders when using multiple order levels

### PR DESCRIPTION
**Pull request by vic-en**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

### CODE REVIEW

**Comment by RC-13** [comment]
Test PR and confirmed that unnecessary profit taking levels are removed, will wait for comments from other QA before approving PR.

Test on AVAX-USDT ( Bid and Ask)
avax live
avax live1

**Comment by rxlxrxsx** [comment]
Still getting an extra take profit order after the second sell order got filled.

Screen Shot 2021-01-03 at 6 07 56 PM

Also, when running `history` command I'm sometimes getting this:

```
2021-01-03 18:14:35,544 - 3732 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'int' object has no attribute 'is_nan'
Traceback (most recent call last):
  File "/Users/reiniersalazar/hummingbot1/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/reiniersalazar/hummingbot1/hummingbot/client/command/history_command.py", line 76, in history_report
    self.report_performance_by_market(market, symbol, perf, precision)
  File "/Users/reiniersalazar/hummingbot1/hummingbot/client/command/history_command.py", line 146, in report_performance_by_market
    smart_round(perf.cur_base_bal, precision),
  File "/Users/reiniersalazar/hummingbot1/hummingbot/client/performance.py", line 152, in smart_round
    if value is None or value.is_nan():
AttributeError: 'int' object has no attribute 'is_nan'
```

**Comment by dennisocana** [comment]
@CoinAlpha/qa-team confirmed the fix works on live but not in testnet. They also noticed an intermittent issue where it doesn't display the `history` output. Requesting code review from @CoinAlpha/dev-client

**Review by Nullably — APPROVED** [review]
LGTM

**Comment by vic-en** [comment]
@dennisocana @rxlxrxsx 
I couldn't reproduce this bug on testnet. Also, I tried running history command several times which was successful on each occasion. Also, note that whatever happens on testnet shold ideally happen in mainnet, except for times when testnet misbehaves.
Kindly reopen this issue and include full log and config file if same errors occur during code freeze or subsequent releases.

**Comment by RC-13** [comment]
Thanks for the update @vic-en will re-test the behavior on the history status once merged.

**Review by RC-13 — APPROVED** [review]

**Pull request merged**
