### PR TITLE
fix/ NDAX price source and paper trading mode issue

### PR DESCRIPTION
**Pull request by CrimsonJacket**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Addresses issues with using NDAX connector in paper trading mode and using NDAX as an external price source.

**For Developer**
- Modify `NdaxOrderBookTracker._init_order_books()`  to use `order_book_create_function` property to initialize `OrderBook`.

**For QA**
- Test that NDAX works in paper trading mode.
- Test that NDAX works as an external price source.

### CODE REVIEW

**Review by aarmoa — APPROVED** [review]
The fix looks good to me

**Comment by RC-13** [comment]
Tested and confirmed that NDAX now works in paper_trade and now can be used as a reference price source. However, a minor issue, the `unexpected clock tick error`  still persists at the start-up of the strategy, both happen in paper trade mode and when NDAX is used as an external price source.
image

**Comment by rapcmia** [comment]
While testing this again, got the same results as the earlier comment. Tested Ndax as an external price source for Binance for both paper trade and mainnet and got the same results. However what I've notice is that when you stop then start again, it did not return the error (only on the first instance of `start`)

Steps to reproduce:
1. Create Pure Market Making ( Papertrade or Live)
2. Set price_source to external and use NDAX
3. Set price_market to BTC-USDT

Her's when the bot starts it returns an `Unexpected error running clock tick.`

Paper trade
Tested papertrade with price source Ndax

On mainnet, I recorded that the bot creates and cancel orders according to Ndax's mid-price (works ok as well on other price types)

https://user-images.githubusercontent.com/73840223/128835268-cea90499-c543-456e-9a7f-ddb7d6d8f594.mp4

```
2021-08-10 16:21:27,096 - 17328 - hummingbot.connector.exchange.binance.binance_order_book_tracker - INFO - Initialized order book for BTC-USDT. 1/1 completed.
2021-08-10 16:21:27,100 - 17328 - hummingbot.connector.exchange.binance.binance_api_user_stream_data_source - INFO - Reconnecting to wss://stream.binance.com:9443/ws/WTohHGbICdHjdMbuFYE8zFW3irbTUyVJtQ3QH3vd5PRiW20OM1HQ75XqoAiK.
2021-08-10 16:21:29,007 - 17328 - hummingbot.core.network_iterator - WARNING - Ask orderbook for BTC-USDT is empty.
2021-08-10 16:21:29,007 - 17328 - hummingbot.core.network_iterator - WARNING - Buy orderbook for BTC-USDT is empty.
2021-08-10 16:21:29,007 - 17328 - hummingbot.core.network_iterator - WARNING - Ask orderbook for BTC-USDT is empty.
2021-08-10 16:21:29,007 - 17328 - hummingbot.core.network_iterator - WARNING - Buy orderbook for BTC-USDT is empty.
2021-08-10 16:21:29,008 - 17328 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot\\core\\clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot\\strategy\\pure_market_making\\pure_market_making.pyx", line 698, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_tick
    self.c_apply_budget_constraint(proposal)
  File "hummingbot\\strategy\\pure_market_making\\pure_market_making.pyx", line 867, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_apply_budget_constraint
    if quote_balance < quote_size:
decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]
```

Attached: 
[3882.zip](https://github.com/CoinAlpha/hummingbot/files/6960273/3882.zip)

**Comment by aarmoa** [comment]
Thank you for the details @RC-13 and @rapcmia. I have investigated the issue in the logs and I have been able to reproduce it locally. The problem is really caused by the PMM strategy. When it creates the proposals for the possible orders, it does not filter the proposals for which the price could not be determined. In the scenario described by QA the price is not determined yet because the client has not finished initializing the order book.
I will create a separate issue (bug) for this, and I will proceed merging the PR. (see #3887)

**Pull request merged**
