### PR TITLE
Fix/hanging order cancel for refresh

### LINKED ISSUE #3790: Hanging orders tracker cancels an order several times when refreshing it at max order age
**Describe the bug**
Using the Avellaneda strategy with hanging orders enabled, when the max order age for a hanging order is reached one can see several entries in the log stating that the cancel request for the order has been sent to the exchange. This message is generated in every tick.

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):
1. Configure the bot to use Avellaneda strategy with hanging orders enabled
2. Reduce max order age to trigger the issue faster
3. Wait for a hanging order to be created

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
0.41.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

### PR DESCRIPTION
**Pull request by aarmoa**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Improve the hanging order refresh strategy and the hanging order process to cancel the ones that have diverged from the market price to keep track of the already canceled orders. This ensures they are canceled only one time and the process then waits for the cancelation confirmation.

**Tests performed by the developer**
I have reproduced the issue with new unit tests.

**Tips for QA testing**
I have added a new log entry (it is a debug log entry) when a cancelation confirmation for an order being refreshed is received. The log message has the following structure:
```
"({trading_pair}) Hanging order {order_id} has been cancelled as part of the renew process. Now the replacing order will be created."
```

Resolves #3790 
(at least partially)

### CODE REVIEW

**Comment by rxlxrxsx** [comment]
Minor issue whenever a hanging order is filled, it's getting notified twice as a hanging order and as a normal order. Same case on the logs as well.

Screen Shot 2021-07-28 at 5 25 46 PM

```python
2021-07-28 08:41:21,646 - 26614 - hummingbot.strategy.hanging_orders_tracker - INFO - (BTC-USDT) Hanging maker BUY order x-XEKWYICX-BBCUT1627461660094859 (BTC-USDT 0.00046600 @ 39460.16000000) has been completely filled.
2021-07-28 08:41:21,646 - 26614 - hummingbot.strategy.avellaneda_market_making.avellaneda_market_making - INFO - (BTC-USDT) Maker buy order x-XEKWYICX-BBCUT1627461660094859 (0.00046600 BTC @ 39460.16000000 USDT) has been completely filled. [clock=2021-07-28 08:41:21+00:00]
2021-07-28 08:41:21,655 - 26614 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1627461681.0, "order_id": "x-XEKWYICX-BBCUT1627461660094859", "base_asset": "BTC", "quote_asset": "USDT", "fee_asset": "BTC", "base_asset_amount": "0.00046600", "quote_asset_amount": "18.3884345600000000", "fee_amount": "4.7E-7", "order_type": "OrderType.LIMIT_MAKER", "exchange_order_id": null, "event_name": "BuyOrderCompletedEvent", "event_source": "binance"}
```

Logs and config: [hanging.zip](https://github.com/CoinAlpha/hummingbot/files/6891990/hanging.zip)

**Comment by aarmoa** [comment]
I added a change in the hanging order tracker to keep a registry of the completed hanging orders. It will allow the strategy to know if the completed order event it receives is for a hanging order even if the even arrived to the hanging order tracker first (causing the tracker to remove the order from the list of current hanging orders).

**Review by RC-13 — APPROVED** [review]
Confirming all reported issue has been addressed, no additional issue seen during testing. LGTM!

**Review by CrimsonJacket — APPROVED** [review]
Using a new set `orders_being_cancelled` to determine if an order should be cancelled  seems pretty straightforward. LGTM

**Pull request merged**
