### PR TITLE
refactor / update celocli with v1.0.3

### PR DESCRIPTION
**Pull request by pgold**
Update the ticker strings used when parsing `celocli` output. It's up-to-date with v1.0.3. Also updates the `celocli` version installed on the docker image, so that both the parsing code and the command-line tool are aligned.

### CODE REVIEW

**Comment by dennisocana** [comment]
This could resolve the issue reported here: https://github.com/CoinAlpha/hummingbot/issues/3876

@CoinAlpha/qa-team is running tests for confirmation and to validate this branch.

**Comment by dennisocana** [comment]
Thank you @pgold for contributing. We're cleaning up any outstanding pull requests and see what we can review to merge into the codebase. Currently, your branch has conflicting files and needs to be updated with `development` branch. I will monitor for this change for the next step.

**Comment by pgold** [comment]
Thanks @dennisocana for looking into it. I've rebased my branch on top of the current `development` tip.

**Review by RC-13 — APPROVED** [review]
LGTM!

**Comment by RC-13** [comment]
@dennisocana This PR works as intended however we still experience these issue #3876

**Comment by dennisocana** [comment]
Thank you, @RC-13 . Moving to code review.

**Review by petioptrv — APPROVED** [review]
Changes LGMT. Thank you for contributing @pgold

**Pull request merged**
