### PR TITLE
Feat / maintain user balances

### PR DESCRIPTION
**Pull request by Nullably**
**Before submitting this PR, please make sure**:
- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue: #2127 #2012 
- Related Clubhouse Story:

**A description of the changes proposed in the pull request**:
- Modify market base class to calculate available balance based on in flight orders and order filled since last snapshot taken, this is for connectors which don't provide real time user balance update.

### CODE REVIEW

**Comment by Nullably** [comment]
retest this please

**Comment by rxlxrxsx** [comment]
## Coinbase Pro
[logs_cbp_test.log](https://github.com/CoinAlpha/hummingbot/files/5089046/logs_cbp_test.log)

Bot is creating orders normally on single and multiple order level after every cycle.

image
image

Found this error upon starting the bot.
image

## Eterbase
[logs_eterbase_test.log](https://github.com/CoinAlpha/hummingbot/files/5089048/logs_eterbase_test.log)

Bot is placing orders normally each cycle on a single order level however when setting it to multiple order level it says that it has ``Insufficient balance`` although it has enough balance to place an order.

image
image

Found this error upon starting the bot.
image

**Comment by Nullably** [comment]
Just pushed changes that should fix most issues above. I also added default fee of 0.35% for eterbase.

**Comment by Nullably** [comment]
Thanks @dennisocana 
I'm going to merge this into development now, for the minor bug we can fix it separately.

**Pull request merged**
