### PR TITLE
fix / error on certain input values for import command

### PR DESCRIPTION
**Pull request by dennisocana**
**Before submitting this PR, please make sure**:
- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

- Related Github issue: https://github.com/CoinAlpha/hummingbot/issues/1674
- Related Clubhouse Story: [8491](https://app.clubhouse.io/coinalpha/story/8491/handle-blank-input-values-for-import-command)

**A description of the changes proposed in the pull request**:

Added handling when `ENTER` key is pressed to enter a blank value on import command prompt. While testing, also found out that using special characters like `/`, `\`, and `.` as values to this prompt results to these errors:
```
PermissionError: [Errno 13] Permission denied: '/'
FileNotFoundError: [Errno 2] No such file or directory: '\\'
PermissionError: [Errno 13] Permission denied: 'conf/.'
```

**Testing**

pycharm64_xcvk6Rhla4

### CODE REVIEW

**Comment by Clint-G13** [comment]
Another issue, after you enter blank input and get the validator output. Existing strategies are considered invalid as well.
import

**Comment by dennisocana** [comment]
Thanks @Clint-G13 will create a patch for that.

**Comment by dennisocana** [comment]
@Clint-G13 I just pushed another commit, please check again.

**Comment by Clint-G13** [comment]
Confirm successful import and able to start the imported strategy.
import

**Comment by dennisocana** [comment]
Thanks @Nullably just pushed another commit with the requested changed.

**Pull request merged**
