### PR TITLE
fix/ history rounding on prices

### PR DESCRIPTION
**Pull request by Nullably**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
- Add smart rounding on prices shown in Assets section.

### CODE REVIEW

**Review by dennisocana — APPROVED** [review]
LGTM

**Comment by dennisocana** [comment]
To be tested and reviewed by @CoinAlpha/qa-team

**Comment by PtrckM** [comment]
@Nullably test PR but price precision is still long for weth-dai market

image

**Comment by Nullably** [comment]
@PtrckM 
Can you please check if you run code from this PR? I just tested, and it shows correctly (though this is Kovan testnet).
image

**Comment by PtrckM** [comment]
@Nullably re-tested again thru live

image

**Review by PtrckM — APPROVED** [review]
**Tested and confirmed working by QA**

**Pull request merged**
