### PR TITLE
Fix / Kraken - Add `Throttler` to `_api_request` with limit of 10 requests per second

### PR DESCRIPTION
**Pull request by TheHolyRoger**
**Before submitting this PR, please make sure**:
- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue: #2205, #2204
- Related Clubhouse Story:

**A description of the changes proposed in the pull request**:
Add `Throttler` to `_api_request` with limit of 10 requests per second

### CODE REVIEW

**Comment by TheHolyRoger** [comment]
Very small change (turn whitespace off) https://github.com/CoinAlpha/hummingbot/pull/2214/files?w=1

**Comment by dennisocana** [comment]
OK to test

**Comment by TheHolyRoger** [comment]
@dennisocana thanks for testing. That's annoying, I think to fix `get_last_traded_price` we should edit `order_book_tracker` - `_update_last_trade_prices_loop` so that it can send the same `Throttler` reference to `get_last_traded_prices`.

At the moment since it's a class method it doesn't receive `Throttler`

**Review by Nullably — APPROVED** [review]
LGTM

**Pull request merged**
