### PR TITLE
fix/fees ftx

### LINKED ISSUE #2084: [BUG] Filled order fees are not recorded correctly
**Describe the bug**

Fees for orders that are filled are not recorded correctly for many connectors, instead of taking fees reported from exchange's API, the connectors call `c_get_fee` (which estimates fee). This results in incorrect fees stored on trades table (sqlite) and incorrect performance reported on `history` command.

This mistake was partly due to Binance connector had this bug which other connectors copied the code from. The bug was fixed on 29 December 2020 on Binance connector so connectors created after the date should not get affected.

Connectors which broadcast fee incorrectly on `OrderFilledEvent`:

- [ ] ~Kucoin~
- [x] Binance Perpetual Derivative
- [x] Bifinex
- [x] Coinbase Pro
- [x] Bittrex
- [ ] ~OkEx~
- [x] Huobi
- [ ] ~Beaxy~
- [x] FTX
- [ ] ~Blocktane~
- [ ] ~Coinzoom~
- [ ] ~DigiFinex~
- [x] Gate.io
- [ ] Liquid

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd1e7e) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by aarmoa**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
The PR include the required changes to consider the fees informed by the exchange when a trade takes place, instead of estimating them.
The PR includes a change to allow the client to give more priority to fill events and try to process them before the complete events, but without blocking the latter.
Partially closes #2084

**Tests performed by the developer**:
Added new unit tests for the order fill process and the fees registration

**Tips for QA testing**:
Please check that partial and complete fills are working correctly in FTX connector. Also verify if the fees are now being registered correctly.

### CODE REVIEW

**Comment by rxlxrxsx** [comment]
- There are instances that filled orders are not being tracked on history, bottom nav and data files (csv/sqlite)

Screen Shot 2021-12-13 at 9 11 42 AM
Screen Shot 2021-12-13 at 9 13 02 AM

Log/config/data: [ftx.zip](https://github.com/CoinAlpha/hummingbot/files/7700373/ftx.zip)

**Comment by aarmoa** [comment]
Hello @rxlxrxsx. I think the 1 second wait time I added in the logic is not being enough to receive the filled updates from FTX. I will add a change to make it 2 seconds, and also to explicitly log when the wait time finishes without receiving the fill updates, so that we can detect them easier.

**Comment by aarmoa** [comment]
I have made the changes. If the order fill updates don't arrive on time now the connector will log a warning with the following text: 
```
The order fill updates did not arrive on time for {ORDER_ID}. The complete update will be processed with estimated fees.
```

**Comment by rapcmia** [comment]
While testing partially filled orders, I've noticed that the FTX connector's trade history shows a record of completed partial orders however its not available on the client's logs, history, csv and sqlite file. On the screenshot below I tested with an order amount of `100` and on the bid order price of `0.15678300`, you would noticed that the remaining partial order has been completed however its not being recorded

image

Checking the logs, it doesn't seem to show any record of the completed partial filled order of `4.00000000`:
```
# Create bid/ask order
2021-12-13 15:55:04,000 - 12108 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (DOGE-USDT) Creating 1 bid orders at (Size, Price): ['1E+2 DOGE, 0.156783 USDT']
2021-12-13 15:55:04,001 - 12108 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (DOGE-USDT) Creating 1 ask orders at (Size, Price): ['1E+2 DOGE, 0.1577265 USDT']
2021-12-13 15:55:04,303 - 12108 - hummingbot.connector.exchange.ftx.ftx_exchange - INFO - Created LIMIT buy order FTX-buy-DOGE-USDT-1639410904001110 for 100.0 DOGE-USDT
2021-12-13 15:55:04,312 - 12108 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1639410904.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "DOGE-USDT", "amount": "100.0", "price": "0.1567830", "order_id": "FTX-buy-DOGE-USDT-1639410904001110", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "BuyOrderCreatedEvent", "event_source": "ftx"}
2021-12-13 15:55:04,539 - 12108 - hummingbot.connector.exchange.ftx.ftx_exchange - INFO - Created LIMIT sell order FTX-sell-DOGE-USDT-1639410904001320 for 100.0 DOGE-USDT.
2021-12-13 15:55:04,548 - 12108 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1639410904.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "DOGE-USDT", "amount": "100.0", "price": "0.1577265", "order_id": "FTX-sell-DOGE-USDT-1639410904001320", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "SellOrderCreatedEvent", "event_source": "ftx"}

# Partially filled 96 out of 100.0 
2021-12-13 15:55:16,512 - 12108 - hummingbot.connector.exchange.ftx.ftx_exchange - INFO - Filled 96.0 out of 100.0 of the limit buy order FTX-buy-DOGE-USDT-1639410904001110
2021-12-13 15:55:16,513 - 12108 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (DOGE-USDT) Maker buy order of 96.0 DOGE filled. [clock=2021-12-13 15:55:16+00:00]
2021-12-13 15:55:16,536 - 12108 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1639410916.0, "order_id": "FTX-buy-DOGE-USDT-1639410904001110", "trading_pair": "DOGE-USDT", "trade_type": "TradeType.BUY", "order_type": "OrderType.LIMIT_MAKER", "price": "0.156783", "amount": "96.0", "trade_fee": ["0", [["DOGE", "0.0192"]]], "exchange_trade_id": 2779896812, "leverage": 1, "position": "NILL", "event_name": "OrderFilledEvent", "event_source": "ftx"}

# Market buy order completed
2021-12-13 15:55:16,537 - 12108 - hummingbot.connector.exchange.ftx.ftx_exchange - INFO - The market buy order FTX-buy-DOGE-USDT-1639410904001110 has completed according to user stream.
2021-12-13 15:55:16,537 - 12108 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (DOGE-USDT) Maker buy order FTX-buy-DOGE-USDT-1639410904001110 (100.0 DOGE @ 0.1567830 USDT) has been completely filled. [clock=2021-12-13 15:55:16+00:00]
```

CSV file:
image

Attached logs,config and CSV file:
[pmm-test.zip](https://github.com/CoinAlpha/hummingbot/files/7705328/pmm-test.zip)

**Comment by aarmoa** [comment]
Hello @rapcmia. The order update message processing was updating the executed amount value in the inflight order (that should be only updated by the order fill update). I have added a fix for that.

**Review by RC-13 — APPROVED** [review]
Confirming that partial fills are now recorded in the history and data files (sqlite and csv), also all trades have been recorded and fees deducted for each trade are correct. LGTM!

**Review by CrimsonJacket — APPROVED** [review]
Changes LGTM.

**Pull request merged**
