### PR TITLE
[v0.34] Feat / Updated configurable Perpetua Market Making Parameters

### PR DESCRIPTION
**Pull request by vic-en**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**After creating this PR, please make sure:**

- [x] You link the related GitHub issue or ticket

**A description of the changes proposed in the pull request**:

### CODE REVIEW

**Comment by Nullably** [comment]
Not sure if we still need this, also the better approach is to not have the configs that are not working or not compatible with Perpetual MM in the config map in the first place.

**Comment by vic-en** [comment]
- Removed unused parameters
- Exchange connectors and custom price source can now be used as price source as requested in #2573

**Comment by rxlxrxsx** [comment]
- ``price_source_derivative`` parameter is still present on current config map.
- I used the ``price_source_derivative`` parameter to choose from exchanges and can confirm most exchanges works except for ``binance_perpetual`` and ``binance_perpetual_testnet``
- Should ``price_source_derivative`` be renamed to ``price_source_exchange``?

- The following parameters are now removed from the perpetual market making strategy config map:
``inventory_skew_enabled``
``inventory_target_base_pct``
``inventory_range_multiplier``

**Comment by vic-en** [comment]
@rxlxrxsx Thanks for the update.
You're right, Binance perpetual and Binance perpetual testnet shouldn't work as a price source atm.
But other derivative connectors should work provided they're not initialized like the binance perpetual connector.

**Comment by rxlxrxsx** [comment]
As discussed with @vic-en there are still some changes to be made with this PR. Will continue testing when there are new commits or when advised ready for QA testing.

**Comment by vic-en** [comment]
@rxlxrxsx 
All is set now.
Either of main perpetual or testnet can  now also be used as price source.

**Comment by rxlxrxsx** [comment]
Confirmed fix for issues listed above and no other issues found during testing by QA.

**Review by dennisocana — APPROVED** [review]
Tested by QA and confirmed working.

**Pull request merged**
