### PR TITLE
fix / Mapping of Kraken trading pairs

### PR DESCRIPTION
**Pull request by keithbaum**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

This should fix issues #1781 #2953 #2930 .
Please test replicating each case scenario for issues.

### CODE REVIEW

**Review by CrimsonJacket — APPROVED** [review]
LGTM. QA team do verify

**Comment by rxlxrxsx** [comment]
- Getting this error every 10 seconds after starting the strategy. It seems to only affect BTC and DOGE related pairs based on testing.
Screen Shot 2021-02-24 at 8 34 43 AM

```
2021-02-24 08:12:20,414 - 2479 - hummingbot.connector.exchange.kraken.kraken_exchange - NETWORK - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 588, in hummingbot.connector.exchange.kraken.kraken_exchange.KrakenExchange._status_polling_loop
    await safe_gather(
  File "/Users/reiniersalazar/hummingbot/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 228, in _update_balances
    (base, quote) = self.split_trading_pair(pair)
  File "hummingbot/connector/connector_base.pyx", line 96, in hummingbot.connector.connector_base.ConnectorBase.split_trading_pair
    return tuple(trading_pair.split('-'))
AttributeError: 'NoneType' object has no attribute 'split'
```

- Getting this error for pairs `ETH-BTC` and `BTC-USD` causing the bot to fail on submitting orders upon starting the strategy
Screen Shot 2021-02-24 at 12 37 35 PM

```
2021-02-24 12:37:22,253 - 4228 - hummingbot.connector.exchange.kraken.kraken_exchange - ERROR - Error received from https://api.kraken.com/0/private/AddOrder. Response is {'error': ['EOrder:Invalid price:XETHXXBT price can only be specified up to 5 decimals.']}.
2021-02-24 12:37:22,255 - 4228 - hummingbot.connector.exchange.kraken.kraken_exchange - NETWORK - Error submitting sell LIMIT_MAKER order to Kraken for 0.00500000 ETH-BTC 0.032986.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 947, in hummingbot.connector.exchange.kraken.kraken_exchange.KrakenExchange.execute_sell
    order_result = await self.place_order(userref=userref,
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 826, in place_order
    return await self._api_request_with_retry("post",
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 736, in _api_request_with_retry
    raise e
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 722, in hummingbot.connector.exchange.kraken.kraken_exchange.KrakenExchange._api_request_with_retry
    result= await self._api_request(method, path_url, params, data, is_auth_required, request_weight)
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 748, in _api_request
    async with self._throttler.weighted_task(request_weight=request_weight):
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 768, in hummingbot.connector.exchange.kraken.kraken_exchange.KrakenExchange._api_request
    async with response_coro as response:
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 793, in hummingbot.connector.exchange.kraken.kraken_exchange.KrakenExchange._api_request
    raise IOError({"error": response_json})
OSError: {'error': {'error': ['EOrder:Invalid price:XETHXXBT price can only be specified up to 5 decimals.']}}
2021-02-24 12:37:22,256 - 4228 - hummingbot.connector.exchange.kraken.kraken_exchange - WARNING - Failed to submit sell order to Kraken. Check API key and network connection.
2021-02-24 12:37:22,261 - 4228 - hummingbot.connector.exchange.kraken.kraken_exchange - ERROR - Error received from https://api.kraken.com/0/private/AddOrder. Response is {'error': ['EOrder:Invalid price:XETHXXBT price can only be specified up to 5 decimals.']}.
2021-02-24 12:37:22,262 - 4228 - hummingbot.connector.exchange.kraken.kraken_exchange - NETWORK - Error submitting buy LIMIT_MAKER order to Kraken for 0.00500000 ETH-BTC 0.031064.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 865, in hummingbot.connector.exchange.kraken.kraken_exchange.KrakenExchange.execute_buy
    order_result = await self.place_order(userref=userref,
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 826, in place_order
    return await self._api_request_with_retry("post",
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 736, in _api_request_with_retry
    raise e
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 722, in hummingbot.connector.exchange.kraken.kraken_exchange.KrakenExchange._api_request_with_retry
    result= await self._api_request(method, path_url, params, data, is_auth_required, request_weight)
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 748, in _api_request
    async with self._throttler.weighted_task(request_weight=request_weight):
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 768, in hummingbot.connector.exchange.kraken.kraken_exchange.KrakenExchange._api_request
    async with response_coro as response:
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 793, in hummingbot.connector.exchange.kraken.kraken_exchange.KrakenExchange._api_request
    raise IOError({"error": response_json})
OSError: {'error': {'error': ['EOrder:Invalid price:XETHXXBT price can only be specified up to 5 decimals.']}}
2021-02-24 12:37:22,262 - 4228 - hummingbot.connector.exchange.kraken.kraken_exchange - WARNING - Failed to submit buy order to Kraken. Check API key and network connection.
```

Screen Shot 2021-02-24 at 12 40 03 PM

```
2021-02-24 12:39:51,193 - 4279 - hummingbot.connector.exchange.kraken.kraken_exchange - ERROR - Error received from https://api.kraken.com/0/private/AddOrder. Response is {'error': ['EOrder:Invalid price:XXBTZUSD price can only be specified up to 1 decimals.']}.
2021-02-24 12:39:51,194 - 4279 - hummingbot.connector.exchange.kraken.kraken_exchange - NETWORK - Error submitting buy LIMIT_MAKER order to Kraken for 0.00020000 BTC-USD 49108.820.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 865, in hummingbot.connector.exchange.kraken.kraken_exchange.KrakenExchange.execute_buy
    order_result = await self.place_order(userref=userref,
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 826, in place_order
    return await self._api_request_with_retry("post",
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 736, in _api_request_with_retry
    raise e
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 722, in hummingbot.connector.exchange.kraken.kraken_exchange.KrakenExchange._api_request_with_retry
    result= await self._api_request(method, path_url, params, data, is_auth_required, request_weight)
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 748, in _api_request
    async with self._throttler.weighted_task(request_weight=request_weight):
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 768, in hummingbot.connector.exchange.kraken.kraken_exchange.KrakenExchange._api_request
    async with response_coro as response:
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 793, in hummingbot.connector.exchange.kraken.kraken_exchange.KrakenExchange._api_request
    raise IOError({"error": response_json})
OSError: {'error': {'error': ['EOrder:Invalid price:XXBTZUSD price can only be specified up to 1 decimals.']}}
2021-02-24 12:39:51,196 - 4279 - hummingbot.connector.exchange.kraken.kraken_exchange - WARNING - Failed to submit buy order to Kraken. Check API key and network connection.
2021-02-24 12:39:51,334 - 4279 - hummingbot.connector.exchange.kraken.kraken_exchange - ERROR - Error received from https://api.kraken.com/0/private/AddOrder. Response is {'error': ['EOrder:Invalid price:XXBTZUSD price can only be specified up to 1 decimals.']}.
2021-02-24 12:39:51,335 - 4279 - hummingbot.connector.exchange.kraken.kraken_exchange - NETWORK - Error submitting sell LIMIT_MAKER order to Kraken for 0.00020000 BTC-USD 52146.480.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 947, in hummingbot.connector.exchange.kraken.kraken_exchange.KrakenExchange.execute_sell
    order_result = await self.place_order(userref=userref,
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 826, in place_order
    return await self._api_request_with_retry("post",
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 736, in _api_request_with_retry
    raise e
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 722, in hummingbot.connector.exchange.kraken.kraken_exchange.KrakenExchange._api_request_with_retry
    result= await self._api_request(method, path_url, params, data, is_auth_required, request_weight)
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 748, in _api_request
    async with self._throttler.weighted_task(request_weight=request_weight):
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 768, in hummingbot.connector.exchange.kraken.kraken_exchange.KrakenExchange._api_request
    async with response_coro as response:
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 793, in hummingbot.connector.exchange.kraken.kraken_exchange.KrakenExchange._api_request
    raise IOError({"error": response_json})
OSError: {'error': {'error': ['EOrder:Invalid price:XXBTZUSD price can only be specified up to 1 decimals.']}}
2021-02-24 12:39:51,336 - 4279 - hummingbot.connector.exchange.kraken.kraken_exchange - WARNING - Failed to submit sell order to Kraken. Check API key and network connection.
```

Logs: [logs_kraken_test.log](https://github.com/CoinAlpha/hummingbot/files/6033414/logs_kraken_test.log)
Config: [kraken_test.txt](https://github.com/CoinAlpha/hummingbot/files/6033419/kraken_test.txt)

**Comment by keithbaum** [comment]
Hi @rxlxrxsx ,
I've pushed a new commit to fix both issues you found. Please try now. Thanks

**Comment by rxlxrxsx** [comment]
Tested and confirmed fix for issues listed above. One minor issue found, Available balance is not updating when there are open orders:

Screen Shot 2021-02-28 at 12 29 39 PM
Screen Shot 2021-02-28 at 12 42 41 PM

**Review by CrimsonJacket — APPROVED** [review]
LGTM 🐙

**Pull request merged**
