### PR TITLE
fix/ `config` command accepting spaces in values

### PR DESCRIPTION
**Pull request by CrimsonJacket**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Modify `_handle_command()` in `HummingbotApplication` to handle commands that accept values with spaces
Note:
All users inputs should strictly follow the following format:
`>>> <command> [argument] [value]`

**Tests performed by the developer**:
Made modifications to `_handle_command()` to specifically handle `config` command.

**Tips for QA testing**:
Ensure that Avellaneda's `config execution_timeframe`(specifically for `from_date_to_date` now works as intended
Verify that other commands and strategy configs that required spaces in its value works as intended.

### CODE REVIEW

**Comment by CrimsonJacket** [comment]
[sc-21323]

**Review by mhrvth — CHANGES_REQUESTED** [review]
I'm not sure if this is the best solution since it assumes there will be only one parameter at most ever, in every command. Probably a better solution would be to enclose arguments with spaces inside parentheses, and add that to parsing.

**Comment by CrimsonJacket** [comment]
> I'm not sure if this is the best solution since it assumes there will be only one parameter at most ever, in every command. Probably a better solution would be to enclose arguments with spaces inside parentheses, and add that to parsing.

Sorry I'm quite sure I'm understanding this.

You're saying we should allow for the handling of the following situation

config argument_1 value with space 1 argument_2 value with space 2

**Comment by mhrvth** [comment]
> 




> > I'm not sure if this is the best solution since it assumes there will be only one parameter at most ever, in every command. Probably a better solution would be to enclose arguments with spaces inside parentheses, and add that to parsing.
> 
> Sorry I'm quite sure I'm understanding this.
> 
> You're saying we should allow for the handling of the following situation
> 
> `config argument_1 value with space 1 argument_2 value with space 2`

This is a general command parser, so it doesn't apply just to the config command.

If we have something like this in the future the parser should be able to handle it:

`order_book --live --tab `

With setting it to maxsplit = 2 you're limiting all commands to having only 1 parameter at most. So although it works now, it's not a universal solution in my opinion.

**Comment by CrimsonJacket** [comment]
@mhrvth After some discussion with the team during ytd's standup, it is decided that we should create another task to implement/refactor the existing command parser to accommodate the scenario you've described above. For now, I will ping @CoinAlpha/qa-team to begin testing this PR.

**Comment by nikspz** [comment]
- create ave_mm strategy = OK
          - execution timeframe selection = OK
                - infinite = OK
                - setting up from_date_to_date with whitespace - OK
                - daily_between_times = OK
                
Issue:                
orders not cancelled after `order_refresh_time`  and after `end_time`
checking now on dev branch
image
image

**Comment by mhrvth** [comment]
> ```
>       - create ave_mm strategy = OK
>       - execution timeframe selection = OK
>             - infinite = OK
>             - setting up from_date_to_date with whitespace - OK
>             - daily_between_times = OK
> ```
> 
> Issue: orders not cancelled after `order_refresh_time` and after `end_time` checking now on dev branch image image

I don't think this is related. But to clarify, the orders don't have to be cancelled at order refresh time if the difference from the proposal is within tolerance.

**Review by mhrvth — APPROVED** [review]
Given the @CrimsonJacket 's last comment, I'm approving the PR.

**Review by nikspz — APPROVED** [review]

**Comment by nikspz** [comment]
The issue above is not related to that PR
Got the same issue on development branch

image
image

**Comment by CrimsonJacket** [comment]
Closed and re-opened a PR in Foundation Repo.
https://github.com/hummingbot/hummingbot/pull/5020

**Pull request closed without merging**
