### PR TITLE
[v0.38] CoinZoom: Update user-agent for order book WS requests

### PR DESCRIPTION
**Pull request by TheHolyRoger**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
As requested by CoinZoom, this PR updates the user-agent sent for unauthenticated Websocket requests.
@dennisocana @CrimsonJacket

### CODE REVIEW

**Comment by RC-13** [comment]
Test PR and sent sample trades, just waiting for confirmation if the orders got picked up before approving the pull request.

**Review by CrimsonJacket — COMMENTED** [review]
Is there a need for this `User-Agent` header for public websocket channels?

**Comment by TheHolyRoger** [comment]
@CrimsonJacket Yes it's for their WAF rules

**Review by CrimsonJacket — APPROVED** [review]
@TheHolyRoger LGTM.

**Pull request merged**
