### PR TITLE
feat / Bitstamp connector

### PR DESCRIPTION
**Pull request by oparex**
Implemented market connector for Bitstamp exchange. The old Market base implemented first, then refactored to the new exchange base, so methods are implemented in cython. Integration tests are implemented and are passing if run one by one. I did not bother with using 2 markets in integration tests. Mock tests are not implemented yet so testing in production is required.

### CODE REVIEW

**Review by TomasFlow — APPROVED** [review]

**Review by TomasFlow — APPROVED** [review]

**Comment by mifeng** [comment]
@dennisocana @RC-13 we need to review this connector during this release. I've contacted the developer and waiting for him to confirm whether he's available to make changes.

**Comment by dennisocana** [comment]
Thanks @mifeng will continue to monitor and test as soon as it's ready.

**Comment by mifeng** [comment]
Actually, I think we should start the review process with this connector. Unlike dy/dx and Loopring, I believe this dev is an individual who built the connector in their spare time, so they may not be available to make fixes.

Since our community chose this connector after governance, we should finish it up if the code is consistent with our other connectors.

**Comment by RC-13** [comment]
Tested connector and here are the following issue/feature that are not working:

1. unit test failed for `test_bitstamp_api_order_book_data_source.py` and stuck for `test_bitstamp_market.py`
2. paper trade not supported
3. market auto-complete list : not available
4. suggested minimum order_amount : shows 0 despite having the quote token added on min_quote_order_amount	
5. price types not working: set `last_trade`, `best_bid`, and `best_ask` but bot still uses the mid price
6. After running long term test bot (more than 15hrs) with high order_refresh_tolerance (5%)
  -> order did not refresh for more than 15 hrs
    -> history: no past trade
    -> check exchange: Sell order showing on the bot was already filled (lost tracked)
    -> check csv and sqlite: no csv, no filled order on sqlite and save 2 orders only on the order table
  - review logs
    -> no filled events
    -> no more order created on logs after `2020-12-23 09:45:08,789` - bot continously trying to cancel the last sell order created but never been successful.
    -> base on bitstamp exchange, order was filled around 12:41 however on the logs it says that orders won't be cancelled due to tolerance
  - stop and exit from bot : stuck cancelling so I had to kill the instance, usually happens when there are error encountered	
  - import and start strategy
    -> Filled event was restored and csv file is created
    -> run history : filled trade is now showing and using the current time as the filled event time  
Bitstamp status and balance
Bitstamp open orders
Bitstamp history
Bitstamp transaction history

**Comment by dennisocana** [comment]
Hummingbot team will try to get the developer docs updated in the next few weeks in order to make the updates to this PR. Moving the target release date of this connector into February v0.36 release.

**Comment by CrimsonJacket** [comment]
@oparex We have since made substantial design changes to implementing connectors and additionally, the current implementation seems to be missing User Websocket Streams. The dev team has decided to assume the development of this connector moving forward.

**Comment by dennisocana** [comment]
The PR has become stale and outdated. We agreed to close for now to trim down the backlog of open pull requests. We can reopen anytime if work will be resumed and for review.

**Pull request closed without merging**
