### PR TITLE
hotfix / KuCoin failing to fetch order book snapshots

### LINKED ISSUE #3505: Kucoin - Connector unusable due to failure to fetch market snapshot
Upon starting the bot with Kucoin as the spot connector, it throws a 404 error and doesn't create orders. The error only happens when you restart the bot and after that the strategy won't start and the connector is unusable. Tested on all build on v0.39 and dev v0.40

**Steps To Reproduce**
1. Create a Pure market making bot
2. Choose Kucoin as the spot connector
3. Start the strategy, upon starting the strategy it will throw you an error and it will not create orders.

image

It affects all trading pairs on Kucoin. It doesn't effect specific trading pairs only.

**Release version**

The build for this screenshot is on dev v0.40 source build

**Attachments**
```
error in background task: Error fetching Kucoin market snapshot for DIVI-USDT. HTTP status is 404.
Traceback (most recent call last):
  File "/Users/jeremykono/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/jeremykono/hummingbot/hummingbot/core/data_type/order_book_tracker.py", line 178, in _init_order_books
    self._order_books[trading_pair] = await self._data_source.get_new_order_book(trading_pair)
  File "/Users/jeremykono/hummingbot/hummingbot/connector/exchange/kucoin/kucoin_api_order_book_data_source.py", line 335, in get_new_order_book
    snapshot: Dict[str, Any] = await self.get_snapshot(client, trading_pair)
  File "/Users/jeremykono/hummingbot/hummingbot/connector/exchange/kucoin/kucoin_api_order_book_data_source.py", line 328, in get_snapshot
    raise IOError(f"Error fetching Kucoin market snapshot for {trading_pair}. "
OSError: Error fetching Kucoin market snapshot for DIVI-USDT. HTTP status is 404.
2021-06-04 20:02:28,334 - 3134 - hummingbot.connector.exchange.kucoin.kucoin_api_user_stream_data_source - INFO - Connecting to wss://push-private.kucoin.com/endpoint?token=2neAiuYvAU737TOajb2U3uT8AEZqSWYe0fBD4LoHuXJDSC7gIzJiH4kNTWhCPISWo6nDpAe7aUaSjjt8hEIwOZ8UVxbWZO9VBlSGde-PDEl0Pd2CJo_e_HwZIngtMdMrjqPnP-biofE9rS8ZTR6fqOMqmuq9FDS6JBvJHl5Vs9Y=._z8rPhNUT7BbHKZrI2mXHQ==&acceptUserMessage=true.
2021-06-04 20:02:28,340 - 3134 - hummingbot.connector.exchange.kucoin.kucoin_api_order_book_data_source - ERROR - Unexpected error.
Traceback (most recent call last):
  File "/Users/jeremykono/hummingbot/hummingbot/connector/exchange/kucoin/kucoin_api_order_book_data_source.py", line 514, in listen_for_order_book_snapshots
    snapshot: Dict[str, Any] = await self.get_snapshot(client, trading_pair)
  File "/Users/jeremykono/hummingbot/hummingbot/connector/exchange/kucoin/kucoin_api_order_book_data_source.py", line 328, in get_snapshot
    raise IOError(f"Error fetching Kucoin market snapshot for {trading_pair}. "
OSError: Error fetching Kucoin market snapshot for DIVI-USDT. HTTP status is 404.
```
[logs_conf_pure_mm_3.log](https://github.com/CoinAlpha/hummingbot/files/6598568/logs_conf_pure_mm_3.log)

### PR DESCRIPTION
**Pull request by CrimsonJacket**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

Fixes #3505 It seems like Kucoin has updated their market order book endpoint without any notice. 

Below are the findings:
- From `GET /api/v2/market/orderbook/level2` -> `GET /api/v3/market/orderbook/level2`
  - This results in the HTTP 404 error 
- V3 API endpoint now requires user to sign the request

### CODE REVIEW

**Comment by JeremyKono** [comment]
Tested and confirmed that it fixed the issue of orders not being created. 
image

**Comment by JeremyKono** [comment]
`paper_trade` doesn't work anymore with Kucoin. Returns this error:

image

```

021-06-04 22:06:59,551 - 4674 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: code = 1000 (OK), no reason
Traceback (most recent call last):
  File "/Users/jeremykono/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/jeremykono/hummingbot/hummingbot/connector/exchange/kucoin/kucoin_api_order_book_data_source.py", line 195, in _ping_loop
    await ws.ensure_open()
  File "/Users/jeremykono/anaconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: code = 1000 (OK), no reason
2021-06-04 22:07:09,896 - 4674 - hummingbot.client.hummingbot_application - ERROR - Unknown error during initialization.
Traceback (most recent call last):
  File "/Users/jeremykono/hummingbot/hummingbot/strategy/pure_market_making/start.py", line 59, in start
    self._initialize_markets(market_names)
  File "/Users/jeremykono/hummingbot/hummingbot/client/hummingbot_application.py", line 231, in _initialize_markets
    connector = create_paper_trade_market(connector_name, trading_pairs)
  File "/Users/jeremykono/hummingbot/hummingbot/connector/exchange/paper_trade/__init__.py", line 26, in create_paper_trade_market
    return PaperTradeExchange(obt_class(**conn_setting.add_domain_parameter(obt_params)),
TypeError: __init__() missing 1 required positional argument: 'auth'
2021-06-04 22:07:09,902 - 4674 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2021-06-04 22:10:35,830 - 4674 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2021-06-04 22:10:35,832 - 4674 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: list.remove(x): x not in list
Traceback (most recent call last):
  File "/Users/jeremykono/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/jeremykono/hummingbot/hummingbot/client/command/stop_command.py", line 37, in stop_loop
    self.clock.remove_iterator(self.strategy)
  File "hummingbot/core/clock.pyx", line 83, in hummingbot.core.clock.Clock.remove_iterator
    self._child_iterators.remove(iterator)
ValueError: list.remove(x): x not in list
```
[logs_conf_pure_mm_3.log](https://github.com/CoinAlpha/hummingbot/files/6599069/logs_conf_pure_mm_3.log)

**Comment by JeremyKono** [comment]
After turning on `paper_trade` then switching back to live, it throws errors and strategy from when `paper_trade` is on cannot be stopped, hence the bot will not work unless you exit and start the bot again.
image

```
ValueError: list.remove(x): x not in list
2021-06-04 22:20:32,880 - 4674 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2021-06-04 22:20:32,881 - 4674 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: list.remove(x): x not in list
Traceback (most recent call last):
  File "/Users/jeremykono/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/jeremykono/hummingbot/hummingbot/client/command/stop_command.py", line 37, in stop_loop
    self.clock.remove_iterator(self.strategy)
  File "hummingbot/core/clock.pyx", line 83, in hummingbot.core.clock.Clock.remove_iterator
    self._child_iterators.remove(iterator)
ValueError: list.remove(x): x not in list
```
[logs_conf_pure_mm_3.log](https://github.com/CoinAlpha/hummingbot/files/6599124/logs_conf_pure_mm_3.log)

**Review by keithbaum — DISMISSED** [review]
Changes LGTM

**Review by dennisocana — APPROVED** [review]
Resubmitting approval.

**Pull request merged**
