### PR TITLE
[v0.30] Removes price_source_enabled and adds mid_price to price_source_type

### PR DESCRIPTION
**Pull request by petioptrv**
**Before submitting this PR, please make sure**:
- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue: #1917 
- Related Clubhouse Story:

**A description of the changes proposed in the pull request**:

### CODE REVIEW

**Comment by petioptrv** [comment]
@Nullably, I'd like to make it possible to disable external source after it has been configured, but couldn't find a clean way to do it. Specifically, could not set price_source_market to None if price_source_exchange was set to None through the config command. Is there a parameter combo that I can take a look at and model to do this?

**Comment by Nullably** [comment]
> @Nullably, I'd like to make it possible to disable external source after it has been configured, but couldn't find a clean way to do it. Specifically, could not set price_source_market to None if price_source_exchange was set to None through the config command. Is there a parameter combo that I can take a look at and model to do this?

@petioptrv 
Sorry, I don't quite understand, can you elaborate your questions a bit more?
The  `price_source_market` and `price_source_exchange` should both have values, or both are None. 
If you mean to set `price_source_market` to None, when `price_source_exchange` is set to None, then you can do use `on_validated` e.g.:
```
"price_source_exchange":
        ConfigVar(key="price_source_exchange",
                  prompt="Enter external price source exchange name (empty to disable) >>> ",
                  required_if=lambda: pure_market_making_config_map.get("price_source_type") == "mid_price",
                  type_str="str",
                  validator=validate_price_source_exchange,
                  on_validated=lambda v: pure_market_making_config_map["price_source_market"].value = None if v is None else pure_market_making_config_map["price_source_market"].value
)
```

**Comment by mifeng** [comment]
Since this is part 1 of a series of enhancements to the Price Source feature, I think we should wait until it's complete before merging this branch to `development`. It may not be done until v0.30 release.

**Comment by mifeng** [comment]
Here's the branch I mentioned: https://github.com/CoinAlpha/hummingbot/tree/price-source

**Comment by petioptrv** [comment]
@Nullably, @mifeng, I attempted to fix the problem of disabling external exchange, but I can see why we had a "switch" for it before. The switch made it so that when it was set to `False`, it would set to `None` all concerned config vars. Now, if the user passes an empty string to the `price_source_exchange` prompt, there is no elegant way of setting its value to `None`. 

I propose we bring back the switch as `external_price_source_enabled` and require it only if `price_source_type` is set to `mid_price`. Switching it to `False` will set `price_source_exchange`, `price_source_market` and `take_if_crossed` to `None`.

**Comment by petioptrv** [comment]
> Here's the branch I mentioned: https://github.com/CoinAlpha/hummingbot/tree/price-source

Just got to that. No problem, I will roll-back merging `development` into my branch and switch the PR to `price-source`.

**Comment by Nullably** [comment]
@petioptrv 
> @Nullably, @mifeng, I attempted to fix the problem of disabling external exchange, but I can see why we had a "switch" for it before. The switch made it so that when it was set to False, it would set to None all concerned config vars. Now, if the user passes an empty string to the price_source_exchange prompt, there is no elegant way of setting its value to None.

Ok, thanks, I now understand the issue. I am proposing a small change in the requirement, let me know what you think.
https://github.com/CoinAlpha/hummingbot/issues/1917#issuecomment-654936952
This will help solve problem above, we only need to validate `price_source_exchange` input if `price_source` is set to `external_market`.

**Comment by petioptrv** [comment]
@Nullably, @mifeng, the changes as discussed in #1917. I have not included `price_type` as that is part of a subsequent issue.

**Pull request merged**
