### PR TITLE
Feat/update gateway script

### PR DESCRIPTION
**Pull request by vic-en**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This PR updates the gateway docker script. 

**Tests performed by the developer**:
Run `create-gateway.sh` and simply test the Balancer connector.

**Tips for QA testing**:

### CODE REVIEW

**Comment by PtrckM** [comment]
- linking issue https://github.com/CoinAlpha/hummingbot/issues/4207

- bot getting this because of the NaN on gateway
Screen Shot 2021-09-18 at 9 06 16 AM
Screen Shot 2021-09-18 at 9 16 15 AM
- even using manual gas price still getting error fetching data
Screen Shot 2021-09-18 at 9 46 56 AM

- this lines need to change from `$MANUAL_GAS_PRICE ` to `$ETH_MANUAL_GAS_PRICE`
https://github.com/CoinAlpha/hummingbot/pull/4214/files#R337
https://github.com/CoinAlpha/hummingbot/pull/4214/files#R377

- fixing the NaN issue from above will fix the problem but when when enabling gas price lookup will cause the NaN again.
image
image

- changing `echo "ETH_MANUAL_GAS_PRICE: 100" >> $ENV_FILE` from https://github.com/CoinAlpha/hummingbot/pull/4214/files#R377 will fix the issue, similar on source build true or false its declared 
image

- however fixing the issue above also found out that even enabled gas price the gateway still uses the manual price causing the calculation of profitability a little bit off. This only happens on docker build.
image

- fixing the NaN Issue will also fix this bug: https://github.com/CoinAlpha/hummingbot/issues/4002

**Comment by vic-en** [comment]
@PtrckM All issues related to gas price should be fixed now. Kindly let me know if you still get any error(s).

**Review by PtrckM — APPROVED** [review]
Confirmed all issues mentioned are fixed. Approving

**Review by Nullably — APPROVED** [review]
LGTM

**Pull request merged**
