### PR TITLE
feat/ new connector exchange Digifinex

### PR DESCRIPTION
**Pull request by szmcdull**
new connector exchange Digifinex

### CODE REVIEW

**Comment by dennisocana** [comment]
@keithbaum's feedback to this connector looks good overall, will spend one more day to run some more tests. Meanwhile, @RC-13 please have QA team set up and deploy long term test bots in this branch and see if there are critical issues we need to fix. Moving to Review/QA

**Comment by RC-13** [comment]
@szmcdull We're having an issue when connecting API keys, the following message keeps coming up:
image
this happens locally and even on cloud

**Comment by RC-13** [comment]
Re-testing pull request, here are some of the issue encountered during testing:
1. When the bot is interrupted and trying to fetch account update, it shows crypto.com instead of Digifinex
Digifinex

2. After running the bot for a while, running the stop command will result in some orders failing to cancel although they get cancelled on the exchange. You need to run the stop command twice to successfully cancel this failed order else, if the bot is restarted it may turn into a non-existing hanging order.
Digifinex stop

We will continue testing once the API ban is lifted.

**Comment by RC-13** [comment]
After running the bot overnight, an intermittent WebSocket error occurred and the connection gets reset.
```
2021-03-15 18:00:02,417 - 5898 - hummingbot.connector.exchange.digifinex.digifinex_websocket - ERROR - Websocket error: 'server rejected WebSocket connection: HTTP 502'
Traceback (most recent call last):
  File "/home/ubuntu/hummingbot/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 50, in connect
    self._client = await websockets.connect(self._WS_URL)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/client.py", line 542, in __await_impl__
    await protocol.handshake(
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/client.py", line 296, in handshake
    raise InvalidStatusCode(status_code)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 502
```

[logs_conf_pure_mm_1.log](https://github.com/CoinAlpha/hummingbot/files/6145719/logs_conf_pure_mm_1.log)

**Comment by szmcdull** [comment]
>     * 20042

@RC-13 
1. Will fix this.
2. Could you check the log for the information details about how the canceling is failed? for example error code or message. The cancel endpoint should not fail even if the order does not exist. I guess it fails because of rate limit?
3. Sorry there is current no way to query to check if a trade pair is disabled for trading until the user query a trade.

**Comment by RC-13** [comment]
> 2. Could you check the log for the information details about how the canceling is failed? for example error code or message. The cancel endpoint should not fail even if the order does not exist. I guess it fails because of rate limit?

digi1
There are no error found on the logs or additional info, and did not hit the API rate limit.
```ruby
2021-03-16 15:01:52,008 - 3224 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Creating 1 bid orders at (Size, Price): ['0.008 ETH, 1788.88 USDT']
2021-03-16 15:01:52,008 - 3224 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Creating 1 ask orders at (Size, Price): ['0.008 ETH, 1806.85 USDT']
2021-03-16 15:01:52,560 - 3224 - hummingbot.connector.exchange.digifinex.digifinex_exchange - INFO - Created LIMIT_MAKER BUY order HBOT-B-ETH-USDT-1615878112008501 for 0.0080 ETH-USDT.
2021-03-16 15:01:52,573 - 3224 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1615878112.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ETH-USDT", "amount": "0.0080", "price": "1788.88", "order_id": "HBOT-B-ETH-USDT-1615878112008501", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "BuyOrderCreatedEvent", "event_source": "digifinex"}
2021-03-16 15:01:52,775 - 3224 - hummingbot.connector.exchange.digifinex.digifinex_exchange - INFO - Created LIMIT_MAKER SELL order HBOT-S-ETH-USDT-1615878112008730 for 0.0080 ETH-USDT.
2021-03-16 15:01:52,787 - 3224 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1615878112.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ETH-USDT", "amount": "0.0080", "price": "1806.85", "order_id": "HBOT-S-ETH-USDT-1615878112008730", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "SellOrderCreatedEvent", "event_source": "digifinex"}
2021-03-16 15:02:17,317 - 3224 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2021-03-16 15:02:18,425 - 3224 - hummingbot.connector.exchange.digifinex.digifinex_exchange - INFO - Successfully cancelled order HBOT-B-ETH-USDT-1615878112008501.
2021-03-16 15:02:18,435 - 3224 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1615878138.0, "order_id": "HBOT-B-ETH-USDT-1615878112008501", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "digifinex"}
2021-03-16 15:02:18,469 - 3224 - hummingbot.connector.exchange.digifinex.digifinex_exchange - INFO - Successfully cancelled order HBOT-S-ETH-USDT-1615878112008730.
2021-03-16 15:02:18,477 - 3224 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1615878138.0, "order_id": "HBOT-S-ETH-USDT-1615878112008730", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "digifinex"}
2021-03-16 15:02:42,920 - 3224 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
//after the second stop command, that's when the order_book initializes and allow the strategy to start
```
[logs_conf_pure_mm_2.log](https://github.com/CoinAlpha/hummingbot/files/6146742/logs_conf_pure_mm_2.log)

**Comment by szmcdull** [comment]
> 
> 
> > 1. Could you check the log for the information details about how the canceling is failed? for example error code or message. The cancel endpoint should not fail even if the order does not exist. I guess it fails because of rate limit?
> 
> digi1
> There are no error found on the logs or additional info, and did not hit the API rate limit.
> 
> ```ruby
> 2021-03-16 15:01:52,008 - 3224 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Creating 1 bid orders at (Size, Price): ['0.008 ETH, 1788.88 USDT']
> 2021-03-16 15:01:52,008 - 3224 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Creating 1 ask orders at (Size, Price): ['0.008 ETH, 1806.85 USDT']
> 2021-03-16 15:01:52,560 - 3224 - hummingbot.connector.exchange.digifinex.digifinex_exchange - INFO - Created LIMIT_MAKER BUY order HBOT-B-ETH-USDT-1615878112008501 for 0.0080 ETH-USDT.
> 2021-03-16 15:01:52,573 - 3224 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1615878112.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ETH-USDT", "amount": "0.0080", "price": "1788.88", "order_id": "HBOT-B-ETH-USDT-1615878112008501", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "BuyOrderCreatedEvent", "event_source": "digifinex"}
> 2021-03-16 15:01:52,775 - 3224 - hummingbot.connector.exchange.digifinex.digifinex_exchange - INFO - Created LIMIT_MAKER SELL order HBOT-S-ETH-USDT-1615878112008730 for 0.0080 ETH-USDT.
> 2021-03-16 15:01:52,787 - 3224 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1615878112.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ETH-USDT", "amount": "0.0080", "price": "1806.85", "order_id": "HBOT-S-ETH-USDT-1615878112008730", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "SellOrderCreatedEvent", "event_source": "digifinex"}
> 2021-03-16 15:02:17,317 - 3224 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
> 2021-03-16 15:02:18,425 - 3224 - hummingbot.connector.exchange.digifinex.digifinex_exchange - INFO - Successfully cancelled order HBOT-B-ETH-USDT-1615878112008501.
> 2021-03-16 15:02:18,435 - 3224 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1615878138.0, "order_id": "HBOT-B-ETH-USDT-1615878112008501", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "digifinex"}
> 2021-03-16 15:02:18,469 - 3224 - hummingbot.connector.exchange.digifinex.digifinex_exchange - INFO - Successfully cancelled order HBOT-S-ETH-USDT-1615878112008730.
> 2021-03-16 15:02:18,477 - 3224 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1615878138.0, "order_id": "HBOT-S-ETH-USDT-1615878112008730", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "digifinex"}
> 2021-03-16 15:02:42,920 - 3224 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
> //after the second stop command, that's when the order_book initializes and allow the strategy to start
> ```
> 
> [logs_conf_pure_mm_2.log](https://github.com/CoinAlpha/hummingbot/files/6146742/logs_conf_pure_mm_2.log)

Oh I checked the code of cancel_all (part of which is from crypto.com). After it cancels all open orders, it if checks each one still in the _in_flight_orders. So if order cancellation messages come after that, cancel_all will report the order failed to cancel.

**Comment by szmcdull** [comment]
> 
> 
> After running the bot overnight, an intermittent WebSocket error occurred and the connection gets reset.
> 
> ```
> 2021-03-15 18:00:02,417 - 5898 - hummingbot.connector.exchange.digifinex.digifinex_websocket - ERROR - Websocket error: 'server rejected WebSocket connection: HTTP 502'
> Traceback (most recent call last):
>   File "/home/ubuntu/hummingbot/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 50, in connect
>     self._client = await websockets.connect(self._WS_URL)
>   File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/client.py", line 542, in __await_impl__
>     await protocol.handshake(
>   File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/client.py", line 296, in handshake
>     raise InvalidStatusCode(status_code)
> websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 502
> ```
> 
> [logs_conf_pure_mm_1.log](https://github.com/CoinAlpha/hummingbot/files/6145719/logs_conf_pure_mm_1.log)

Seems there are many connection errors. What is the geo-location at which the test is performed? Can you try in different location?

**Comment by RC-13** [comment]
@szmcdull The geolocation set on our test bot is in Singapore, I'm trying other region (US-east) for now but I think there is a new issue that arise with the time server,
image
```
2021-03-17 12:29:53,910 - 2373 - hummingbot.connector.exchange.digifinex.time_patcher - NETWORK - Error getting Digifinex server time.
Traceback (most recent call last):
  File "/home/clint_g/hb-digifinex/hummingbot/connector/exchange/digifinex/time_patcher.py", line 96, in update_server_time_offset
    server_time = await query_time_func()
  File "/home/clint_g/hb-digifinex/hummingbot/connector/exchange/digifinex/digifinex_auth.py", line 38, in query_time_func
    resp_data: Dict[str, float] = await resp.json()
  File "/home/clint_g/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1026, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://openapi.digifinex.com/v3/time')
```

**Comment by szmcdull** [comment]
> 
> 
> @szmcdull The geolocation set on our test bot is in Singapore, I'm trying other region (US-east) for now but I think there is a new issue that arise with the time server,
> image
> 
> ```
> 2021-03-17 12:29:53,910 - 2373 - hummingbot.connector.exchange.digifinex.time_patcher - NETWORK - Error getting Digifinex server time.
> Traceback (most recent call last):
>   File "/home/clint_g/hb-digifinex/hummingbot/connector/exchange/digifinex/time_patcher.py", line 96, in update_server_time_offset
>     server_time = await query_time_func()
>   File "/home/clint_g/hb-digifinex/hummingbot/connector/exchange/digifinex/digifinex_auth.py", line 38, in query_time_func
>     resp_data: Dict[str, float] = await resp.json()
>   File "/home/clint_g/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1026, in json
>     raise ContentTypeError(
> aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://openapi.digifinex.com/v3/time')
> ```

Digifinex is currently under DDOS attack. Can use an alternative hostname. Modify line 7 of digifinex_constants.py, from 'openapi.digifinex.com' to 'openapi.digifinex.io'

**Comment by RC-13** [comment]
@szmcdull I've started to get the same issue after few minutes even after changing the hostname will pause the testing for now.

**Comment by szmcdull** [comment]
> 
> 
> @szmcdull I've started to get the same issue after few minutes even after changing the hostname will pause the testing for now.

@RC-13 Hi, it should be back to normal now. Please check it when you have time.

**Comment by szmcdull** [comment]
openapi.digifinex.com not working from time to time. 
but openapi.digifinex.io should work

**Comment by RC-13** [comment]
> Oh I checked the code of cancel_all (part of which is from crypto.com). After it cancels all open orders, it checks if each one still in the _in_flight_orders. So if order cancellation messages come after that, cancel_all will report the order failed to cancel.

@szmcdull Thanks for the update, confirming that the previous issue reported when stopping the bot has been fixed. The test bot is now using the other hostname and currently running as expected. I Will let it run overnight and will send an update if a new issue will occur.

**Comment by rxlxrxsx** [comment]
Question, is it expected that the exchange_trade_id is shown as N/A?

Screen Shot 2021-03-18 at 3 23 20 PM

See samples here:
[digifinex_trades.zip](https://github.com/CoinAlpha/hummingbot/files/6162072/digifinex_trades.zip)

**Comment by szmcdull** [comment]
> 
> 
> Question, is it expected that the exchange_trade_id is shown as N/A?
> 
> Screen Shot 2021-03-18 at 3 23 20 PM
> 
> See samples here:
> [digifinex_trades.zip](https://github.com/CoinAlpha/hummingbot/files/6162072/digifinex_trades.zip)

Yes. Websocket order update does not contain trade-id information

**Comment by RC-13** [comment]
Retesting the connector, it seems that the HTTP 502 status appears every after 2hours, this is when using `openapi.digifinex.com` After changing to `'openapi.digifinex.io` so far I haven't seen the http status however there are still timeouts but bot recovers. Will continue running the test bot to check if the behavior change.

Another thing, two unit tests are currently failing: `test_digifinex_auth.py` and `test_digifinex_exchange.py`
[test_digifinex_auth.py.log](https://github.com/CoinAlpha/hummingbot/files/6180883/test_digifinex_auth.py.log)
[test_digifinex_exchange.py.log](https://github.com/CoinAlpha/hummingbot/files/6180885/test_digifinex_exchange.py.log)

**Comment by szmcdull** [comment]
> 
> 
> Retesting the connector, it seems that the HTTP 502 status appears every after 2hours, this is when using `openapi.digifinex.com` After changing to `'openapi.digifinex.io` so far I haven't seen the http status however there are still timeouts but bot recovers. Will continue running the test bot to check if the behavior change.
> 
> Another thing, two unit tests are currently failing: `test_digifinex_auth.py` and `test_digifinex_exchange.py`
> [test_digifinex_auth.py.log](https://github.com/CoinAlpha/hummingbot/files/6180883/test_digifinex_auth.py.log)
> [test_digifinex_exchange.py.log](https://github.com/CoinAlpha/hummingbot/files/6180885/test_digifinex_exchange.py.log)

`test_digifinex_auth.py` Did you set up key and secret? If not the server will disconnect when asked to subscribe a private channel.
`test_digifinex_exchange.py` How did you run the test? Seems your tool failed to load the test.

**Comment by RC-13** [comment]
@szmcdull Yup, we added our keys. Done this by creating another conf file (conf_local.py) and use nose to run the tests. Those two reported fails, while the other 2 passed.

**Comment by szmcdull** [comment]
@RC-13 Can you describe the steps you run test_digifinex_exchange.py? Can you test test_crypto_com_exchange.py and see if it passes? Because the tests were copied from crypto_com.

**Comment by keithbaum** [comment]
@RC-13 Please try now. Removed lines referring to __main__ and main() in test files

**Comment by RC-13** [comment]
Thanks @keithbaum, QA team re-tested the unit test and the main issue has been sorted, however, two function within the test are failing. Will re-test once new commit is added.

**Comment by szmcdull** [comment]
@RC-13 Can you try again with the tests?

**Comment by RC-13** [comment]
Will do, thanks for the update

**Review by keithbaum — APPROVED** [review]
After running tests, no orders were left hanging in the exchange and tests passed.
Code looks good to me.

**Review by RC-13 — APPROVED** [review]
Confirmed all unit test passed and no other issue encountered except for the random connectivity interruption however bot immediately recover.

**Pull request merged**
