### PR TITLE
fix / correct condition check for KuCoin filled orders

### PR DESCRIPTION
**Pull request by vic-en**
**Before submitting this PR, please make sure**:
- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue: #2111
- Related Clubhouse Story:

**A description of the changes proposed in the pull request**:

### CODE REVIEW

**Comment by Clint-G13** [comment]
Test PR however only the first 2 trades are recorded on the history and database file and an error keeps appearing:
```
2020-07-27 23:24:13,433 - 2501 - hummingbot.market.kucoin.kucoin_market - ERROR - Unexpected error in user stream listener loop.
Traceback (most recent call last):
  File "hummingbot/market/kucoin/kucoin_market.pyx", line 303, in hummingbot.market.kucoin.kucoin_market.KucoinMarket._user_stream_event_listener
    if (execution_status == "open" or execution_status == "match") and Decimal(execution_data["matchSize"]) > 0:
KeyError: 'matchSize'
```
KuCoin
KuCoinDB
KuCoin exchange:
KuCoin exchange history
[logs_KuCoin.log](https://github.com/CoinAlpha/hummingbot/files/4983223/logs_KuCoin.log)

**Comment by rxlxrxsx** [comment]
Tested and confirmed fix.

image

**Comment by dennisocana** [comment]
retest this please

**Comment by dennisocana** [comment]
test this please

**Pull request merged**
