### PR TITLE
Fix/Missing import in AvellanedaMarketMakingStrategy

### PR DESCRIPTION
**Pull request by mhrvth**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

Adds a missing import of the `ConditionalExecutionState `

**Tests performed by the developer**:

- ran unit tests
- ran the strategy with binance paper

### CODE REVIEW

**Comment by mhrvth** [comment]
[sc-23678]

**Review by aarmoa — APPROVED** [review]
The change looks good to me

**Comment by aarmoa** [comment]
I don't really think we need to request QA's approval for this change

**Review by PtrckM — APPROVED** [review]
Tested and approved in behalf QA team.
Test summary:

- Created avellaneda_market_making strategy and went through initial prompts successfully
- Confirmed wallet and exchange balances are reflecting correct
- Started the strategy without issues, confirmed orders are created and cancelled based on config
- Ran a test for hours without errors
- Confirmed in logs that there are no errors 
- Confirmed that there are no errors during filled trade event.
- Trade information are correct (price, size) based on history command output
- Compared trades in client, csv, sqlite and exchange are all matched.
- Configure settings (and advance settings) on avellaneda_market_making and confirmed it behave accordingly.

**Comment by mhrvth** [comment]
Created a PR in the Foundation repo: https://github.com/hummingbot/hummingbot/pull/5153

**Pull request closed without merging**
