### PR TITLE
feat/ omit commands from coverage

### PR DESCRIPTION
**Pull request by CrimsonJacket**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Omit commands from tested by the coverage tool.

**Tests performed by the developer**:
Simple inclusion to omit all files in the `hummingbot/client/command/` folder when running the coverage tool.

**Tips for QA testing**:
None needed.

### CODE REVIEW

**Review by aarmoa — COMMENTED** [review]
I don't think it is a good idea to add a generic exception to all commands. I think in the case of Zappra's PR we should merge it ignoring the diff-coverage error (thinking it as a one of case)

**Comment by CrimsonJacket** [comment]
I understand, I will close this PR and proceed to approve Zappra's PR.

**Comment by aarmoa** [comment]
I am reopening this PR because we will not be able to approve #3065 without the exclusions

**Review by aarmoa — APPROVED** [review]
I agree with the changes. We should change this back after #3065 is merged

**Pull request merged**
