### PR TITLE
feat/ CLOB Perpetual interface and InjectivePerpetual connector in Hummingbot 2

### PR DESCRIPTION
**Pull request by petioptrv**
This PR is a replacement for #324 to address rebasing issues.

**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Added base class for CLOB perpetual connectors and included Injective Perpetual connector
Made additions into `GatewayHTTPClient` to support new routes

[sc-37633]
**Tests performed by the developer**:
- Added unit tests for the injective perpetual API data source
- Manually tested the connector

**Tips for QA testing**:
Test that connector works as intended.

### CODE REVIEW

**Comment by mrhzysbl** [comment]
Test run: https://hummingbot.testrail.io/index.php?/runs/view/4190&group_by=cases:section_id&group_order=asc

**Comment by petioptrv** [comment]
@CoinAlpha/qa-client, please resume testing for this PR

**Review by vic-en — APPROVED** [review]
Changes LGTM

**Review by vic-en — APPROVED** [review]
LGTM

**Review by mrhzysbl — APPROVED** [review]
Tested and confirmed working by QA:
* Successfully cloned and installed the branch
* Able to connect the wallet successfully
* Created and ran a perpetual market making strategy on Injective Perpetual
* Confirmed orders are created and cancelled based on config
* Confirmed no orders are lost during run time and after stopping the strategy
* Compared trades in client and exchange, no discrepancies found
* Funding payment message is showing on the log pane
* Build docker image and repeat same tests performed on source build. Confirmed no issues

**Comment by petioptrv** [comment]
Closing in favour of foundation PR: https://github.com/hummingbot/hummingbot/pull/6200

**Pull request closed without merging**
