### PR TITLE
fix / update websockets version to 9.1

### PR DESCRIPTION
**Pull request by aarmoa**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Update websockets library dependency from version 8.1 to 9.1. Also updates all dependent libraries to versions that are prepared to work with that websockets release.

**Tests performed by the developer**:
All unit tests passing.

**Tips for QA testing**:
The testing should include validation that connectors in general still work without issues (they are the ones using websockets).
Also test connectors to descentralized exchanges (balancer, terra, uniswap and uniswap_v3), since we need to include several eth libraries in the update.

**IMPORTANT**:
When using this branch the `hummingbot` conda environment has to be reinstalled:
- `./clean`
- `conda deactivate`
- `./uninstall`
- `./install`
- `conda activate hummingbot`
-  `./compile`

### CODE REVIEW

**Comment by RC-13** [comment]
Getting the following error when starting the bot and when connecting kucoin 
image
```python
2021-09-13 14:05:36,735 - 5563 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: No module named 'websockets.legacy'
Traceback (most recent call last):
  File "/home/clint_g/websocket/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/clint_g/websocket/hummingbot/client/command/connect_command.py", line 63, in connect_exchange
    err_msg = await UserBalances.instance().add_exchange(exchange, **api_keys)
  File "/home/clint_g/websocket/hummingbot/user/user_balances.py", line 53, in add_exchange
    market = UserBalances.connect_market(exchange, **api_details)
  File "/home/clint_g/websocket/hummingbot/user/user_balances.py", line 24, in connect_market
    connector_class = get_connector_class(exchange)
  File "/home/clint_g/websocket/hummingbot/client/config/config_helpers.py", line 177, in get_connector_class
    mod = __import__(conn_setting.module_path(),
  File "hummingbot/connector/exchange/kucoin/kucoin_exchange.pyx", line 48, in init hummingbot.connector.exchange.kucoin.kucoin_exchange
    from hummingbot.connector.exchange.kucoin.kucoin_order_book_tracker import KucoinOrderBookTracker
  File "/home/clint_g/websocket/hummingbot/connector/exchange/kucoin/kucoin_order_book_tracker.py", line 18, in <module>
    from hummingbot.connector.exchange.kucoin.kucoin_api_order_book_data_source import KucoinAPIOrderBookDataSource
  File "/home/clint_g/websocket/hummingbot/connector/exchange/kucoin/kucoin_api_order_book_data_source.py", line 24, in <module>
    from websockets.legacy.client import Connect as WSConnectionContext
ModuleNotFoundError: No module named 'websockets.legacy'
```

**Comment by aarmoa** [comment]
@RC-13 What OS were you using when this issue happened? I tried reproducing it but I could connect to Kucoin without issues (I tested in Mac).
Please remember to follow the steps I have added in the PR description to ensure your `hummingbot` conda environment is correctly configured with the new dependencies.

**Comment by RC-13** [comment]
@aarmoa This occurred on a mac and windows environment however I can confirm that the error no longer appear after another cleanup. Will inform the rest of the QA team that encounter the same error.

**Comment by Nullably** [comment]
@RC-13 Please test Raspberry Pi installation for both docker and source as well.

**Review by Nullably — APPROVED** [review]
LGTM

**Comment by RC-13** [comment]
When starting a docker instance on a raspberry pi using an image created base on the PR, the bot crash and throws an import error. We checked other environment and it appears to just affect raspberry pi.
image

**Comment by aarmoa** [comment]
@RC-13 could you please run the same test with the current master version? I would like to find out if that error is really caused by this PR, since we have not changed anything related to telegram library

**Comment by RC-13** [comment]
@aarmoa I can confirm that 0.43.0 and 0.43.1(arm) image are working on raspberry pi. We did another test and created a docker image using 2 different environment (Mac M1 and Ubuntu 20.04 LTS - Focal (Arm)), both are working when running from source but gets the same error when creating a docker instance.

**Comment by RC-13** [comment]
Adding the steps that is use by QA and support to build a docker image 
```python
# clone project or branch
# install, activate conda, and compile

# set variables
export TAG="v0.43.1"
export INSTANCE_NAME="hb_v0.43.1"
export FOLDER="hb_v0.43.1_files"

# build ARM version
docker build -t coinalpha/hummingbot:$TAG -f Dockerfile.arm .
```

**Review by RC-13 — DISMISSED** [review]
Confirming that the `./install`  command is now working on raspberry pi source installation and confirm that the docker instance no longer crash using an image created base on the PR. Although the `Dockerfile.arm` needs updating as it currently uses the `requirement-arm.txt`, I guess this can be done on a separate PR.

**Review by Nullably — APPROVED** [review]
LGTM

**Comment by aarmoa** [comment]
I could not change the current `Docker.arm` file to not use `setup/requirements-arm.txt` easily because the arm image is not currently prepared to use miniconda, and there is not public image with miniconda for arm64v8 architecture. We need to create a new image configuration that downloads and installs the correct miniconda version. But that will take some time. I will create a separate task for that change.
In the meantime I have updated the requirements file with the latest dependencies.

**Comment by aarmoa** [comment]
https://app.zenhub.com/workspaces/hummingbot-5f340755c5e17300167a8f30/issues/coinalpha/hummingbot/4237

**Review by RC-13 — APPROVED** [review]
LGTM! Confirm no issue building docker image on raspberry pi using the updated `requirement-arm.txt` file.

**Pull request merged**
