### PR TITLE
Refactor/coibase pro websockets

### PR DESCRIPTION
**Pull request by petioptrv**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
- Adapts Coinbase Pro connector to use the `WebAssistants` layer
- Adds authenticator capabilities to the `WebAssistants` layer
- Adds costrings to the `web_assistant` layer. Docs only add where necessary for the understanding of the layer.

**Tests performed by the developer**:
- Tests cases for the changes
- Minor fixes on some of the Gate.io tests

**Tips for QA testing**:
- The full range of Coinbase Pro connector's communication with the server (posting order, cancelling orders, receiving order updates, receiving order book data, etc)

### CODE REVIEW

**Comment by petioptrv** [comment]
@aarmoa, I fixed the order of imports flagged on the foundation PR. I am using `isort -m=3 -l=120  hummingbot/connector/exchange/coinbase_pro` to sort, but it almost completely fails on cython files, so I had to do those ones manually.

I've also reverted for now to our current pattern of ensuring that the `web_assistant` layer uses a single `ClientSession`. As you suggested, we can discus maybe refactoring the base classes in a separate task

**Comment by dennisocana** [comment]
Closed and reopened to trigger the workflow validation process.

**Review by aarmoa — APPROVED** [review]
The changes look good to me

**Review by RC-13 — APPROVED** [review]
LGTM! Tested and confirmed working by QA.
Test performed:
- Start a pure market-making strategy without experiencing any issue.
- Run status --live command and observe the order cancellation and creation 
- Compare the order book displayed in the bot vs exchange and confirm that the best prices are synchronized.
- Check the trade fee deducted for each trade and confirm that it matches the fees displayed in the exchange.
- Sum up the individual fee and confirm that totally matches the total fee displayed in the history performance.
- Configure multiple orders with fast refresh time (1-3 sec) and confirm no order was lost during the testing session.
- Setup multiple bots running on Coinbase pro connector and didn't hit any issue.
-  Test connector using other strategies.

**Pull request closed without merging**
