### PR TITLE
fix/fees liquid

### LINKED ISSUE #2084: [BUG] Filled order fees are not recorded correctly
**Describe the bug**

Fees for orders that are filled are not recorded correctly for many connectors, instead of taking fees reported from exchange's API, the connectors call `c_get_fee` (which estimates fee). This results in incorrect fees stored on trades table (sqlite) and incorrect performance reported on `history` command.

This mistake was partly due to Binance connector had this bug which other connectors copied the code from. The bug was fixed on 29 December 2020 on Binance connector so connectors created after the date should not get affected.

Connectors which broadcast fee incorrectly on `OrderFilledEvent`:

- [ ] ~Kucoin~
- [x] Binance Perpetual Derivative
- [x] Bifinex
- [x] Coinbase Pro
- [x] Bittrex
- [ ] ~OkEx~
- [x] Huobi
- [ ] ~Beaxy~
- [x] FTX
- [ ] ~Blocktane~
- [ ] ~Coinzoom~
- [ ] ~DigiFinex~
- [x] Gate.io
- [ ] Liquid

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd1e7e) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by aarmoa**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
The PR include the required changes to consider the fees informed by the exchange when a trade takes place, instead of estimating them.
Partially closes #2084

**Tests performed by the developer**:
Added new unit tests for the order fill process and the fees registration

**Tips for QA testing**:
Please check that partial and complete fills are working correctly in Liquid connector. Also verify if the fees are now being registered correctly.

### CODE REVIEW

**Review by RC-13 — DISMISSED** [review]
LGTM! Tested and confirmed by QA, maker and taker fees deducted in each trade matches the record in the exchange trade history.

**Review by CrimsonJacket — DISMISSED** [review]
Changes LGTM

**Review by RC-13 — APPROVED** [review]
Re-approving PR on behalf of the QA team.

**Review by CrimsonJacket — APPROVED** [review]
Changes LGTM.

**Pull request merged**
