### PR TITLE
fix/ fix race condition in status_poll_loop in KuCoin connector

### PR DESCRIPTION
**Pull request by CrimsonJacket**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

This PR should address possibility of a delayed strategy start within the `status_poll_loop()` function in the KuCoin connector.

Relates to #3490

### CODE REVIEW

**Comment by aarmoa** [comment]
@CrimsonJacket Maybe it would be a good idea to reset the _poll_notifier also in _stop_network

**Review by aarmoa — DISMISSED** [review]
Change to allow the _status_polling_loop to work properly if a connector is restarted by reseting control variables

**Review by rapcmia — APPROVED** [review]
Tested and confirmed working by QA team,
- Start the bot then stop. After 3-5s, start again. No errors or delays.
- Start the bot, ran for 10-15mins. Stop then wait for 3-5s. Start the bot again and no errors or delays when creating orders.
- Start the bot with a different strategy, stop then switch to another and start. No error or delay

**Review by aarmoa — APPROVED** [review]
LGTM

**Pull request merged**
