### PR TITLE
Introduce a single command to run all stable tests

### PR DESCRIPTION
**Pull request by ellieeee**
Before submitting this PR, please make sure:

[Y] Your code builds clean without any errors or warnings
[Y] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)
Optional:

Related Github issue: N/A
Related Clubhouse Story: 4099
A description of the changes proposed in the pull request:
Introduce a command to run all stable tests in Hummingbot using Makefile and nose. The set of stable tests is not exhaustive but just to cover the obvious cases.
Going forward we should start to make tests stable by default (with mocks, fakes, etc), but this will be a good start.

### CODE REVIEW

**Comment by ellieeee** [comment]
ping @carlolm

**Comment by carlolm** [comment]
Thanks @ellieeee , this looks good. Just some questions:

- so the command to run is `make test`?
- when I try to run the strategy tests (python test/test_*: arbitrage, cross exchange market making, discovery), the tests now complete without logging any output. Is that intended?
- should the additional packages be added to the win64 environment file also?

**Comment by ellieeee** [comment]
>>so the command to run is make test?
Yes.

>>when I try to run the strategy tests (python test/test_*: arbitrage, cross exchange market making, discovery), the tests now complete without logging any output. Is that intended?
Yes, but can make it more detailed by adding a -v. Either way works.

>>should the additional packages be added to the win64 environment file also?
I don't have the windows env dump, I think Martin edited manually. How about after this is submitted someone who have a windows env fix the package diff?

**Comment by ellieeee** [comment]
Added a modification. Try run make test again, you'll see more output:


```
(hummingbot) echio@DESKTOP-Q00OMKR:/mnt/d/Source/hummingbot$ make test
nosetests -d -v -A 'stable' test/test*.py
/home/echio/anaconda3/envs/hummingbot/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: hummingbot.core.data_type.limit_order.LimitOrder size changed, may indicate binary incompatibility. Expected 72 from C header, got 168 from PyObject
  return f(*args, **kwds)
/home/echio/anaconda3/envs/hummingbot/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: hummingbot.core.data_type.order_expiration_entry.OrderExpirationEntry size changed, may indicate binary incompatibility. Expected 48 from C header, got 96 from PyObject
  return f(*args, **kwds)
test_arbitrage_not_profitable (test_arbitrage.ArbitrageUnitTest) ... ok
test_arbitrage_profitable (test_arbitrage.ArbitrageUnitTest) ... ok
test_asset_limit (test_arbitrage.ArbitrageUnitTest) ... ok
test_find_best_profitable_amount (test_arbitrage.ArbitrageUnitTest) ... ok
test_find_profitable_arbitrage_orders (test_arbitrage.ArbitrageUnitTest) ... ok
test_min_profitability_limit_1 (test_arbitrage.ArbitrageUnitTest) ... ok
test_min_profitability_limit_2 (test_arbitrage.ArbitrageUnitTest) ... ok
test_ready_for_new_orders (test_arbitrage.ArbitrageUnitTest) ... ok
test_ask_side_profitable (test_cross_exchange_market_making.HedgedMarketMakingUnitTest) ... ok
test_bid_side_profitable (test_cross_exchange_market_making.HedgedMarketMakingUnitTest) ... ok
test_both_sides_profitable (test_cross_exchange_market_making.HedgedMarketMakingUnitTest) ... ok
test_market_became_narrower (test_cross_exchange_market_making.HedgedMarketMakingUnitTest) ... ok
test_market_became_wider (test_cross_exchange_market_making.HedgedMarketMakingUnitTest) ... ok
test_market_changed_to_unprofitable (test_cross_exchange_market_making.HedgedMarketMakingUnitTest) ... ok
test_neither_side_profitable (test_cross_exchange_market_making.HedgedMarketMakingUnitTest) ... ok
test_order_fills_after_cancellation (test_cross_exchange_market_making.HedgedMarketMakingUnitTest) ... ok
test_price_and_size_limit_calculation (test_cross_exchange_market_making.HedgedMarketMakingUnitTest) ... ok
test_profitability_with_conversion (test_cross_exchange_market_making.HedgedMarketMakingUnitTest) ... ok
test_profitability_without_conversion (test_cross_exchange_market_making.HedgedMarketMakingUnitTest) ... ok
test_top_depth_tolerance (test_cross_exchange_market_making.HedgedMarketMakingUnitTest) ... ok
test_filter_trading_pairs (test_discovery_strategy.DiscoveryUnitTest) ... ok
test_market_info_spec (test_discovery_strategy.DiscoveryUnitTest) ... ok
test_matching_pairs (test_discovery_strategy.DiscoveryUnitTest) ... ok
test_check_if_active_orders_are_cancelled_every_tick (test_pure_market_making.PureMarketMakingUnitTest) ... ok
test_check_sufficient_balance (test_pure_market_making.PureMarketMakingUnitTest) ... ok
test_confirm_active_bids_asks (test_pure_market_making.PureMarketMakingUnitTest) ... ok
test_correct_price_correct_size (test_pure_market_making.PureMarketMakingUnitTest) ... ok
test_create_new_orders (test_pure_market_making.PureMarketMakingUnitTest) ... ok
test_market_became_narrower (test_pure_market_making.PureMarketMakingUnitTest) ... ok
test_market_become_wider (test_pure_market_making.PureMarketMakingUnitTest) ... ok
test_order_fills (test_pure_market_making.PureMarketMakingUnitTest) ... ok
test_order_fills_after_cancellation (test_pure_market_making.PureMarketMakingUnitTest) ... ok
test_strategy_after_user_cancels_orders (test_pure_market_making.PureMarketMakingUnitTest) ... ok

----------------------------------------------------------------------
Ran 33 tests in 2.613s

OK
(hummingbot) echio@DESKTOP-Q00OMKR:/mnt/d/Source/hummingbot$ ga Makefile
(hummingbot) echio@DESKTOP-Q00OMKR:/mnt/d/Source/hummingbot$ gm
[add-test-suite-dev be9834f] Show executed test case names and print detailed error on test failure/error.
 1 file changed, 1 insertion(+), 1 deletion(-)
(hummingbot) echio@DESKTOP-Q00OMKR:/mnt/d/Source/hummingbot$ git push origin add-test-suite-dev
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 357 bytes | 178.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To github.com:ellieeee/hummingbot.git
   174a693..be9834f  add-test-suite-dev -> add-test-suite-dev
(hummingbot) echio@DESKTOP-Q00OMKR:/mnt/d/Source/hummingbot$
```

**Comment by carlolm** [comment]
Thanks for explaining @ellieeee

**Pull request merged**
