### PR TITLE
Fix/Ascendex: Fail to cancel an order due to order status not found

### PR DESCRIPTION
**Pull request by mhrvth**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

If an `create_order()` request results in a failure, the connector should emit an order update to remove it from the In Flight Order Tracker.

**Tests performed by the developer**:

Ran unit tests
I wasn't able to reproduce the problem, but this should fix it.

### CODE REVIEW

**Comment by mhrvth** [comment]
[sc-24493]

**Comment by Deepali6997** [comment]
hi @mhrvth while testing the feature branch, we can see error in log pane. As shown in below screenshot.

Screenshot 2022-07-01 at 5 21 44 PM

log file and configs for your reference are shared below : 
[Support Packets.zip](https://github.com/CoinAlpha/hummingbot/files/9028618/Support.Packets.zip)

**Comment by gerald-hb** [comment]
I can confirm that it no longer show the "failed to cancel order" error/flood but I see this new error.
image
```
2022-07-02 00:18:20,148 - 18316 - hummingbot.connector.exchange.ascend_ex.ascend_ex_exchange - ERROR - sequence item 0: expected str instance, NoneType found
Traceback (most recent call last):
  File "/home/geraldhb/pr265/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 761, in _status_polling_loop
    await safe_gather(
  File "/home/geraldhb/pr265/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/geraldhb/pr265/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 823, in _update_order_status
    exchange_order_ids_param_str: str = ",".join(list(ex_oid_to_c_oid_map.keys()))
TypeError: sequence item 0: expected str instance, NoneType found
```

[logs_conf_pure_mm_1.log](https://github.com/CoinAlpha/hummingbot/files/9030308/logs_conf_pure_mm_1.log)
[conf_pure_mm_1.zip](https://github.com/CoinAlpha/hummingbot/files/9030311/conf_pure_mm_1.zip)

**Comment by RC-13** [comment]
@mhrvth Can we improve this message when an order is remove due to not meeting the exchange trade rules?
image
Similar to how binance handles orders that are below the exchange trade rules:
image

**Comment by mhrvth** [comment]
@RC-13  Hi, I'll change that to be similar to Binance.

**Comment by mhrvth** [comment]
@gerald-hb Hi, I wasn't able to reproduce the issue, however I've pushed a possible fix to the PR. Can you please retest it?

**Comment by Deepali6997** [comment]
Thanks @mhrvth for quick action. Although we can see the updated message now. But somehow the later half of the message is not giving the full information **"lower than or equal to the minimum order amount 0"**

Regarding, https://github.com/CoinAlpha/hummingbot/pull/265#issuecomment-1173597256 -- wasn't able to reproduce the mentioned issue

Screenshot 2022-07-04 at 5 03 56 PM

**Comment by Deepali6997** [comment]
can see the updated error message now.

Screenshot 2022-07-04 at 6 43 50 PM

**Review by Deepali6997 — APPROVED** [review]
Test Summary

- Clone and install feature branch
- Connecting ascdenx API
- Create PMM strategy for ascendex
- Checking log-pane for fail to cancel order due to order status not found
- Improved message on log-pane due to order not meeting the exchange trading rules

**Review by CrimsonJacket — APPROVED** [review]
Changes LGTM.

**Comment by mhrvth** [comment]
Created a PR in the Foundation repo: https://github.com/hummingbot/hummingbot/pull/5460

**Pull request closed without merging**
